### ISSUE TITLE
2d path view can not be zoomed 

### ISSUE THREAD

**Issue by mkeyno** [svenhb/GRBL-Plotter#10]
hi @svenhb , 
I've noticed 2d path view area can not be zoomed whereas G-cod text are perfectly zoomed , is this any feature that I miss about that?
BR

**Comment by svenhb** [comment]
Are you unsing latest version 1.1.2.0? Zooming is then connected to mouse-wheel when mouse-pointer is above 2d view.

**Comment by mkeyno** [comment]
thanks @svenhb   I did but it seems  it works partially , and during the CAM job if feedrate or zoom changed , the program  jammed , 
do you have any plan to make some changes in your software ?

**Comment by svenhb** [comment]
During a CAM job the 'realtime' 2d view will be replaced by a picture (to avoid redrawing the whole graphics with each change of the tool position) to increase performance on (my) XP PC. 
I will check if can solve the described problem.

**Comment by mkeyno** [comment]
can you add  feedrate in the control area like many CAM software ?

**Comment by svenhb** [comment]
Feedrate for what? When using the joystick control, feedrate is taken from setup-values.
Perhaps you have a screenshot for me as an example.

**Comment by mkeyno** [comment]
I don't have joystick  and may user need decreased or increased speed of CAM job during operation  , many software like Repiteir have this option
![image](https://user-images.githubusercontent.com/6232001/32766801-b993ccc2-c925-11e7-8bcc-afb5694b5f48.png)

and  when I change the feedrate in override screen , the software got jammed , 
don't you think is it better to add this feature in control/jogging area  ?
![image](https://user-images.githubusercontent.com/6232001/32766907-3e493d76-c926-11e7-946b-223ec589c51e.png)

**Comment by svenhb** [comment]
I meant the yellow control aerea - this is the joystick-like-control...
![image](https://user-images.githubusercontent.com/19973251/32767183-91a3be06-c912-11e7-8730-a5cab74b6686.png)

> feedrate in override screen.....  to add this feature in control/jogging area
I don't use it very much but I will check where I could add it to the main form.

**Comment by mkeyno** [comment]
thanks @svenhb  , please let me know if have any plan to enhanced its features , I have couple of suggestion that may useful for user-friendly capability of your software

**Comment by svenhb** [comment]
Did you try GRBL Version 1.1 for feedrate override? Your screenshot shows GRBL 0.9 override screen...
With GRBL 0.9 I have to interrupt the data stream to inject the new feedrate command - probably this is the reason for jamming.
With GRBL 1.1 override is handled by GRBL itself.

**Comment by mkeyno** [comment]
no I've always use last available frameware , have you check the feedrade change  during CAM job?

**Comment by svenhb** [comment]
With GRBL 0.9 I checked one year ago (with GRBL-Plotter 1.0? I don't remember). With 1.1 I checked 1 hour ago on my old XP-notebook and it worked.

**Comment by hilam8899** [comment]
HI,@svenhb
when I try to compile grbl_plotter ,
CS2001	Source file 'D:\9\VISUAL_STUDIO_PROJECT\GRBL-Plotter-master\GRBL-Plotter\eventHandler.cs' could not be found.	GRBL-Plotter	D:\9\VISUAL_STUDIO_PROJECT\GRBL-Plotter-master\GRBL-Plotter\CSC	1	
can you help me?thank you!

**Comment by svenhb** [comment]
I forgot to upload this file - now done.
