### ISSUE TITLE
A very strange thing happened --- the software automatically increased the straight line

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#100]
A very strange thing happened. The rectangle of the dxf file I tested was overlapped by three rectangles of the same size (as shown in Figure 1). The semicircle was also overlapped by three geometric figures of the same size Together, this dxf was opened for the first time in the plotter software and displayed as shown in Figure 2. However, when opened again with the plotter software, it was displayed as shown in Figure 3. (The blue line in Figure 3 is The software itself shows that this line does not appear in the dxf file. However, this line was not displayed when it was first opened with the plotter software, and it was displayed the second time, which is strange)
![1](https://user-images.githubusercontent.com/53146195/72046887-43418d80-32f4-11ea-9de2-dfe3fb99cf6f.jpg)
![2](https://user-images.githubusercontent.com/53146195/72046895-49d00500-32f4-11ea-9c0d-2cd68e122c2f.jpg)

![3](https://user-images.githubusercontent.com/53146195/72046888-463c7e00-32f4-11ea-9a04-11d8cabb851f.jpg)
[testdxf.zip](https://github.com/svenhb/GRBL-Plotter/files/4039150/testdxf.zip)

**Comment by svenhb** [comment]
Which 'Use case' did you select? Perhaps you can provide the generated G-Code?

**Comment by lianzaozi** [comment]
![11111](https://user-images.githubusercontent.com/53146195/72116722-1a69d880-3386-11ea-8a48-c2367e81586f.gif)
[test.zip](https://github.com/svenhb/GRBL-Plotter/files/4043407/test.zip)
[test_dxf.zip](https://github.com/svenhb/GRBL-Plotter/files/4043409/test_dxf.zip)

**Comment by svenhb** [comment]
Try https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_1331_publish.zip
Should be fixed:
Language in menu points
Additional Line
Hopefully "Reload SVG" button now visible

**Comment by lianzaozi** [comment]
ok thanks

**Comment by svenhb** [comment]
Should be fixed in 1.3.3.2 https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_1332_publish.zip
#102 should be fixed (missing 'close' for polyline)
'Reload' button position changed
#101 translation changed
#100 fixed
#98 fixed (DXF points wrong conversion)
