### ISSUE TITLE
Tradução Inicial

### ISSUE THREAD

**Issue by Wdespontin** [svenhb/GRBL-Plotter#101]
![72212339-fc50c500-34b8-11ea-823e-f7546ede3396](https://user-images.githubusercontent.com/42222369/72218782-a06c5780-351d-11ea-832d-3bd4ccf7270e.jpg)

[Comando 12345678910111213.txt](https://github.com/svenhb/GRBL-Plotter/files/4050640/Comando.12345678910111213.txt)

![Screenshot_1](https://user-images.githubusercontent.com/42222369/72218790-be39bc80-351d-11ea-8ad6-d24c0ad55f26.jpg)

[Comando D.txt](https://github.com/svenhb/GRBL-Plotter/files/4050642/Comando.D.txt)

![Screenshot_2](https://user-images.githubusercontent.com/42222369/72218795-cbef4200-351d-11ea-973a-38fd1cdae562.jpg)

[Comando ABCD.txt](https://github.com/svenhb/GRBL-Plotter/files/4050644/Comando.ABCD.txt)

of course this is impossible
follow image and txt

**Comment by svenhb** [comment]
To have your text as real text (not as a screenshot) would help to make the changes (copy & paste).
Do you think the original grbl messages should be translated also (3 IDLE - Esperando)?

**Comment by Wdespontin** [comment]
Follows the changes, from portuguese to english translator very erroneous
or vice versa

*Att; *
*Valter*


Em dom., 12 de jan. de 2020 às 05:48, Sven <notifications@github.com>
escreveu:

**Comment by svenhb** [comment]
Thanks,
these are the other grbl specific messages...

Alarm	
Check	
Door	
Hold	
Home	
Idle	         Ocioso
Jog	
Probe	
Run		Ecexutando
Sleep

**Comment by Wdespontin** [comment]
![72218790-be39bc80-351d-11ea-8ad6-d24c0ad55f26](https://user-images.githubusercontent.com/42222369/72226324-b9e9bf80-356e-11ea-8ca0-11aa03a5ad10.jpg)
[Comando.D.txt](https://github.com/svenhb/GRBL-Plotter/files/4051587/Comando.D.txt)

**Comment by svenhb** [comment]
Check update for translation
Should be fixed in 1.3.3.2 https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_1332_publish.zip
#102 should be fixed (missing 'close' for polyline)
'Reload' button position changed
#101 translation changed
#100 fixed
#98 fixed (DXF points wrong conversion)

**Comment by svenhb** [comment]
Thank you for your help.
