### ISSUE TITLE
Plotter software lost some geometric primitives

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#102]
Plotter software will discard some geometric primitives in the dxf file (these geometric primitives not displayed by the plotter software should not be parsed)

Open with plotter software
![test1](https://user-images.githubusercontent.com/53146195/72228361-e807e780-35e0-11ea-83db-203365b2106f.jpg)

Open the same dxf with CAD software
![Open the dxf use by CAD software](https://user-images.githubusercontent.com/53146195/72228367-fa822100-35e0-11ea-9351-c9d57321f57b.jpg)

**Comment by lianzaozi** [comment]
This is the dxf file I used for testing
[WenZiGuiJi_Test.zip](https://github.com/svenhb/GRBL-Plotter/files/4051828/WenZiGuiJi_Test.zip)

**Comment by lianzaozi** [comment]
I am curious, the function of generating GCode with text in the plotter software can not achieve the effect of this hollow text.

**Comment by svenhb** [comment]
Did you create the text with LibreCad? Because in LibreCad the file "WenZiGuiJi_Test" just contains polyline, not text.
In grbl-Plotter I copied all fonts, which are available in LibreCad...

**Comment by lianzaozi** [comment]
![GRBL-Plotter_1331_botton_test](https://user-images.githubusercontent.com/53146195/72254891-49ab6e80-3640-11ea-8bf0-a0f4b2c4a852.jpg)
No effect

**Comment by svenhb** [comment]
![LibreCAD_Fonts](https://user-images.githubusercontent.com/19973251/72261960-2e2b6e00-3616-11ea-926d-2f8182cee35b.jpg)

**Comment by svenhb** [comment]
Should look like this:
![image](https://user-images.githubusercontent.com/19973251/72269521-03481680-3624-11ea-901a-d64ea8d13d6d.png)

**Comment by svenhb** [comment]
Should be fixed in 1.3.3.2 https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_1332_publish.zip
#102 should be fixed (missing 'close' for polyline)
'Reload' button position changed
#101 translation changed
#100 fixed
#98 fixed (DXF points wrong conversion)

**Comment by lianzaozi** [comment]
![image](https://user-images.githubusercontent.com/53146195/72306962-b57aef00-36b3-11ea-9bdb-a880b2d45492.png)
Thank you, the effect is great

**Comment by lianzaozi** [comment]
Which font of the plotter software can I choose to make hollow Chinese characters? I have tried all the fonts provided in the plotter software and can only produce single-line Chinese characters. No font can produce hollow Chinese characters

**Comment by svenhb** [comment]
To use (probably) any font you like, you write your text in inkscape, select contour and fill, then convert object to path, then copy and paste to grbl-Plotter.    
https://inkscape.org/de/doc/tutorials/advanced/tutorial-advanced.html   
  
Perhaps here are matching fonts? https://www.dafont.com/theme.php?cat=201

**Comment by svenhb** [comment]
Already fixed
