### ISSUE TITLE
Plotter software reads dxf files containing text and svg files, an error occurs

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#103]
Plotter software reads dxf files containing text and svg files, an error occurs

Plotter software reads screenshots of dxf files with text
![5](https://user-images.githubusercontent.com/53146195/72339061-9ce4f600-3700-11ea-8c16-5ebccbbaef90.jpg)

CAD software reads a screenshot of the same DXF file with text
![6](https://user-images.githubusercontent.com/53146195/72339235-db7ab080-3700-11ea-9ed7-f6fb3956051c.jpg)

Plotter software reads screenshots of svg files with text
![3](https://user-images.githubusercontent.com/53146195/72339248-e46b8200-3700-11ea-9354-5343ad332b5b.jpg)

Screenshot of Inkscape software reading the same SVG file with text
![2](https://user-images.githubusercontent.com/53146195/72339344-0b29b880-3701-11ea-8328-d736f9f2551f.jpg)

**Comment by svenhb** [comment]
grbl-Plotter can't read real text from SVG - too complicated to implement.
Workarround for SVG: convert text to path, then it works.

**Comment by lianzaozi** [comment]
But the text in the dxf file cannot be parsed normally.

**Comment by svenhb** [comment]
I already use the DXF font (*.lff) when "Generating G-Code from Text". So I can support Text-entity from DXF file. Inside DXF file, the text, font-family, size, position etc. are stored...

**Comment by lianzaozi** [comment]
Thank you very much.
I tested it with LibreCAD to create a dxf file with text. The plotter software does recognize the text in a dxf file with text created with LibreCAD. The fonts in LibreCAD software do not support Chinese. I tested all the fonts in LibreCAD and displayed garbled characters when typing Chinese.

But read the text created by AUTOCAD software with dxf plotter software that can not recognize the text.

**Comment by svenhb** [comment]
In Inkscape you can use any windows-font (I think), I tried with chinese text and at least there are two fonts showing difference style for chinese text.
![image](https://user-images.githubusercontent.com/19973251/72413752-c0e02000-3770-11ea-95d4-5f1b294aa33b.png)

**Comment by lianzaozi** [comment]
Thank you very much for your answer
Inkscape supports Chinese very well, LibreCAD software does not support Chinese. Now there is only the method of converting text to track and saving as SVG in Inkscape.

**Comment by svenhb** [comment]
* You can copy the path in Inkscape and paste in GRBL-Plotter (on 2D view)  
* You can save as SVG and load in GRBL-Plotter  
* You can export to DXF in Inkscape and go on in LibeCAD - still as path, not as text  
  
You have a lot of options

**Comment by lianzaozi** [comment]
ok

**Comment by svenhb** [comment]
As described, it's too complicated to implement real text import from SVG.
