### ISSUE TITLE
tradução da tela inicial

### ISSUE THREAD

**Issue by Wdespontin** [svenhb/GRBL-Plotter#104]
![Screenshot_1](https://user-images.githubusercontent.com/42222369/72368033-0c94ba00-36dc-11ea-8da5-7e25c199d88d.jpg)
[Comando.D.txt](https://github.com/svenhb/GRBL-Plotter/files/4060527/Comando.D.txt)

**Comment by svenhb** [comment]
Enable translation for grbl-messages in Setup - Flow control

https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_1334_publish.zip
