### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#106]
Thanks for your work
Version 1.3.3.4 does not scale well

**Comment by lianzaozi** [comment]
I have two suggestions for improvements regarding scaling:
1. Regardless of moving the trajectory to any position in the display area, when you double-click the mouse wheel quickly, the trajectory is immediately and adaptively displayed in the center of the display area (this can refer to libreCAD software).
![zoom](https://user-images.githubusercontent.com/53146195/76921328-b96ffb00-6908-11ea-9b3c-c86fb3e4c2e0.gif)


2. Regarding zooming, the zoom magnification should not be increased by 2 times each time the mouse wheel is scrolled.

**Comment by svenhb** [comment]
* 2D-View: fix strange zomm-in, -out behavior  
Reset zooming on double-click middle mouse button    

https://github.com/svenhb/GRBL-Plotter/releases/tag/v1.3.4.3

I could fix the problem finally :-)
