### ISSUE TITLE
Tangential axis

### ISSUE THREAD

**Issue by raercan** [svenhb/GRBL-Plotter#107]
Hi . Can you add tangential axis support . thank you.

**Comment by svenhb** [comment]
You mean an additional axis "A" which shows the direction of the path within 360° angle?

**Comment by raercan** [comment]
https://youtu.be/_CTAL7Dl0zU

İ want to use like this machine. machine is using rotary blade and conveyor axis. Rotary blade is controlled by theta axis ( mean a or c axis). Thank you

**Comment by svenhb** [comment]
Hope my implementation is ok:  
https://github.com/svenhb/GRBL-Plotter/releases/tag/v1.3.4.0

**Comment by raercan** [comment]
Thank you
