### ISSUE TITLE
Plt and hpgl data format is possible ? 

### ISSUE THREAD

**Issue by raercan** [svenhb/GRBL-Plotter#108]
Hi. Can you support Plt and hpgl file type drawing? Thank you.

**Comment by raercan** [comment]
https://youtu.be/eO6vynBqP78

**Comment by svenhb** [comment]
I thought HPGL is way out of date - why don't you use SVG? You may still have old files?
Can you upload a HPGL file - so I can check if special commands are used, like scaling?

**Comment by raercan** [comment]
Hpgl is older but lot of cad software is supported.  İ ll attach  soon

**Comment by svenhb** [comment]
Hope the implementation of basic commands is enough:
https://github.com/svenhb/GRBL-Plotter/releases/tag/v1.3.4.0

**Comment by raercan** [comment]
Thank you
