### ISSUE TITLE
link to latest  version is broken

### ISSUE THREAD

**Issue by docsparks** [svenhb/GRBL-Plotter#11]
link : https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_1130_Publish.zip
is going to 404 broken page.

**Comment by svenhb** [comment]
You can also download from the release-page 
https://github.com/svenhb/GRBL-Plotter/releases/download/v1.1.3.0/GRBL-Plotter_1130_Publish.zip
