### ISSUE TITLE
Laser cutting path planning

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#112]
First of all, thank you for your commitment to the plotter software.

I have an idea. I want to use this software for laser cutting. Generally, laser cutting has to plan the path first, and then read the dxf file to generate a specific trajectory Gcode. I looked for it in the software and did not find a setting item about the path planning of the laser cutting.

**Comment by svenhb** [comment]
You mean planning to reduce unneeded G0 moves?
Including reversing of lines (switching start- and end-point)?

**Comment by lianzaozi** [comment]
thank you for your reply

What I mean is not what you understand.

Let me give an example. Take the following picture as an example. Figure 3 is the product I want to actually get after laser cutting. I used dxf in Figure 1 to import the software. After the software actually planned the path, the starting point of the cut was A and B, because the corners of the cut product would fit the size. The cutting start points A and B and the green segment line trajectories in Figure 2 are automatically planned by the software according to the cutting process settings. The red arrow in Figure 2 is the motion trajectory. (I remember FastCAM software has similar nesting function and path planning function)

![picture1](https://user-images.githubusercontent.com/53146195/77512878-d4b1ac00-6eae-11ea-9f51-471aaa266a21.jpg)
Figure 1

![picture2](https://user-images.githubusercontent.com/53146195/77513056-2eb27180-6eaf-11ea-8ca2-2e3566650a03.jpg)
Figure 2

![picture3](https://user-images.githubusercontent.com/53146195/77512979-032f8700-6eaf-11ea-993e-debab3ac31c5.jpg)
Figure 3

**Comment by svenhb** [comment]
I think this is too complicated for me.
Perhaps you can do the filling in Inkscape using the Egg-Bot add-ons?
https://wiki.evilmadscientist.com/Hatch_fill

**Comment by lianzaozi** [comment]
thank you
