### ISSUE TITLE
About the method of quickly adjusting the trajectory order

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#113]
If I want to adjust the trajectory order, now click on the Gcode generated by the geometric primitives in the Gcode display area and select "Code Blocks". In the pop-up menu, "Move selected code block up" and "Move selected code block Down" cannot be used. Or you can use Gcode blocks and use shortcut keys to adjust the order.
As shown in Figure 1
![picture1](https://user-images.githubusercontent.com/53146195/77550817-7efbf480-6eec-11ea-97b7-378b2ff398a9.jpg)
 Figure 1

If I can drag the selected Gcode up or down to adjust the order, I think it will be great. As shown in Figure 3, the selected part can be dragged to the position of the red arrow with the mouse.
![picture3](https://user-images.githubusercontent.com/53146195/77550864-8ae7b680-6eec-11ea-92e0-ac6cfa4dd4a9.jpg)
 Figure 3

The first line of the gCode block generated by each geometric element is added to display the name of this geometric element as shown in Figure 2. In this way, if there are many geometric elements, from the gcode display area can help me determine the corresponding gcode block. Which geometric primitive. Of course, directly clicking on the geometric primitive will also highlight the corresponding gcode, which is indeed possible but not convenient. Now directly clicking on the geometric primitive will expand and display the gcode block corresponding to the selected primitive. Sometimes I just select the primitive to see which corresponding Gcode block is. It is not like expanding the gcode block to display it. I hope I can also add When selecting whether the gcode block corresponding to the geometric primitive is collapsed or expanded.
![picture2](https://user-images.githubusercontent.com/53146195/77550962-ac48a280-6eec-11ea-9eab-38619c0d4e51.jpg)
 Figure 2

**Comment by svenhb** [comment]
Move selected code was made for "Groups", I will extend for any block.
I will also try:
- move up/down by one or on top
- Click in 2D-View will not expand a block (perhaps something like Shift + Click will expand)
- perhaps selectable XML-Attributes for the "Figure" Element
- perhaps sorting GCode-Blocks by attributes

**Comment by svenhb** [comment]
Hi, check new version https://github.com/svenhb/GRBL-Plotter/releases/latest
With improoved Code-Blocks handling.

**Comment by lianzaozi** [comment]
> Hi, check new version https://github.com/svenhb/GRBL-Plotter/releases/latest
> With improoved Code-Blocks handling.

how to use

**Comment by svenhb** [comment]
https://github.com/svenhb/GRBL-Plotter/wiki#code-blocks

**Comment by svenhb** [comment]
Hope the sort function for the code-blocks works for you?
