### ISSUE TITLE
Semicircle in DXF file cannot be parsed

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#118]
Semicircle in DXF file cannot be parsed
Figure 1 is displayed by the plotter software
Figure 2 is a CAD file display
"Drawing1.zip" is the dxf file I used for testing
There are the same problems when testing with software versions 1.3.4.4 and 1.3.4.5.

Figure 1
![1](https://user-images.githubusercontent.com/53146195/79300149-78273700-7f18-11ea-98bd-17b15764c28b.png)

Figure 2 
![2](https://user-images.githubusercontent.com/53146195/79300158-7fe6db80-7f18-11ea-826d-081987a2e760.png)

dxf file
[Drawing1.zip](https://github.com/svenhb/GRBL-Plotter/files/4479188/Drawing1.zip)

**Comment by lianzaozi** [comment]
I haven't tested the software version 1.3.4.4 and 1.3.4.5.

**Comment by lianzaozi** [comment]
I used another dxf file with a semicircle to test, and the semicircle in the other dxf file can be displayed. The arc in the file "Drawing1" cannot be displayed. But the problem must not be with the Drawing1.dxf file.

Drawing2 files can be displayed normally.
[Drawing2.zip](https://github.com/svenhb/GRBL-Plotter/files/4479589/Drawing2.zip)

**Comment by svenhb** [comment]
Drawing1 is very small - default setting of 1.00 for step witdh is too low, better use 0.1:
![image](https://user-images.githubusercontent.com/19973251/79328614-a277f500-7f16-11ea-97d0-ca411d4e81fa.png)

**Comment by lianzaozi** [comment]
I'm very sorry. I didn't pay attention to this option before. I tested it according to your method, and the semicircular arc was displayed.

**Comment by svenhb** [comment]
No problem, I will add a detection to correct the "Arc step width" if needed (if radius is too small).
Thanks for your hard testing :-)
