### ISSUE TITLE
Shortcut key for empty track

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#122]
I have a small suggestion, can I change the shortcut key for displaying the empty walk track to press the space bar once to display the empty walk track, and press the space bar again to hide the empty walk track, so that my finger does not have to keep holding the space bar . The current operation method of the software is to hide the empty walking track only by pressing the space bar all the time.

**Comment by svenhb** [comment]
Good idea. I will implement.

**Comment by lianzaozi** [comment]
Thank you

**Comment by lianzaozi** [comment]
I suddenly thought that the space bar will also be used when editing gcode in the gCode display area, so when editing Gcode, it may affect the display of the empty travel track. If it is really influential, you can change the shortcut key that controls the display of the empty travel track to another key

**Comment by svenhb** [comment]
Toggling the pen-up path only appears if the space-bar is pressed when the 2D view has the focus.

**Comment by lianzaozi** [comment]
OK, I get it. thank you for your reply. Hope the plotter software is getting better and better.

**Comment by svenhb** [comment]
Check new release

**Comment by lianzaozi** [comment]
After the modification, it is very convenient to show and hide the empty track, thank you.
