### ISSUE TITLE
Will the plotter software add the function of generating gcode from two-dimensional codes and one-dimensional codes in the future?

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#123]
Will the plotter software add the function of generating gcode from two-dimensional codes and one-dimensional codes in the future?

If the software provides such a function, you can directly use the plotter software to draw the QR code or use the laser to engrave the QR code. Some open source QR code 1D code libraries can be used directly on github. QRCoder (https://github.com/codebude/QRCoder)
QR.NET (https://github.com/aaronogan/QR.NET)
ThoughtWorks.QRCode (http://www.codeproject.com/Articles/20574/Open-Source-QRCode-Library https://github.com/aaronogan/QR.NET)
QRCodeTools (https://github.com/yunfeifei/QRCodeTools)
ZXing
ZBar

**Comment by svenhb** [comment]
It may work to copy the QR image to the clipboard and paste it in GRBL-Plotter.
Or do you need the generation inside GRBL-Plotter?

**Comment by lianzaozi** [comment]
External generation is a way of importing into the plotter software.
I think the plotter software directly integrates the function of generating gcode from two-dimensional codes and one-dimensional codes, which is very convenient to use. Just as the plotter software now supports generating gcode from text / pictures / simple shapes, it is very convenient.

**Comment by lianzaozi** [comment]
ZXing.Net is an open source library that supports two-dimensional codes and one-dimensional codes very well, and can be called by c # language. It can be found on github.

**Comment by svenhb** [comment]
Check menu 'G-Code creation - Create Barcode'
![image](https://user-images.githubusercontent.com/19973251/88341356-c16bfb80-cd3d-11ea-9148-6cb106934739.png)
