### ISSUE TITLE
Outline font fill

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#124]
Recently, when I used the plotter software, I found that there are two fonts built in the plotter software: 1. Single-line font 2. Outline font

There are only 4 fonts that can display Chinese: unicode.lff, kst32b.lff, azomix_i.lff, azomix.lff. These 4 fonts are single-line fonts, which I like very much, but they can only support some Chinese fonts. This leads to the failure to create correct gcode when the Chinese I input is a font that is not supported. I searched through Google for a font that supports Chinese comprehensively. This font is wqy-unicode.lff. The Chinese I entered using this font can be displayed correctly. But this font is outline font. Of course, outline font is very helpful for laser cutting, so laser cutting uses outline font. But if I want to use laser to engrave the characters, I often use it to fill the font. So I hope that the interface of generating gcode from text can add the option of outline word filling. In this way, I can use laser engraving or use a pen to write the effect of filling the font.

Figure 1 is the effect of filling the outline font
![1](https://user-images.githubusercontent.com/53146195/82787969-1c968480-9e9a-11ea-9c18-bbbe7904f8dc.PNG)

Figure 2 is the result of the plotter software's processing of outline fonts
![2](https://user-images.githubusercontent.com/53146195/82787981-21f3cf00-9e9a-11ea-83c1-887d7752e6d7.PNG)

**Comment by svenhb** [comment]
Check new option [Hatch fill](https://github.com/svenhb/GRBL-Plotter/wiki/Import-options#fill-closed-paths) in new release.
![image](https://user-images.githubusercontent.com/19973251/88341617-34757200-cd3e-11ea-984a-8800f934beb3.png)

**Comment by lianzaozi** [comment]
The outline word filling function is very easy to use and great.
