### ISSUE TITLE
Overlay fonts on 5k displays

### ISSUE THREAD

**Issue by wwwlxs** [svenhb/GRBL-Plotter#125]
Overlay fonts on 5k displays
<img width="2560" alt="截屏2020-06-18 上午1 42 50" src="https://user-images.githubusercontent.com/44305220/85363298-1f48d000-b553-11ea-84e3-2d48c9273e1b.png">

**Comment by wwwlxs** [comment]
Some Chinese translations are not very accurate, I can help improve the translation

**Comment by svenhb** [comment]
Wow this is huge :-) But I don't see the bug... 
Are the markers for tool position too big? 
Or should the virtual joystick be larger?
Or the editor?:
![image](https://user-images.githubusercontent.com/19973251/85365532-da5a7480-b525-11ea-8ca5-5f3bfb39634c.png)
You can use Ctrl+Mousewheel to enlarge editor font - perhaps this helps?

>Some Chinese translations are not very accurate, I can help improve the translation

Yes this would be nice - perhaps deliver screenshot (so I know where) and Text to copy&paste for easy replacement.

**Comment by wwwlxs** [comment]
1 It is the editor ，Ctrl+Mousewheel can only scroll up and down，cannot to enlarge editor font on windows10 with iMac.  2 The black comment in the pdf file is ok, the gray is not sure.I don’t know how to use 'Tool change' , so I didn’t modify the translation “how does it work”in Tool change
[grblplotter simplified chinese .zip](https://github.com/svenhb/GRBL-Plotter/files/4827152/grblplotter.simplified.chinese.zip)

**Comment by wwwlxs** [comment]
Another bug?
<img width="2021" alt="截屏2020-06-25 上午2 12 27" src="https://user-images.githubusercontent.com/44305220/85610832-f119dc00-b689-11ea-8c20-458839e7dbb1.png">

**Comment by wwwlxs** [comment]
![截屏2020-06-27 下午7 30 38](https://user-images.githubusercontent.com/44305220/85921197-1f2b3600-b8ad-11ea-9de8-570232670725.jpg)

**Comment by svenhb** [comment]
Check new setting line distance in new release:
![image](https://user-images.githubusercontent.com/19973251/88341751-74d4f000-cd3e-11ea-994b-36746f127209.png)

**Comment by svenhb** [comment]
I assume it is working as expected
