### ISSUE TITLE
Add Pos.A to Tooltable

### ISSUE THREAD

**Issue by wwwlxs** [svenhb/GRBL-Plotter#126]
Hi
Can add Pos.A to Tooltable  in the new version ?My plotter is 4-axis and is placed vertically.I want to make it to a “WaterColorBot” like your YouTube vedio，and How to setup “ToolChange” and “Tooltable” and “G-code modification”？
<img width="658" alt="截屏2020-06-27 下午11 23 03" src="https://user-images.githubusercontent.com/44305220/85925891-041cee00-b8ce-11ea-8272-2e76263b6760.png">
<img width="1004" alt="截屏2020-06-27 下午11 38 35" src="https://user-images.githubusercontent.com/44305220/85926075-61656f00-b8cf-11ea-9f25-bcf3ed5b5ac9.png">

**Comment by svenhb** [comment]
>How to setup “ToolChange” and “Tooltable” and “G-code modification”？  

Not so easy to describe:
1. tools will be seleceted by graphic colors: check video https://www.youtube.com/watch?v=Ebe2kFlE058  at 0:10  
in the video green is assigned for a pen, red / dash line for weak laser, black for strong laser for cutting.
2. Enable Grouping (Graphic Import - Path Import)
3. Add tool exchange command (Graphic Import - Add tool change command)
4. To interrupt drawing to refresh water-color you may want:
![image](https://user-images.githubusercontent.com/19973251/85932478-c4093b80-b8cc-11ea-83ee-f4caa0dabe11.png)
5. Setup your script in 4) for your needs.

>Can add Pos.A to Tooltable in the new version?  

I don't understand how do you select a color. I will insert a a position for tool change position...


In new version (I still need some weeks) tool can also be selected by 
tool-width <-> pen-width
tool-name <-> Graphic-Layer

**Comment by wwwlxs** [comment]
> I don't understand how do you select a color. I will insert a a position for tool change position...
this video shows:
[我的项目 81.MP4.zip](https://github.com/svenhb/GRBL-Plotter/files/4842105/81.MP4.zip)

**Comment by wwwlxs** [comment]
another bug:The simulation preview and actual streaming preview are show different
<img width="221" alt="截屏2020-06-28 下午6 55 29" src="https://user-images.githubusercontent.com/44305220/85945536-1bf97e00-b971-11ea-9aa6-17650e3f5510.png">

<img width="689" alt="截屏2020-06-28 下午7 03 14" src="https://user-images.githubusercontent.com/44305220/85945686-0cc70000-b972-11ea-9e12-250f397e2eaa.png">
[压缩文件.zip](https://github.com/svenhb/GRBL-Plotter/files/4842118/default.zip)

**Comment by wwwlxs** [comment]
another bug? 
this code cannot run in the ZX plane and becomes a circle in the XY plane
`G91 G01 X-8.000 Z0.000 F4000    ( stir brush inside cup )
G02 X0.000 Z0.000 I8.000 K0.000 
G02 X0.000 Z0.000 I8.000 K0.000 
G02 X0.000 Z0.000 I8.000 K0.000 
`

**Comment by svenhb** [comment]
GCode manual says you need to switch the plane via G17, G18 or G19 - not sure if grbl supports this: http://linuxcnc.org/docs/html/gcode/g-code.html#gcode:g2-g3

**Comment by wwwlxs** [comment]
ok，thank you very much，it supported in V1.1 https://github.com/gnea/grbl/wiki

**Comment by svenhb** [comment]
Check new release, unfortunatly not really tested, I hope it works.
![image](https://user-images.githubusercontent.com/19973251/88341881-b1085080-cd3e-11ea-99c1-9aed863a1b81.png)

**Comment by wwwlxs** [comment]
ok, thanks again ,I will check it (maybe tomorrow )
 ,my plotter has some problems now
