### ISSUE TITLE
SVG Line stroke-width map to Z value

### ISSUE THREAD

**Issue by wwwlxs** [svenhb/GRBL-Plotter#127]
Hi sven, Feature request: Line stroke-width map to Z value(Z-Min , Z-Max)(or constrain Z-Min & Z-Max )
![1](https://user-images.githubusercontent.com/44305220/86464949-31045180-bd63-11ea-9802-48d2bcc28e3f.jpg)
![2](https://user-images.githubusercontent.com/44305220/86464964-3b265000-bd63-11ea-97ad-34e4e4a0a13d.jpg)
[line.svg.zip](https://github.com/svenhb/GRBL-Plotter/files/4869404/line.svg.zip)

**Comment by svenhb** [comment]
Yes, I was also thinking about that, but could not generate data for this. I planned to support a graphic-tablet and take drawing data (including pen-pressuse) inside GRBL-Plotter, but I couldnt find example code for windows-form application to include graphic-tablet (examples are always in WPF)...
Anyway I will check how I could support that.

**Comment by wwwlxs** [comment]
> Yes, I was also thinking about that, but could not generate data for this. I planned to support a graphic-tablet and take drawing data (including pen-pressuse) inside GRBL-Plotter, but I couldnt find example code for windows-form application to include graphic-tablet (examples are always in WPF)...
> Anyway I will check how I could support that.

this line was draw from iPad and apple pencil ,  pen-pressuse and svg files was modified  for gcode,

**Comment by wwwlxs** [comment]
or Feature request:Can GCode (with different Z values) be imported into GRBL-Poltter just like SVG is imported into GRBL-Poltter to automatically add A value?

**Comment by svenhb** [comment]
>or Feature request:Can GCode (with different" Z values" by pen-pressure) be imported into GRBL-Poltter just like SVG is imported into GRBL-Poltter for automatically add" A value"?

I don't understand. You can replace 'Z' by 'A' using the editors-replace function (also available via menu). 
What do you mean with "for automatically add" A value" - from where should the 'A' value come?

**Comment by wwwlxs** [comment]
> > or Feature request:Can GCode (with different" Z values" by pen-pressure) be imported into GRBL-Poltter just like SVG is imported into GRBL-Poltter for automatically add" A value"?
> 
> I don't understand. You can replace 'Z' by 'A' using the editors-replace function (also available via menu).
> What do you mean with "for automatically add" A value" - from where should the 'A' value come?

for example,when I draw a curve in adobe illustrator and make GCode  ( with pen-pressure" Z values"  , But at this time there is still a lack of tangential value) with GCode plugin   ,then I import the GCode to GRBLPlotter for adding tangential axis (A value)and tool change ,then send it to plotter.
if I paste the curve from illustrator to GRBLPlotter,tangential axis value and tool change code can be add to GCode from 'G-Code modification 'setting  ,but lack of  "pen-pressure- Z values" .
 if I paste  GCode that exported  from adobe illustrator , all of" Pen-pressure-Z values" are works, but lack of  tangential axis value and tool change code.

**Comment by svenhb** [comment]
Check new option [Translate pen with to Z value](https://github.com/svenhb/GRBL-Plotter/wiki/Import-options#path-interpretation) in new release.

**Comment by wwwlxs** [comment]
> Check new option [Translate pen with to Z value](https://github.com/svenhb/GRBL-Plotter/wiki/Import-options#path-interpretation) in new release.

thanks, I will test it,There may be a bug in version 1.46. I wonder if it has been fixed?  That is, when" tangential axis" and "drag tool compensation" are used together, the angle of rotation and the new track is incorrect. If you create a square track, you can find it

**Comment by svenhb** [comment]
>That is, when" tangential axis" and "drag tool compensation" are used together  
I don't think this is a usefull combination...
But this could be fixed because of "new backbone" during import and path modification.

**Comment by wwwlxs** [comment]
Useful for correcting the position deviation of the tool（ brush ）and the axis

**Comment by svenhb** [comment]
I checked the code - it will not work, because: 
1st I calculate the tangential angle of the original graphic
2nd I calculate new drag-knife path

For the next version I will switch the order - than it could work as expected.

**Comment by wwwlxs** [comment]
HI svennb,In the same svg file, some lines have variable z values, but the z values ​​of some lines do not change with the line width.SVG file:
[A5.zip](https://github.com/svenhb/GRBL-Plotter/files/4974953/A5.zip)
The red marked lines have the same z value for each segment, and the black ones are variable
<img width="844" alt="截屏2020-07-25 下午1 55 45" src="https://user-images.githubusercontent.com/44305220/88450070-cab0b180-ce7e-11ea-929d-08abf4400d66.png">

**Comment by wwwlxs** [comment]
![Uploading C.jpg…]()

**Comment by wwwlxs** [comment]
![Dragtool](https://user-images.githubusercontent.com/44305220/88469289-9393dc00-cf22-11ea-89fc-c71104b90ba4.jpg)
Will this （ green line）change with the z value of each line?  Or can it only be based on the setting of z-Height engrave?

**Comment by wwwlxs** [comment]
![B2](https://user-images.githubusercontent.com/44305220/88609351-7728a880-d0b6-11ea-960b-07c4af5b1f22.jpg)

**Comment by svenhb** [comment]
Version 1) is my current implementation 
You mean like version 2) ?
![image](https://user-images.githubusercontent.com/19973251/88625068-5f4a2800-d0a8-11ea-8b5b-81802d57dab7.png)

**Comment by svenhb** [comment]
From your post above:  
>Will this （ green line）change with the z value of each line? Or can it only be based on the setting of z-Height engrave?  
  
Nice graphics to show the relationship z-depth and radius - It will be calculated from the initial 'Z-Heigth engrave'

**Comment by svenhb** [comment]
Check new release for missing z-depth - because of path reversing, z-data got lost

**Comment by wwwlxs** [comment]
> From your post above:
> 
> > Will this （ green line）change with the z value of each line? Or can it only be based on the setting of z-Height engrave?
> 
> Nice graphics to show the relationship z-depth and radius - It will be calculated from the initial 'Z-Heigth engrave'


> Version 1) is my current implementation
> You mean like version 2) ?
> ![image](https://user-images.githubusercontent.com/19973251/88625068-5f4a2800-d0a8-11ea-8b5b-81802d57dab7.png)

Yes, I mean that version 2 is reserved for the brush as the default function, which will suit the actual soft brush. If the length of each green line is very long, you can keep version1 as an option and use it for hard pen lines

**Comment by wwwlxs** [comment]
> Check new release for missing z-depth - because of path reversing, z-data got lost

 z-data got lost:)

**Comment by wwwlxs** [comment]
[H.zip](https://github.com/svenhb/GRBL-Plotter/files/4991852/H.zip)
I tested the svg file on V15.02 and it doesn't seem to work.  
"A generic error occurred in GDI+ "pops up, and the generated gcode is still the same as version 15.01

**Comment by wwwlxs** [comment]
> From your post above:
> 
> > Will this （ green line）change with the z value of each line? Or can it only be based on the setting of z-Height engrave?
> 
> Nice graphics to show the relationship z-depth and radius - It will be calculated from the initial 'Z-Heigth engrave'

If the length of the green line can be changed with different Z values, it will be more accurate

**Comment by svenhb** [comment]
![image](https://user-images.githubusercontent.com/19973251/88842548-eb12a000-d1df-11ea-825d-8ad593ab18e9.png)

New option to make a ramp instead of steps...
Check new release

**Comment by wwwlxs** [comment]
> ![image](https://user-images.githubusercontent.com/19973251/88842548-eb12a000-d1df-11ea-825d-8ad593ab18e9.png)
> 
> New option to make a ramp instead of steps...
> Check new release
Thank you very much, you are great! I test by this file: https://github.com/svenhb/GRBL-Plotter/files/4991852/H.zip,The new version is work!

**Comment by wwwlxs** [comment]
> ![image](https://user-images.githubusercontent.com/19973251/88842548-eb12a000-d1df-11ea-825d-8ad593ab18e9.png)
> 
> New option to make a ramp instead of steps...
> Check new release
But there are still some problems, the line direction is reversed, which is wrong for writing calligraphy

**Comment by lianzaozi** [comment]
Why is the GCode generated by opening H.SVG different from the uploaded H.nc

image2 is a screenshot of my opening H.SVG
![image2](https://user-images.githubusercontent.com/53146195/89005142-540c2c00-d336-11ea-94d0-3c286944025e.png)


image3 is a screenshot of my opening H.nc
![image3](https://user-images.githubusercontent.com/53146195/89005118-4787d380-d336-11ea-9d8a-ba39d8841a5a.png)

**Comment by wwwlxs** [comment]
> Why is the GCode generated by opening H.SVG different from the uploaded H.nc
> 
> image2 is a screenshot of my opening H.SVG
> ![image2](https://user-images.githubusercontent.com/53146195/89005142-540c2c00-d336-11ea-94d0-3c286944025e.png)
> 
> image3 is a screenshot of my opening H.nc
> ![image3](https://user-images.githubusercontent.com/53146195/89005118-4787d380-d336-11ea-9d8a-ba39d8841a5a.png)
Try to increase the range of “z-height engrave” 
![7C7427EA-74D2-490F-BE06-7D4C514D38D1](https://user-images.githubusercontent.com/44305220/89054812-03272280-d38c-11ea-9984-8b262a277796.jpeg)

**Comment by svenhb** [comment]
I don't know when you saved the .nc file....
Gcode (like your H.nc) can not be modified with all the new options - it is only for import of SVG or DXF files....
And there is no chance for implementation.
The difference is because of the new option "Apply ramp instead of a step" to get the Z movement as shown in example 2).   

![image](https://user-images.githubusercontent.com/19973251/89062409-abc28b80-d366-11ea-9976-2ebf28ff39b5.png)

**Comment by wwwlxs** [comment]
> And there is no chance for implementation.

hi svenhb， I uploaded the newest calligraphy test video to my instagram, you are welcome to take a look.if “drag tool compensation”can be calculated
 from pen width，it will be better. But it's pretty good now.thank you very much.
![3C2BC090-13F8-4475-A022-1BA8E0C96A52](https://user-images.githubusercontent.com/44305220/89092186-267cbc80-d3e2-11ea-996d-aeb881eff445.jpeg)

**Comment by lianzaozi** [comment]
Thank you very much for your reply
I used the H.SVG file you uploaded, but I can't get the Z-axis coordinates of the gradient. I don't know why. From the gif animation, I can see that the Z-axis coordinates of the GCode I get are all -1. The whole process of operating the software can be seen in the gif animation


![gif1](https://user-images.githubusercontent.com/53146195/89100446-9c584680-d429-11ea-8aa9-f41e08a83672.gif)

**Comment by svenhb** [comment]
The maximum depth (or minimum Z value) is limited by the engrave depth - for safety reasons...
![image](https://user-images.githubusercontent.com/19973251/89100525-df012b00-d3f7-11ea-8289-99a72494d45f.png)

**Comment by lianzaozi** [comment]
You are right, thank you, now you can get the Gcode where the value of the Z axis changes with the line width. After your guidance, the software is now working properly.

**Comment by svenhb** [comment]
Drag tool % now checks actual depth

**Comment by wwwlxs** [comment]
> w with Version

thanks！

**Comment by wwwlxs** [comment]
> Before: "Drag tool Offset in % of Z-depth" used the "Z-heigth engrave" value.
> Now with Version 1.5.0.4 : it uses the Z-depth, calculated by penWith (if option is enbaled
> ![image](https://user-images.githubusercontent.com/19973251/89330716-f6a71080-d690-11ea-9bb6-fae6e360deb6.png)

<img width="521" alt="image" src="https://user-images.githubusercontent.com/44305220/89357692-d197b980-d6f3-11ea-955f-091fbd80c107.png">
thanks you very much，It  work now！ Maybe there is a problem with my SVG file, or there is a problem with my settings, the lines are a bit jittery，I will try further and submit to you if there is any problem

**Comment by svenhb** [comment]
Seems to work
