### ISSUE TITLE
A axis and B axis can only use 1 axis, but display 2 axis

### ISSUE THREAD

**Issue by wwwlxs** [svenhb/GRBL-Plotter#128]
A axis and B axis can only use 1 axis, but display 2 axis
![截屏2020-07-04 下午5 19 31](https://user-images.githubusercontent.com/44305220/86509455-ab43dd00-be1a-11ea-8d90-073da4938e71.jpg)
![截屏2020-07-04 下午5 19 24](https://user-images.githubusercontent.com/44305220/86509457-abdc7380-be1a-11ea-8455-7d60ce619237.jpg)
![截屏2020-07-04 下午5 20 52](https://user-images.githubusercontent.com/44305220/86509472-d5959a80-be1a-11ea-843f-efe87fdeb62a.jpg)

**Comment by svenhb** [comment]
Your controller probably controls 5 axis - correct? Then A must be named "A":
And I think GRBL 4th axis can be switched off.  
![image](https://user-images.githubusercontent.com/19973251/86509842-21305000-bdeb-11ea-9c99-1ae5c3e9b40b.png)

**Comment by wwwlxs** [comment]
yes,grbl-Mega-5X,5 axis,arduino Mega2560+ramps1.4

**Comment by wwwlxs** [comment]
![IMG_8946 2](https://user-images.githubusercontent.com/44305220/86510710-b0a62500-be24-11ea-85e1-0e30ea0ec050.jpg)

**Comment by wwwlxs** [comment]
https://github.com/fra589/grbl-Mega-5X. and end stop doesn't  works

**Comment by svenhb** [comment]
Does it work now? I think it is a settings issue.

**Comment by wwwlxs** [comment]
It's not working for the time being, and it has not been retested. The homing function of grbl-mega-5X does not work

**Comment by wwwlxs** [comment]
> Does it work now? I think it is a settings issue.

![C44](https://user-images.githubusercontent.com/44305220/88468973-eb7c1400-cf1d-11ea-825a-6af4cfb89376.jpg)
![C4442](https://user-images.githubusercontent.com/44305220/88469013-67765c00-cf1e-11ea-821e-b8f3861c151a.jpg)

**Comment by svenhb** [comment]
Should be fixed in 1.5.0.1 (except gamepad)

**Comment by svenhb** [comment]
I will not change the GamePad dialog - the user has to be careful himself
