### ISSUE TITLE
Questions about simulation and offset

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#129]
Thank you for your hard work. This version brings exciting features. I like it very much. Below are the problems I encountered in my test (the software version used for the test is V1.5.0.0)

1. V1.5.0.0 version of the software can now simulate circles and arcs (G02 and G03), but the software will pop up an error when simulating circles and arcs (G02 and G03). As shown in Figure 1
![picture1](https://user-images.githubusercontent.com/53146195/88364872-dfc20d80-cdb6-11ea-92e6-d1842db2442c.png)

2. After setting the offset, the position of the red graphic will change, but the position of the gray graphic will not change, and it will remain at the original position. as shown in picture 2
3. The gif file can show the whole process of my operation and the screen record of the problem.

![picture2](https://user-images.githubusercontent.com/53146195/88364878-e3559480-cdb6-11ea-88ac-085992a0940a.png)

git
![123](https://user-images.githubusercontent.com/53146195/88364889-e81a4880-cdb6-11ea-9e62-a6d4685b1e6d.gif)

**Comment by lianzaozi** [comment]
During simulation, there is a pause at one point of the arc, and there is no pause at the other point. The phenomenon can be observed in the gif animation. Below is the dxf file I used for testing. The position indicated by the mouse in the 1234.gif file is the position where the simulation will pause.

![1234](https://user-images.githubusercontent.com/53146195/88371379-7e099f80-cdc6-11ea-8933-798c03506d26.gif)

There is a test dxf file that is paused during simulation
[2013.zip](https://github.com/svenhb/GRBL-Plotter/files/4970783/2013.zip)


Test dxf file for simulation and offset problems
[circle.zip](https://github.com/svenhb/GRBL-Plotter/files/4970788/circle.zip)

**Comment by svenhb** [comment]
Strange: 2013.dxf is simulated correctly -  without error (which may causes the pause after each arc on your side).
Did you use special options? Perhaps you can check the logfile for more information?
In the "About" window you will find the startup path, where "logfile.txt" is located.

I used this options (using z axis) and get just one figure:
![image](https://user-images.githubusercontent.com/19973251/88389247-61656b80-cdb6-11ea-829b-8dd82ef555de.png)

**Comment by lianzaozi** [comment]
I probably found the reason for the pop-ups and pauses in the simulated circle and arc. I found that as long as the use cases are selected as "example_laser" and "example_laser_and_pen", it will happen when the simulated circle and arc have pop-up windows, and in the arc Another point of the phenomenon will stop. Other use cases do not have this problem.

"11111.png" is the use case I chose in this picture

![11111](https://user-images.githubusercontent.com/53146195/88400837-7b756d00-cdfb-11ea-8b15-f2b6d0b895f7.png)

**Comment by svenhb** [comment]
Should be fixed in 1.5.0.1

**Comment by lianzaozi** [comment]
Thank you very much.

The V1.5.0.1 version of the software has solved the problem of simulated arc pop-ups and pauses, and the problem of offset has also been solved.

**Comment by svenhb** [comment]
Thank you for testing
