### ISSUE TITLE
How to add missing words to the lff file?

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#130]
The Chinese in unicode.lff is not complete, I want to add the missing words, but I don’t know what tool to edit it and the steps of operation.

**Comment by lianzaozi** [comment]
Where are the fonts in the screenshot below stored?


![image1](https://user-images.githubusercontent.com/53146195/88453455-8979cb00-ce99-11ea-9304-df22b83009ff.png)

**Comment by svenhb** [comment]
These fonts are inside GCodeCreation\CreateFromForm\GCodeFromFontHershey.cs
Check here: https://gitlab.com/oskay/hershey-text/tree/master/hershey-text/svg_fonts
and here https://www.evilmadscientist.com/2019/hershey-text-v30/

**Comment by lianzaozi** [comment]
Thank you, I know the source of these fonts.

What tools do you use to edit lff fonts? For example, I want to add Chinese to unicode.lff font, how do I do it? Do you mean that you can edit and make lff fonts using inkscape software?

Does the software after version V1.5.0.1 support the analysis of numbers and letters (ttf) in dxf files? I tested that the following numbers and letters can be displayed, but Chinese does not support display.

**Comment by svenhb** [comment]
I didn't edit any font, I just took the data I found.  
With inkscape it may work: http://write.flossmanuals.net/start-with-inkscape/creating-fonts/#:~:text=Creating%20Custom%20Fonts,-With%20HTML5%20and&text=Fonts%20can%20be%20saved%20in,under%20Text%20%3E%20SVG%20Font%20Editor%20.

**Comment by svenhb** [comment]
Can't help here.
