### ISSUE TITLE
The plotter software opens gcode and reports an error

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#131]
Open gcode with Chinese annotations with the software version between V1.3.4.4 and V1.5.0.0, the software will pop up an error message, but the software version is between V1.3.4.3 and v1.3.3.0 When opening gcode with Chinese annotations, the software can be opened and displayed normally.

Test files
[DemoTest_UTF-16 BE.zip](https://github.com/svenhb/GRBL-Plotter/files/4975347/DemoTest_UTF-16.BE.zip)

Use V1.5.0.0 version software to open the error screenshot
![image2](https://user-images.githubusercontent.com/53146195/88454410-090b9800-cea2-11ea-81d2-40da5529d1b2.png)

**Comment by svenhb** [comment]
Should be fixed in 1.5.0.1

**Comment by lianzaozi** [comment]
Thank you very much, the Chinese comments are now displayed normally for the software version V1.5.0.1
