### ISSUE TITLE
Regarding the problem of garbled characters in the Chinese layer name displayed in the gcode editing area

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#134]
FastColoredTextBox.dll supports displaying Chinese, and the path containing Chinese in the screenshot can be displayed normally. But the layer name of the Chinese name in the dxf file is displayed as garbled characters.

![image5](https://user-images.githubusercontent.com/53146195/88469920-0f912280-cf29-11ea-900d-ff69b8c983e4.png)

**Comment by svenhb** [comment]
Cab you upload this file for testing?
How did you open your file?

**Comment by lianzaozi** [comment]
Sorry I forgot to upload my test file. I used several different dxf files to test and found that the Chinese layer name in test1 was garbled, and the Chinese layer name in test2 was displayed normally. I use CAD to open the test1 and test2 files in the cad software, and the Chinese layer names of these two files can be displayed normally.

Chinese layer names display garbled characters
[test1.zip](https://github.com/svenhb/GRBL-Plotter/files/4979132/test1.zip)


Chinese layer names are displayed normally
[test2.zip](https://github.com/svenhb/GRBL-Plotter/files/4979135/test2.zip)

**Comment by lianzaozi** [comment]
The way I open the file:
  "File"=>"open file" Select the .nc file to be opened, and click the ok button.

**Comment by svenhb** [comment]
If I open both files in LibreCad, test2 looks normal, test1 is already garbled - so the source is not ok:
![image](https://user-images.githubusercontent.com/19973251/88624419-39705380-d0a7-11ea-8d49-57a7a3d43b10.png)

**Comment by lianzaozi** [comment]
Thank you, I just used librecad to test the layer name of the test1 file is garbled. I used another brand of cad software to open the test1 file. In that cad software, the layer names of test1 and test2 can be displayed normally.

I will only use librecad when testing in the future, which can avoid some strange problems.

**Comment by svenhb** [comment]
>I will only use librecad when testing in the future, which can avoid some strange problems.   
  
Good idea, thanks
