### ISSUE TITLE
Also add "Closed path overlap" function to generate circles and rectangles from simple graphics?

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#136]
The new "Closed path overlap" function of the software is very good, but this function is only effective for vector graphics such as dxf and svg.
Is it possible to add the "Closed path overlap" function for the "Create Simple Shapes" function to generate from circles and rectangles?

**Comment by svenhb** [comment]
Simple shape dialog creates gcode directly, too much work to add overlap function here.
Better import shapes and then enable the overlap option.
