### ISSUE TITLE
Improve the left-click to select other geometric primitives

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#140]
Thanks for your hard work

Now the plotter software has an inconvenient use, that is, when I select certain geometric primitives by left-clicking in the track display area, I often select other geometric primitives near this geometric primitive. But left-click on other geometric primitives can sometimes be accurately selected. This problem exists in every version of plotter software.

Test dxf file
[2007.zip](https://github.com/svenhb/GRBL-Plotter/files/5025601/2007.zip)

The circles and lines selected in the blue frame in the screenshot, I left-click on them, and the graphics near them are selected. When I zoomed in and displayed the track display area and left click on them, sometimes I could select them again.
![image1](https://user-images.githubusercontent.com/53146195/89361718-8fc04080-d6fe-11ea-9f3f-30d4db9c257c.png)

The small cross mark in the gif animation that demonstrates the operation process is the position of my mouse. When I left click the mouse, the cross mark will have a highlighted yellow circle, by looking at whether there is a yellow circle at the cross mark Can tell if I pressed the mouse button.
![gif1](https://user-images.githubusercontent.com/53146195/89361938-268cfd00-d6ff-11ea-8d63-94f221a20a8f.gif)

**Comment by svenhb** [comment]
Yes, I know. Up to know  I just look for known coordinates near by, which are known from G-Code. To find a line when clicking in the middle, I need to interpolate all possible coordinates inbetween...

**Comment by lianzaozi** [comment]
Thank you for your reply.

**Comment by svenhb** [comment]
Check new release for improovement: https://github.com/svenhb/GRBL-Plotter/releases

**Comment by lslouka** [comment]
Hello.
I have a problem with compile firmware for ATMEGA 2560. When I connect atmega, I read only Missing 11 Real-time Status Reports per 10 seconds. 
If I use your hex file grbl-Mega-5X-v1.1l.20190605.hex all is working fine.
Can you please send me a GRBL code for arduino IDE from which was generate this hex file? I must set some settings for my machine.
My e-mail adress is: ace1x@centrum.cz

**Comment by svenhb** [comment]
Hello,
as I remember I took the hex file directly from here: https://github.com/fra589/grbl-Mega-5X/releases.
But I'm not sure, so need to look on my computer.

**Comment by lianzaozi** [comment]
When the software of V1.6.0.1 selects a straight line, other straight lines are also selected, and when an ellipse is selected, the elliptical arc will also be selected.

**Comment by lianzaozi** [comment]
![11111](https://user-images.githubusercontent.com/53146195/128525810-6325d76f-5aef-4529-bf28-30a4f707160b.png)
![222222](https://user-images.githubusercontent.com/53146195/128525826-46c2f0af-fee9-4aaf-9758-251a0c22812e.png)
![123456789](https://user-images.githubusercontent.com/53146195/128525840-61dd745f-b361-4e18-ba4c-d312f9c76265.gif)
[2007_test_dxf.zip](https://github.com/svenhb/GRBL-Plotter/files/6946143/2007_test_dxf.zip)

**Comment by svenhb** [comment]
Because the lines are placed in same figure (the two arcs also).
Will fix this

**Comment by lianzaozi** [comment]
The software of V1.6.0.2 cannot open the dxf file. The dxf file "2007_test_dxf.zip" used in the test has been uploaded.
![111111](https://user-images.githubusercontent.com/53146195/129641303-f9da98bb-56ed-498f-9b21-cd87e80a526a.png)

![22222](https://user-images.githubusercontent.com/53146195/129641320-601c1d00-fc2a-42af-a972-2911c66a9d38.png)

**Comment by svenhb** [comment]
I updated the setup in the 1.6.0.2 release

**Comment by lianzaozi** [comment]
What do I need to set up to read DXF files properly

**Comment by svenhb** [comment]
>What do I need to set up to read DXF files properly 
 
What do you mean?

**Comment by lianzaozi** [comment]
> > 我需要设置什么才能正确读取 DXF 文件
> 
> 你的意思是？

The latest version of the software can not load the DXF file, what can I do?

**Comment by svenhb** [comment]
1.6.0.3 can : https://github.com/svenhb/GRBL-Plotter/releases/download/v1.6.0.2/GRBL-Plotter_1603_release.zip

**Comment by lianzaozi** [comment]
hello

How to set slotting compensation in plotter software? If I cut the size of 100*100, in the laser cutting process, the laser will burn some of the material, resulting in the cut out of the size of less than 100*100

**Comment by svenhb** [comment]
Try cutter radius compensation, use + or - radius for inner or outer contour:
Grey background path shows original path, before radius compensation. Result depends on figure path direction: clockwise or counter-clockwise.
![image](https://user-images.githubusercontent.com/19973251/130293046-4e96e59f-4829-441d-b078-7114aedb5f48.png)

**Comment by lianzaozi** [comment]
Thank you for your answer. If I want to cut a circle, both inside and outside of it need to be compensated. Is there any way to do that?

**Comment by lianzaozi** [comment]
Cut concentric rings

**Comment by svenhb** [comment]
Perhaps, 
- load graphic, do radius compensation inside, cut inside
- load graphic, do radius compensation outside, cut outside 

I would create both cuts in LibreCad via Polyline - Equidistance polyline
![image](https://user-images.githubusercontent.com/19973251/130311518-5fae00d1-9179-4b0d-85ce-40918bce14ba.png)

**Comment by lianzaozi** [comment]
Thank you for your answer. I don't quite understand. Does it have to be cut twice? Can it be solved once and for all? If there are too many concentric rings to cut, then the procedure is a little cumbersome

**Comment by svenhb** [comment]
Perhaps I don't understand your needs: I though you want to cut a circle inside and outside the shape - for me the result is a ring.

**Comment by lianzaozi** [comment]
yes

**Comment by lianzaozi** [comment]
The effect of clicking the left button to select primitives has been improved a lot, which is very good. I will conduct more tests. The software version I use for testing is V1.6.0.5.

**Comment by lianzaozi** [comment]
An error is reported when the software of the applicable version V1.6.0.5 opens the ".nc" file, which is automatically generated by the plotter software reading the dxf file.

nc file
[2007_test - 1_.zip](https://github.com/svenhb/GRBL-Plotter/files/7026316/2007_test.-.1_.zip)

dxf file

[2007_test - 1dxf.zip](https://github.com/svenhb/GRBL-Plotter/files/7026317/2007_test.-.1dxf.zip)

**Comment by lianzaozi** [comment]
![123](https://user-images.githubusercontent.com/53146195/130336787-203de0fe-cddb-436c-a9d4-b448bce616ca.gif)

**Comment by svenhb** [comment]
I updated the setup to 1.6.0.6
https://github.com/svenhb/GRBL-Plotter/releases/download/v1.6.0.5/GRBL-Plotter_Setup.exe

**Comment by svenhb** [comment]
Also update of changed files: GCodeVisuAndTransform.cs, MainFormLoadFile.cs

**Comment by svenhb** [comment]
I think it's solved and works
