### ISSUE TITLE
Add an example to allow users to customize the generated GCode format

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#141]
I found a problem today. I used plotter software to convert the dxf file into a GCode file, and then I let a laser device read the GCode and run it, but the device reported an error. After my inspection, I found that there is no space after a line of GCode. I know that the GCode generated by the plotter software will automatically add a space after it. This error may be caused by manually modifying GCode outside the plotter software to delete the spaces at the end of the line. However, it is difficult for people to judge whether there are spaces after each line.

Based on the above considerations, I have the following ideas
1. So I wonder if the plotter software can be a TextBox control when generating GCode. If I fill in a semicolon (;) in this TextBox control, there will be a semicolon after each line of GCode generated. (This setting item is made optional)
2. I want to be able to make a TextBox control when the plotter software generates GCode. If I fill in "M10;G04 T50;" in this TextBox control, I can insert between G00 and G01/G02/G03 "M10;G04 T50;". (This setting item is made optional)
3. I want to be able to make a TextBox control when the plotter software generates GCode. If I fill in "M30;G04 T20;" in this TextBox control, I can insert it between G01/G02/G03 and G00 "M30;G04 T20;". (This setting item is made optional)

In this way, it is convenient for users to generate a GCode format that conforms to their own. As far as I know, the plotter software now allows users to customize the header and footer of GCode, which is great.

To illustrate my idea, I made two pictures to illustrate, image1 is the GCode style generated by the plotter software that the user has not set the GGcode format. image2 is the GCode format generated by the plotter software after the user sets some conditions that meet his own requirements.

image1
![image1](https://user-images.githubusercontent.com/53146195/89643210-dc1aa480-d8e7-11ea-8d2b-1bc74c631ad2.png)

image2
![image2](https://user-images.githubusercontent.com/53146195/89643236-eccb1a80-d8e7-11ea-8ce0-bd8e28834364.png)

**Comment by svenhb** [comment]
For 2) and 3) the individual Pen up/down commands should work:
![image](https://user-images.githubusercontent.com/19973251/89775748-bfa98280-db08-11ea-9c6b-bc49553650e7.png)

**Comment by lianzaozi** [comment]
Thank you
For 2 and 3, I tested according to the method you said, and the test results fully meet my requirements

**Comment by svenhb** [comment]
Now 1) is also implemented - I don't if it is useful. Perhaps indivdual line end disappears after G-Code transformation...
![image](https://user-images.githubusercontent.com/19973251/90317017-af3d4180-df26-11ea-8066-0199762db56f.png)

**Comment by lianzaozi** [comment]
When the "apply text at line end" function is enabled, can the next version of the plotter software add the same symbol after each line of GCode? I have a good idea to call one when GCode is exported and saved A method to add symbols to each line of GCode. This may solve the problem that some CGode lines have symbols after them, and some CGode lines have no terminator after them, because in order to maximize the avoidance of other problems, you only need to traverse each line when saving (the lines with comments are ignored) GCode and then Add a symbol to the end of the line. The saved GCode will add a symbol at the end of each line.

**Comment by svenhb** [comment]
Function is implemented
