### ISSUE TITLE
Problems with opening dxf files in plotter software V1.5.0.0 or later

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#146]
There is a problem with the plotter software V1.5.0.0 and later versions. There will be problems when opening the 1.dxf file, but it can be opened normally with the software version before V1.3.4.6

Test dxf file
[1.zip](https://github.com/svenhb/GRBL-Plotter/files/5049930/1.zip)

**Comment by svenhb** [comment]
LibreCad shows also errors when loading...
I need to figure out how to handle this problem
![image](https://user-images.githubusercontent.com/19973251/89770483-2033c200-daff-11ea-9f9a-78bec1b5170d.png)

**Comment by lianzaozi** [comment]
Thank you for your reply. This is a screenshot of the "1.zip" file opened with the software version V1.3.4.6.
![image1](https://user-images.githubusercontent.com/53146195/89775639-d7016380-db3a-11ea-8f19-e499c030a925.png)

**Comment by svenhb** [comment]
Should be fixed. Reason: somwhere is anArc with r = 1.1e-13 too small for float, caused error when drawing an Arc.

**Comment by lianzaozi** [comment]
Thank you for fixing the problem in time, and I will conduct some tests.

**Comment by svenhb** [comment]
I hope your tests were succesful
