### ISSUE TITLE
Chinese translation error correction

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#148]
Copy the Chinese in the document and replace the Chinese in the original location.
[Chinese translation error correction.zip](https://github.com/svenhb/GRBL-Plotter/files/5055635/Chinese.translation.error.correction.zip)

**Comment by lianzaozi** [comment]
supplement
decimal places=======>小数位

**Comment by svenhb** [comment]
I took your translations, thanks.

**Comment by lianzaozi** [comment]
Thank you for correcting some Chinese translations, the Chinese translation in the screenshot below also needs to be corrected

MainForm
![image](https://user-images.githubusercontent.com/53146195/90407692-5b268e80-e0d9-11ea-99c5-338f6854e414.png)
Ruler==========>标尺

![image](https://user-images.githubusercontent.com/53146195/90408092-f1f34b00-e0d9-11ea-80a8-3beedd981934.png)
Pen-Up path==============>笔上升路径(快速定位)

ControlSetupForm
![image](https://user-images.githubusercontent.com/53146195/90408380-56aea580-e0da-11ea-96b4-be2edaf3f9fe.png)
Min===================>最小

**Comment by svenhb** [comment]
Thank for your help
