### ISSUE TITLE
Using Multiple Fiducials for modifying the cutting file

### ISSUE THREAD

**Issue by futurau** [svenhb/GRBL-Plotter#149]
Hi sven

I have a A3 printer and I can print on fabrics. I want to cut this printed fabrics. But the printed artwork deforms some time 2-3mm.

Feature request:
I want to put some registration marks (fiducials) and read the marks with a camera to correct the cut path automatically.

Is it possible to add this capability?

**Comment by svenhb** [comment]
Hello,
it is already implemented, but I haven't tried for a long time...   
https://github.com/svenhb/GRBL-Plotter/wiki/PCB-drilling 
Let me know if it works, or how to improove.

**Comment by futurau** [comment]
Thank You
I will try asap.

**Comment by svenhb** [comment]
Hope it's working
