### ISSUE TITLE
Which point is the zoom center of the zoom GCode operation?

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#150]
Hi svenhb
1. Rotating GCode takes the intersection of diagonal lines with the largest area occupied by the track as the center of rotation.
2. Zoom X/Zoom Y is to zoom in the midpoint of the X direction/the midpoint of the Y direction
3. Mirror X/Mirror Y is to mirror the midpoint in the X direction/the midpoint in the Y direction
4. Scale XY By...% Is the zoom center of this function also the intersection of the diagonals with the largest area occupied by the track?

**Comment by lianzaozi** [comment]
Sorry, the software already supports increasing the number of user-defined buttons, I found a way to increase the number

**Comment by svenhb** [comment]
Yes, for 4) it should also be the center of the figure-dimension.

**Comment by lianzaozi** [comment]
Thank you
