### ISSUE TITLE
Z-axis display in 2D window for simulator

### ISSUE THREAD

**Issue by beautifulsmall** [svenhb/GRBL-Plotter#152]
The simulator only displays x and Y axis, could the Z axis be displayed in either the 2Dbox or the xyz in the main xyz display for simulation only ? great program.

**Comment by svenhb** [comment]
>or the xyz in the main xyz display 
good idea!
Will try to implement soon.

**Comment by svenhb** [comment]
It's implemented now, thanks for the idea
![image](https://user-images.githubusercontent.com/19973251/96351276-971aa780-10ba-11eb-9b11-9349359a95d2.png)
