### ISSUE TITLE
Loosing settings when copy-pasting the solution

### ISSUE THREAD

**Issue by amoineau** [svenhb/GRBL-Plotter#153]
**Describe the bug**
I'm using your amazing work to build an HMI for a machine. Among other modifications, I wanted to change the custom buttons to fit my needs. I tried changing through the Settings in VS but it wasn't updated when launching the app. I then realised that I could change them at runtime through the setup menu. This worked fine but when I tried to copy-paste the solution (or even the build) to an USB stick to bring it to the PC connected to the machine I realised that everything was back to default.

Edit: I tried pushing the modified version to github and cloning on the other PC but ended up with the same result (not a big surprise but thought it would be worth mentioning)

**To Reproduce**
1. Download the newest release
2. Open the app and change a custom button behavior
3. Close eveything
4. Copy paste the solution somewhere else on your drive
5. Open the copy

**Expected behavior**
The changes should be visible on the copied version.

Thank you very much for your help and for all the hard work you must have put in this project !

**Comment by svenhb** [comment]
Thanks for the detailed description. You have two options:
1) Export and import the setting to an INI file:
![image](https://user-images.githubusercontent.com/19973251/96272197-141c2300-0fce-11eb-8725-4c60bb958068.png)

2) Or find the location of the properties (somewhere in c:\User\YourUser\AppData\Local\GRBL_Plotter\someStrangePathLike GRBL-Plotter.exe_Url_dfcqomyqns4mxblxdl1jbpyubn5ak31o\Version\user.config.
Copy this user.config and paste it to your new location....

**Comment by svenhb** [comment]
As shown here https://grbl-plotter.de/index.php?id=auto-pen-change you can now drop INI file to change settings.

**Comment by amoineau** [comment]
Thanks for the swift reply ! I feel kind of dumb... A week ago I wondered what this machine config meant and when I reached my problem I didn't put two and two together.
