### ISSUE TITLE
The software of version 1.5.2.0 has some problems in the function of x=0 and y=0 when importing DXF graphics.

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#154]
When using version 1.5.2.0 software to import dxf graphics, check the option "Offset graphics origin to 0;0". The dxf graphic is not offset to the coordinates x=0, y=0

In the 1.5.0.5 version of the software, the offset is 0; the 0 function can work well.

The screenshot image1 below is a screenshot of using 1.5.0.5 version software to test the offset to coordinates x=0 and y=0. The screenshot image2 is a screenshot that uses the 1.5.2.0 version of the software to test the offset to the coordinates x=0 and y=0.

image1  （using 1.5.0.5 version software）
![image1](https://user-images.githubusercontent.com/53146195/96392598-2d4fea00-11ef-11eb-99d2-f0b961e56a92.png)

image2 （using 1.5.2.0 version software）
![image2](https://user-images.githubusercontent.com/53146195/96392627-448ed780-11ef-11eb-9e0e-8c1bf5d86247.png)

**Comment by svenhb** [comment]
Check new version https://github.com/svenhb/GRBL-Plotter/releases/latest

**Comment by lianzaozi** [comment]
Thank you, the problem is solved

**Comment by svenhb** [comment]
Should still work
