### ISSUE TITLE
Problem in 'M' commands!

### ISSUE THREAD

**Issue by BehiTaj** [svenhb/GRBL-Plotter#155]
**Problem in 'M' commands**
At the first I have to thanks for having this project.
I’m beginner in using GRBL and have a question.
G-code commands sent in order and stay in line then also execution occurred in order too , but M codes executed while they enter the buffer without staying in line.
Whereas we want after finishing some special G-code commands run the M code.
Actually we want the M codes also stays in line too.

**Comment by svenhb** [comment]
I'm not sure if I understand your question, perhaps you should give a real example.

As written here, order of execution of command in one line is defined: http://linuxcnc.org/docs/html/gcode/overview.html#_g_code_order_of_execution

If you talk about commands for pen-up/-down, you can add your own commands and M-Codes here. Seperation by ';' means starting a new command-line:
![image](https://user-images.githubusercontent.com/19973251/96567676-5a6fcb80-12c7-11eb-8e8a-b5d84193b06e.png)
