### ISSUE TITLE
Line number in gcode

### ISSUE THREAD

**Issue by BehiTaj** [svenhb/GRBL-Plotter#157]
**Adding 'Line Number' in gcode**
Is there any feature for adding line number in gcode file; for example:
`N1 G01 X100 Y10`
`N2 G01 X200 Y11`

[https://github.com/grbl/grbl]() suppurted 'Line Number'.
thanks

**Comment by svenhb** [comment]
Check new version https://github.com/svenhb/GRBL-Plotter/releases/latest

**Comment by svenhb** [comment]
Line numbers are implemented:
![image](https://user-images.githubusercontent.com/19973251/99890044-892ce900-2c5b-11eb-85f0-28e5b3a25fd7.png)
