### ISSUE TITLE
The software source code of version 1.5.2.2 cannot be compiled normally

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#158]
When using Visual studio software to compile the source code of the plotter of version 1.5.2.2, it cannot be compiled normally, and visual studio will report an error.

**Comment by svenhb** [comment]
Can you show the error here? Probably an outdated file.

**Comment by lianzaozi** [comment]
> 您可以在这里显示错误吗？可能是过时的文件。

The error message is as follows:

CS1061'"Settings" does not contain the definition of "sizeSerForm1", and the accessible extension method "sizeSerForm1" that can accept the first "Settings" type parameter cannot be found (are you missing a using directive or assembly reference?) GRBL-Plotter D :\GRBL-Plotter-V1.5.2.2 20201025\GRBL-Plotter-master\GRBL-Plotter\MachineControl\ControlSerialForm.cs 166 Active
![image](https://user-images.githubusercontent.com/53146195/97961547-7fe3f580-1dee-11eb-8512-468edb5fc6c3.png)

CS1061'"Settings" does not contain the definition of "sizeSerForm1", and the accessible extension method "sizeSerForm1" that can accept the first "Settings" type parameter cannot be found (are you missing a using directive or assembly reference?) GRBL-Plotter D :\GRBL-Plotter-V1.5.2.2 20201025\GRBL-Plotter-master\GRBL-Plotter\MachineControl\ControlSerialForm.cs 387 Active
![image](https://user-images.githubusercontent.com/53146195/97961587-8ffbd500-1dee-11eb-946a-471e75073a6b.png)

**Comment by svenhb** [comment]
I forgot to upload the settings files, check here: https://github.com/svenhb/GRBL-Plotter/tree/master/GRBL-Plotter/Properties

**Comment by lianzaozi** [comment]
It will now compile normally
