### ISSUE TITLE
Missing Settings in 1.5.2.2

### ISSUE THREAD

**Issue by amoineau** [svenhb/GRBL-Plotter#160]
**Describe the bug**
When building the latest version an error occurs:

**Screenshots**
![image](https://user-images.githubusercontent.com/72978966/98927518-ec3eb300-24d8-11eb-81cd-f59fae24786e.png)

**Comment by svenhb** [comment]
Problem was solved here: https://github.com/svenhb/GRBL-Plotter/issues/158

**Comment by amoineau** [comment]
Thank you, sorry for the duplicate...
