### ISSUE TITLE
Freeze within setup menu

### ISSUE THREAD

**Issue by amoineau** [svenhb/GRBL-Plotter#161]
**Describe the bug**
I downloaded the latest version of GRBL-plotter (1.5.2.2) and I started changing things in the setup menu (Working area, DXF to Gcode settings, tool table, etc..). Every time I click on a tick box or change a text field the application freezes, plus a second time when I apply the changes. It can vary from a second to a full minute.

I wanted to know if it was a known behavior or if the problem was specific to my setup and if you had any idea on how to solve this ?

_I know I have been requesting a lot of help from you recently and I'm really grateful for your responsiveness and your hard work._

**Comment by svenhb** [comment]
Did you run it from VisualStudio?
It's the same for me, I don't remember which debug option must be switched off - I will figure out.

**Comment by amoineau** [comment]
Yes I realised after posting that it might be the source of the problem. I started trying from the bin/Debug and Release .exe and indeed it seems to work fine there !

**Comment by amoineau** [comment]
But if I change the setup there it will not be persistent ?

**Comment by svenhb** [comment]
The settings should be saved in C:\User\myName\AppData\Local\GRBL_Plotter\subfolder

**Comment by amoineau** [comment]
It seems that saving a usecase when I change things and loading it when I want to apply the changes is a viable option. Does it seems right to you ?
It's just a bit tedious to move the usecase around and make sure that it is up to date. But that way I do the the setup through the .exe version and I can still use VS to edit things.

**Comment by svenhb** [comment]
I still need to check the debug-option, which needs to be swichted off, to speed up the setup form.  
You could save your INI-files on the desktop and just drag and drop them on GRBL-Plotter, as shown here: https://youtu.be/2Cc7sjwkxK8

**Comment by amoineau** [comment]
About that, I was wondering: does machine config includes everything in the current use case ? Because I've been saving and importing both every time but by reading them it feels like I could just use the global config file.

**Comment by svenhb** [comment]
Saving the "machine config" includes almost all settings (including custom buttons).  
"Use case" should save only import options. You could extend this files (via text editor) with settings from the machine config. 
Reading is the same for both: if set 
```
[Info]
Set Defaults=True
```
All import settings will be set to default. Check file \MachineControl\IniFile.cs

**Comment by svenhb** [comment]
This may help (https://stackoverflow.com/questions/12567984/visual-studio-debugging-loading-very-slow):
- Go to Tools -> Options -> Debugging -> General  
- CHECK the checkmark next to "Enable Just My Code".

**Comment by amoineau** [comment]
Ok I'll try that !

**Comment by amoineau** [comment]
It works but now I get these kind of messages every time something happens : 
![image](https://user-images.githubusercontent.com/72978966/101014913-e29fec80-3566-11eb-9cd6-8646e4030050.png)

**Comment by amoineau** [comment]
But it's not really a problem to be honest, I compile then if I want to debug (more like use breakpoints to understand how things work) I run and if I want to use it for real or adjust setup, I open with the .exe .

**Comment by svenhb** [comment]
You may try to fix it with this code (I can't try it out until tonight):  
Find function "private void updateProgressBar" in file "MainFormStreaming.cs"  
Replace this two lines: 
```
pbFile.Value = cPrgs;
pbBuffer.Value = bPrgs;
```

by:  
```
        //    pbFile.Value = cPrgs;
            if (this.pbFile.InvokeRequired)
            {   this.pbFile.BeginInvoke((MethodInvoker)delegate () { this.pbFile.Value = cPrgs; }); }
            else
            {   this.pbFile.Value = cPrgs;   }

        //    pbBuffer.Value = bPrgs;
            if (this.pbBuffer.InvokeRequired)
            {   this.pbBuffer.BeginInvoke((MethodInvoker)delegate () { this.pbBuffer.Value = bPrgs; }); }
            else
            {   this.pbBuffer.Value = bPrgs;   }

```

**Comment by amoineau** [comment]
Ok, though I gave you this one has an example but I get many different ones ^^'.
I can usually skip them by doing "continue" but when it happens in a loop....
So I decided to uncheck "just my code" and work like that.
