### ISSUE TITLE
Link a command/script to a specific tool

### ISSUE THREAD

**Issue by amoineau** [svenhb/GRBL-Plotter#162]
**Context**
Sorry for bothering you again...
I want to be able to send the command "M9" after "T1 M6" and "M7" after "T2 M6" because I overrided this command to control a relay to divert the PWM between my 2 tools.

My first thought was to use the "Tool Change" setup but I couldn't find a way to make the script conditional (depending on the new tool).

I then noticed the Gcode column in the tool table which seemed to fit my need.

**Problem**
The tool tip says "code to apply after tool change command"

![image](https://user-images.githubusercontent.com/72978966/99049494-338b7900-2597-11eb-885f-0ee765a93367.png)

So I added my commands but nothing happens after Tx M6 when I import the DXF. I checked and the .csv is correctly saved. However I might just have misunderstood what that column was about.

**Screenshots**
Here I import a DXF with 2 squares, one on a layer called "Laser" and one on a layer called "Encre". The tool matching features works great by the way (thank you for that !).

![image](https://user-images.githubusercontent.com/72978966/99049905-b3b1de80-2597-11eb-828e-07e48bab7055.png)

**Comment by svenhb** [comment]
I checked the code: the gcode from tool table will only be added if "Set XY-Feed from tool table" is enabled.
![image](https://user-images.githubusercontent.com/19973251/99053827-63d41700-2599-11eb-957c-f763acdcae0a.png)

**Comment by amoineau** [comment]
OK I'll try !

**Comment by amoineau** [comment]
Working great thank you again !
Can I put several commands in the gcode column of the Tool Table ?

**Comment by amoineau** [comment]
Huh, it's a different problem but the command M7 is not recognized and return an error. M8 and M9 work fine.
Do you want me to open a new issue or can we attend this here ?

![image](https://user-images.githubusercontent.com/72978966/99056552-be21a780-259a-11eb-8b6c-2cc9648502db.png)

**Comment by svenhb** [comment]
Yes, line seperation by ';' as for custom buttons

**Comment by amoineau** [comment]
Ok thanks.
The M7 problem seems to come from GRBL itself, but it worked not long ago... weird but maybe not your problem.

**Comment by svenhb** [comment]
This is an error from grbl... See description:
![image](https://user-images.githubusercontent.com/19973251/99056913-4b64fc00-259b-11eb-977a-827d962b3df6.png)

**Comment by amoineau** [comment]
Ok I have a grbl version mismatch between my debug board and the machine board...
But initial problem solved !

**Comment by amoineau** [comment]
Graphic import > Path import > Grouping and Tools > Tool Table
"Set XY Feed..." needs to be ticked.
