### ISSUE TITLE
Question about the coordinate system

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#165]
What is the difference between the frames G54, G55, G56, G57, G58, and G59? How to use it?

I'd like you to help me out.

**Comment by svenhb** [comment]
You can use them as different coordinate systems. I did it here - using two tools with offset to each other: https://grbl-plotter.de/index.php?id=laser-pen  
G55 is used for the pen, G54 for the laser.  
Video: https://youtu.be/m6up-oYwP_M
