### ISSUE TITLE
Can plotter support Marlin?

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#167]
Can plotter support Marlin and Smoothieware?

**Comment by svenhb** [comment]
Not yet. Will see what I can do.

**Comment by svenhb** [comment]
Please check new version: https://github.com/svenhb/GRBL-Plotter/releases

**Comment by lianzaozi** [comment]
Thank you for adding support for Marlin firmware, I will do some testing.
