### ISSUE TITLE
Is it possible to allow the user to decide whether to expand the Gcode block or not when clicking on it?

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#168]
As shown in the gif animation, select the geometric track in the geometric track display area, and the GCode block corresponding to the selected geometric track will be automatically expanded. Click to select the GCode block in the GCode display area, the selected GCode block will also be automatically expanded, but when I adjust the processing order, the expanded GCode block is not conducive to my work.

I hope to add an option in the settings to allow users to decide whether to expand the GCode block.

![image](https://user-images.githubusercontent.com/53146195/100988660-eb0a1e80-358a-11eb-8421-78a1ca1af8ab.gif)

**Comment by svenhb** [comment]
Try new version: https://github.com/svenhb/GRBL-Plotter/releases
![image](https://user-images.githubusercontent.com/19973251/170823676-12bd263c-997b-483a-8812-72328a82bbd5.png)
