### ISSUE TITLE
What do the two rectangles represent?

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#169]
When running, the geometric trajectory display area shows a black rectangle and a pink rectangle. Both rectangles are moving. What do these two rectangles represent?

![Snipaste_2020-12-04_15-47-23](https://user-images.githubusercontent.com/53146195/101136279-1141c400-3648-11eb-919d-7e4f5fe9aeb3.png)

![image](https://user-images.githubusercontent.com/53146195/101136137-d9d31780-3647-11eb-85da-4bcb52479150.gif)

**Comment by svenhb** [comment]
The black marker is the actual tool positon from the coordinates above.  
The red marker shows the coordinates from the GCode which was yet sent.

**Comment by lianzaozi** [comment]
Thank you
