### ISSUE TITLE
Missing font

### ISSUE THREAD

**Issue by endstreet** [svenhb/GRBL-Plotter#17]
The font wqy-unicode.llf is included in the project but not included in the zip. You can just remove the font from the project as it is not used. Currently the build is failing because the font is missing.

**Comment by svenhb** [comment]
The size of this font-file is 42MB, if I try to upload to github I get the message "Yowza, that’s a big file. Try again with a file smaller than 25MB." - what can I do?
Yes I should remove this font from the project.

**Comment by endstreet** [comment]
You can extract it from there..since it is not used in the project you can
just exclude it. The project will build at least. Zipping these resources
is maybe an option if you need to include it for dxf functionality.
