### ISSUE TITLE
The trace shows that some strange problems have occurred

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#170]
When processing the letter "B" and letter "L", there are some problems with the track displayed by the software.
The track display is normal during simulation processing. Could this be related to my hardware? I hope you can load this GCode and try it on your machine.

[GCode.zip](https://github.com/svenhb/GRBL-Plotter/files/5642393/GCode.zip)

![Snipaste_2020-12-04_19-19-31](https://user-images.githubusercontent.com/53146195/101158238-668cce00-3666-11eb-8927-bf763afc2282.png)

![image](https://user-images.githubusercontent.com/53146195/101158311-7f957f00-3666-11eb-899a-51d6e9ea69dc.gif)

**Comment by svenhb** [comment]
What kind of computer and operating system are you using? Maybe it is out of date?
Do you get errors inside the COM window?

**Comment by lianzaozi** [comment]
> 您使用哪种计算机和操作系统？也许已经过时了？
> 您是否在COM窗口中收到错误？

OS: windows10 X64
computer: notebook

**Comment by lianzaozi** [comment]
Does the reason for this problem have anything to do with the processing speed in GCode?

**Comment by svenhb** [comment]
Yes, as faster the movement as more complicate to display the processed path, because tool-position and gcode-line-nr will be updated to main GUI with 2 Hz to max 10 Hz:
![image](https://user-images.githubusercontent.com/19973251/101236947-46482800-36d5-11eb-8a47-5fa44d2f332e.png)

**Comment by lianzaozi** [comment]
This is the configuration information of my grbl control board that I used the plotter software to query. The information shows that the maximum speed allowed is 500. Now I set the processing speed in GCode to 100, but there are still strange things in the process of drawing the processing track line.

![image](https://user-images.githubusercontent.com/53146195/101339819-dba41180-38b9-11eb-8160-54f4c684579b.png)


> $$
< $0=10          (Sets time length per step. Minimum 3usec.)
< $1=25          (Sets a short hold delay when stopping to let dynamics settle before disabling steppers. Value 255 keeps motors enabled with no delay.)
< $2=0           (Inverts the step signal. Set axis bit to invert (00000ZYX).)
< $3=0           (Inverts the direction signal. Set axis bit to invert (00000ZYX).)
< $4=0           (Inverts the stepper driver enable pin signal.)
< $5=0           (Inverts the all of the limit input pins.)
< $6=0           (Inverts the probe input pin signal.)
< $10=0          (Alters data included in status reports.)
< $11=0.010      (Sets how fast Grbl travels through consecutive motions. Lower value slows it down.)
< $12=0.002      (Sets the G2 and G3 arc tracing accuracy based on radial error. Beware: A very small value may effect performance.)
< $13=0          (Enables inch units when returning any position and rate value that is not a settings value.)
< $20=0          (Enables soft limits checks within machine travel and sets alarm when exceeded. Requires homing.)
< $21=0          (Enables hard limits. Immediately halts motion and throws an alarm when switch is triggered.)
< $22=0          (Enables homing cycle. Requires limit switches on all axes.)
< $23=0          (Homing searches for a switch in the positive direction. Set axis bit (00000ZYX) to search in negative direction.)
< $24=25.000     (Feed rate to slowly engage limit switch to determine its location accurately.)
< $25=500.000    (Seek rate to quickly find the limit switch before the slower locating phase.)
< $26=250        (Sets a short delay between phases of homing cycle to let a switch debounce.)
< $27=1.000      (Retract distance after triggering switch to disengage it. Homing will fail if switch isn't cleared.)
< $30=1000       (Maximum spindle speed. Sets PWM to 100% duty cycle.)
< $31=0          (Minimum spindle speed. Sets PWM to 0.4% or lowest duty cycle.)
< $32=0          (Enables laser mode. Consecutive G1/2/3 commands will not halt when spindle speed is changed.)
< $100=250.000   (X-axis travel resolution in steps per millimeter.)
< $101=250.000   (Y-axis travel resolution in steps per millimeter.)
< $102=250.000   (Z-axis travel resolution in steps per millimeter.)
< $110=500.000   (X-axis maximum rate. Used as G0 rapid rate.)
< $111=500.000   (Y-axis maximum rate. Used as G0 rapid rate.)
< $112=500.000   (Z-axis maximum rate. Used as G0 rapid rate.)
< $120=10.000    (X-axis acceleration. Used for motion planning to not exceed motor torque and lose steps.)
< $121=10.000    (Y-axis acceleration. Used for motion planning to not exceed motor torque and lose steps.)
< $122=10.000    (Z-axis acceleration. Used for motion planning to not exceed motor torque and lose steps.)
< $130=200.000   (Maximum X-axis travel distance from homing switch. Determines valid machine space for soft-limits and homing search distances.)
< $131=200.000   (Maximum Y-axis travel distance from homing switch. Determines valid machine space for soft-limits and homing search distances.)
< $132=200.000   (Maximum Z-axis travel distance from homing switch. Determines valid machine space for soft-limits and homing search distances.)
< ok

**Comment by lianzaozi** [comment]
Now my speed reduction problem still occurs, I hope you can test it with the GCode I uploaded.

**Comment by svenhb** [comment]
If I run the program inside Visual Studio in Debug-Mode I get the same problem, but not in Release-Mode or without Visual-Studio.

**Comment by svenhb** [comment]
Improoved behavior of progressed path display: https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_Setup_1_6_2_1.exe
