### ISSUE TITLE
How do I specify the speed and distance of jogging when jogging?

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#171]
How do I specify the speed and distance of jogging when jogging?
Suppose I want the X axis to jog at a speed of f=100 to x=10 and then stop. What should I do?

**Comment by svenhb** [comment]
Setup the virtual joystick here:
![image](https://user-images.githubusercontent.com/19973251/101330525-fef79e00-3872-11eb-8eb0-491987ec1a50.png)
To move the given distance completly, switch off "STOP Jogging on mouse up" 
![image](https://user-images.githubusercontent.com/19973251/101330651-26e70180-3873-11eb-949b-84e8a0c932d8.png)

**Comment by lianzaozi** [comment]
Thank you
