### ISSUE TITLE
Version v1.5.3.0 of the software does not support opening by dragging and dropping dxf files

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#172]
Version v1.5.3.0 of the software does not support opening by dragging and dropping dxf files.
Version v1.5.2.4 supports drag-and-drop file opening. Have you cancelled the drag-and-drop file opening in the new version?

**Comment by lianzaozi** [comment]
V1.5.3.0 source code click on the vs menu bar "generate "->" rebuild solution ",vs will report an error.

**Comment by svenhb** [comment]
>Version v1.5.3.0 of the software does not support opening by dragging and dropping dxf files.  

For me it's working - strange, also downloading https://github.com/svenhb/GRBL-Plotter/archive/v1.5.3.0.zip works.

**Comment by lianzaozi** [comment]
Visualstudio will still report an error when regenerating the solution. I used visualstudio 2019 as my IDE.

But press the F5 shortcut to run the source code, which does not report errors

**Comment by svenhb** [comment]
I use Visual Studio 2015...  
>Visualstudio will still report an error   

What kind of error?

**Comment by lianzaozi** [comment]
![image7](https://user-images.githubusercontent.com/53146195/102690658-e5c2fa00-4241-11eb-87b7-0f1a0c9eef78.gif)
[Error information.zip](https://github.com/svenhb/GRBL-Plotter/files/5719478/Error.information.zip)

**Comment by svenhb** [comment]
Sorry, no idea, what's wrong.  
Older version 1.5.2.4 works?

**Comment by lianzaozi** [comment]
The source code of version 1.5.2.4 will also report an error when regenerating the solution. I guess this error has nothing to do with the source code of the program. I am looking for the cause of the error.
