### ISSUE TITLE
grbl mega 5 axis compiled hex with limit

### ISSUE THREAD

**Issue by 78Matteo78** [svenhb/GRBL-Plotter#173]
Hello
i can't get hard limits to work with grbl mega 2560
Could it be that the compiled version of 2019 doesn't work?
it is possible to have the latest version which should have active limits.
the pins of the limits are D2, D3, D14, D15, D18, D19.

**Comment by svenhb** [comment]
I never tried this option with my mega 2560. 
You may follow this text: https://github.com/fra589/grbl-Mega-5X/releases/tag/v1.1l.20190605
- Download the latest files here https://github.com/fra589/grbl-Mega-5X
- And follow the instructions here, how to compile the source inside the Arduino-IDE: https://github.com/gnea/grbl/wiki/Compiling-Grbl

**Comment by futurau** [comment]
grbl-Mega-5X is working great. I am using it on my cnc. I am not using max limits. Only min limits for homing (NC contact switches). []https://github.com/fra589/grbl-Mega-5X/wiki/grbl-Mega-5X-pinout(url)

**Comment by 78Matteo78** [comment]
Merry Christmas
I solved it by making a change on the cpu_map.h enable hard limit library, as explained in the firmware site, now they work.
thanks
greetings matteo

**Comment by svenhb** [comment]
👍👍👍
If you like, I can upload your Hex File here
