### ISSUE TITLE
Incorrect apply to gcode approximated height map

### ISSUE THREAD

**Issue by alligator77** [svenhb/GRBL-Plotter#175]
Incorrect apply to gcode approximated height map

Source gcode
[main34-source.txt](https://github.com/svenhb/GRBL-Plotter/files/5752471/main34-source.txt)
Map
![изображение](https://user-images.githubusercontent.com/6526798/103318936-10326580-4a41-11eb-8164-d3445a64533f.png)
[map.txt](https://github.com/svenhb/GRBL-Plotter/files/5752415/map.txt)

if try to apply this map to main34, then generated bad code:
[main34_bad.txt](https://github.com/svenhb/GRBL-Plotter/files/5752473/main34_bad.txt)

Without height map:
![изображение](https://user-images.githubusercontent.com/6526798/103318820-a31ed000-4a40-11eb-9539-dd77b6c7b6ac.png)
![изображение](https://user-images.githubusercontent.com/6526798/103318756-7c609980-4a40-11eb-98b7-1e968050fa6b.png)

After apply height map:
![изображение](https://user-images.githubusercontent.com/6526798/103319197-f6455280-4a41-11eb-97f2-797e56ad75f8.png)
![изображение](https://user-images.githubusercontent.com/6526798/103319215-052c0500-4a42-11eb-8b48-a8be9579ddee.png)

**Comment by svenhb** [comment]
Your source code looks a bit wired to me:
If I just go through the code in GRBL-Plotter and watch the position marker:
why this jumps in code lines 974 (N2032), 1061 (N2206), 1145 (N2374), 1226 (N2536), 1290 (N2664) for the first element?

It seems the gcode was stiched together - real line numbers and N-numbers are not matching.

The real problem for my algorithm is probably the already given Z in XY move statring in line 253 (N590)

Please try with a more clean gcode -> XY and Z moves seperated.

**Comment by alligator77** [comment]
> 
> why this jumps in code lines 974 (N2032), 1061 (N2206), 1145 (N2374), 1226 (N2536), 1290 (N2664) for the first element?
> 
Yep, this code contains 3 operations for one end mill, but this is normally. And transormed for cutting 6 pieces.

> The real problem for my algorithm is probably the already given Z in XY move starting at line 253 (N590)
Probably yes. this moving is spiral cutting, with smooth Z adjustment.

> Please try with a more clean gcode -> XY and Z moves seperated.
This source code is ok, and testing with Candle. But You software is better for me, and And I hope to completely switch to it.

I am also a .Net developer, but only the day before yesterday I found your software for myself, and have not had time to dig into it yet. :)

**Comment by svenhb** [comment]
BTW: grbl for Arduino Uno doesn't support G43 H2... Up to now "H2" will be removed by GRBL-Plotter

**Comment by alligator77** [comment]
> 
> 
> BTW: grbl for Arduino Uno doesn't support G43 H2... Up to now "H2" will be removed by GRBL-Plotter

Yep, some commands grbl not supported, these commands are ignored by grbl and do not affect the result

**Comment by svenhb** [comment]
Please check new release: https://github.com/svenhb/GRBL-Plotter/releases

**Comment by alligator77** [comment]
Tnx very mutch! Now it is fine!
