### ISSUE TITLE
Rotation gcode in Camera window is failed

### ISSUE THREAD

**Issue by alligator77** [svenhb/GRBL-Plotter#176]
If I try to rotate to any angle ("Apply Angle To GCode" button in Camera Window), all path is disappears. 
But if I rotate GCode from Top menu, that works fine.

**Reproduce**
Video
https://user-images.githubusercontent.com/6526798/105091477-ef45b900-5ab0-11eb-94e0-73210ed33f32.mp4

**Comment by svenhb** [comment]
I haven't tried the camera functionality in a long time - I'll check it out and repair.
Thanks for the feedback

**Comment by alligator77** [comment]
Pull requested

**Comment by svenhb** [comment]
Thanks, there are some more bugs to fix: e.g. importing the drill file doesn't work. 
I need to check the described work flow: https://github.com/svenhb/GRBL-Plotter/wiki/PCB-drilling

**Comment by svenhb** [comment]
Should be fixed now: https://github.com/svenhb/GRBL-Plotter/releases

**Comment by alligator77** [comment]
Now works fine! Tnx

**Comment by svenhb** [comment]
Thanks for testing
