### ISSUE TITLE
Remove/Choose Tool Change Pause

### ISSUE THREAD

**Issue by amoineau** [svenhb/GRBL-Plotter#179]
Hello, it's me again...
I just remembered something we talked about some time ago.
When using the tool change feature there is automatically a pause after every changes. Is is possible to remove this pause / choose the delay ?

**Comment by svenhb** [comment]
Have a look here: https://github.com/svenhb/GRBL-Plotter/releases

**Comment by amoineau** [comment]
Thanks I'll test it as soon as I can.

**Comment by amoineau** [comment]
It seems to be working fine.
