### ISSUE TITLE
Gamepad cross-buttons support

### ISSUE THREAD

**Issue by alligator77** [svenhb/GRBL-Plotter#181]
Can You add gamepad cross-buttons support?

The main basic joystick on the gamepad sometimes behaves unpredictably...

![изображение](https://user-images.githubusercontent.com/6526798/106518999-b44d7780-64eb-11eb-938c-03de91095ab9.png)

**Comment by svenhb** [comment]
Are the cross keys different from keys 0 to 15?
![image](https://user-images.githubusercontent.com/19973251/106597145-4b4f1980-6556-11eb-9eb4-2df127bce998.png)

**Comment by alligator77** [comment]
> 
> 
> Are the cross keys different from keys 0 to 15?
> ![image](https://user-images.githubusercontent.com/19973251/106597145-4b4f1980-6556-11eb-9eb4-2df127bce998.png)

Looks like yes, don't light up when pressed.

**Comment by alligator77** [comment]
I will add the description, check these buttons on the gamepad and what will be written in the line "Message from Gamepad" when I press these buttons.

**Comment by svenhb** [comment]
Good idea, thanks

**Comment by alligator77** [comment]
![изображение](https://user-images.githubusercontent.com/6526798/106618139-3dae8980-6580-11eb-8c70-5d9d51b57e39.png)

left : 27000
right : 9000
up : 0
down : 18000
neutral : -1

**Comment by svenhb** [comment]
For each direction the first word is "PointOfViewControllers0"?
Unfortunatly my gamepad doesn't send this value, just Buttons and X,Y,Z,RotationZ.

**Comment by alligator77** [comment]
> 
> 
> For each direction the first word is "PointOfViewControllers0"?
> Unfortunatly my gamepad doesn't send this value, just Buttons and X,Y,Z,RotationZ.

Yep, for all directions "PointOfViewControllers0".

**Comment by svenhb** [comment]
And they should act like X,Y on full scale, or are individual commands ok, like for the buttons?

**Comment by alligator77** [comment]
There are combinations of buttons, such as up and left. It is probably better to set jogging on all buttons with current feed or with adjustable feed.

**Comment by alligator77** [comment]
For example to use them for more accurate supply to a point of

**Comment by svenhb** [comment]
Check new release: https://github.com/svenhb/GRBL-Plotter/releases

**Comment by alligator77** [comment]
It works! Tnx

**Comment by svenhb** [comment]
Thanks for testing
