### ISSUE TITLE
Possibility to fix height differences of the machine axis'

### ISSUE THREAD

**Issue by metzger100** [svenhb/GRBL-Plotter#187]
My selfbuilt CNC is not perfectly aligned. So the right side of my basepalte is 1,5mm lower than the left side.
After the machine is a Sprite-typed machine I can't fix this difference of height on the machine without completly rebuilding it. Maybe it is possible to fix in the software. It would be awesome. Maybe the settings would look like:
X-axis to Z-axis: +-x mm for 10cm
Y-axis to Z-axis: +-x mm for 10cm
X-axis to Y-axis: +-x mm for 10cm

**Comment by svenhb** [comment]
You may use the height map option (Menu Workpiece - Surface Scan/Height map) :
1. Option you measure the map of your machine bed and apply it to yout workiece, or
2. You create the map by your self and load it into the Surface-scan dialog.
Height mao file looks like this (MaxX/Y = dimension in mm, SizeX/Y = number of points):
```
<?xml version="1.0" encoding="utf-8"?>
<heightmap MinX="0" MinY="0" MaxX="100" MaxY="100" SizeX="2" SizeY="2">
  <point X="0" Y="0">0</point>
  <point X="0" Y="1">0</point>
  <point X="1" Y="0">-1</point>
  <point X="1" Y="1">-1</point>
</heightmap>
```
This results to (just watch color map and use blue button):
![image](https://user-images.githubusercontent.com/19973251/109336078-33239f00-7863-11eb-95a4-8f6d7b37795f.png)


Only problem: the heigth map is bound to the work coordinate 0;0 and not to the machine coordinate.

**Comment by metzger100** [comment]
Yes. I already use the heightmap, but it would the life of all selfmade CNC-men easier if you could implement that Solution i proposed above. I would love to see that in a future version.
Greetings.

**Comment by svenhb** [comment]
You wrote "After the machine is a Sprite-typed machine I can't fix this difference of height on the machine"
What doesit mean "sprite-typed machine", do you have a picture?

**Comment by metzger100** [comment]
Sure. Maybe you know grblgru? The dev uses those CNC-types for his Gcode creation. The types describe the relations between workpiece and the axis of the machine. e.g Workpiece is fixed, Z axis is fixed, co.
Spritetyp machines have the workpiece on the y-axis and the z-axis is mounted on the x-axis.
![IMG_20210225_141323.jpg](https://user-images.githubusercontent.com/62517154/109395536-2e2b2200-792d-11eb-989e-ea1caad6f933.jpg)

**Comment by svenhb** [comment]
I just knew the german wording...
![image](https://user-images.githubusercontent.com/19973251/109398803-5e7bbc00-793f-11eb-8565-9a231a8dca1f.png)

**Comment by metzger100** [comment]
Ah okay. 
Ja. Ich kenn nur die Typen auf Englisch. Hab im Studium auch nur die englischen Begriffe gehabt, aber das scheint das selbe zu sein.
Danke für deine Arbeit.
Hab nachdem ich nun auch selbst ohne Gegenleistung Software anzubieten hab ich noch mehr Respekt vor deiner Leistung.
Vielen Dank. Sehr cool!

**Comment by svenhb** [comment]
Probably it's easier to use a waste board, where you mill off the surface with fixed Z value - then the surface is parallel to your XY mechanincs and you can fix your workpiece on it. Thats the way other CNC user do it...

**Comment by metzger100** [comment]
Thats how how I am doing right now. Didn't think about it when I opened the request.

**Comment by svenhb** [comment]
Thanks for the feedback
