### ISSUE TITLE
In the same dxf file, choose a use case that is not used, and the empty stroke arrows are displayed differently

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#189]
image1 uses example_laser.ini, the arrow direction of the empty stroke is correct
![image1-1](https://user-images.githubusercontent.com/53146195/113253393-c4b97d00-92f7-11eb-8c85-d564aaa7d276.png)

![image1](https://user-images.githubusercontent.com/53146195/113253380-bcf9d880-92f7-11eb-85a6-de4ad5efbf7e.png)

image2 uses example_plotter.ini, the arrow direction of the empty stroke is wrong
![image2-2](https://user-images.githubusercontent.com/53146195/113253411-ca16c780-92f7-11eb-864b-424d2c6e39f6.png)
![image2](https://user-images.githubusercontent.com/53146195/113253417-cc792180-92f7-11eb-8794-7aa392967423.png)

Test dxf file
[2008.zip](https://github.com/svenhb/GRBL-Plotter/files/6241503/2008.zip)

**Comment by svenhb** [comment]
Thanks, for the detailed explanation, the problem should be fixed here: https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_1577_publish.zip

**Comment by lianzaozi** [comment]
I downloaded the latest version of the software for testing, and found that except for the direction of the arrow on the first track is incorrect, everything else is correct.

![image](https://user-images.githubusercontent.com/53146195/114543588-f9c8b680-9c8b-11eb-9495-9f8f9eacf74d.png)
![111](https://user-images.githubusercontent.com/53146195/114543848-5af08a00-9c8c-11eb-8b14-60709f9d07eb.png)


![image](https://user-images.githubusercontent.com/53146195/114543588-f9c8b680-9c8b-11eb-9495-9f8f9eacf74d.png)
![2222](https://user-images.githubusercontent.com/53146195/114543865-604dd480-9c8c-11eb-8a6b-043906ec8a7a.png)

**Comment by svenhb** [comment]
I think it's fixed
