### ISSUE TITLE
GRBL -Plotter

### ISSUE THREAD

**Issue by levrob** [svenhb/GRBL-Plotter#19]
That's a nice sender except the user's manual.
My questions are:
1. The surface scan setup (the video is somewhat garbled)
2. The jogging with a mouse a joystick or game pad? or keyboard if it's possible

**Comment by svenhb** [comment]
I add a manual about the joystick to the wiki https://github.com/svenhb/GRBL-Plotter/wiki/joystick-control
For a manual about the surface scan I need more time...

**Comment by svenhb** [comment]
I started to test the surface scan and found a bug and space for improovement.

**Comment by svenhb** [comment]
Hope this manual is ok: https://github.com/svenhb/GRBL-Plotter/wiki/surface-scan

**Comment by levrob** [comment]
Thank you very much it was really helpful 

    On Thursday, May 31, 2018, 9:10:14 PM GMT+3, Sven <notifications@github.com> wrote:  
 
 
Hope this manual is ok: https://github.com/svenhb/GRBL-Plotter/wiki/surface-scan
