### ISSUE TITLE
The latest version of the software text filling cannot be used

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#190]
The latest version of the software text filling cannot be used.

The software text filling function of version 1.5.0.1 is normal.

Can you add a filling function to vector graphics? (e.g. dxf file, svg file)

**Comment by svenhb** [comment]
I didn't changed this function - for me it's working:
![image](https://user-images.githubusercontent.com/19973251/114823092-54186300-9dc3-11eb-8c05-7649c28f742f.png)

Also vector filling for SVG is working, DXF-fill is not implemented.
![image](https://user-images.githubusercontent.com/19973251/114823530-f20c2d80-9dc3-11eb-86b1-1af80d15fe07.png)

[SVG_Layers_filled.zip](https://github.com/svenhb/GRBL-Plotter/files/6315558/SVG_Layers_filled.zip)

**Comment by lianzaozi** [comment]
This is my operation process, the software version I use is 1.5.7.8
![Uploading image11.gif…]()

**Comment by svenhb** [comment]
You have to use smaller values for this numbers because your dimension are smaller:
![image](https://user-images.githubusercontent.com/19973251/116821985-b7a0df80-ab7c-11eb-9859-6c0b4f8142f0.png)
