### ISSUE TITLE
Add another feature please

### ISSUE THREAD

**Issue by mmcmNew** [svenhb/GRBL-Plotter#197]
When creating a g code from the text, so that the movement is not on the outer contour, but on the inner one.

**Comment by svenhb** [comment]
Can you make a picture? I don't get the problem...
The GCode is created on the contour....
![image](https://user-images.githubusercontent.com/19973251/116406079-995f7a80-a830-11eb-8d49-c28be9c4a299.png)

You could use radius compensation to get the outer contour of closed shapes:
If the contour is on the wrong side, try negative value for radius
![image](https://user-images.githubusercontent.com/19973251/116406474-ff4c0200-a830-11eb-82ae-3b6f17a121dd.png)

**Comment by mmcmNew** [comment]
![image](https://user-images.githubusercontent.com/77157663/116408039-0c6dee80-a83b-11eb-942c-e3ed4ac00752.png)

But I need inner one

**Comment by svenhb** [comment]
If this is the original font, you can't remove it.
You may try radius compensation with negativ value
![image](https://user-images.githubusercontent.com/19973251/116408916-a29e1680-a833-11eb-8c99-010799093525.png)

**Comment by svenhb** [comment]
With this font and characters it works:
![image](https://user-images.githubusercontent.com/19973251/116410116-c0b84680-a834-11eb-9b94-e9f41c72791c.png)

**Comment by mmcmNew** [comment]
This doesn't work with all fonts, but thank you.

**Comment by mmcmNew** [comment]
I ran into another problem. When you send gcode for execution at the beginning, it is written well, but towards the end it starts to be executed in jerks. But if you press the pause button in the program at this moment, the execution will continue smoothly again

https://user-images.githubusercontent.com/77157663/116414000-c61b8e00-a840-11eb-9fc0-2e0b6cdc02eb.mp4

**Comment by svenhb** [comment]
Did you enable this checkboxes? This may cause delays...
![image](https://user-images.githubusercontent.com/19973251/116417017-2f989e00-a83b-11eb-93da-ddfaa29473d2.png)

**Comment by mmcmNew** [comment]
not enabled

**Comment by mmcmNew** [comment]
Enabled
This happens at the end of the code. If the text is large, then it will be on the extreme lines

**Comment by svenhb** [comment]
Perhaps a memory problem...
You may watch Streaming progress - the green bars and Task-manager memory usage...
What kind of PC and operating system do you use?

**Comment by mmcmNew** [comment]
Win 10. Laptop
vimple.co/93a4f3c1e6a24efdb08d300bc1426657

**Comment by svenhb** [comment]
I think your feedrate is too high and the grbl buffer runs empty. With pause there is chance to fill up the grbl buffer again.
What controller do you use?
Same problem in my video, check at 4:40 https://youtu.be/7Nvf4UwK_yk?t=282

**Comment by mmcmNew** [comment]
It's may be. Using USB Type-C port

**Comment by mmcmNew** [comment]
Is it possible to implement the ability to specify the page width when creating code from text, and thus the text would automatically be transferred to the next line? Otherwise, you have to put hyphenation manually throughout the text

**Comment by svenhb** [comment]
It is grbl related, somewhere I read that at maximum 10 Gcode lines per second can be processed to fill up the internal path algorythm...

**Comment by svenhb** [comment]
> the ability to specify the page width  
  
I need to check this

**Comment by mmcmNew** [comment]
it will be very convenient

**Comment by mmcmNew** [comment]
thank you so much for your help

**Comment by mmcmNew** [comment]
https://youtu.be/wuy6Ry_xmRU?t=107
And the ability to trace along the center line too I think will be very convenient especially when writing with a pen

**Comment by mmcmNew** [comment]
I'm tired of trying to get the printer to write what I need
![image](https://user-images.githubusercontent.com/77157663/116590703-bd9d8300-a926-11eb-94cf-7445cfe22a5f.png)
![image](https://user-images.githubusercontent.com/77157663/116590753-cbeb9f00-a926-11eb-9fea-8bf8827947a9.png)
since there is no creation of code from the font along the center line, I created an image without a background through Corel. The result is shown in the screenshot. I don't understand how to do it normally.
In addition, whatever image I insert, it also creates a frame along the borders of this image, but I don't need it

**Comment by svenhb** [comment]
> The result is shown in the screenshot. I don't understand how to do it normally. 
 
Strange idea - why don't use another font? For me it works:
![image](https://user-images.githubusercontent.com/19973251/116594525-993fa780-a922-11eb-93a7-4dfb69e000eb.png)

Settings - I pressed "Comic - few colors" reduced number of colors to 2, increased brightness, use small ResoX:
![image](https://user-images.githubusercontent.com/19973251/116594805-eb80c880-a922-11eb-94fb-e0977e538ba1.png)
![image](https://user-images.githubusercontent.com/19973251/116594832-f0de1300-a922-11eb-8228-31a94342c28f.png)
![image](https://user-images.githubusercontent.com/19973251/116594950-0fdca500-a923-11eb-9361-36d223921c42.png)



>In addition, whatever image I insert, it also creates a frame along the borders of this image, but I don't need it  

It just shows the graphic dimension, it is no gcode wich will be processed... You can switch off here:
![image](https://user-images.githubusercontent.com/19973251/116594039-14548e00-a922-11eb-923f-ca9b4240ad3e.png)

**Comment by svenhb** [comment]
Check new version for automatic line break on given page width... https://github.com/svenhb/GRBL-Plotter/releases
![image](https://user-images.githubusercontent.com/19973251/116821828-bd49f580-ab7b-11eb-9f49-494f900f1c3b.png)

**Comment by mmcmNew** [comment]
Thanks) This is very convenient. 
Is there a chance that a centerline will appear for the text?)

**Comment by svenhb** [comment]
What do you mean with center line?

**Comment by mmcmNew** [comment]
https://youtu.be/wuy6Ry_xmRU?t=113

**Comment by mmcmNew** [comment]
So that the text is created not on the contour, but on the center line

**Comment by svenhb** [comment]
Sorry, I think this is too complicted for me

**Comment by mmcmNew** [comment]
What procedure is responsible for drawing letters to the program?
I'll try to figure it out and do what I need to do

**Comment by svenhb** [comment]
Text will be created from LFF of SVG fonts: https://github.com/svenhb/GRBL-Plotter/tree/master/GRBL-Plotter/GCodeCreation/CreateFromForm check for files with 'text' or 'font' in the name.
The example above - finding inside path - is imaging processing - same path, files with 'image' in the name. 
 
What's about the font you used - from where did you get it? Perhaps there is also the style available you need?
![image](https://user-images.githubusercontent.com/19973251/116915225-0b2e2e80-ac4c-11eb-92c1-359a15fe0295.png)
 

My suggestion is: make your own SVG font - here are some links to start with:
https://www.evilmadscientist.com/2019/hershey-text-v30/ 
https://inkscape-manuals.readthedocs.io/en/latest/creating-custom-fonts.html

**Comment by mmcmNew** [comment]
I want to try to do this so as not to redo the fonts. I think it will be easier this way

**Comment by svenhb** [comment]
You may try it in inkscape:
https://inkscape.org/de/~arpruss/%E2%98%85centerline-trace-on-windows-instructions
