### ISSUE TITLE
MKS DLC 2.0  firmware DLC-CNC

### ISSUE THREAD

**Issue by qulet** [svenhb/GRBL-Plotter#198]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Comment by qulet** [comment]
I don't want to connect to serial port.
"GRBL Panel" connects correctly.
I don't know where the problem is.
This occurs in V1.8, I had an older version of the GRBL plotter and it was not a problem.
Where can I download the older version of the program from?

**Comment by svenhb** [comment]
I never heared about this MKS DLC....
What kind of error do you get? Any screenshots?

About older  version - just scroll down here: https://github.com/svenhb/GRBL-Plotter/releases

**Comment by qulet** [comment]
Thank you for your response
![com_error](https://user-images.githubusercontent.com/30979927/116747710-a03be800-a9fe-11eb-889b-9397c59f0437.jpg)

**Comment by qulet** [comment]
MKS DLC V2
[MKS DLC V2.0_001 SCH.pdf](https://github.com/svenhb/GRBL-Plotter/files/6407775/MKS.DLC.V2.0_001.SCH.pdf)
[MKS DLC V2.0_001 PIN.pdf](https://github.com/svenhb/GRBL-Plotter/files/6407778/MKS.DLC.V2.0_001.PIN.pdf)

**Comment by qulet** [comment]
Pin_out  arduino-UNO

**Comment by svenhb** [comment]
You wrote GRBL Panel connects to your hardware - you should check the selecteded baudrate. I assume the default baudrate (115200) is not correct for your board:
![image](https://user-images.githubusercontent.com/19973251/116752448-e21c5c80-aa05-11eb-8326-50b2b610d8e0.png)

**Comment by qulet** [comment]
115200 is the correct value with this speed my MKS board connects to programs "GRBL Panel" and "Ligthtburn"

**Comment by svenhb** [comment]
Can you send the logfile (same folder as the exe)?

**Comment by svenhb** [comment]
Do you get any welcome message, when using the other programs? I assume your firmware behaves different compared to "classic" grbl.

**Comment by qulet** [comment]
Hello
The problem occurs when I run applications from a file:
GRBL-Plotter.application

disappears when I run the program from a file:
GRBL-Plotter.exe
[logfile.txt](https://github.com/svenhb/GRBL-Plotter/files/6411730/logfile.txt)

**Comment by qulet** [comment]
Thank you very much for your help and for providing such versatile software !!!
The problem is clarified, I close the topic
Greetings !

**Comment by qulet** [comment]
[logfile.2.txt](https://github.com/svenhb/GRBL-Plotter/files/6411794/logfile.2.txt)

Unfortunately, the problem has reappeared. What's with this buffer?
![Bez tytułu](https://user-images.githubusercontent.com/30979927/116820168-db135c80-ab73-11eb-95c5-7528c50f2dad.jpg)
![Bez tytułu_2](https://user-images.githubusercontent.com/30979927/116820172-de0e4d00-ab73-11eb-8814-85360800ec97.jpg)

**Comment by svenhb** [comment]
Please try https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_1581_publish.zip
To be able to switch off the alarm via $X - Kill Alarm.

Buffer size is the size of the serial receive buffer inside the Arduino  Uno (Arduino Mega has more buffer...)

**Comment by qulet** [comment]
GRBL-Plotter_1581_publish.zip
GRBL-Plotter_1582_publish.zip
[logfile.txt](https://github.com/svenhb/GRBL-Plotter/files/6412003/logfile.txt)
homing not work....

**Comment by svenhb** [comment]
You need to correct your settings, grbl message:
`grbl ALARM 'ALARM:9' Homing fail. Could not find limit switch within search distances. Try increasing max travel, decreasing pull-off distance, or check wiring.`

**Comment by qulet** [comment]
svenhb Please contact me privately by e-mail
kuleta@wtvk.pl

For help in starting the ATtiny44 pen lifter
