### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by 3dfixer** [svenhb/GRBL-Plotter#20]
found a bug
if you go into setup - gamepad, a box pops up saying thread exception that you then can't get rid of.
only way out is shut down program via task manager

**Comment by svenhb** [comment]
Please give more information - I can't get the problem:
Which Operating System? Was an Arduino connected? Was a gamepad connected?

**Comment by 3dfixer** [comment]
ran program as just downloaded. i'm using windows 10. nothing was connected to computer. was just trying it out

**Comment by svenhb** [comment]
Could not retry the problem. Perhaps it disappeared with the new version
