### ISSUE TITLE
The input box is blocked by the window, and the text cannot be input

### ISSUE THREAD

**Issue by wwwlxs** [svenhb/GRBL-Plotter#200]
**Describe the bug**
The input box is blocked by the window, and the text cannot be input.Can't scroll the page at the same time

**Screenshots**

![截屏2021-05-09 下午7 47 26](https://user-images.githubusercontent.com/44305220/117571340-bfbec900-b100-11eb-9ef9-7aa30952b967.jpg)

**Comment by svenhb** [comment]
I don't know why the layout is so different, In my form designer, the apply button has the same Y coordinate as the Reload button, but on your system not...
Your screenshot: 
![image](https://user-images.githubusercontent.com/19973251/117580232-59817880-b0f7-11eb-9d7d-b7a87fbfa2c6.png)
My form designer: 
![image](https://user-images.githubusercontent.com/19973251/117580277-86359000-b0f7-11eb-9338-592a5b8e5d62.png)

**Comment by svenhb** [comment]
I reordered the options, please try: https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_1583_publish.zip

**Comment by svenhb** [comment]
Perhaps you can send a screenshot to show if the button "Apply changes" is still moved upwards

**Comment by svenhb** [comment]
I cleaned up the window
