### ISSUE TITLE
Spline Bugs

### ISSUE THREAD

**Issue by Behiiitaj** [svenhb/GRBL-Plotter#201]
**Spline bugs**
Hi...
Sorry, I'm not good in English...
I open a 'Dxf' file that contain spline. (DXF file exported from "Solidworks" )
Unfortunately 'GRBL_plotter' generate g_code like this...
![bug](https://user-images.githubusercontent.com/83219041/118657412-b4eeed00-b800-11eb-813c-921ede830ec7.png)

**To Reproduce**
1. Go to 'File.'
2. Click on 'Open file'
3. Select the 'example_router.ini' use case

**Comment by svenhb** [comment]
Try to increase this number in setup:
![image](https://user-images.githubusercontent.com/19973251/118660771-c8915800-b7ee-11eb-95f9-c6cd487600af.png)

**Comment by svenhb** [comment]
And be sure this one is not checked:
![image](https://user-images.githubusercontent.com/19973251/118663788-42c2dc00-b7f1-11eb-9ab4-e05fea21a846.png)

**Comment by Behiiitaj** [comment]
This is my file

**Comment by svenhb** [comment]
No attachment...

**Comment by Behiiitaj** [comment]
https://drive.google.com/file/d/131l8l16vk3T2ImMVjilJMBomSrM_H022/view?usp=drivesdk

**Comment by svenhb** [comment]
Ok, I get the same result - I will try to fix it

**Comment by svenhb** [comment]
Found and fixed the problem, please try: https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_1583_publish.zip

**Comment by Behiiitaj** [comment]
Thank you so much
I've tested the program, The problem has fixed.

**Comment by Behiiitaj** [comment]
Is source code updated after fixing spline problem?

**Comment by svenhb** [comment]
I need some time to practical check the other improovements I built in (more positions for rc-servo, available as subroutines for improoved watercolor usage). But at the moment my hobby room is occupied by other things.

**Comment by svenhb** [comment]
Source code is updated
