### ISSUE TITLE
Detecting tools from layers

### ISSUE THREAD

**Issue by amoineau** [svenhb/GRBL-Plotter#202]
**Describe the bug**
Not sure if it's actually a bug, maybe I'm just missing something.
I use these options to detect which tool the machine is supposed to use :

![image](https://user-images.githubusercontent.com/72978966/120435864-86cfe800-c37e-11eb-8e2b-af9817832ae8.png)

The tool table looks something like that : 

![image](https://user-images.githubusercontent.com/72978966/120436126-d7474580-c37e-11eb-971d-00bcda6663c6.png)

And the detection is not consistent. I can have a file with an empty default layer and a second layer called LASER with the forms to cut and GRBL-P will pair the layer with the ENCRE tool. 

I recently had the idea to match the color as well and it seems to be much more consistent. 
If it works like that it's not a huge problem but it makes creating the DXFs and tool tables a bit more tedious and prone to error.

**Comment by svenhb** [comment]
Did you select the desired properties here?
![image](https://user-images.githubusercontent.com/19973251/120479333-1e006400-c3ae-11eb-9144-1b23d1732b34.png)

**Comment by svenhb** [comment]
Perhaps differences in uppercase lowercase? I use the LevenshteinDistanceAlgorithm to judge tool-name versus layer-name.
I guess "LASER" gives the same score as "encre" if you look for "ENCRE" (5 chars needs to be replaced).

**Comment by amoineau** [comment]
Hi, yes I made sure the case was the same on both sides and both tools. 
I did select "XY feedrate from TT" and "Spindle Speed from TT" but not the Z axis one. Although I don't use a Z axis and this window is different on my version (1.5.8.2):
![image](https://user-images.githubusercontent.com/72978966/120501747-25316d00-c3c2-11eb-8951-380e89891f19.png)

(Am I using too many decimal places ?)

**Comment by amoineau** [comment]
> Did you saved your new tool-table?

[laser_and_pen_ISP.zip](https://github.com/svenhb/GRBL-Plotter/files/6589336/laser_and_pen_ISP.zip)

> Can you try different layer-name length?

Sure, I can try. Do you mean that each layer should have a different length than the others, or that the layer name should be longer ?

> I can't check the code before weekend.

No problem ! Thank you for your help.

**Comment by svenhb** [comment]
I don't know why: in your tool table the seperators are not consistent. All my examples uses "," comma, but yours also shows ";" semicolons - could be a problem.
Different name-length would be good as a test: yes: Do you mean that each layer should have a different length than the others.

**Comment by amoineau** [comment]
If you mean the last column, it's a separator for the commands to execute when switching to the tool, not a csv separator.
I played around with different name length and casing and it didn't solve the problem, but matching the colours does.

One file where this problem appears :  
[ia21a1342pmi0002-01_slc.zip](https://github.com/svenhb/GRBL-Plotter/files/6590225/ia21a1342pmi0002-01_slc.zip)

**Comment by svenhb** [comment]
I think the problem is, that this DXF file has only one layer with objects.
Because of a problem in earlier time #147, grouping with just one group-item will not be performed...

I need to check for a workarround

**Comment by amoineau** [comment]
I thought so because there are information in the g-code header about that, so I tried earlier this week to add an empty ENCRE layer on another version of this file and it didn't change anything :(

**Comment by svenhb** [comment]
Hope it is fixed: https://github.com/svenhb/GRBL-Plotter/releases

**Comment by amoineau** [comment]
Thx, I'll try it this week !
