### ISSUE TITLE
Step movement function

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#206]
Does the plotter software have the function of step movement?
For example: I set 10mm, and every time I click the button, the axis moves 10mm.

**Comment by svenhb** [comment]
Sure, just uncheck "STOP jogging on mouse up", then the full move wil be perfomed. If you click 3 times, it moves 3*distance. 
If checked, the move will be interrupted, when rleasing the mouse:
![image](https://user-images.githubusercontent.com/19973251/123538824-e7143880-d736-11eb-9d0e-e211c6a1665f.png)

**Comment by lianzaozi** [comment]
Thank you, I tried it and it was very easy to use.

but how to adjust the manual speed of the axis?

**Comment by lianzaozi** [comment]
Chinese translation correction

The correct Chinese translation of "Stop jogging on mouse up" is "Stop jogging on mouse up"

**Comment by svenhb** [comment]
Thanks for correction.
Setup of jogging is here:
"Calculation of best speed" is not correct (a bit too fast). 10 mm with feedrate F=1000 is ok, calculation gives F=1200, which causes interrupted moves if mouse is pressed for a longer time.
![image](https://user-images.githubusercontent.com/19973251/123540751-e2ed1880-d740-11eb-9dd7-1cae8b8c8b8a.png)

**Comment by lianzaozi** [comment]
thank you

The source code of version 1.5.8.4 fails to compile in the visual studio of my computer, and an error will be reported.

**Comment by svenhb** [comment]
>The source code of version 1.5.8.4 fails to compile  
 
I don't know how I could help

**Comment by lianzaozi** [comment]
You can download the software source code of V1.5.8.4, open it with VS on your computer, and compile it to see if there is an error.

**Comment by svenhb** [comment]
>You can download the software source code of V1.5.8.4, open it with VS on your computer, and compile it to see if there is an error.
 
No errors, just warnings... Perhaps you can show a screenshot of the error?
Perhaps it is a missing nuget packet... I thought just delivering the DLLs is enough - perhaps not:
![image](https://user-images.githubusercontent.com/19973251/123548029-6e77a100-d763-11eb-9bf1-d36c618cb0ce.png)

**Comment by lianzaozi** [comment]
My operating software steps are like this:
![image1](https://user-images.githubusercontent.com/53146195/123551242-81aa6100-d7a3-11eb-8909-d7c839553107.png)

![image2](https://user-images.githubusercontent.com/53146195/123551241-7f480700-d7a3-11eb-8f16-b564a2b0781c.png)

**Comment by svenhb** [comment]
Perhaps you need to disable some debug options? 
What happens if you select "Release":
![image](https://user-images.githubusercontent.com/19973251/123551692-26f91100-d773-11eb-8742-aa44bc32be75.png)

**Comment by lianzaozi** [comment]
Thank you for your reply, you are right.

The problem disappeared after selecting "Release", but I don't understand why there is a problem in regenerating the source code after selecting "debug"

**Comment by lianzaozi** [comment]
After selecting "debug" on your computer, will there be problems in regenerating the source code?

**Comment by svenhb** [comment]
In debug mode, stronger rules will be applied. I don't know how to setup. If I run it in Debug mode I get no errors...

**Comment by svenhb** [comment]
Sometime you can disable warnings, if you click on them. Don't know if it will work with this links:
![image](https://user-images.githubusercontent.com/19973251/123552377-2c0b8f80-d776-11eb-8471-ffc794727a59.png)

**Comment by svenhb** [comment]
Perhaps if you now switch back to "Debug" it works?

**Comment by lianzaozi** [comment]
The problem is still not solved. Clicking on the error message link will jump to the Microsoft website. This page explains that the source code needs to be modified to solve the error.

**Comment by lianzaozi** [comment]
try rebuild solution

**Comment by svenhb** [comment]
Perhaps this is the trick:
![image](https://user-images.githubusercontent.com/19973251/123837867-a02b6c00-d90b-11eb-8db4-6742bb55c394.png)

**Comment by lianzaozi** [comment]
My computer set
![image](https://user-images.githubusercontent.com/53146195/124043096-e7654a00-da3c-11eb-9ba6-edf07c654452.png)

**Comment by svenhb** [comment]
Perhaps you need to select another rule or reset the rule: https://stackoverflow.com/questions/33637211/vs2015-warning-msb3884-could-not-find-rule-set-file

**Comment by lianzaozi** [comment]
Thank you for your reply

I kept the same settings of visual studio unchanged, then opened the source code of another program, clicked to regenerate the solution, and no error was reported.
I think the error reported when compiling the source code of the plotter should have nothing to do with the visual studio settings.

**Comment by svenhb** [comment]
>I think the error reported when compiling the source code of the plotter should have nothing to do with the visual studio settings.

But it has: if you select "Release" you get no errors because of different rules...

**Comment by lianzaozi** [comment]
I copied some wrong links for vs jump, these pages explain the cause of the error.
I have the location of these error codes in the screenshot above.

CA1500
https://docs.microsoft.com/zh-cn/previous-versions/visualstudio/visual-studio-2015/code-quality/ca1500-variable-names-should-not-match-field-names?view=vs-2015&redirectedfrom=MSDN

CA1502
https://docs.microsoft.com/zh-cn/previous-versions/visualstudio/visual-studio-2015/code-quality/ca1502-avoid-excessive-complexity?view=vs-2015&redirectedfrom=MSDN

CA1806
https://docs.microsoft.com/zh-cn/previous-versions/visualstudio/visual-studio-2015/code-quality/ca1806-do-not-ignore-method-results?view=vs-2015&redirectedfrom=MSDN

CA1505
https://docs.microsoft.com/zh-cn/previous-versions/visualstudio/visual-studio-2015/code-quality/ca1505-avoid-unmaintainable-code?view=vs-2015&redirectedfrom=MSDN

**Comment by svenhb** [comment]
Yes, but these are warnings - as the webpages says, not errors. Your setup is not ok...

**Comment by lianzaozi** [comment]
I reset the settings of visual studio and restarted visual studio, but the problem is still not resolved
![image](https://user-images.githubusercontent.com/53146195/124146379-49b35e80-dac0-11eb-90ae-f1976ceb9899.png)

![image](https://user-images.githubusercontent.com/53146195/124146328-3e603300-dac0-11eb-8b9b-7477fc28f6e0.png)

**Comment by svenhb** [comment]
Did you try VS 2019 or VS 2022? Both are also working...
Did you load the project from the GRBL-Plotter.sln file? Perhaps thats the differnece?

**Comment by lianzaozi** [comment]
My computer only has VS 2019 installed.
I load the project from the "GRBL-Plotter.sln file".

**Comment by svenhb** [comment]
Whats about this setting: Treat warnings as errors:
![image](https://user-images.githubusercontent.com/19973251/124163962-7b1c3200-daa0-11eb-898c-c28c098d956c.png)

**Comment by lianzaozi** [comment]
Thank you for your reply.

The settings of the vs software on my computer are the same as in your screenshot.

**Comment by lianzaozi** [comment]
I tested other programs can compile normally

**Comment by lianzaozi** [comment]
VS2022 compilation code failed, error code CA0001, this is the only error

**Comment by svenhb** [comment]
I'm reworking the code, to get rid of most warnings - give me some weeks...
Just another try for your problem:
Close project in visual studio
Perhaps it helps if you replace with text-editor in GRBL-Plotter.csproj:
2nd line "<Project ToolsVersion="14.0" ..." by
<Project ToolsVersion="4.0" 
Open project

**Comment by svenhb** [comment]
Check new pre-release: https://github.com/svenhb/GRBL-Plotter/releases
