### ISSUE TITLE
i cant download GRBL-Plotter Vers. 1.1.6.1 2018-05-04 

### ISSUE THREAD

**Issue by dnshvra** [svenhb/GRBL-Plotter#21]
the linke is  not work

**Comment by svenhb** [comment]
I removed old versions.
Please always check the "Release" area for latest version: https://github.com/svenhb/GRBL-Plotter/releases

**Comment by svenhb** [comment]
Where did you find the link to "Vers. 1.1.6.1 2018-05-04"? I should correct this.

**Comment by svenhb** [comment]
I found the link inside the README.md file - I corrected the link
