### ISSUE TITLE
Source code recompile error

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#210]
Source code recompile error

**Comment by svenhb** [comment]
no picture uploaded.
Do you have all the needed packages, not sure if they will be installed automatically.
![image](https://user-images.githubusercontent.com/19973251/127746434-7dd87ee7-1503-4eb8-a7c4-ae5e1e88c54f.png)

**Comment by lianzaozi** [comment]
The file "Dimensions" was not found, resulting in an error in compiling the source code

![image](https://user-images.githubusercontent.com/53146195/127755725-7f374055-c9f9-42af-af46-239f32fd0798.png)

**Comment by svenhb** [comment]
Is it fixed?

**Comment by svenhb** [comment]
No idea, sorry.

**Comment by lianzaozi** [comment]
Thank you very much for your reply. I am looking into the reason myself.

**Comment by svenhb** [comment]
Could you fix it? I assume mixing file versions in same folder (e.g. "xmlMarker.cs" = old version, "XmlMarker.cs" = new version)
There where to files with same name but the right one (new version) starts with capital letter.

**Comment by svenhb** [comment]
Probably fixed
