### ISSUE TITLE
Why do I dynamically change G code and he becomes what he was

### ISSUE THREAD

**Issue by lirui-dot** [svenhb/GRBL-Plotter#211]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Comment by svenhb** [comment]
I don't understand this issue

**Comment by lirui-dot** [comment]
> 我不明白这个问题

You change the G code in the code, and it becomes the original G code

**Comment by lirui-dot** [comment]
> > 我不明白这个问题
> 
> 你把代码里的G代码改了，就变成原来的G代码了

There is also the box can choose graphics, or choose multiple graphics

**Comment by svenhb** [comment]
I still don't understand, do you talk about transformations? Or import options?
Please give screenshots and examples.

**Comment by lirui-dot** [comment]
> 我还是不明白，你说转换吗？还是导入选项？
> 请给出截图和例子。

Can I choose more than one graphic

**Comment by lirui-dot** [comment]
> > 我还是不明白，你说转换吗？还是导入选项？
> > 请给出截图和例子。
> 
> Can I choose more than one graphic

Probably got into the timer and changed the G code

**Comment by svenhb** [comment]
No: only one figure (marked yellow) or all figures = whole graphics

**Comment by svenhb** [comment]
If you use grouping, I think all figures within a marked group can be trnasformed

**Comment by lirui-dot** [comment]
> 如果使用分组，我认为标记组内的所有数字都可以转换

Like washing when the knife into the knife back where to set

**Comment by lirui-dot** [comment]
> > 如果使用分组，我认为标记组内的所有数字都可以转换
> 
> Like washing when the knife into the knife back where to set

像洗的时候进刀退刀量在哪设置呢

**Comment by lirui-dot** [comment]
How to set the amount of edge wash in and out

**Comment by lirui-dot** [comment]
> 如何设置洗边进出量

我看你这边的进刀量是0.1

**Comment by lirui-dot** [comment]
> > 如何设置洗边进出量
> 
> 我看你这篇的进刀量是0.1

How do you set it up

**Comment by svenhb** [comment]
Please show a screenshot of the settings you are talking about. Just paste an image from the clipoard here...

**Comment by lirui-dot** [comment]
> 请显示您正在谈论的设置的屏幕截图。只需在此处粘贴剪贴板中的图像...

I mean there is a compensation for the amount of knife in and out when washing the edge

**Comment by lirui-dot** [comment]
> > 请显示您正在拍摄的影像设置的屏幕截图。
> 
> 我的意思是清洗边缘时进出刀的数量是有补偿的

I don't know if yours has this function

**Comment by lirui-dot** [comment]
> > > 请显示您正在拍摄的影像设置的屏幕截图。
> > 
> > 
> > 我的英文是锁边时进出刀的数量是有证明的
> 
> 不知道你的有没有这个功能

我的意思是在洗边的时候是否有进刀退刀量这个参数

**Comment by svenhb** [comment]
I think you mean offset from center?
https://github.com/svenhb/GRBL-Plotter/wiki/Drag-tool-compensation
![image](https://user-images.githubusercontent.com/19973251/128140679-09648a8d-b413-45cc-8fa8-57734cd3b816.png)

**Comment by lirui-dot** [comment]
> 我想你的意思是从中心偏移？
> https://github.com/svenhb/GRBL-Plotter/wiki/Drag-tool-compensation
> ![图像](https://user-images.githubusercontent.com/19973251/128140679-09648a8d-b413-45cc-8fa8-57734cd3b816.png)



> 我你的英文是从中心偏移想？
> https://github.com/svenhb/GRBL-Plotter/wiki/Drag-tool-compensation
> ![图像](https://user-images.githubusercontent.com/19973251/128140679-09648a8d-b413-45cc-8fa8-57734cd3b816.png)

I'll try

**Comment by svenhb** [comment]
Yes the distance from center to tip of the tool (brush or knife)
![image](https://user-images.githubusercontent.com/19973251/128142860-d237e163-01da-4992-aa93-3ae7db884843.png)

**Comment by lirui-dot** [comment]
![image](https://user-images.githubusercontent.com/74805870/128143067-75396663-764b-421c-ac13-067b701db73e.png)
这里设置吗

**Comment by svenhb** [comment]
![image](https://user-images.githubusercontent.com/19973251/128144654-e32e1610-6afe-41af-9d84-d84a56f4d73c.png)

**Comment by lirui-dot** [comment]
![image](https://user-images.githubusercontent.com/74805870/128144996-82c5f469-ddac-424c-8cbe-9b0167e12fd0.png)

**Comment by svenhb** [comment]
This looks correct: if the ramp z-value is below zero, the path will be drawn inside the 2-d view

**Comment by lirui-dot** [comment]
Can I choose more than one graphic

**Comment by svenhb** [comment]
No - sorry, all or one figure.
But I will try to implement.

**Comment by lirui-dot** [comment]
> 不 - 对不起，全部或一个数字。
> 但我会努力实现。

This should be easy to implement

**Comment by lirui-dot** [comment]
![image](https://user-images.githubusercontent.com/74805870/129515661-2030ca3c-a235-4573-a921-4f1d0d7991e4.png)
Can I set the XY center axis according to a graph

**Comment by lirui-dot** [comment]
![image](https://user-images.githubusercontent.com/74805870/129515772-e86b0db9-c061-42ce-b15e-d8e869c37bff.png)
Let's say I want to set it to this place in my circle based on this square

**Comment by svenhb** [comment]
You can change the offset in your GCode using this:
![image](https://user-images.githubusercontent.com/19973251/129529027-875008c7-9e9b-4383-85eb-f1779445fefb.png)
or this:
![image](https://user-images.githubusercontent.com/19973251/129529345-d30e545f-41f6-43e9-a4e5-19abe3e26be8.png)

Or you can apply an offset to your coordinate system, if a grbl controller is connected: https://grbl-plotter.de/index.php?id=form-coordinates&setlang=en

**Comment by lirui-dot** [comment]
> 您可以使用以下内容更改 GCode 中的偏移量 ：
> ![图像](https://user-images.githubusercontent.com/19973251/129529027-875008c7-9e9b-4383-85eb-f1779445fefb.png)
> 
> ![图像](https://user-images.githubusercontent.com/19973251/129529345-d30e545f-41f6-43e9-a4e5-19abe3e26be8.png)
> 
> 或者，如果连接了 grbl 控制器，您可以对坐标系应用偏移量：[https](https://grbl-plotter.de/index.php?id=form-coordinates&setlang=en) ://grbl-plotter.de/index.php?id [=](https://grbl-plotter.de/index.php?id=form-coordinates&setlang=en) form-coordinates&setlang [=](https://grbl-plotter.de/index.php?id=form-coordinates&setlang=en) en[](https://grbl-plotter.de/index.php?id=form-coordinates&setlang=en)

Is it possible to move according to a particular pattern

**Comment by lirui-dot** [comment]
![image](https://user-images.githubusercontent.com/74805870/129689044-35fe0a7a-dc04-4867-9464-4b02df7d78fa.png)
What is the order of the click graph

**Comment by lirui-dot** [comment]
> ![image](https://user-images.githubusercontent.com/74805870/129689044-35fe0a7a-dc04-4867-9464-4b02df7d78fa.png)
> What is the order of the click graph

Can you set it to a graph a grap

**Comment by lirui-dot** [comment]
![image](https://user-images.githubusercontent.com/74805870/129694260-e4be847a-a6a5-4141-94fa-f5d9a38acecf.png)
If I just want to dot one line here, it all changes color

**Comment by lirui-dot** [comment]
![image](https://user-images.githubusercontent.com/74805870/129697567-1111caba-e4d3-4460-a8e0-ad27d62c1515.png)
![image](https://user-images.githubusercontent.com/74805870/129697667-9c9d8df2-7e70-4a34-9646-850230ff1fe1.png)
Cad和导入的不一致

**Comment by lirui-dot** [comment]
![image](https://user-images.githubusercontent.com/74805870/129697865-04759be2-910f-4cea-8402-8db62d2550f2.png)
And what was the reason you said before

**Comment by svenhb** [comment]
>What is the order of the click graph 

If you enable pen-up path, you will see numbers of figure id.
![image](https://user-images.githubusercontent.com/19973251/129704946-de6709a8-8656-4bc3-bc28-95aa1c710d1d.png)

>If I just want to dot one line here, it all changes color 

Try selection modifier:
![image](https://user-images.githubusercontent.com/19973251/129705278-07dcb892-0748-4a68-8915-89ac76110972.png)

>And what was the reason you said before 

Division by zero, but was fixed: https://github.com/svenhb/GRBL-Plotter/issues/207
 Which version you are using? 
Try 1.6.0.2/3 https://github.com/svenhb/GRBL-Plotter/releases/tag/v1.6.0.2

**Comment by lirui-dot** [comment]
> > 点击图的顺序是什么
> 
> 如果您启用画笔路径，您将看到人物 ID 的数字。
> ![图像](https://user-images.githubusercontent.com/19973251/129704946-de6709a8-8656-4bc3-bc28-95aa1c710d1d.png)
> 
> > 如果我只想在这里画一条线，它都会改变颜色
> 
> 尝试选择修饰符：
> ![图像](https://user-images.githubusercontent.com/19973251/129705278-07dcb892-0748-4a68-8915-89ac76110972.png)
> 
> > 你之前说的原因是什么
> 
> 除以零，但已修复：#207
> 您使用的是哪个版本？
> 尝试 1.6.0.2/3 https://github.com/svenhb/GRBL-Plotter/releases/tag/v1.6.0.2

What do I need to change if I want to make changes in the previous version

**Comment by lirui-dot** [comment]
![image](https://user-images.githubusercontent.com/74805870/129828662-ce24b478-2951-44e7-b5f4-bdb17adc981e.png)
The latest version of this DXF has an error
[6-4-282-24.txt](https://github.com/svenhb/GRBL-Plotter/files/7004153/6-4-282-24.txt)

**Comment by lirui-dot** [comment]
What is the minimum computer that the latest version does not support

**Comment by lirui-dot** [comment]
> 最新版本不支持的最低电脑是多少

There is also a problem is the complex graphics too card, card burst

**Comment by svenhb** [comment]
>What is the minimum computer that the latest version does not support

Win XP is ok, but you can't use the installer. Instead unzip the ZIP file.

>There is also a problem is the complex graphics too card, card burst 

Can you explain?

**Comment by lirui-dot** [comment]
[测试.txt](https://github.com/svenhb/GRBL-Plotter/files/7005184/default.txt)
Try using this file

**Comment by lirui-dot** [comment]
> > 最新版本不支持的最低电脑是多少
> 
> Win XP 可以，但不能使用安装程序。而是解压缩 ZIP 文件。
> 
> > 还有一个问题就是复杂显卡太卡，卡爆了
> 
> 你可以解释吗？

You can do it in Xp but you have to generate a file

**Comment by svenhb** [comment]
>Try using this file 

It works on my old (14 years?) I5 notebook.

>You can do it in Xp but you have to generate a file 

Idea: you have your CNC plotter / router in the basement and control it with an old notebook/pc (e.g. with Win XP) via GRBL-Plotter.

**Comment by lirui-dot** [comment]
> > Try using this file
> 
> It works on my old (14 years?) I5 notebook.
> 
> > You can do it in Xp but you have to generate a file
> 
> Idea: you have your CNC plotter / router in the basement and control it with an old notebook/pc (e.g. with Win XP) via GRBL-Plotter.

Today's computers are also very slow

**Comment by lirui-dot** [comment]
> > > Try using this file
> > 
> > 
> > It works on my old (14 years?) I5 notebook.
> > > You can do it in Xp but you have to generate a file
> > 
> > 
> > Idea: you have your CNC plotter / router in the basement and control it with an old notebook/pc (e.g. with Win XP) via GRBL-Plotter.
> 
> Today's computers are also very slow

I just sent you that file

**Comment by lirui-dot** [comment]
> > > > 尝试使用此文件
> > > 
> > > 
> > > 它适用于我的旧（14 岁？）I5 笔记本。
> > > > 您可以在 Xp 中执行此操作，但必须生成一个文件
> > > 
> > > 
> > > 想法：你在地下室有你的 CNC 绘图仪/路由器，并通过 GRBL-Plotter 用旧笔记本/电脑（例如使用 Win XP）控制它。
> > 
> > 
> > 现在的电脑也很慢
> 
> 我刚把那个文件发给你

You can try it. Is it stuck

**Comment by svenhb** [comment]
I updated both setups here: https://github.com/svenhb/GRBL-Plotter/releases/tag/v1.6.0.2

**Comment by lirui-dot** [comment]
> 我在这里更新了两个设置：[https](https://github.com/svenhb/GRBL-Plotter/releases/tag/v1.6.0.2) : [//github.com/svenhb/GRBL-Plotter/releases/tag/v1.6.0.2](https://github.com/svenhb/GRBL-Plotter/releases/tag/v1.6.0.2)

That doesn't seem to help my problem

**Comment by svenhb** [comment]
I think your file-sizes are very huge, compared to the visible content. Perhaps you can export your drawings to SVG and then test import performance of GRBL-Plotter?

**Comment by lirui-dot** [comment]
> 我认为与可见内容相比，您的文件大小非常大。也许您可以将您的绘图导出为 SVG，然后测试 GRBL-Plotter 的导入性能？

But we mainly have more needs for DXF files

**Comment by lirui-dot** [comment]
> > 我认为与观察到的内容非常大，您可以将您的绘图导出为 SVG，然后测试 GRBL-Plotter 的导入性能？
> 
> 但是我们主要是对DXF文件有更多的需求

How to Export SVG

**Comment by svenhb** [comment]
>That doesn't seem to help my problem 

What exactly is the problem? This file 测试.txt ha a size of 2414 kB and took 5 sec. to be first visible and 12 sec. to be fully loaded - on my old I5.

**Comment by svenhb** [comment]
>How to Export SVG 

I don't know your CAD software, perhaps it's not possible.

**Comment by svenhb** [comment]
>I updated both setups here: https://github.com/svenhb/GRBL-Plotter/releases/tag/v1.6.0.2 

This link is now for version 1.6.0.4 with fix for this 
![image](https://user-images.githubusercontent.com/19973251/129857583-bcc7837d-6603-4822-abcb-c0885dfbc1bd.png)

**Comment by lirui-dot** [comment]
> > 我在这里更新了两个设置：[https](https://github.com/svenhb/GRBL-Plotter/releases/tag/v1.6.0.2) : [//github.com/svenhb/GRBL-Plotter/releases/tag/v1.6.0.2](https://github.com/svenhb/GRBL-Plotter/releases/tag/v1.6.0.2)
> 
> 此链接现在适用于 1.6.0.4 版，并对此进行了修复
> ![图像](https://user-images.githubusercontent.com/19973251/129857583-bcc7837d-6603-4822-abcb-c0885dfbc1bd.png)

I'm using the latest version

**Comment by lirui-dot** [comment]
> > > 我在这里更新了两个设置：[https](https://github.com/svenhb/GRBL-Plotter/releases/tag/v1.6.0.2) : [//github.com/svenhb/GRBL-Plotter/releases/tag/v1.6.0.2](https://github.com/svenhb/GRBL-Plotter/releases/tag/v1.6.0.2)
> > 
> > 
> > 此链接现在适用于 1.6.0.4 版，并在此进行了修复
> > ![图像](https://user-images.githubusercontent.com/19973251/129857583-bcc7837d-6603-4822-abcb-c0885dfbc1bd.png)
> 
> 我正在使用最新版本

Will the latest version support Windows 7 and XP

**Comment by svenhb** [comment]
>Will the latest version support Windows 7 and XP

I think so

**Comment by lirui-dot** [comment]
> > 最新版本是否支持 Windows 7 和 XP
> 
> 我认同

This version can support both

**Comment by lirui-dot** [comment]
> > > 最新版本是否支持 Windows 7 和 XP
> > 
> > 
> > 我是瑞士人
> 
> 这个版本可以同时支持

Can I set read-only graphics to not read G code

**Comment by svenhb** [comment]
>Can I set read-only graphics to not read G code

no

**Comment by lirui-dot** [comment]
Your latest source code does not work

**Comment by lirui-dot** [comment]
The latest source code run reported an error
![image](https://user-images.githubusercontent.com/74805870/129869155-3627bd29-cef4-4803-9db1-644378f747c4.png)

**Comment by svenhb** [comment]
There are two files like xmlMarker (old) and XmlMarker (new).
You need to delete the old files xmlMarker.cs and toolTable.cs

**Comment by svenhb** [comment]
And importMath

**Comment by lirui-dot** [comment]
> 有两个文件，如 xmlMarker（旧）和 XmlMarker（新）。
> 您需要删除旧文件 xmlMarker.cs 和 toolTable.cs

Are these two files changed in the latest version

**Comment by svenhb** [comment]
Yes changed content and name in 1.6.0.0

**Comment by lirui-dot** [comment]
When is there no error in updating the source code

**Comment by lirui-dot** [comment]
> 是在 1.6.0.0 中更改了内容和名称

There are still a lot of errors deleted
![image](https://user-images.githubusercontent.com/74805870/130170811-6a081c50-cc6e-4f63-8fa5-31e6aa8f9898.png)

**Comment by lirui-dot** [comment]
When is the latest source code updated

**Comment by lirui-dot** [comment]
> 最新的源代码什么时候更新

1.6.0.3     This version

**Comment by svenhb** [comment]
>When is the latest source code updated
Soon

**Comment by lirui-dot** [comment]
> > 最新的源代码什么时候更新
> 
> 很快

![image](https://user-images.githubusercontent.com/74805870/130211000-c6d82340-5db3-4b4c-bfc9-33d794519dc8.png)
The latest version reported an error
[as250-bottom-cover.txt](https://github.com/svenhb/GRBL-Plotter/files/7020458/as250-bottom-cover.txt)

**Comment by svenhb** [comment]
>The latest version reported an error 

Bug fix and source code update: https://github.com/svenhb/GRBL-Plotter/releases

**Comment by lirui-dot** [comment]
![image](https://user-images.githubusercontent.com/74805870/130345107-bd9b78d1-85a9-4cc6-8a89-654fe2f0157e.png)
The latest version is inconsistent with CAD
![image](https://user-images.githubusercontent.com/74805870/130345128-129bb6b6-db02-442e-a03c-7fc26b6b4c85.png)

**Comment by svenhb** [comment]
On the uper left edge is your drawing.
There is an artefact in the lower right edge, which is also imported - you should check inside your CAD:
![image](https://user-images.githubusercontent.com/19973251/130349487-20cac599-c18c-4aed-936a-07f2b0d66a92.png)

**Comment by lirui-dot** [comment]
> 左上角是您的绘图。
> 右下角有一个人工制品，它也是导入的 - 您应该检查 CAD 内部：
> ![形象](https://user-images.githubusercontent.com/19973251/130349487-20cac599-c18c-4aed-936a-07f2b0d66a92.png)

How to operate

**Comment by svenhb** [comment]
How to create a screenshot of the 2D view?
![image](https://user-images.githubusercontent.com/19973251/130349637-b76f2726-259c-4959-9e50-1180c083634c.png)

**Comment by lirui-dot** [comment]
> 如何创建 2D 视图的屏幕截图？
> ![形象](https://user-images.githubusercontent.com/19973251/130349637-b76f2726-259c-4959-9e50-1180c083634c.png)

It's the same thing

**Comment by svenhb** [comment]
You mean changing the view?
Use mouse wheel to zoom, arrow key to move view, press middle mouse key to move view or selected figure

**Comment by lirui-dot** [comment]
> 你是说换个角度？
> 使用鼠标滚轮缩放，方向键移动视图，按鼠标中键移动视图或选定图形

But the coordinates are wrong

**Comment by lirui-dot** [comment]
> > 你是说换个角度？
> > 使用鼠标滚轮缩放，方向键移动视图，按鼠标中键移动视图或指定图形
> 
> 但是坐标不对

We can't get this one off by a millimeter

**Comment by lirui-dot** [comment]
> > > 你是说换个角度？用
> > > 鼠标滚轮缩放，方向键移动视图，按鼠标中键移动视图或指定图形
> > 
> > 
> > 但是坐标不对
> 
> 我们不能把这个弄掉一毫米

We can't have any errors in our axes

**Comment by svenhb** [comment]
>The latest version is inconsistent with CAD 

I don't understand the problem - LibreCAD shows same coordinates (but not the artefact on the lower right edge).
GRBL-Plotter shows everythink inside the DXF file
![image](https://user-images.githubusercontent.com/19973251/132008090-87da61ab-31d2-4048-92a2-49fc8201867d.png)
![image](https://user-images.githubusercontent.com/19973251/132008183-e9ff7ab2-e9f2-4ab7-9e73-39dc67cde1df.png)
