### ISSUE TITLE
program stopped in middle of cutting, 

### ISSUE THREAD

**Issue by engine3061** [svenhb/GRBL-Plotter#214]
program stopped and machine stopped in the middle of cutting, is there a way to start the cutting back at a certain line in the gcode?

**Comment by svenhb** [comment]
Don't know if it works after break up, but after pause: you find a _processed.nc file in Menu-Open recent file.  
This file contains the GCode from editor when job was started.  
During a pasue the line number will be stored. 
If you load the _processed.nc file, you will be asked to continou at the last line. 
 
You may send me the logfile, to find the problem - located in the data folder (check the about window)

**Comment by engine3061** [comment]
i ran it after to see if it would start from spot it stopped but it started from beginning, and went into about and didnt see any data folder, i just deleted the lines out it already cut in editor and restarted it from there and seems to be working fine, not sure if you can put a run from command it where we can just type in what line we want to start from in cases like this

**Comment by engine3061** [comment]
also is there a delay i can put in for when the spindle goes to the starting point from the time i hit start, so the spindle can get u to speed before it starts without hitting the start spindle box

**Comment by svenhb** [comment]
>not sure if you can put a run from command it where we can just type in what line we want to start from  

It's difficult, because the grbl-controller doesn't know the modal states of the code before. E.g. Line 1 starts with switching on the spindle, but you start the code at line 5 - expecting the spindle is on, but it's not... You would break your tool.

**Comment by svenhb** [comment]
>also is there a delay i can put in for when the spindle 
 
If you import a graphic, you can set it:
![image](https://user-images.githubusercontent.com/19973251/128892830-3740d2c9-0557-45cc-9401-fd331d64ee02.png)

**Comment by svenhb** [comment]
I added the feature to start anywhere inside the code:
https://github.com/svenhb/GRBL-Plotter/releases

**Comment by svenhb** [comment]
No feedback is a good feedback 😉
