### ISSUE TITLE
Stabilo color palette

### ISSUE THREAD

**Issue by Kiriki-kun** [svenhb/GRBL-Plotter#216]
Hi,

In tutorial, you mentioned your stabilo color palette for gimp and inkscape.
I Can't find it inside GRBL.
Could you tell me where i can find it?

Best regards
Lucas

**Comment by svenhb** [comment]
Find attached what I have
[Color_palette.zip](https://github.com/svenhb/GRBL-Plotter/files/7012108/Color_palette.zip)

**Comment by Kiriki-kun** [comment]
Thanks, that is great!!
