### ISSUE TITLE
Improve graphic visualization (specifically with tiling)

### ISSUE THREAD

**Issue by amoineau** [svenhb/GRBL-Plotter#217]
Hi, I have two suggestions I would really like to see implemented to improve QoL :

**Don't superpose tiles when using the tiling feature**

Currently, when using the tiling feature every tile is displayed on top of each others, which makes the graph completely unreadable. Would it be possible to have the graph to be displayed "as is"?

**Form color**

Would it be possible for the forms to be drawn using the layer / tool color? This would allow for a much better understanding of what is going to happen and immediately notice if a form is not matched with the correct tool.

**Comment by amoineau** [comment]
I just wanted to specify that hiding the shapes that are not on the current tile could be a solution too. If it's simpler to achieve.

**Comment by svenhb** [comment]
>I just wanted to specify that hiding the shapes that are not on the current tile could be a solution too. If it's simpler to achieve. 

I need a good reason / context / switch: why to hide figures in the 2D view that are programmed in G-code.
What is your command to move to next tile - maybe that's a starting point to seperate the tiles.

**Comment by amoineau** [comment]
I see, the command I run between tiles is (^3 $CP1000). It tells the conveyor to move forward 1000 mm.

**Comment by svenhb** [comment]
I added the suggested features:
https://github.com/svenhb/GRBL-Plotter/releases

**Comment by amoineau** [comment]
Wow thank you, I'll try that today !

**Comment by amoineau** [comment]
Once again, it's some really nice work :

* The 2D view figure color is great, thank you !
---
* The display of tiles is a real improvement... with some limits ^^'
* Always seeing the original shape, instead of it folding, is obviously the big improvement !
* When the shapes of the second+ tiles are being processed the fact that the pink cursor is on the "real shape" plan and the black one is on the "machine" plan is actually really cool because you keep the best of both world : "where is the head IRL, and what am I drawing (or at least about to draw) ?".
* The big problem I see is that the green drawing is happening on the machine plan. Which makes things as messy as before after the first tile and go against the idea above, it's quickly impossible to follow what as been done, what is about to be done and even where is the head. 

![image](https://user-images.githubusercontent.com/72978966/132177930-8d104e4b-f0dd-4d32-871b-d001fe94644c.png)

(Here I chose a very hollow file with only two tiles just to keep the readability, but imagine 6 very busy tiles ^^).

It would be amazing if the green tracing happened on the "real shape" plan. Do you think it would be remotely possible ? That way we would have every possible information with complete readability !

I'm sorry to ask so much of you, I would understand if you wanted to keep it there. I just feel like the tile feature would be so neat and complete with that. (I hope I am not the only one using it because it would be a shame)

**Comment by svenhb** [comment]
>It would be amazing if the green tracing happened on the "real shape" plan. Do you think it would be remotely possible ? That way we would have every possible information with complete readability ! 

I understand the problem, but not your suggested solution. Perhaps: Within the working area you want only to see the figures of the actually proccessed tile?

**Comment by amoineau** [comment]
I made the worst paint edit in hope that it would be clearer than words x) :

![image](https://user-images.githubusercontent.com/72978966/132199724-595ca762-78c1-4190-8cf7-1b7c4e8b7f8f.png)

I wished the green tracing that overwrites the processed shapes, would actually overwrite the shapes (even after the first tile). Right now the green lines are all stacked on the "machine" plan. 

I don't know if this is any clearer, don't hesitate to ask again ! ^^

**Comment by amoineau** [comment]
The drawback would be that the black cursor would be moving alone in the machine plan, but hey, you can't have it all ;)

**Comment by svenhb** [comment]
Like this? https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_Setup_1611_20190906.exe

**Comment by amoineau** [comment]
I got this :

![image](https://user-images.githubusercontent.com/72978966/132313018-b8c1ca0a-b651-45bb-8799-968b996995d9.png)

(The exterior of all sails has been processed on both tiles)

The green tracing doesn't stack on the machine plan but it doesn't seem to appear elsewhere either :(
And in the areas I circled there are some artefacts, but maybe it is not related to the changes.

**Comment by svenhb** [comment]
Can you try to hide the limit area? I think it's a problem with the red grid.

**Comment by amoineau** [comment]
I got a similar result :

![image](https://user-images.githubusercontent.com/72978966/132330794-fe7553c6-fcc8-4545-a091-f39cfcab5ba5.png)

Is that what you wanted ?

**Comment by svenhb** [comment]
How does it look, if you simulate the path?

**Comment by svenhb** [comment]
This means:
- with simulation all figures are marked correctly one by one tile by tile? (don't look at the "glitches") 
- on real process it only marks the figures within the working space 

Is this correct?

**Comment by amoineau** [comment]
Yes, I will try with a file more than two tiles long just to make sure.

**Comment by svenhb** [comment]
Good to know, will try to fix it

**Comment by amoineau** [comment]
Thank you ! Good luck ^^'

**Comment by svenhb** [comment]
Try https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_Setup_1611_20210907.exe

**Comment by amoineau** [comment]
I'm running the tests but for now the thing I noticed is that the dark green lines representing the pen path are slightly broken :/
 
![image](https://user-images.githubusercontent.com/72978966/132458324-f1501185-dd22-4225-886b-e317de845e81.png)

**Comment by amoineau** [comment]
It worked on that file !

![image](https://user-images.githubusercontent.com/72978966/132458633-9b8db104-714b-4a25-855f-a04dd51455f7.png)

**Comment by svenhb** [comment]
Little improovement with pen-up path: https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_Setup_1611_20210908.exe

**Comment by amoineau** [comment]
Hi, sorry I am on a business trip since yesterday, I'll check it next week. Thank you again :)

**Comment by amoineau** [comment]
Hi ! I finally got time to test it and it seems to be working well, thank you :)

I showed the previous version to the people who are going to use the machine and they found it confusing that the graphic doesn't shift left into the machine limit when moving to the next tile...
I know we are straying further and further from the original purpose of your software but do you think it would be hard to offset the visual after each tile ?

What they want would be to always have the current tile inside the machine limit (and that way the black cursor would stay on the graphic). I'm really hoping they will be satisfied after that so you can close this issue :/

**Comment by amoineau** [comment]
Hello, did you consider my request ? I would understand if it was a no ^^'

**Comment by svenhb** [comment]
>What they want would be to always have the current tile inside the machine limit (and that way the black cursor would stay on the graphic).

I tried to implement, but you have to live with strange behavior of the progress path. You need to wait until the next release - perhaps next weekend.

**Comment by amoineau** [comment]
Ok sure, It's really not a pressing matter ! I simply wasn't sure you saw my last messages considering I took quite some time to answer yours last time, you might have moved on ^^
Thank you.

**Comment by svenhb** [comment]
Improoved behavior of progressed path display: https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_Setup_1_6_2_1.exe

**Comment by svenhb** [comment]
Check new release: https://github.com/svenhb/GRBL-Plotter/releases
Perhaps a bit improovement of behavior if "Move the tiles" is enabled.
![image](https://user-images.githubusercontent.com/19973251/139717017-a236cddc-8dce-49aa-b074-847901fa13a8.png)

**Comment by amoineau** [comment]
Ok, I'll try that as soon as I can, thank you.

**Comment by amoineau** [comment]
I tried it and it seems to have two problems (which might be the same) :
* When I don't use "Moves the tiles to 0;0", the light green tracing representing what has been done stays on the first tile even when doing the second one. However I recall that at some point you succeeded in making sure that this tracing followed the current progression in this configuration.
* When using "Moves the tiles to 0;0", after shifting, the light green tracing disappear for the previous tile and the one for the next tile is drawn on the first tile instead of the "0;0 area" ( which looks even weirder since the tile is shifted left, in the negative positions) :

![image](https://user-images.githubusercontent.com/72978966/139854596-ce30cc5e-1098-47c1-9f86-89cbcb1cbe98.png)

Here we can see the green light tracing for the first tile is missing and is currently being drawn on the current position of the first tile.

Apart from that, having the option to switch between both mode is really great and everything else seems to be working very well !

**Comment by svenhb** [comment]
Hard to understand, perhaps you can make a short video?
With my test data it looks as expected.

**Comment by amoineau** [comment]
Short video will be hard, the files are rather long to process and i'm really not well versed in video capture with what I have at work. But I will try to make step by step captures to explain better. In the meantime here is the file if you want to try it and see if you get a different result than my previous screenshots :

[dxf-sample-amoineau.zip](https://github.com/svenhb/GRBL-Plotter/files/7461197/dxf-sample-amoineau.zip)

Maybe  some settings are interfering with each other, in my config and not yours...

**Comment by amoineau** [comment]
When I start, the first tile is processed normally :
![processing-first-tile](https://user-images.githubusercontent.com/72978966/139864648-e2505cfb-ae46-4a46-8800-ac50d4738a34.png)

The the first is finished, the green tracing is perfect :
![first-tile-processed](https://user-images.githubusercontent.com/72978966/139864928-4be03039-5f15-4a19-a83d-1d9555a519aa.png)

Then the graph is shifted to the left, as expected, but the green tracing drawn until then disappears :
![just-after-shifting](https://user-images.githubusercontent.com/72978966/139865179-cb4e51cf-35e4-43d2-9751-c6728cbe05e4.png)

Now we are processing the second tile, and the green tracing is being drawn correctly, albeit one tile to the left : 
![processing-second-tile](https://user-images.githubusercontent.com/72978966/139865466-02e0d9ec-361f-4845-9efc-f6a0e12eaae6.png)

At the end of the second tile we have this : 
![second-tile-processed](https://user-images.githubusercontent.com/72978966/139865596-cae4de5f-d7ec-4564-ab39-a432650afabe.png)

**Comment by amoineau** [comment]
Does this help you understand ?

**Comment by svenhb** [comment]
>Does this help you understand ? 

Yes 
>Then the graph is shifted to the left, as expected, but the green tracing drawn until then disappears :  

that is intentional, otherwise each tile needs to get a seperate "processed" path. 

>Now we are processing the second tile, and the green tracing is being drawn correctly, albeit one tile to the left : 

this looks wrong and is different to my intention and tests - the green path should appear in the work area of the current tile...

**Comment by svenhb** [comment]
Perhaps you can also show your tool-table "laser_pen_default.csv"?

**Comment by svenhb** [comment]
I edited the last release: https://github.com/svenhb/GRBL-Plotter/releases 
#### 1.6.2.3
- DXF Import add DXFText (before just DXFMText)
- Bug fix tile shift offset of processed path

**Comment by amoineau** [comment]
> > Then the graph is shifted to the left, as expected, but the green tracing drawn until then disappears :
> 
> that is intentional, otherwise each tile needs to get a seperate "processed" path.

That's understandable, and really not a problem indeed, considering we already know on which tile we are when using this mode.

**Comment by amoineau** [comment]
> Perhaps you can also show your tool-table "laser_pen_default.csv"?

Sure : 
![image](https://user-images.githubusercontent.com/72978966/140021791-ff0b503f-928a-4fe4-a9ab-4b93bd090ebf.png)

**Comment by amoineau** [comment]
> I edited the last release: https://github.com/svenhb/GRBL-Plotter/releases
>

Thank you ! I will try to test it today.

**Comment by svenhb** [comment]
>Here is my config if it can help :  

BTW,, to reduce G-Code size and communication load,
I would use just 2 decimals
![image](https://user-images.githubusercontent.com/19973251/140054061-cc007b13-c02a-4dd1-9fff-9069e2d7c5ea.png)

and enable "Remove very short moves" with perhaps 0.5? Should be accurate enough in this dimensions.
![image](https://user-images.githubusercontent.com/19973251/140054643-5021500a-24f4-4b70-a6c1-e92258c7a682.png)

**Comment by amoineau** [comment]
Thanks for the advice !

**Comment by amoineau** [comment]
I unchecked the remove very short moves because it used to completely alter the shapes. I tried again and even with 0.05 it still does, here is a example (not the most visible one but is already too much).

This is the file without the option :

![not-ignored](https://user-images.githubusercontent.com/72978966/141770466-1e4f9a01-85e5-4b9a-bc01-81de3523a25b.png)

And this is the file with :

![ignored](https://user-images.githubusercontent.com/72978966/141770387-0a0d31c8-e2d4-4cb9-9fe7-782da7ca2a93.png)

**Comment by amoineau** [comment]
On a side note, the new version works really well ! I'll do more extensive test this afternoon and tomorrow but the first test is really satisfying.

**Comment by svenhb** [comment]
I found a bug in "remove very short moves", will fix it soon.

**Comment by amoineau** [comment]
Ok, cool !

**Comment by svenhb** [comment]
I fixed the bug: https://github.com/svenhb/GRBL-Plotter/releases

**Comment by amoineau** [comment]
Ok cool I should be able to try it on Thursday !
