### ISSUE TITLE
Does the current version have lathe machining

### ISSUE THREAD

**Issue by lirui-dot** [svenhb/GRBL-Plotter#218]
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by svenhb** [comment]
No lathe machining, but rotary axis is supported

**Comment by lirui-dot** [comment]
> 无车床加工，但支持旋转轴

How to set up

**Comment by svenhb** [comment]
https://youtu.be/BLRfBk9yIbw

**Comment by lirui-dot** [comment]
Why can't you debug it

**Comment by svenhb** [comment]
Debug what?

**Comment by lirui-dot** [comment]
> Debug what?

I just can't debug it

**Comment by lirui-dot** [comment]
![微信图片_20210901084724](https://user-images.githubusercontent.com/74805870/131594087-2324be71-cea4-410c-82fc-e66b527f29f3.png)

**Comment by lirui-dot** [comment]
![image](https://user-images.githubusercontent.com/74805870/131597084-9d6c6ef6-7cf8-49e5-b12c-e62288a48a50.png)
Can't debug

**Comment by svenhb** [comment]
You use old version of CheckUpdate.cs

**Comment by lirui-dot** [comment]
> 您使用旧版本的 CheckUpdate.cs

ok

**Comment by lirui-dot** [comment]
Still can't

**Comment by svenhb** [comment]
You may delete all your local  files and download again the project

**Comment by lirui-dot** [comment]
> 您可以删除所有本地文件并重新下载项目

ok

**Comment by lirui-dot** [comment]
Still can't

**Comment by lirui-dot** [comment]
> 还是不能

debug Still can't

**Comment by svenhb** [comment]
Did you try Release-mode?
![image](https://user-images.githubusercontent.com/19973251/131628716-b96a1a35-2752-43ac-ba62-b8ad5dbf0a4d.png)

**Comment by lirui-dot** [comment]
> 您是否尝试过发布模式？
> ![图片](https://user-images.githubusercontent.com/19973251/131628716-b96a1a35-2752-43ac-ba62-b8ad5dbf0a4d.png)

NO

**Comment by lirui-dot** [comment]
> > 您是否已经尝试过发布模式？
> > ![图片](https://user-images.githubusercontent.com/19973251/131628716-b96a1a35-2752-43ac-ba62-b8ad5dbf0a4d.png)
> 
> 不

You can't

**Comment by lirui-dot** [comment]
> > > 您是否已经尝试过发布模式？
> > > ![图片](https://user-images.githubusercontent.com/19973251/131628716-b96a1a35-2752-43ac-ba62-b8ad5dbf0a4d.png)
> > 
> > 
> > 不
> 
> You can't

How to deal with this problem

**Comment by svenhb** [comment]
Do you use VisualStudio 2019?
Did you also replace https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter.sln?

**Comment by lirui-dot** [comment]
> 你使用 VisualStudio 2019 吗？
> 您是否也替换了https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter.sln？

yes

**Comment by svenhb** [comment]
Current Version is with uppercase
![image](https://user-images.githubusercontent.com/19973251/131639719-7e442c2c-fd7e-45ab-bc43-0d6a60fb12d0.png)

**Comment by lirui-dot** [comment]
> 当前版本为大写
> ![图片](https://user-images.githubusercontent.com/19973251/131639719-7e442c2c-fd7e-45ab-bc43-0d6a60fb12d0.png)

Also tried
