### ISSUE TITLE
Tangential knife angle does not follow xy trajectory

### ISSUE THREAD

**Issue by lm150617** [svenhb/GRBL-Plotter#219]
The tangential knife angle does not follow the xy trajectory of my path. The blade stays at a 0 degree angle.

Changes to the default setup:

File/Setup/Graphic imports/Path imports/Path modifications
1. Add Tangential Axis (Enabled)
2. Name of tangential axis (Z)
3. Swivel angle (30)
4. Correct start angle if deviation is > (5)
5. Units per turn (3.6)

File/Setup/Graphic imports/G-Code generation
1. Z axis (Disabled)
2. PWM(Enabled)
3. Pen Up (50)
4. Pend Down (500)

I expected the blade to rotate as it passes through the rounded edge, like in this demo: https://youtu.be/uMFyTCK8Ggw

Screenshot:
![Capture](https://user-images.githubusercontent.com/89826429/131446543-24d5022a-3d6a-4585-b4ce-60c73b6f8293.PNG)

**Comment by svenhb** [comment]
This modification only works on graphics import. After import you see the applied modifications in the bottom line:
![image](https://user-images.githubusercontent.com/19973251/131453542-cc423c18-af49-4ff0-9c53-7e925fb4c0c2.png)
I don't see this in your screenshot, propably you loaded a GCode file, which will not be modified by this setup.

**Comment by lm150617** [comment]
Im using Inkscape. I made a path to look similar to the one on your Youtube video. I imported as an .svg file.

![Capture2 reset](https://user-images.githubusercontent.com/89826429/131454287-bda36c16-f01f-40ef-b42a-0ba4ad3ceb07.PNG)

**Comment by svenhb** [comment]
Did you read my edited comment?
What do you see as import options in the bottom line after import?
![image](https://user-images.githubusercontent.com/19973251/131455035-f4fa358a-fcba-4e39-aa0d-8b3e0d8d11be.png)

**Comment by lm150617** [comment]
I see :
[Import options: <Remove offset> <Tangent axis>]

**Comment by lm150617** [comment]
I see:
[Import options:<Remove offset><Tangent axis>]

**Comment by svenhb** [comment]
Can you upload your svg file?

**Comment by lm150617** [comment]
I tried but github error says "We don't support that file type"  
Is a zip okay?
[test 1.zip](https://github.com/svenhb/GRBL-Plotter/files/7081821/test.1.zip)

**Comment by svenhb** [comment]
Are you sure your settings here are same?
![image](https://user-images.githubusercontent.com/19973251/131456046-341d21af-a7a6-4cbf-939d-740566ea8e25.png)

**Comment by lm150617** [comment]
Yeah I checked it many times and tried to play aroud with the numbers and its the same every time.

**Comment by lm150617** [comment]
![Capture settings](https://user-images.githubusercontent.com/89826429/131456398-5a62ddc2-51ee-4c5e-a8df-24b1987b9465.PNG)

**Comment by lm150617** [comment]
The only way ive been able to make it work is doing a circle with a 90 
![Capture working](https://user-images.githubusercontent.com/89826429/131458029-8f02f725-9b9d-486b-acfe-adebcb1b4112.PNG)
degree cw transformation.

**Comment by lm150617** [comment]
The only way ive been able to make it work is doing a circle with a 90 degree cw transformation.


![Capture working](https://user-images.githubusercontent.com/89826429/131458165-137a30cb-74c9-4218-b8ea-65159d85f4dc.PNG)

**Comment by svenhb** [comment]
Your test1.svg works for me... What settings do have here:
![image](https://user-images.githubusercontent.com/19973251/131460749-c4009fef-5135-4bed-b7bc-e8f73c629c07.png)

**Comment by lm150617** [comment]
![Capture question](https://user-images.githubusercontent.com/89826429/131461252-690d4209-52d3-4814-8522-5df2b10c0d38.PNG)

**Comment by svenhb** [comment]
I assume there is an additional modification activated, which is not listet in the bottom line...
There should be no difference with this issue, but who knows... Try latest Version 1.6.0.5: https://github.com/svenhb/GRBL-Plotter/releases

**Comment by lm150617** [comment]
Thank you for taking the time to look at my issue. I appreciate you!

**Comment by svenhb** [comment]
Any success up to now?

**Comment by lm150617** [comment]
No, I've noticed that when I upload an svg the z axis stays at 0 unles its a circle. Also I don't see an up/down translation command at corners. Any idea why im not having success?

**Comment by svenhb** [comment]
Perhaps it is solved, if your problem matches #270 or #272
[New features](https://github.com/svenhb/GRBL-Plotter/releases)
