### ISSUE TITLE
Special conversion

### ISSUE THREAD

**Issue by trantai369** [svenhb/GRBL-Plotter#220]
Hi!
how to remove groove in curve
i want the grooves in the corner
can you suggest the code
thanks

![image](https://user-images.githubusercontent.com/90038474/131989964-5db29cf6-dcfd-4fab-931b-a6c3e00b3569.png)
![image](https://user-images.githubusercontent.com/90038474/131990690-71dfde32-c019-49c3-90d7-ee95b619f724.png)

**Comment by svenhb** [comment]
Should work if you comment out lines 194, 195:
```
//                            else
//                            { distAccumulated += distance; }   // is curve, accumulate small distances

```

**Comment by trantai369** [comment]
> Sẽ hoạt động nếu bạn nhận xét ra các dòng 194, 195:
> 
> ```
> //                            else
> //                            { distAccumulated += distance; }   // is curve, accumulate small distances
> ```

I made it
but not active
thanks you

**Comment by trantai369** [comment]
I fixed many codes
but they don't work
someone help me

**Comment by svenhb** [comment]
I  built in an option to switch off notches in curves. Will upload in some hours.

**Comment by trantai369** [comment]
> I built in an option to switch off notches in curves. Will upload in some hours.

Thanks you !

**Comment by svenhb** [comment]
https://github.com/svenhb/GRBL-Plotter/releases
![image](https://user-images.githubusercontent.com/19973251/132100700-ba35255c-730f-4cb5-a821-ff3819c54804.png)

**Comment by trantai369** [comment]
Hi Svenhb !
doesn't seem to work well
![2](https://user-images.githubusercontent.com/90038474/132102981-21d19d33-093b-49dc-842c-976c2b0f1442.png)
![1](https://user-images.githubusercontent.com/90038474/132102982-162d925d-01c3-46f3-a1d1-546a9c697b2f.png)

**Comment by svenhb** [comment]
It looks like, what I expect - no grooves / notches within the curves
![image](https://user-images.githubusercontent.com/19973251/132106434-848d8ad0-bc88-45b6-acd1-d3808f0dfc22.png)

And here with grooves / notches for easier bending:
![image](https://user-images.githubusercontent.com/19973251/132106461-096b8e3e-72b3-473e-a787-500c57bccd41.png)

**Comment by trantai369** [comment]
I think it's more than one paragraph

![image](https://user-images.githubusercontent.com/90038474/132110259-dbf32c92-1248-40cc-b64b-96cfea0358f1.png)

**Comment by svenhb** [comment]
For me it is correct:
I assume an endless band of material, so you can cut more letters in once.
1) the start cut will be made to have a defined edge
5) end of the object, cut off from material band 
![image](https://user-images.githubusercontent.com/19973251/132118456-7b57581e-5fbe-4531-887a-598353c52874.png)

**Comment by trantai369** [comment]
> ![image](https://user-images.githubusercontent.com/19973251/132106434-848d8ad0-bc88-45b6-acd1-d3808f0dfc22.png)

can you optimize it?
there is 1 more embryo to remove

![132118456-7b57581e-5fbe-4531-887a-598353c52874](https://user-images.githubusercontent.com/90038474/132126289-5dc1d51a-5577-490b-af60-5733b599401c.png)

Like the picture this picture is better

**Comment by svenhb** [comment]
Startpoint depends on your graphics and import settings:
Switch off sorting to keep original start point from your drawing
![image](https://user-images.githubusercontent.com/19973251/132139958-494ea48e-5f30-4b66-aec4-f1f8683e27cc.png)

**Comment by trantai369** [comment]
Hi Svenhb !

![Untitled](https://user-images.githubusercontent.com/90038474/132259303-ef337dac-0de6-4eb7-9251-6e31fa363aef.png)

**Comment by svenhb** [comment]
You are wrong, explanation of "Min distance....":
Drawing with segment length of ca. 5:
![image](https://user-images.githubusercontent.com/19973251/132296252-14c558ad-218a-4cc2-859c-64df67440be3.png)
If "Min distance..." is 4, every edge causes a notch:
![image](https://user-images.githubusercontent.com/19973251/132296426-cbbdeab1-bd87-4582-9fa9-e7944f6f2a35.png)
If "Min distance..." is 6, segments will be summed up to create a curve - if enabled (it's not here):
![image](https://user-images.githubusercontent.com/19973251/132296583-8fe1bf28-1907-4dd3-a108-3e3fcb4a1a64.png)
With curves enabled:
![image](https://user-images.githubusercontent.com/19973251/132296695-ad77fd48-66e5-46cf-9e35-9bd86a426329.png)

Also Tool angle has an influence to the total length:
![image](https://user-images.githubusercontent.com/19973251/132296755-bcc8702e-6e08-402f-b097-c77bbde3a032.png)

**Comment by trantai369** [comment]
how to have numbers automatically ?  For some vectors it hasn't eliminated the "curve" completely.

**Comment by svenhb** [comment]
>how to have numbers automatically ?  

https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_Setup_1611_20190906.exe

>For some vectors it hasn't eliminated the "curve" completely. 

Then you need to adapt the "Min distance" value

**Comment by trantai369** [comment]
![Untitled-2](https://user-images.githubusercontent.com/90038474/132318915-266a8be2-33a7-4e1b-890d-252e24a124d4.png)

You can completely remove the curved points automatically. If tick "No curve".

**Comment by svenhb** [comment]
I choose 10% of figure height: https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_Setup_1611_20210907.exe

**Comment by trantai369** [comment]
> I choose 10% of figure height: https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_Setup_1611_20210907.exe

Thanks you
I checked, it's working fine now

**Comment by trantai369** [comment]
![Untitled](https://user-images.githubusercontent.com/90038474/132491689-9b4829d7-de59-481a-8d9e-07e888c724ff.png)

**Comment by svenhb** [comment]
https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_Setup_1611_20210908.exe
![image](https://user-images.githubusercontent.com/19973251/132572160-359941de-c60f-4bd6-9656-e6003ba1a183.png)

**Comment by trantai369** [comment]
You open source code ?
Thanks

**Comment by svenhb** [comment]
I will collect improovements - then I make a new release with updated source code

**Comment by trantai369** [comment]
![1](https://user-images.githubusercontent.com/90038474/132955518-7bbb4304-b529-4280-a354-fb598b66f2ab.png)
![2](https://user-images.githubusercontent.com/90038474/132955526-70b2afd9-bd3e-4a1d-85d5-5052cc1d4653.png)

Error detected
Same file, when increasing or decreasing "Min distance" length will be lost

**Comment by svenhb** [comment]
A tool angle of 1° is not recommended I would say.... 
Better try with something usefull 30° to 120° which you could buy as a tool.

**Comment by trantai369** [comment]
> A tool angle of 1° is not recommended I would say....
> Better try with something usefull 30° to 120° which you could buy as a tool.

I've done it but it doesn't work well
It works fine when setting "Min. distance" >=1 but this doesn't change the distance of edges
The "Z-Height" parameters do not work well, they run too many times at small distances, which is unnecessary. Just run 1 position according to the number of times Z is turned on.
You should see how the gcode length will change when adjusting these parameters.
The parameter "Tool angle" is not really necessary, just set it fixed, the paths will overlap, but no problem
The No cuver function works fine at this point.

**Comment by trantai369** [comment]
Loss of length
I think the "Tool angle" should be fixed
The grooves are evenly divided according to the limit when "No curve" is removed.

![Untitled](https://user-images.githubusercontent.com/90038474/133009060-50dd4c43-5d8f-49f7-9081-6bdedd29541f.png)
![c6d43d3004e7f2b9abf6](https://user-images.githubusercontent.com/90038474/133009093-c8de03e9-76b3-4362-aec0-1d1557574fa1.jpg)

**Comment by svenhb** [comment]
The distance from notch to notch depends on tool angle and "Z-height for notch engraving": 
 - the larger the angle, the greater the distance 
 - the deeper the notch, the greater the distance
![image](https://user-images.githubusercontent.com/19973251/133068600-22f0768c-79c8-49b4-b80e-b11d0e7c8fc8.png)

**Comment by svenhb** [comment]
Can you upload your 33.svg file?
![image](https://user-images.githubusercontent.com/19973251/133076245-e47571f9-fb19-4f32-88ea-b9abb15af951.png)

**Comment by trantai369** [comment]
![image](https://user-images.githubusercontent.com/90038474/133134690-061336a8-9976-4283-bb55-c08bd66af0ae.png)

[33.zip](https://github.com/svenhb/GRBL-Plotter/files/7156500/33.zip)

**Comment by svenhb** [comment]
Now with more information in the background path: https://grbl-plotter.de/index.php?id=form-setup#pathdevelopment
