### ISSUE TITLE
Center red circle function moves counter clockwise around the red circle 

### ISSUE THREAD

**Issue by yagizzha** [svenhb/GRBL-Plotter#222]
Tried the center red circle function , it was just moving counter clockwise around it rather then actually centering it

**Comment by svenhb** [comment]
I don't know which function you try to use.
Please give screenshots, the file you try to import, everything which helps to understand and follow the problem.

**Comment by yagizzha** [comment]
![image](https://user-images.githubusercontent.com/88779645/132485188-7d971a36-99bb-4eaf-91dc-a3923b04bf42.png)

This is the button/function i was trying to use , because of a electric outage i cant send the full screenshot

**Comment by svenhb** [comment]
I didn't tried for a long time.... Perhaps you need to select a filter set first (upper right drop-down)? As seen on the screenshot here: https://github.com/svenhb/GRBL-Plotter/wiki/PCB-drilling
