### ISSUE TITLE
Help with fiducial marking

### ISSUE THREAD

**Issue by yagizzha** [svenhb/GRBL-Plotter#223]
I am trying to automate the fiducial selecting process, 
wanted to ask at which part is the svg files drawings go into GRBL-Plotter's coordinate system and how i could mark them as fiducials

**Comment by trantai369** [comment]
![Untitled](https://user-images.githubusercontent.com/90038474/132874384-5977f225-b073-46c4-bc8d-4f457ec6befa.png)
Is this the problem?
Please provide more photos

**Comment by futurau** [comment]
We want to select a circle named with id="fiducial
For example: 
<svg xmlns="http://www.w3.org/2000/svg" width="210mm" height="297mm" viewBox="0 0 595.28 841.89">
  <defs>
    <style>
      .cls-1 {
        fill: #231f20;
      }
    </style>
  </defs>
  <title>test</title>
  <g id="fiducial">
    <circle class="cls-1" cx="118.5" cy="269.5" r="16.5"/>
  </g>
</svg>
How can we select the circle with a specific id after importing to GRBL-Plotter.

**Comment by yagizzha** [comment]
![image](https://user-images.githubusercontent.com/88779645/132928587-38d99c6b-8da8-4def-9d1d-347aece49d4f.png)
when you use this function to select a circle for example , how does the code know which circle in the svg file is selected. 
Trying to have a system that puts dots to similiar places so i can automate it , but not sure on how to select them to start formatting

**Comment by svenhb** [comment]
This dialog is for image recognition, check: https://github.com/svenhb/GRBL-Plotter/wiki/PCB-drilling
![image](https://user-images.githubusercontent.com/19973251/132939544-cda9c384-7ea5-42df-a7f0-ad3afdebeda9.png)

**Comment by svenhb** [comment]
>wanted to ask at which part is the svg files drawings go into GRBL-Plotter's coordinate system 

Check here: https://github.com/svenhb/GRBL-Plotter/tree/master/GRBL-Plotter/GCodeCreation/ImportFromFile

**Comment by futurau** [comment]
can  we add (comments) in G-code?

**Comment by svenhb** [comment]
No, but you may see SVG-id in group or figure XML attribute

**Comment by svenhb** [comment]
![image](https://user-images.githubusercontent.com/19973251/132940569-f6867b8b-3d27-4604-b0b3-c128e2ff5778.png)

**Comment by yagizzha** [comment]
Another problem i have right now is not being able to mark circles as fiducials or not being sure if i picked or not  : 

![image](https://user-images.githubusercontent.com/88779645/133088761-26af7529-3826-4890-b369-dd991e2a4bff.png)

On https://github.com/svenhb/GRBL-Plotter/wiki/PCB-drilling it says i need to click on it to mark as teach point . 

![image](https://user-images.githubusercontent.com/88779645/133088954-8f4e38dd-0839-4263-8c95-82698d20c3f2.png)

on here the picked one has a pink cross on it

**Comment by svenhb** [comment]
In my example the figures are drills (just a point in DXF file). The marker will only snap on coordinates which are given in the GCode.

**Comment by svenhb** [comment]
In the next release the center of real circles (G2 / G3 GCode) can be selected.
