### ISSUE TITLE
Coordinate systems breaking after setting up fiducials 

### ISSUE THREAD

**Issue by yagizzha** [svenhb/GRBL-Plotter#224]
![image](https://user-images.githubusercontent.com/88779645/133613852-d4c48440-948f-44f4-824c-b9b670be8db4.png)

Coordinate system works correctly until we use fiducials to compensate angle and scaling , at which point they become diffrent . Zero'ing them doesnt take them to their original zero. Is there a step im missing or maybe there is a fix ?

**Comment by svenhb** [comment]
When teaching and applying the points, the GCode will be modified - no step back, except reloading the GCode.
https://github.com/svenhb/GRBL-Plotter/wiki/PCB-drilling

Not sure if "Undo" will be shown, as for other operations, via menu - translation

**Comment by futurau** [comment]
On main screen DRO shows offset between g54 and machine coordinate system 
but on control coordinate system window we can’t see the offset.

**Comment by svenhb** [comment]
Camera form applies G92:
![image](https://user-images.githubusercontent.com/19973251/133620865-5f175f59-4f5b-41ca-85ff-d0d47c0439ef.png)

**Comment by futurau** [comment]
https://media.giphy.com/media/3ohhwkfYcpOyeuepqw/giphy.gif

**Comment by futurau** [comment]
`https://media.giphy.com/media/3ohhwkfYcpOyeuepqw/giphy.gif`

**Comment by futurau** [comment]
Thanks a lot.
