### ISSUE TITLE
After doing camera setup for tool coordinate, coordinate system breaks

### ISSUE THREAD

**Issue by yagizzha** [svenhb/GRBL-Plotter#225]
![image](https://user-images.githubusercontent.com/88779645/134130457-a124b947-6d73-45a1-b415-de4aba09466f.png)

After 0'ing X and Y to set up our tool and camera coordinate , homing again results in weird points . -711 and -370 on G54 for example . Is there a way to make tool coordinate so that its relative to our current position rather then having a set position?

**Comment by svenhb** [comment]
Don't you use homing to get a machine reference point?

**Comment by svenhb** [comment]
At least you could move to lower left position (hardware stop) and do an hardware reset of you grbl-controller to get 0;0 for machine coordinates.

**Comment by futurau** [comment]
In reality, camera position is relative to tool position (xy offset between camera and tool). 
But camera coordinate system and tool coordinate systems are relative to machine coordinate system in g-code logic.
If we reset grbl or zero machine coordinate system; selected coordinate system (for example G54) change but the other coordinate system doesn’t change (for example G59). 
And the offset value between G54 and G59 became wrong.
We can’t find a way to store and reuse tool and camera offset after homing or resetting system.
Any suggestions?

**Comment by svenhb** [comment]
I'm working on two new camera mountings:
- fix camera - observing the whole working area
- camera mounted on xy platform, but pointing on tool position - no need for G54 / G59
Still in progress but I already started the manual: https://grbl-plotter.de/index.php?id=form-camera-1&lang=en
