### ISSUE TITLE
Potential addition for automation

### ISSUE THREAD

**Issue by yagizzha** [svenhb/GRBL-Plotter#226]
We've been using your code's changed version together with python to calculate how to automate the process of cutting/drawing . To do this we've used circle fiducials on a checkboard table . Python side changes angle of camera to near 90 degree from top vision and finds fiducials on paper after image has been processed. After taking these and knowing the total size of table it can tell where to go in GCode which we send through a server we put on your program . 

If any of this would be helpful to you i can post them  

Base:
![distort1](https://user-images.githubusercontent.com/88779645/134161433-6a991cae-9e97-4a96-8a84-6ba168f697b8.jpg)

Top to bottom : 
![caliResultFinal1](https://user-images.githubusercontent.com/88779645/134161491-0fa4ab5f-5af9-47ed-ae21-3ed31c2dc242.png)

Fiducials marked:
![image](https://user-images.githubusercontent.com/88779645/134161549-97b46d65-1243-4e01-8c71-20606fe81f44.png)

GCode output for top circle first then the bottom one (Top=Empty inside , Bottom=Filled ):
![image](https://user-images.githubusercontent.com/88779645/134161674-823e52d4-7758-483f-a8ea-e26bce75c830.png)

**Comment by futurau** [comment]
![IMG-20210827-WA0006](https://user-images.githubusercontent.com/48054678/134162904-87080983-580c-4562-a9d9-47be574b2d87.jpg)

**Comment by svenhb** [comment]
Check new release 1.6.2.0 for automatic fiducial correction:
https://grbl-plotter.de/index.php?id=fiducial-correction&setlang=en

**Comment by svenhb** [comment]
No feedback is a good feedback 😉
Next release will have option to discard fiducial G-Code
