### ISSUE TITLE
Ascii nc file

### ISSUE THREAD

**Issue by SimonJohnCastle** [svenhb/GRBL-Plotter#227]
It looks like the exported nc gcode file is UTF-16 which adds an additionl step if I want to use it else where as I have to convert it to 8 bit ascii.
Is there a reason for this ?, is it a standard ?

Could you add an option for the saved output format UTF-8 or Ascii.

Thanks for all you hard work on this plotter and making it available to all.

**Comment by trantai369** [comment]
edit code "fCTBCode.SaveToFile(saveFileDialog1.FileName, Encoding.ASCII);"
Encoding.ASCII

**Comment by svenhb** [comment]
Didn't know this could be a problem...
I choosed "UTF-8" for the next release (new option to select between UTF-16 / UTF-8)

**Comment by SimonJohnCastle** [comment]
Thank you.
Could you have Ascii as an option so there is no BOM (Byte Order Mark) saved at the begining of the fille.

**Comment by svenhb** [comment]
Check new option in release 1.6.2.0:
I hope it works - I didn't check function.
![image](https://user-images.githubusercontent.com/19973251/135804274-48bfefc2-a88c-4447-ae18-4d496c2e5ff8.png)

**Comment by SimonJohnCastle** [comment]
works as expected, thank you
