### ISSUE TITLE
Cant find the line that i marked the string on 

### ISSUE THREAD

**Issue by yagizzha** [svenhb/GRBL-Plotter#228]
![image](https://user-images.githubusercontent.com/88779645/135089817-80eee2c4-c607-420f-9285-a6c0aa6e090a.png)

im trying to find which variable is holding the line number of yellowed elements , i mark them with pathId's but need the lines to use them for setting teach points. 

looked through the graphic2GCode mostly but couldnt find it , was hoping maybe you could help

**Comment by svenhb** [comment]
The XML will be generated in graphic2GCode, but processed in GCodeAnalyze.
Note: in next version, center of circles, labeled as fiducial, are collected seperatly.

**Comment by yagizzha** [comment]
Thanks a lot
