### ISSUE TITLE
The large file will load but not run.

### ISSUE THREAD

**Issue by rlwoodjr** [svenhb/GRBL-Plotter#229]
**Describe the bug**
I have large gcode file that will not run once you click play. It works on other senders.

**To Reproduce**
Load a gcode file with 500,000 lines (XYZ) wait until loaded, then click play.  It looks like it is going to run, but only a few lines, then it stops, waits for a few seconds and starts.  I will not run the file and the screen locks until the next bit

**Expected behavior**
Wait for a minute or two to load, then run the file.

The large gcode file can be downloaded here:
https://cdn.shopify.com/s/files/1/1563/9873/files/V-Carve_LL.gcode?v=1632859331

Is there settings I need to change?

**Comment by rlwoodjr** [comment]
I also get these lines in the com port window.


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Missing 12 Real-time Status Reports per 10 seconds

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Missing -21 Real-time Status Reports per 10 seconds

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Missing 42 Real-time Status Reports per 10 seconds

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Missing -34 Real-time Status Reports per 10 seconds

**Comment by rlwoodjr** [comment]
When the graphic is zoomed out it runs good
![SG](https://user-images.githubusercontent.com/10801570/135167318-ab3fb249-c250-4e1f-a4fd-69f1dc014408.png)
.

**Comment by rlwoodjr** [comment]
When the graphic is zoomed in , it stall
![LG](https://user-images.githubusercontent.com/10801570/135167370-5d0fd5cd-a882-4e15-a0cc-490d9f4abff8.png)
s.

**Comment by svenhb** [comment]
If you create the code by graphics import, I recommend to use "Remove very short moves"  perhaps < 0.2 ...
![image](https://user-images.githubusercontent.com/19973251/135210652-1534bb93-31f8-4118-85a7-9f5374b77e70.png)

Because your code shows really tiny step-width, which are probably not needed, but may causes a lot of trouble (I assume these are mm not inch). 
With high feedrate grbl sends many "ok" messages (because command line  was parsed and executed) per second and fill up the receive buffer of the pc.
![image](https://user-images.githubusercontent.com/19973251/135210395-f9a353f6-b10a-4d0c-8067-49a3d5892fbc.png)

**Comment by svenhb** [comment]
>The large gcode file can be downloaded here 

Ok it's ready to use G-Code... Probably in inch. 441518 lines. 
No idea how to improove the behavior - loading with a notebook i5 8th gen. is ok. It's loaded and zoomable after 12 seconds.

**Comment by svenhb** [comment]
About missing status reports, try to reduce polling frequency:
![image](https://user-images.githubusercontent.com/19973251/135255865-51c7fe43-931a-42fa-bcd5-6fe50dde141f.png)

**Comment by rlwoodjr** [comment]
The gcode file is written by VCarve Pro.  I do have the Status poll frequency set to 2 Hz.

If the graphics are zoomed out, then it runs fine.  It stalls when the graphics are larger.  I do not think it is grbl that is locked.  I can try running this on the ESP32 and see if there is a difference.

Is there a way to turn off or reduce the graphics calculations for a large file?

**Comment by rlwoodjr** [comment]
> > The large gcode file can be downloaded here
> 
> Ok it's ready to use G-Code... Probably in inch. 441518 lines. No idea how to improove the behavior - loading with a notebook i5 8th gen. is ok. It's loaded and zoomable after 12 seconds.

Did you try to run the file, zoom in or Zoom out?

**Comment by rlwoodjr** [comment]
One last question.  I have downloaded the source code and maybe I changed something while I was exploring the code..   Does the software write any configuration files in other directories other than the installed folder?

**Comment by svenhb** [comment]
>Does the software write any configuration files in other directories other than the installed folder?

Yes, the configuration, stored via "Properties.Settings.Default.xyz" - somwhere User\...\AppData\Local\GRBL-Plotter\GRBL-Plotter.exe_Url_5v3rojcbm....

>Did you try to run the file, zoom in or Zoom out?

Not yet

>Is there a way to turn off or reduce the graphics calculations for a large file?

Perhaps this helps, if switched off:
![image](https://user-images.githubusercontent.com/19973251/135311781-4b53be55-3ba1-4eb9-b617-098065e420ac.png)

**Comment by rlwoodjr** [comment]
Checking this setting did the trick!  Working good.  Thanks
![Screenshot 2021-09-29 121158](https://user-images.githubusercontent.com/10801570/135317014-8c2922b7-51e0-4838-9743-9c78f74c253c.png)
.

**Comment by rlwoodjr** [comment]
Thanks for the quick response.

**Comment by svenhb** [comment]
New release 1.6.2.0
I improoved loading of large g-code files a bit, also take care of G20 (units = inch).
But strong zooming is still not good.
