### ISSUE TITLE
Positions dont update 

### ISSUE THREAD

**Issue by yagizzha** [svenhb/GRBL-Plotter#231]
![image](https://user-images.githubusercontent.com/88779645/135478017-4416a933-3e41-494c-bc63-cf35dac0655a.png)

messages are an array of coordinates like "X205 Y488 ", when i start this function it gets stuck inside the while loop because X and Y positions dont update but it still goes to the given position . i've tried to make and use a public version of your ProcessGrblPositionUpdate function but it didnt help . 

Is there a way to send this function a signal when the machine reaches its destination or a way to update the X and Y values real time ?

**Comment by svenhb** [comment]
Instead of
`if (xabs + yabs < 0.001)`
Which is wrong in my eyes, you could use
`if (Grbl.posChanged)`

**Comment by svenhb** [comment]
Grbl.PosChanged will be cleared after usage - probably not save for you.
In next release you could use 
`if (Grbl.Status != GrblState.idle)`

**Comment by svenhb** [comment]
No feedback is a good feedback 😉
