### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by yagizzha** [svenhb/GRBL-Plotter#232]
![image](https://user-images.githubusercontent.com/88779645/135807488-bc4f83e6-44ca-4806-9113-0f45efbb8897.png)

there are missing files in the new version

**Comment by svenhb** [comment]
Before publishing, I renamed all files from the lowercase first letter to the uppercase, and the files are here: https://github.com/svenhb/GRBL-Plotter/tree/master/GRBL-Plotter/GCodeCreation

**Comment by yagizzha** [comment]
there is Graphic**Related**Tangential.cs and Graphic**Related**HatchFill.cs  but when i changed those into the missing files i got this error 
![image](https://user-images.githubusercontent.com/88779645/135810727-a73a5b98-3cf0-4cc8-bfa4-5f91f0b2f05c.png)
thats is why i assumed there was a file missing , if those are the correct files , what is cbroundup meant to be as in type , so i can add it to the class

**Comment by svenhb** [comment]
Did you also update this folder: https://github.com/svenhb/GRBL-Plotter/tree/master/GRBL-Plotter/MachineControl
I renamed from gcode... to Gcode...

**Comment by yagizzha** [comment]
i have downloaded full source code from here : https://github.com/svenhb/GRBL-Plotter/releases/tag/v1.6.2.0 

every GCode is in upper case 
![image](https://user-images.githubusercontent.com/88779645/135818691-5219514a-f131-4b5d-9ffc-b999bedfc420.png)

**Comment by svenhb** [comment]
CbRoundUp is used in ControlHeightMap.cs and ControlHeightMap.Designer.cs my files are from 30.08. no need to update again

**Comment by yagizzha** [comment]
New designer file fixed it , thanks
