### ISSUE TITLE
Teach scaling problem

### ISSUE THREAD

**Issue by yagizzha** [svenhb/GRBL-Plotter#233]
![image](https://user-images.githubusercontent.com/88779645/135850544-58ca5edd-2e9c-42d2-a52b-a7eece0c7ae5.png)
After teaching scaling noticed that it was going near double the amount it was supposed to . Calibration was done same as last version .

**Comment by svenhb** [comment]
You should select square or circle - not both.
![image](https://user-images.githubusercontent.com/19973251/135853634-e0c7619b-547e-4301-b387-2a2812bcbc04.png)

How does your fiducials look like? I just can see a dot.
Which camera mounting do you use?
![image](https://user-images.githubusercontent.com/19973251/135853830-b30ab94d-db5b-409b-a41c-182fbac3a8f2.png)

**Comment by svenhb** [comment]
Did you follow the distortion correction? https://grbl-plotter.de/index.php?id=form-camera&setlang=en#movable-mounted
If you don't needed it, you need to teach them to the outermost edges of the image, because the correction is enabled by default after opening the camera form.

**Comment by svenhb** [comment]
No feedback is a good feedback 😉

**Comment by yagizzha** [comment]
> No feedback is a good feedback 😉

Sorry about no reply , completely slipped my mind , after your last update you basically implemented all we were working on so there was no need to continue for us 😄
