### ISSUE TITLE
File is missing

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#234]
![2021-10-18](https://user-images.githubusercontent.com/53146195/137683797-9f990a30-a4c3-400f-a720-12ec5cfc795c.png)

The file in the screenshot below is missing
This is the code for version 1.6.2.1

**Comment by svenhb** [comment]
Mistake in renaming: 
wrong:  GraphicRelatedHatchFill.cs
Correct GraphicGenerateHatchFill.cs
