### ISSUE TITLE
How to create a new use case?

### ISSUE THREAD

**Issue by averydelmiller** [svenhb/GRBL-Plotter#237]
Hello!
I'm pretty new to the software, but I'm really enjoying it so far. However, I'm having trouble creating and loading new use cases. I want to turn SVG hatching off, but I can't seem to add a new use case-- I can save a default use case .ini file, but it doesn't appear in the selection list. Any help or suggestions would be amazing!

**Comment by svenhb** [comment]
You can save a part of the current settings here (screenshot), or you save the complete machine settings and copy the file to the according location.
![image](https://user-images.githubusercontent.com/19973251/142753580-97edf51a-de68-4575-a9f7-08ac9a5ab8c9.png)
