### ISSUE TITLE
Error message when closing Settings dialog

### ISSUE THREAD

**Issue by deHarro** [svenhb/GRBL-Plotter#24]
Hi Sven,
when I browse the settings and want to close the dialog window I encounter the following error:

![grafik](https://user-images.githubusercontent.com/26298406/44959829-92540300-aef5-11e8-9e7a-476dfb92cf3e.png)

This happens with and without having changed anything in the settings.
[edit] Version 1.2.0.0 from today [\edit]

**Comment by svenhb** [comment]
Please check Bugfix 1.2.0.1

**Comment by svenhb** [comment]
There was a problem with a missing default value (I cleared custom button Nr. 8) and bad error handling.
Also there was a historic thread event handler - I assume (hope) this was the reason for #25 and #26.
Thanks for testing ;-)
