### ISSUE TITLE
How to remove circles from "Image to Gcode" results?

### ISSUE THREAD

**Issue by averydelmiller** [svenhb/GRBL-Plotter#240]
Hello!
I've been experimenting with converting images into gcode, and I'm loving the results. However, on some images, there are a large amount of small circles/scribbles around the outlines (with some even in the filled area), seen in the screenshot below.
![thfhfhgf](https://user-images.githubusercontent.com/4822424/145084727-1e0769c0-a2f5-4634-8593-15c4ebcd71ab.png)
Sometimes it's not a big deal, but with this particular image the amount of circles is redundant, as many of them overlap in addition to extending the plotting time.
Any advice on how to manage this?
Thanks.

**Comment by svenhb** [comment]
To be able to understand it: can you upload the image and your settings (Export Machine Settings)?

**Comment by svenhb** [comment]
Did you try to switch off "smooth" and "Shrink path" or the whole "Draw outline" ?
It seems that "Shrink path" may cause the effect...
![image](https://user-images.githubusercontent.com/19973251/145580798-6883f451-e19c-4587-a33d-484a856ecbac.png)

**Comment by svenhb** [comment]
No feedback - hopefully solved
