### ISSUE TITLE
GRBL ADVANCE FIRMAWARE 

### ISSUE THREAD

**Issue by trkadam58** [svenhb/GRBL-Plotter#247]
I am using STM32F446RE with Ethernet communication using Candle2 software (https://github.com/Schildkroet/Candle2) is it possible ethernet communication using Grbl Plotter if have this function, Grbl Plotter again it will go one step up.

(GRBL Advance Firmware) https://github.com/Schildkroet/GRBL-Advanced

**Comment by svenhb** [comment]
Not easy to implement, I will try.

**Comment by trkadam58** [comment]
Only you need to add Ethernet function GRBL-Plotter, In GRBL Advanced firmware ethernet function available

**Comment by svenhb** [comment]
I hope it also works with your controller...
Check new release: https://github.com/svenhb/GRBL-Plotter/releases

**Comment by svenhb** [comment]
No feedback, no problem anymore :-)
