### ISSUE TITLE
Required New Function In Grbl Plotter

### ISSUE THREAD

**Issue by trkadam58** [svenhb/GRBL-Plotter#248]
Need New function in GRBL Plotter as attached video link

https://youtu.be/h4IQuHPnOe4

**Comment by svenhb** [comment]
You mean text import and text-path modification? I think thats toooooo much work.
Did you ever try Inkscape (https://inkscape.org/de/)? Just do it there, when graphic looks fine, convert text into paths, then select all paths and copy to clipboard, then paste from clipboard into GRBL-Plotter (ctrl-V on 2D-view).

**Comment by trkadam58** [comment]
But i need this function  in GRBL-Plotter only, u made for me required small changes, i will Donate every month 100usd this is just my small Donation, today i have done 50Eruo

**Comment by svenhb** [comment]
Check new release: https://github.com/svenhb/GRBL-Plotter/releases

**Comment by svenhb** [comment]
You need to enable grouping to select whole text: 
![image](https://user-images.githubusercontent.com/19973251/150079311-49106f01-0875-4baf-b539-c8fc0cd17940.png)

On the lower left edge you also get some infos:
![image](https://user-images.githubusercontent.com/19973251/150079464-b9b553ac-7927-4c2e-b987-0994c1d2c654.png)

**Comment by trkadam58** [comment]
is it possible select whole line without pressing control key

**Comment by svenhb** [comment]
Check new release: https://github.com/svenhb/GRBL-Plotter/releases

**Comment by svenhb** [comment]
No feedback, seems to work :-)
