### ISSUE TITLE
Error message when opening "Settings-GamePad"

### ISSUE THREAD

**Issue by deHarro** [svenhb/GRBL-Plotter#25]
Hi Sven,
when I try to open the GamePad-settings dialog I get the error

![grafik](https://user-images.githubusercontent.com/26298406/44959870-16a68600-aef6-11e8-9305-2d2572e19c44.png)

From then on I am unable to close the settings dialog, clicking on OK only reopens the error messsage.
I have to kill GRBLPlotter via taskmanager.

Version 1.2.0.0 from today

**Comment by svenhb** [comment]
I can't get this error, hope bugfix 1.2.0.1 helps. Please check out.
