### ISSUE TITLE
Change starting point

### ISSUE THREAD

**Issue by pilotak** [svenhb/GRBL-Plotter#250]
Is there a way to set starting point to top left corner instead of bottom left? the thing is that the path is showed corretcly in program but on plotter it's mirrored
![2](https://user-images.githubusercontent.com/8101753/149622264-0a4e1e90-05d6-4cf9-a74b-134480258395.jpg)

when i select the option to "Mirror Y" it's displayed wrong but comes as it should
![1](https://user-images.githubusercontent.com/8101753/149622263-dc5b504c-6bbf-4ce6-8fdb-e912d6086a55.jpg)

**Comment by svenhb** [comment]
>Is there a way to set starting point to top left corner

Just select origin, then apply offset:
![image](https://user-images.githubusercontent.com/19973251/149629009-7a0d93ff-36cc-44ce-8456-fba821eb79ae.png)


>but on plotter it's mirrored

You need to change your Y-axis direction via $3 https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration#3--direction-port-invert-mask

Check https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration

**Comment by pilotak** [comment]
Thank you
