### ISSUE TITLE
Tool change script not found

### ISSUE THREAD

**Issue by amoineau** [svenhb/GRBL-Plotter#251]
**Disclaimer : This is not exactly a bug.**

**Description**
I'm using the tool change feature but without scripts, so my setup is empty :
![image](https://user-images.githubusercontent.com/72978966/149748543-de4f8a37-d8e6-4db3-9448-9dc4988d5804.png)

Before version 1.6.4.0 I had no problem with that.
After switching to 1.6.4.0, I get hundreds of lines saying : "tool change script not found" in the console when starting streaming, and 5 time that in the logs.

**Expected behavior**
I wish there was a less worrying way of telling us we are not using a script, like a one liner.

Thank you for your help.

**Comment by amoineau** [comment]
This is worsened by another problem I'd like to report : the layers tend to be split so that every shape has its own layer, even when using only one layer for the whole file. I made sure that the name in the dxf and the tool table are the same.

I believe this is why I get the error so many times.

**Comment by svenhb** [comment]
I thing the problem is the relative filepath, try to put in the absolute path in the setup (copy the path-string manually from file-explorer, don't select via "..." button):
![image](https://user-images.githubusercontent.com/19973251/149756422-4bd88ea9-8443-424e-b1c6-40a10dee71d5.png)

**Comment by amoineau** [comment]
Ok I'll try that before the next file, thanks !

**Comment by amoineau** [comment]
It did not solve the problem :/

**Comment by svenhb** [comment]
Because of this issue https://github.com/svenhb/GRBL-Plotter/issues/244 I added the warnings...

I don't think you need to enable "Perform tool change" if you don't use any scripts - can you check?

**Comment by svenhb** [comment]
I will change the behavior: if textbox is empty - no check if file is existing...

**Comment by amoineau** [comment]
I'll check again, but I tried a long time ago and I think it didn't apply the gcode in the tool table if unchecked.

**Comment by amoineau** [comment]
Ok, it seems to work with "Perform tool change" unchecked but I get this message when reaching a tool change :
```!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
< error:20 	Unsupported or invalid g-code command found in block.
! Last processed 'T01M06'  line-Nr:51
Try to continue err-count:1```

**Comment by svenhb** [comment]
Ok, I will take care

**Comment by amoineau** [comment]
Thanks !

**Comment by svenhb** [comment]
Check new release: https://github.com/svenhb/GRBL-Plotter/releases

**Comment by amoineau** [comment]
Cool thanks ! I should be able to try it today or tomorrow.

**Comment by amoineau** [comment]
Sorry I forgot to give you a feedback ! It works well

**Comment by svenhb** [comment]
Thanks for feedback

**Comment by amoineau** [comment]
It's the least I can do ! Thank you for all the updates
