### ISSUE TITLE
HLDI. Включения лазера при движении в одном направлении по оси.

### ISSUE THREAD

**Issue by carrotFoxx** [svenhb/GRBL-Plotter#254]
Добрый день Дамир и прочие участники проекта.

Есть ли возможность добавить функцию при использовании режима HLDI, позволяющая активировать лазер при движении только в одном направлении по оси?
Это позволит снизитьпогрешность, вызванную люфтами в механизме станка.

**Comment by svenhb** [comment]
I'm not sure what you mean, perhaps you can explain with screenshots?
I assume you mean image import function, like in this video? https://youtu.be/7Nvf4UwK_yk

**Comment by svenhb** [comment]
No further feedback, no problem anymore
