### ISSUE TITLE
 tangential axis help

### ISSUE THREAD

**Issue by lfmmd** [svenhb/GRBL-Plotter#257]
I set the A-axis as the rotation axis during testing and found that the Z-axis was raised during each z-rotation, which setting affects his work

**Comment by svenhb** [comment]
You can define what happens on graphics-path-start and -end (pen-down, pen-up):
https://grbl-plotter.de/index.php?id=form-setup#Gcodegeneration
![image](https://user-images.githubusercontent.com/19973251/153815239-49f50234-b8ac-48ac-a0e3-b31438520479.png)

**Comment by lfmmd** [comment]
Thank you for your reply because I set the wrong parameters.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
