### ISSUE TITLE
Camera - Tool coordinate teaching goes away if you set work coord 0:0 for fiducial

### ISSUE THREAD

**Issue by yagizzha** [svenhb/GRBL-Plotter#265]
https://grbl-plotter.de/data/uploads/pic/plotter_fiducials/fiducial_xy_auto.gif
when following this , if you do the "set work coordinate 0;0 here , it removes the teachings from this window:
![image](https://user-images.githubusercontent.com/88779645/159237448-34d48f60-1637-4e0b-b9dc-9091d875c3df.png)

**Comment by svenhb** [comment]
I never tried with "Camera mounted on Z axis" and assume that the offset is applied to the wrong coordinate system (probably the currently active one)...
I need to figure out...

**Comment by yagizzha** [comment]
![image](https://user-images.githubusercontent.com/88779645/159244602-e4fd9718-129e-440d-a124-c877d0bf7002.png)
When swapped to tool coordinate with move stage , goes where camera was , as we expect , making me think the calibration is succesful.
![image](https://user-images.githubusercontent.com/88779645/159245198-dfcb2f40-8eb9-435d-83a3-b5b8ecca93d3.png)

![image](https://user-images.githubusercontent.com/88779645/159245088-3019cc74-49fb-4a47-b5dd-2a7ab12b681c.png)
But then if we do the "set work coordinate 0;0 here" it ruins all the previous steps.

**Comment by svenhb** [comment]
The step "set work coordinate 0;0 here" will be done first, to be close to the fudcial - as a rough teaching.
Then the "automatic fiducial correction" will be started.

You are right, if you do then again a "set work coordinate 0;0 here" you loose the previous teaching - so don't do it :-)

**Comment by yagizzha** [comment]
if we do the "set work coordinate 0;0 here" first , how will the process go ? 
wont it be "set0;0-->calibrate-->cut", in that case we'd have to calibrate with every cut since we likely wont be putting it in an exact position . Is there any way to set up tool distance manually ? or have it as a "relative" system rather then a fixed coordinate system ?
