### ISSUE TITLE
Circle detection doesnt work on zip version

### ISSUE THREAD

**Issue by yagizzha** [svenhb/GRBL-Plotter#266]
![image](https://user-images.githubusercontent.com/88779645/159523998-fa7c5489-0430-4859-b325-82c4e7a721fc.png)
Circle detection isnt working when using the zip version , using .net 4 , VS2019 , works fine with the exe version

**Comment by svenhb** [comment]
That's strange, the Zip and the installer are using the same files. Most probably the settings are not identical, when starting from different locations. 
You may check C:\user\xyz\AppData\Local\GRBL-Plotter\GRBL-Plotter.exe_Url_....\Version\user.config... for the date of stored cofigurations, to check if different files are used, when starting from different locations...

![image](https://user-images.githubusercontent.com/19973251/159655576-19096b23-1f12-4573-aa52-df4152cb8c4f.png)

**Comment by yagizzha** [comment]
Weirdly , it keeps resetting my values to this as soon as i open the camera form :
![image](https://user-images.githubusercontent.com/88779645/159661372-16b9b583-47ee-44c6-8bf2-9f0f0020cea3.png)
Thought maybe it was because of something i changed in the code so downloaded a fresh version but same problem still occurs.

**Comment by yagizzha** [comment]
It changes when you click "paper" for filters , which i guess is expected but still doesnt detect

**Comment by svenhb** [comment]
Can you compare files between installed (see logfile for location) and zipped version? If they are identical, it must work.
I tried at work with simulation picture and it works from both location (installed and copied):
![image](https://user-images.githubusercontent.com/19973251/159682677-bd8be807-92e6-4ff0-9fc5-6767f5779497.png)

Perhaps the teaching for Z mounted camera is missing when starting the zip-version?

**Comment by yagizzha** [comment]
Made 
![image](https://user-images.githubusercontent.com/88779645/159688170-48d4cc6b-91be-4ae8-8aa6-257095a0a8a6.png)
max side bigger and its working now , however i have no clue why zip and installed reacts diffrently since they had the same parameters.
![image](https://user-images.githubusercontent.com/88779645/159688261-408094fc-bd08-493b-9fdd-6eb38f7690ab.png)
also there is a false detection , also on VS2019 clicking "save" or "load" next to filter settings was crashing the problem , works fine on VS2022

**Comment by svenhb** [comment]
Probably the scaling between both are different: do you get the same circle diameter in the picture, if set to e.g. 10?
![image](https://user-images.githubusercontent.com/19973251/159692008-92ea4431-89d9-453b-95da-48f83575e35f.png)

**Comment by yagizzha** [comment]
yeah i do , i've set both to 10 then calibrated it , had a very weird bug tho , randomly fiducial circles on svg got bigger , calibrated again and it fixed itself after

**Comment by yagizzha** [comment]
Since problem itself is solved , im closing this
