### ISSUE TITLE
G-Code 4 axis convert to Marlin V.2.09

### ISSUE THREAD

**Issue by qulet** [svenhb/GRBL-Plotter#268]
Is it possible to add a connection with Marlin to the program in order to use only the CNC 4 axis functions, omitting the heating function?

**Comment by svenhb** [comment]
How needs the code to look like?

**Comment by qulet** [comment]
G-code for the 4th axis of the tangential knife after a slight modification {ASCI "conversion "(" to ";" and "A" to "E") allows you to run the code in the Marlin software. My request is to add a connection to the Marlin firmware as it is done in program "LaserGRBL" Your GRBL_Plotter program is very good, adding this function would make it even BETTER ...

**Comment by svenhb** [comment]
>My request is to add a connection to the Marlin firmware

I see. I added this feature in 1.5.4.0 but got no feedback.... https://github.com/svenhb/GRBL-Plotter/releases/tag/v1.5.4.0

**Comment by qulet** [comment]
234 / 5 000
Wyniki tłumaczenia
I am currently using GRBL-PLOTTER 1.6.5.2 and despite the change:
I can't connect to the Marlin 2.09.01 firmware from your software. From the LaserGRBL programs to the switch to the Marlin software, this connection works. 
![image](https://user-images.githubusercontent.com/30979927/160831723-949be342-995a-408f-956a-69489902c5ca.png)

**Comment by svenhb** [comment]
Perhaps no it works: I switched line-end marker from \r to \n. I have no hardware to check function.

**Comment by qulet** [comment]
![Bez tytułu](https://user-images.githubusercontent.com/30979927/161448570-6026873a-d806-4e6d-8147-e8770a1b87a6.jpg)
Niestety nie udało się nawiązać połączenia z Marlinem :(((

**Comment by svenhb** [comment]
Are you sure it is the right baud rate? I read about 250000 instead of 115200. 
I never used LaserGRBL, so I don't know what the message means: Sounds to me it is also not connected...
![image](https://user-images.githubusercontent.com/19973251/161481043-898a4125-7d92-464f-823f-3341738f9513.png)

**Comment by qulet** [comment]
In LaserGRBL, the correct Firmware must be selected: GRBL; Marlin or Smoothie.
I chose Marlin with 115200 baud rate. Pressing the button - connect highlights the jog icons in green and it is possible to control the motors of the X, Y, Z axes.

**Comment by svenhb** [comment]
I could load Marlin on my Mega 2560 and improove behavior of GRBL-Plotter, please check:
https://github.com/svenhb/GRBL-Plotter/releases

**Comment by qulet** [comment]
The connection worked !!! on these settings:
![setup](https://user-images.githubusercontent.com/30979927/162576698-70abe2d7-926e-4029-81f2-5380ab7fdd4e.png)

**Comment by qulet** [comment]
My joy was a little before early ...
I have two printers:
1. Marlin 1.9 Ramps1.3 firmware. The connection is working
![Marlin_1 9_Ramps](https://user-images.githubusercontent.com/30979927/162613390-329b913c-e7c8-4bc8-aa8c-022fcd44cb8a.png)

2. Firmware Marlin 2.09 Mks-Sbase1.3. The connection is not working.
![Marlin2 0_MKS-Sbase1 3](https://user-images.githubusercontent.com/30979927/162613521-dd7ab339-9595-4de0-b2e3-0e85c906e024.png)
I want to connect with the Marlin 2.0 MKS-Sbase1.3 32bit firmware. This printer has the ability to manually change the extruder to any other tool: LED laser, tangential knife. Unfortunately, here the connection does not work.

**Comment by svenhb** [comment]
Ok, too bad...
Are you sure the 2nd printer uses same baud rate?
Did you try disconnect/connect button?
Did you try restart of GRBL-Plotter?

I assume yes...

In the start up I miss the "unknown command" as for the 1st printer
Perhaps you can figure out, what are the first messages? Perhaps finally I need to add a checkbox to force marlin and not try to automatic recognize
![image](https://user-images.githubusercontent.com/19973251/162676259-8697e98b-a4e6-44b5-9966-acb1aefc3ce9.png)

**Comment by qulet** [comment]
In Marlin 2.0 the transfer was changed to 25,000 to be the same as in Marlin 1.9. Of course, I tried to change this value and restart GRBLPlotter, but unfortunately it did not allow the connection to be established. On ramps 1.3, after activating RST, values such as the M501 g-code were loaded. Unfortunately, it was not possible to establish such a connection on the MKS SBase.

**Comment by svenhb** [comment]
Check new release 1.6.6.2: https://github.com/svenhb/GRBL-Plotter/releases
![image](https://user-images.githubusercontent.com/19973251/163236875-80588a72-8aae-4024-b24e-1e29b4db62eb.png)

**Comment by qulet** [comment]
Connection to Marlin 2.0 interface 4 axis Control / Jogging works after connection is established. G-Code Streaming does not work ...
![Marlin2 0_MKS-Sbase1 3](https://user-images.githubusercontent.com/30979927/163476982-0e27691b-af72-4756-8016-9bbfc7e7c7f1.png)

**Comment by svenhb** [comment]
you may switch on this options to get more informations
![image](https://user-images.githubusercontent.com/19973251/163541360-8e6bd317-380b-4edc-89ab-fc63c5b5bfe2.png)

**Comment by qulet** [comment]
![setitings](https://user-images.githubusercontent.com/30979927/163561765-e87079e2-5f24-414e-8660-d3df5e3e31c5.png)
![1](https://user-images.githubusercontent.com/30979927/163562028-ffc4b51e-67eb-4d05-aa7a-9755e36120ad.png)
![log](https://user-images.githubusercontent.com/30979927/163562206-e71114bf-8fba-46b7-a73f-3efc36c5a7c4.png)

**Comment by svenhb** [comment]
I made another change, perhaps no it works?: https://github.com/svenhb/GRBL-Plotter/releases

**Comment by qulet** [comment]
![1](https://user-images.githubusercontent.com/30979927/164290263-01ee2202-1685-46d8-b9db-bd1b4454307a.png)
![2](https://user-images.githubusercontent.com/30979927/164290270-3ead0010-b2a5-4732-b9fe-201647cc1bab.png)
[lastProcessed_.zip](https://github.com/svenhb/GRBL-Plotter/files/8523918/lastProcessed_.zip)
SVEN sorry to tire you so much with these amendments. Maybe I'm doing something wrong?
The latest version connects to Marlin just like the previous one. Unfortunately, G-code streaming does not work.

**Comment by svenhb** [comment]
Did you try to press "RST"?
![image](https://user-images.githubusercontent.com/19973251/164380813-1782541e-7489-4f83-9b83-7f17f70ff305.png)
You also change the streaming method:
![image](https://user-images.githubusercontent.com/19973251/164380937-648799b2-be6e-4125-86ea-60befbad10d7.png)

**Comment by qulet** [comment]
All the functions of your program work fine on Marlin 1.9 Ramps:
![MarlinRamps](https://user-images.githubusercontent.com/30979927/164510932-516f0da3-3c66-42f9-81ec-c74b4e50604a.jpg)
![MarlinRamps_0](https://user-images.githubusercontent.com/30979927/164510937-e528b77c-b5b4-425c-89e4-
a26e0bf7a9d5.jpg)

The problem is Marlin 2.0 MKS-Sbase. There you can get a connection sometimes, jogging works, but there is a blank field in the connection status ... and g-code forwarding is not working.There, for the connection to work (jogging), I have to press RESET in the program window. But the connection status is blank and g-code uploading is not working.
![Marlin2 0](https://user-images.githubusercontent.com/30979927/164513155-ced10541-7eb1-4161-80b1-2c0ae2cf2e88.jpg)

**Comment by svenhb** [comment]
>The problem is Marlin 2.0 MKS-Sbase.

Strange, there is no start-up message after hard-reset.
Do you have a HEX-file of this firmware, which I can upload to my Arduino Mega-2560?
As shown above I also use Marlin 2.0

**Comment by qulet** [comment]
I use Visual Studio Code to compile Marlin for MKS-Sbase CD. The output file there is the file: firmware. bin. There must be a different pinout for ramps. I never compiled Marlin 2.0 for ramps to get the Hex peak. Enclosed my Marlin 2 configuration for the MKS-Sbase board.
[Uploading M_2.0 MKS-SBASE_config.zip…]()

**Comment by qulet** [comment]
As soon as RST is pressed in the main program window, jogging starts, connection status clean button. how will i do a RESET on the board: the message [ERROR] Closing port pops up
![3](https://user-images.githubusercontent.com/30979927/164893065-112befbb-a265-4e48-a99c-05e3e04336ac.png)

**Comment by qulet** [comment]
Svenhb with compiled GRBL LPC Ceprezzi. I have uploaded the firmware.bin file to the MKS-Sbase SD card.
Everything about GRBLPlotter on this firmware seems to be working fine. I have to accept that if I want to use your software, I have to change the Marlin firmware to the GRBL LPC firmware. Thank you for your help.

**Comment by svenhb** [comment]
I'm happy to hear this. Marlin is really strange and I have no idea what's going on with this MKS board...
