### ISSUE TITLE
Circles in cutting mode are bugged

### ISSUE THREAD

**Issue by yagizzha** [svenhb/GRBL-Plotter#270]
Using svg 
![image](https://user-images.githubusercontent.com/88779645/160599443-76afe4ee-ac7d-4bd9-a9f5-eae10a35af49.png)
this circle starts out line this , which is what we expect but it gradually gets worse and becomes like this :
![image](https://user-images.githubusercontent.com/88779645/160599523-4db9843c-1e20-4643-910b-bb962e184d28.png)

SVG used was this : 
![d1](https://user-images.githubusercontent.com/88779645/160599656-4c896fc6-df27-4a10-b318-34e5f334998c.svg)
Also even tho 2 circles were marked as fid1 and fid3 in id , they werent detected , i can open a new issues for that if needed ?

**Comment by svenhb** [comment]
I don't understand the first part of your issue...

2nd part: not the id but the layer must be named - setup:
![image](https://user-images.githubusercontent.com/19973251/160609110-bfddb1b2-6a5f-4cee-87d9-e0018a5511e4.png)

My example "graphic_fiducial_circle.svg":
![image](https://user-images.githubusercontent.com/19973251/160609336-e81a119c-0860-4376-b3df-8e4f62d8a303.png)

**Comment by yagizzha** [comment]
First part of issue is the cutting part goes in angles that wont cut the paper but tear it instead like it is at the end , it starts out at a correct angle but slowly gets worse and at the end its 90 degrees of what it should be

**Comment by svenhb** [comment]
It is just the simulation, I need to check. If you avoid G2/G3 it looks correct:
![image](https://user-images.githubusercontent.com/19973251/160612837-25487d3a-beb2-48b7-ad91-b5c6678b6496.png)

**Comment by svenhb** [comment]
Ok it is a bug, when using G2/G3: it starts at A90 and should end at A(90+360) = 450, but ends at 360...

**Comment by svenhb** [comment]
No feedback? Seems to work now...
