### ISSUE TITLE
While cutting circles , A axis starts to move weirdly sometimes

### ISSUE THREAD

**Issue by yagizzha** [svenhb/GRBL-Plotter#271]
During this cut (its supposed to be a circle , because it was for testing calibrations werent done perfectly) it does a weird clicky-ish sound while cutting , not going smoothly 
https://user-images.githubusercontent.com/88779645/160825346-6bc63b26-6850-455f-a2a6-b6f6b6166ec8.mp4
Gcode for that one looks like this :
![5ca0651b-0d3e-4312-8cfb-7599a2a5b4ad](https://user-images.githubusercontent.com/88779645/160825486-52683f11-deac-42d1-bb35-9e9df28ebef1.jpg)
However , another circle from same file works fine (again dont mind the paper moving , its just to show the movement):
https://user-images.githubusercontent.com/88779645/160825636-6576d7fd-1b55-4dbb-b293-2c764c4f0477.mp4
GCode for that one is 
![e111ae63-737f-4af8-9ff5-6c72e71d0a68](https://user-images.githubusercontent.com/88779645/160825707-f902f432-4685-4509-ba12-e31660722dd6.jpg)
 Is this a bug or some feature we are missing ? if a feature how to work around so it cuts smoothly aswell

**Comment by svenhb** [comment]
You need to increase this value:
If angle between two lines is too big (bigger than this value), the start angle for the second line will be adapted.
![image](https://user-images.githubusercontent.com/19973251/160828104-bd27d3de-3842-456c-a077-80e2c4da7a66.png)

**Comment by yagizzha** [comment]
Same issue happened while doing it with ellipses , increasing start angle didnt help

**Comment by svenhb** [comment]
Please send graphic, gcode.result and expected behavior

**Comment by yagizzha** [comment]
GCode: ( Use case: ? )
( SVG import by GRBL-Plotter 1.6.5.2 )
( Source: C:\Users\Owner\Desktop\tests\F23.svg )
(<Header >)
( G-Code lines: 222 )
( Pen Down/Up : 15 times )
( Duration ca.: 1.0 min. )
( Conv. time  : 00:00:00.1230846 )
( Original graphic dimension min:1.049;1.052  max:303.769;155.675)
(</Header >)
(<Tangential Axis="A"/>)
G54 (Setup - GCode-Header)
G90
G00 Z3.000
M3 S1000 
(<Figure Id="1" Geometry="circle" Layer="fiducial" PathLength="30.7"> )
G00 X9.793 Y4.896 A4.262  
G01 Z-1.111 F1000 (PD)
G01 X9.690 Y5.896 A4.262 F2000 
G01 X9.385 Y6.854 A4.786  
G01 X8.890 Y7.729 A5.309  
G01 X8.228 Y8.485 A5.833  
G01 X7.425 Y9.090 A6.357  
G01 X6.515 Y9.517 A6.880  
G01 X5.537 Y9.751 A7.404  
G01 X4.532 Y9.779 A7.928  
G01 X3.542 Y9.602 A8.452  
G01 X2.610 Y9.226 A8.975  
G01 X1.774 Y8.668 A9.499  
G01 X1.069 Y7.950 A10.023  
G01 X0.526 Y7.104 A10.547  
G01 X0.167 Y6.165 A11.070  
G01 X0.008 Y5.173 A11.594  
G01 X0.054 Y4.169 A12.118  
G01 X0.305 Y3.195 A12.642  
G01 X0.749 Y2.293 A13.165  
G01 X1.368 Y1.501 A13.689  
G01 X2.136 Y0.852 A14.213  
G01 X3.020 Y0.373 A14.736  
G01 X3.983 Y0.085 A15.260  
G01 X4.985 Y0.000 A15.784  
G01 X5.983 Y0.121 A16.308  
G01 X6.935 Y0.444 A16.831  
G01 X7.801 Y0.954 A17.355  
G01 X8.545 Y1.630 A17.879  
G01 X9.135 Y2.444 A18.403  
G01 X9.547 Y3.361 A18.926  
G01 X9.762 Y4.343 A19.450  
G01 X9.793 Y4.896 A19.856  
G00 Z3.000 (PU)
(</Figure>)
(<Figure Id="2" Geometry="polygon" Layer="Katman_x0020_1" PathLength="31.3"> )
G00 X88.490 Y67.522 A-1.347  
G01 Z-1.111 F1000 (PD)
G01 X101.956 Y59.650 A-1.347 F2000 
G01 X115.596 Y51.778 A-1.333  
G00 Z3.000 (PU)
G00 X115.596 Y51.778 A-4.000  
G01 Z-1.111 F1000 (PD)
G01 X115.596 Y20.465 A-4.000 F2000 
G00 Z3.000 (PU)
G00 X115.596 Y20.465 A-6.692  
G01 Z-1.111 F1000 (PD)
G01 X101.956 Y12.768 A-6.692 F2000 
G01 X88.490 Y4.896 A-6.653  
G00 Z3.000 (PU)
G00 X88.490 Y4.896 A-9.333  
G01 Z-1.111 F1000 (PD)
G01 X74.849 Y12.768 A-9.333 F2000 
G01 X61.208 Y20.465 A-9.308  
G00 Z3.000 (PU)
G00 X61.208 Y20.465 A-12.000  
G01 Z-1.111 F1000 (PD)
G01 X61.208 Y51.778 A-12.000 F2000 
G00 Z3.000 (PU)
G00 X61.208 Y51.778 A-14.667  
G01 Z-1.111 F1000 (PD)
G01 X88.490 Y67.522 A-14.667 F2000 
G00 Z3.000 (PU)
(</Figure>)
(<Figure Id="3" Geometry="ellipse" Layer="Katman_x0020_1" PathLength="141.9"> )
G00 X32.878 Y112.480 A11.899  
G01 Z-1.111 F1000 (PD)
G01 X32.728 Y108.682 A11.899 F2000 
G01 X32.290 Y105.039 A11.696  
G01 X31.586 Y101.585 A11.488  
G01 X30.633 Y98.353 A11.270  
G01 X29.452 Y95.376 A11.038  
G01 X28.063 Y92.688 A10.785  
G01 X26.484 Y90.322 A10.502  
G01 X24.736 Y88.312 A10.177  
G01 X22.838 Y86.690 A9.800  
G01 X20.809 Y85.490 A9.360  
G01 X18.669 Y84.746 A8.853  
G01 X16.439 Y84.490 A8.290  
G01 X14.208 Y84.746 A7.710  
G01 X12.069 Y85.490 A7.147  
G01 X10.040 Y86.690 A6.640  
G01 X8.142 Y88.312 A6.200  
G01 X6.394 Y90.322 A5.823  
G01 X4.815 Y92.688 A5.498  
G01 X3.425 Y95.376 A5.215  
G01 X2.244 Y98.353 A4.962  
G01 X1.292 Y101.585 A4.730  
G01 X0.587 Y105.039 A4.512  
G01 X0.150 Y108.682 A4.304  
G01 X0.000 Y112.480 A4.101  
G01 X0.150 Y116.278 A3.899  
G01 X0.587 Y119.920 A3.696  
G01 X1.292 Y123.374 A3.488  
G01 X2.244 Y126.606 A3.270  
G01 X3.425 Y129.583 A3.038  
G01 X4.815 Y132.271 A2.785  
G01 X6.394 Y134.637 A2.502  
G01 X8.142 Y136.648 A2.177  
G01 X10.040 Y138.269 A1.800  
G01 X12.069 Y139.469 A1.360  
G01 X14.208 Y140.214 A0.853  
G01 X16.439 Y140.469 A0.290  
G01 X18.669 Y140.214 A-0.290  
G01 X20.809 Y139.469 A-0.853  
G01 X22.838 Y138.269 A-1.360  
G01 X24.736 Y136.648 A-1.800  
G01 X26.484 Y134.637 A-2.177  
G01 X28.063 Y132.271 A-2.502  
G01 X29.452 Y129.583 A-2.785  
G01 X30.633 Y126.606 A-3.038  
G01 X31.586 Y123.374 A-3.270  
G01 X32.290 Y119.920 A-3.488  
G01 X32.728 Y116.278 A-3.696  
G01 X32.878 Y112.480 A-3.899  
G00 Z3.000 (PU)
(</Figure>)
(<Figure Id="4" Geometry="rect" Layer="Katman_x0020_1" PathLength="94.1"> )
G00 X201.113 Y7.520 A0.000  
G01 Z-1.111 F1000 (PD)
G01 X295.199 Y7.520 A0.000 F2000 
G00 Z3.000 (PU)
G00 X295.199 Y7.520 A4.000  
G01 Z-1.111 F1000 (PD)
G01 X295.199 Y48.979 A4.000 F2000 
G00 Z3.000 (PU)
G00 X295.199 Y48.979 A8.000  
G01 Z-1.111 F1000 (PD)
G01 X201.113 Y48.979 A8.000 F2000 
G00 Z3.000 (PU)
G00 X201.113 Y48.979 A12.000  
G01 Z-1.111 F1000 (PD)
G01 X201.113 Y7.520 A12.000 F2000 
G00 Z3.000 (PU)
(</Figure>)
(<Figure Id="5" Geometry="ellipse" Layer="Katman_x0020_1" PathLength="265.7"> )
G00 X302.719 Y112.480 A11.255  
G01 Z-1.111 F1000 (PD)
G01 X301.575 Y108.682 A11.255 F2000 
G01 X298.240 Y105.039 A10.112  
G01 X292.866 Y101.585 A9.455  
G01 X285.600 Y98.353 A9.066  
G01 X276.593 Y95.376 A8.813  
G01 X265.993 Y92.688 A8.632  
G01 X253.951 Y90.322 A8.494  
G01 X240.616 Y88.312 A8.381  
G01 X226.137 Y86.690 A8.284  
G01 X210.663 Y85.490 A8.197  
G01 X194.344 Y84.746 A8.116  
G01 X177.329 Y84.490 A8.038  
G01 X160.315 Y84.746 A7.962  
G01 X143.996 Y85.490 A7.884  
G01 X128.522 Y86.690 A7.803  
G01 X114.043 Y88.312 A7.716  
G01 X100.708 Y90.322 A7.619  
G01 X88.666 Y92.688 A7.506  
G01 X78.066 Y95.376 A7.368  
G01 X69.059 Y98.353 A7.187  
G01 X61.793 Y101.585 A6.934  
G01 X56.419 Y105.039 A6.545  
G01 X53.084 Y108.682 A5.888  
G01 X51.940 Y112.480 A4.745  
G00 Z3.000 (PU)
G00 X51.940 Y112.480 A3.255  
G01 Z-1.111 F1000 (PD)
G01 X53.084 Y116.278 A3.255 F2000 
G01 X56.419 Y119.920 A2.112  
G01 X61.793 Y123.374 A1.455  
G01 X69.059 Y126.606 A1.066  
G01 X78.066 Y129.583 A0.813  
G01 X88.666 Y132.271 A0.632  
G01 X100.708 Y134.637 A0.494  
G01 X114.043 Y136.648 A0.381  
G01 X128.522 Y138.269 A0.284  
G01 X143.996 Y139.469 A0.197  
G01 X160.315 Y140.214 A0.116  
G01 X177.329 Y140.469 A0.038  
G01 X194.344 Y140.214 A-0.038  
G01 X210.663 Y139.469 A-0.116  
G01 X226.137 Y138.269 A-0.197  
G01 X240.616 Y136.648 A-0.284  
G01 X253.951 Y134.637 A-0.381  
G01 X265.993 Y132.271 A-0.494  
G01 X276.593 Y129.583 A-0.632  
G01 X285.600 Y126.606 A-0.813  
G01 X292.866 Y123.374 A-1.066  
G01 X298.240 Y119.920 A-1.455  
G01 X301.575 Y116.278 A-2.112  
G01 X302.719 Y112.480 A-3.255  
G00 Z3.000 (PU)
(</Figure>)
(<Figure Id="6" Geometry="circle" Layer="fiducial" PathLength="30.7"> )
G00 X302.544 Y149.740 A4.262  
G01 Z-1.111 F1000 (PD)
G01 X302.441 Y150.740 A4.262 F2000 
G01 X302.136 Y151.698 A4.786  
G01 X301.642 Y152.574 A5.309  
G01 X300.979 Y153.330 A5.833  
G01 X300.176 Y153.934 A6.357  
G01 X299.266 Y154.362 A6.880  
G01 X298.288 Y154.595 A7.404  
G01 X297.283 Y154.624 A7.928  
G01 X296.294 Y154.446 A8.452  
G01 X295.361 Y154.070 A8.975  
G01 X294.525 Y153.512 A9.499  
G01 X293.821 Y152.795 A10.023  
G01 X293.277 Y151.949 A10.547  
G01 X292.918 Y151.010 A11.070  
G01 X292.759 Y150.017 A11.594  
G01 X292.805 Y149.013 A12.118  
G01 X293.056 Y148.040 A12.642  
G01 X293.500 Y147.138 A13.165  
G01 X294.119 Y146.346 A13.689  
G01 X294.887 Y145.696 A14.213  
G01 X295.771 Y145.218 A14.736  
G01 X296.734 Y144.930 A15.260  
G01 X297.736 Y144.845 A15.784  
G01 X298.734 Y144.966 A16.308  
G01 X299.686 Y145.288 A16.831  
G01 X300.552 Y145.798 A17.355  
G01 X301.296 Y146.474 A17.879  
G01 X301.886 Y147.288 A18.403  
G01 X302.298 Y148.206 A18.926  
G01 X302.513 Y149.188 A19.450  
G01 X302.544 Y149.740 A19.856  
G00 Z3.000 (PU)
(</Figure>)
M05
M30
File : 
![F23](https://user-images.githubusercontent.com/88779645/165092589-88d24c21-a2c4-49f1-b0bc-2dcc111105b4.svg)

This is the one where we have problem :
![Screen](https://user-images.githubusercontent.com/88779645/165092552-e26c1e4a-4e29-4cfd-995e-b1e5d2197ebc.png)

This is how the cut ends up being , expected was it being smooth:
![WhatsApp Image 2022-04-25 at 15 42 25](https://user-images.githubusercontent.com/88779645/165092655-6b92a60c-9623-458a-ba69-8d41ffd98bcb.jpeg)

**Comment by svenhb** [comment]
If I copy & paste your GCode I see the same edges in the 2D-view, as in your picture:
![image](https://user-images.githubusercontent.com/19973251/165096886-59366372-aec5-478f-bf68-176398344bad.png)

You should adapt this parameters:
![image](https://user-images.githubusercontent.com/19973251/165097327-6ba9a782-a12d-449e-a0e6-e0db066c4fb2.png)

Then curve is less angular:
![image](https://user-images.githubusercontent.com/19973251/165097477-fdafa25e-15a9-4a60-99cb-68d5b310ed45.png)

**Comment by svenhb** [comment]
No further feedback, seems to work now...
