### ISSUE TITLE
When using camera form to correct fiducials , cutting piece angle gets bugged

### ISSUE THREAD

**Issue by yagizzha** [svenhb/GRBL-Plotter#272]
When cutting without any camera input it follows like this :
![image](https://user-images.githubusercontent.com/88779645/160864222-6e93c454-be27-4d5d-b09d-a5be17e8316d.png)
But after fiducial correction it becomes : 
![image](https://user-images.githubusercontent.com/88779645/160864302-c715cc9a-a8de-4c8d-9681-835b323b264d.png)

**Comment by svenhb** [comment]
I never tried fiducial correction together with tangential axis. 
I assume, you are not using 360° for a full turn, so the applied rotation-offset to the tangential axis would be wrong...
![image](https://user-images.githubusercontent.com/19973251/161002564-d6af3ea4-e8b0-4f43-8b96-0950d7b72b3c.png)

**Comment by svenhb** [comment]
Also you need to click into the 2D view to set the marker again

**Comment by yagizzha** [comment]
Units per turn on our machine is set to 16 since that causes a 360 degree turn . 

The problem is the angle of the knife starts wrong and goes like that all the way through the cutting process when using fiducial detection .

**Comment by yagizzha** [comment]
If its a bug spesific to my case , can you give me the line where knife angle gets calculated so i can try to fix ?

**Comment by svenhb** [comment]
I already fixed it, I plan to release the new version this evening or tomorrow - I still working on another part of the software.

If you can't wait:
In /MachineControl/GCodeTransform.cs - line 269, change the block to this:
```
                    if (tangentialAxisEnable)
                    {
			double tangle =((double)Properties.Settings.Default.importGCTangentialTurn * angle / 360);

                        if ((tangentialAxisName == "C") && (gcline.c != null)) { gcline.c += tangle; }
                        else if ((tangentialAxisName == "B") && (gcline.b != null)) { gcline.b += tangle; }
                        else if ((tangentialAxisName == "A") && (gcline.a != null)) { gcline.a += tangle; }
                        else if ((tangentialAxisName == "Z") && (gcline.z != null)) { gcline.z += tangle; }
                    }

```

**Comment by yagizzha** [comment]
that worked perfectly, thanks
