### ISSUE TITLE
Detection inside svg files taking id aswell

### ISSUE THREAD

**Issue by yagizzha** [svenhb/GRBL-Plotter#275]
Program we are using right now doesnt add labels to our svg files so we cant use the output directly without changing them . Would it be possible to mark fiducial layer with id ? or any other solution to this . If there is a line in code that we can look at for this that'd help too .

**Comment by svenhb** [comment]
Some more changes are needed, right now I can say - without any tests:
Add "PathId" in MachineControl\GCodeAnalysis.cs line 751:
![image](https://user-images.githubusercontent.com/19973251/161549999-1aacf8ec-1753-4f67-8047-919093068fc5.png)

In GCodeCreation\XmlMarker.cs change variable "PathId" from int to string. 
In function SetBlockData change accoring new type.
tmp.PathId = "";
if (element.Contains("PathId")) { tmp.PathId = GetAttributeValue(element, "PathId"); }

Perhaps thats all

**Comment by svenhb** [comment]
There is a small bug: the created XML-Tag is "PathI**D**" but, as shown above, variable is looking for "PathI**d**"
Please change line 547 in GCodeCreation\Graphic2GCode.cs to
`            if (pathObject.Info.PathId.Length > 0) attributes.Append(string.Format(" PathId=\"{0}\"", pathObject.Info.PathId));
`

**Comment by yagizzha** [comment]
Thanks that worked perfectly !
