### ISSUE TITLE
pen up and pen down gets bugged after cutting process

### ISSUE THREAD

**Issue by yagizzha** [svenhb/GRBL-Plotter#278]
Both pen up and pen down goes to -1.0 after cutting , normally pen up is 2.0 , if i re select the file from file section it fixes itself

**Comment by svenhb** [comment]
Can you show me the Gcode you used?

**Comment by yagizzha** [comment]
![d1](https://user-images.githubusercontent.com/88779645/162220605-1331669f-acd7-4b2f-a9dc-3979406c74f1.svg)
this was one of the svg's this problem happened with but it has happened with others aswell , also it happens mostly after fidicual detection

**Comment by svenhb** [comment]
No answer - no problem
