### ISSUE TITLE
Workingspace dimensions

### ISSUE THREAD

**Issue by Gabse** [svenhb/GRBL-Plotter#28]
Hi, I updated to the new version to test the new soft limit Feature an here is some feedback:

In my opinion would it would be nicer to input both max and min coordinates from home point instead of the traveling distance and home position

In my test a file which would leave the workspace did launch like normal. It would be nice if not only the Dimensions box would toggle color, but also a message box would show up like in jogging mode

In my opinion a message box with OK and Cancel isn't a good idea, because people (me included) tend to just press OK instead of reading the text. It would be better if you have to tick a box to leave working space, or you could simply not leave it.

Otherwise thanks for the new features, I’m sure they will save a lot of trouble.

**Comment by svenhb** [comment]
Thanks for the feedback.
Perhaps I should implement a 2nd level of alert - which gets the tick box. 
As a 'normal' alert the tick box and message box on data-load sounds to restrctive to me...
