### ISSUE TITLE
Screen Sizing Issue

### ISSUE THREAD

**Issue by supercrewed** [svenhb/GRBL-Plotter#280]
When I load the program 1.6.6.2, the Feed Hold, Resume, Kill Alarm, Door, and Reset buttons are not visible.  Is there a way to adjust this?
I am using Windows 10, screen res. of 1920 x 1080, and cannot be changed, due to it being a laptop.
The program loads perfectly, except for this, can you recommend a solution?

**Comment by svenhb** [comment]
You may try to shrink the jouystick control:
![image](https://user-images.githubusercontent.com/19973251/163939658-a551dfce-e7cc-439b-a629-5519ba8e62f7.png)

**Comment by supercrewed** [comment]
I will try it, the new program has some cool features, over the previous version.

**Comment by svenhb** [comment]
Seems to be fixed
