### ISSUE TITLE
Windows 64 bit updated. 

### ISSUE THREAD

**Issue by 78Matteo78** [svenhb/GRBL-Plotter#281]
hello svhen I wanted to ask you if it is possible to update grbl plotter to the 64-bit platform as well. I tested on Windows 10 and it struggles to run. then as regards an old problem of speed of the axes, which above 600 went half as if it were 300, since I use a mega 2560 clone, I solved it with the firmware update you published. Thanks for everything

**Comment by svenhb** [comment]
What is the advantage of 64-bit version? I had no problems up to now with 64-bit Win-10 operating systems.

**Comment by 78Matteo78** [comment]
I am using an old version, 1.3.3.4 because it has no problems in the sense that I can open large gcode files But the other versions, starting from the 1.4-1.5-1.6 series, fail to load the gcode and slow down all the program functions. the program is also installed in the x86 folder for compatibility but new versions don't work. I wanted to let you know that with the new firmware I have also solved communication problem, often with error 25 in the COM window. Greetings Matteo

**Comment by svenhb** [comment]
Bad to hear you have problems to open large gcode files - are they "pure" gcode, or with my XML-Tag extensions?
Can you upload or email me such a large file, to find the problem? Perhaps I can add an option to bypass parsing uneeded features...
Good to hear that other firmware could fix a problem.

**Comment by 78Matteo78** [comment]
With versione 1.3.3.4 in 10 seconds open file martedì, 19 aprile 2022, 08:58PM +02:00 da Sven  ***@***.*** :

**Comment by 78Matteo78** [comment]
ok svhen, software 1.6.6.2 works fine even in 64 bits. All functions work well. There remains the problem of the file being too large and not opening. Please delete from the list of problems .... Thanks greetings Matteo

**Comment by svenhb** [comment]
>software 1.6.6.2 works fine even in 64 bits

Good to hear,

>There remains the problem of the file being too large and not opening

Can you upload or email me such a large file?

**Comment by 78Matteo78** [comment]
I sent you 2 emails with the file attached, did they arrive?

**Comment by svenhb** [comment]
no, I got no email

**Comment by 78Matteo78** [comment]
Big file gcode
--
Inviato da Libero Mail per Android mercoledì, 20 aprile 2022, 08:09AM +02:00 da Sven  ***@***.*** :

**Comment by 78Matteo78** [comment]
perhaps files with the extension. nc are not accepted ??

**Comment by 78Matteo78** [comment]
however it is an image file converted into gcode with grbl laser with 3 lines per millimeter. if you don't receive the file I convert it to txt and try to send it to you

**Comment by 78Matteo78** [comment]
or I try to zip

**Comment by 78Matteo78** [comment]
Zip file. 
--
Inviato da Libero Mail per Android mercoledì, 20 aprile 2022, 10:48AM +02:00 da Sven  ***@***.*** :

**Comment by svenhb** [comment]
no... right email adress? svenhb@web.de

**Comment by 78Matteo78** [comment]
Now?

**Comment by svenhb** [comment]
yes, now I got it - thanks.
1st try: after 1 minute still not displayed :-(

**Comment by 78Matteo78** [comment]
Tanks svenh!!!

**Comment by svenhb** [comment]
Ok, to bad. Your example has 91500 lines, at 100000 lines GRBL-Plotter skips time consuming display features....
I will make this limit changeable in the setup....
Time consuming features are:

- direction arrow and id at pen-up path
- try to colorize pen-down path by tool-table settings

**Comment by svenhb** [comment]
Check new release: https://github.com/svenhb/GRBL-Plotter/releases
![image](https://user-images.githubusercontent.com/19973251/164270703-a0782ccd-d251-49ea-bd69-a28e54ed980b.png)

**Comment by svenhb** [comment]
Thank you, 
I hope the loading time is now ok?

**Comment by 78Matteo78** [comment]
Yes yes.... Perfect

**Comment by svenhb** [comment]
Seems to work...
