### ISSUE TITLE
Wire bending mode

### ISSUE THREAD

**Issue by Ams-Laser** [svenhb/GRBL-Plotter#282]
**Describe the solution you'd like**
is there a way to have feed and bend support for a wire bending machine
there is already a tangential knife support, so angles to "bend" are already calculated, it is just a matter of adding springback compensation and handle the bending peg

**Describe alternatives you've considered**

this should be easy by conbinig the "tangential knife settings" along the "covert 2d shape to development"

**Additional context**
![image](https://user-images.githubusercontent.com/87819514/164743949-47e90ee1-3024-4625-8b97-b4fc61304d00.png)

**Comment by svenhb** [comment]
I was also thinking about such a wire-bender - my problem: how to create content in 2D view (SVG, DXF) which I can export to wire-bender data. Free dimensions to calculate turn-angle are line-color and line-width.
Your machine only bend in 2D dimension, without turning the wire?

>there is already a tangential knife support, so angles to "bend" are already calculated, it is just a matter of adding springback compensation and handle the bending peg

No problem. Is it a fix add-on in angle or depending on the bent-angle = a percentage value?

**Comment by Ams-Laser** [comment]
springback varies with material, best guess would be to be able to use both
mabe a checkmark use springback compensation and value then another two check marks one indicating value is percent other indicating is angle in degrees

the peg that does the bending also needs to account for the offsetradius of the peg, and a gcode block to duck (lower) the peg to go under the wire when bends ara the other way

**Comment by Ams-Laser** [comment]
look at this https://youtu.be/SQIYZ-iKuG4

**Comment by svenhb** [comment]
Yes, nice.
To make letters out of a stripe of material, by making grooves at the bending positions, I made an add-on. Check this "issue": https://github.com/svenhb/GRBL-Plotter/issues/220

**Comment by Ams-Laser** [comment]
would it be possible to conbine that with the actual bending of the profile ?

**Comment by Ams-Laser** [comment]
the pegs could be either solenoid or axis control
it is better for the diferent setups if we leave a "pull pegs code" "push pegs out code" input section (for custom gcode to retract or extend the pegs, also a single or double peg tik march is needed
same for the cut wire command "cut wire code" as i mighy need to feed in more material to get to the cut location then either axis or solenoid used to do the cut

**Comment by svenhb** [comment]
Try this first version with fix axis X for feed and Y for bend angle...
https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_Setup_1664a.exe
![image](https://user-images.githubusercontent.com/19973251/164944627-7f5e11d1-8e9c-4940-953e-59bb2daf3d60.png)

**Comment by Ams-Laser** [comment]
Hello,
Thanks!!!!!!!
on machine parameters, the bend radius is the peg radius ?
there is a grayed wire diameter setting ?

**Comment by svenhb** [comment]
>on machine parameters, the bend radius is the peg radius ?

The radius of the bent wire: probably peg position from center of turning wheel, minus peg-radius

>there is a grayed wire diameter setting ?

Perhaps it is needed later on, for fine tuning the algorithm

**Comment by svenhb** [comment]
Any results up to now. you could show?

**Comment by Ams-Laser** [comment]
Hello, 
im finishing the hardware and will get back with feedback

Thanks
Ed

**Comment by svenhb** [comment]
Still no feedback, seems to work...

**Comment by ivofuture** [comment]
I'm going to make the Bending channel letters machine and could you tell me if I charge marlin or any version of grbl? 2 weeks and you're good to go.

**Comment by svenhb** [comment]
If you want to use GRBL-Plotter, better go with grbl. Communication with marlin is not well tested and a bit strange in my eyes.
Any feedback is welcome.

**Comment by ivofuture** [comment]
Excellent start to work.
