### ISSUE TITLE
tangential axis and drag knife doesnot works simultaneously

### ISSUE THREAD

**Issue by huley76** [svenhb/GRBL-Plotter#284]
As suggested , i  enabled both tangential knife and drag knife options for my tangential knife operation. Still the g code that i create from "Create simple shapes" doesnot take account into for the offset and the g code and figure i get is unbroken therefore everytime the knife is raised and lowerd , a gap appears due to the offset

![Bug](https://user-images.githubusercontent.com/105011612/166985306-b755e8b8-22cc-4fa8-b902-f2ae71dc4728.PNG)

![279775992_1005387200118664_5897705146319899588_n](https://user-images.githubusercontent.com/105011612/166985635-d9d87330-e62b-4e17-a93e-00bd09b325aa.jpg)

How i can activate the feature to compensate the offset and use tangential knife at the same time.

P.S. how can i choose the depth of cut and number of passes. I want to cut 2mm paper in one cut and now It cuts  with 1.1 depth and in two pass even if i set Z min as 2.
 Thank you

**Comment by svenhb** [comment]
Here you need to put in the offset from center (tip of knife to axis of rotation): 
![image](https://user-images.githubusercontent.com/19973251/166994053-ae8131c0-812e-4207-91c9-a02dccd715da.png)
![image](https://user-images.githubusercontent.com/19973251/166994973-7587b82a-2ae9-4308-8057-61985d858dbe.png)

![image](https://user-images.githubusercontent.com/19973251/166998018-2bd9283a-c457-4a15-a1ed-846d75485aa8.png)

If you want to cut same path several times:
![image](https://user-images.githubusercontent.com/19973251/166998792-8c702f2e-107f-4407-8017-73fcabb23d28.png)

**Comment by huley76** [comment]
I have adjusted the settings as you recommended but still it doesnot work for me.
![error offset](https://user-images.githubusercontent.com/105011612/167267325-2a7bee48-c6cf-4f5d-8306-386d8474de1a.PNG)

The problem that i have is the while the knife is raised and rotated it lands not on the position where the cut was, but a little behind as shown below.
![279683448_1218977375540814_4615353422464428107_n](https://user-images.githubusercontent.com/105011612/167267703-856f7290-e83e-4660-93a5-2c7a7fbb2b84.jpg)

I looked at one of the issue with same problem as mine where you solved this problem recently and that was made available recently in new version, as you can see i installed the newest version  but i still couldnot get the same result which was somewhat like this
![withoffest](https://user-images.githubusercontent.com/105011612/167267820-57d69cec-2554-4ada-ab08-f8a4d906661a.PNG)
:

how can i activate this feature?

**Comment by svenhb** [comment]
You need to set "Offset from center" very exactly

**Comment by huley76** [comment]
Mine is almost same as you used in video for tangential knife

![279894087_322541673291227_7415532899114138996_n](https://user-images.githubusercontent.com/105011612/167269098-00ededf8-2a24-4c63-a57c-fc08b9898133.jpg)

I even tried with different values but the offset remains the same which is my mechanical offset of knife holder

**Comment by svenhb** [comment]
Looks like your knife-tip is in front of the rotation axis - sorry not supported.
Your tip must be BEHIND the rotation axis.
![image](https://user-images.githubusercontent.com/19973251/167270710-1a4110fc-2c05-455b-afbe-679182245636.png)

**Comment by huley76** [comment]
Do you have an example of it?  Mine is almost in the same plane with the rotary axis.

![279893681_543366103850560_6875722846406775378_n](https://user-images.githubusercontent.com/105011612/167271027-9db4d9c1-5a53-45cd-b5a9-91a38bb331f2.jpg)
"Your tip must be BEHIND the rotation axis." do you mean by this or how can i achieve this

**Comment by svenhb** [comment]
Almost is not good enough.
Either the tip is on the rotation axis (center exemple) then you don't need to enable "drag tool".
Or right example, then "drag tool" must be enabled.
![image](https://user-images.githubusercontent.com/19973251/167271532-5c95ec0a-d93b-4f6f-b3fb-29851525f79f.png)

**Comment by huley76** [comment]
Thank you for the help. I will impliment the modification necessary.

**Comment by huley76** [comment]
Now i made changes as in right example above still the issue is same because the software doesnot accounts for offset. In the GUI the line is not broken therefore it rotates and the blades moves down and starts cutting, whereas in my case it should rotate go further a little to compensate the offset and only then the knife should be lowered
https://user-images.githubusercontent.com/105011612/167293842-8fbc688e-d021-473c-a6ca-bcb206bd0fa3.mp4

**Comment by svenhb** [comment]
Ok, now I see an offset of ca. 8 mm in the correct direction, so I would try this settings:
![image](https://user-images.githubusercontent.com/19973251/167314116-0f8a2fab-1399-4c3d-9ddc-da324035bf8b.png)
![image](https://user-images.githubusercontent.com/19973251/167313771-b2f96960-5a88-44cc-a24f-6bb9b5ece092.png)
The path should look like this, to take care of the offset:
![image](https://user-images.githubusercontent.com/19973251/167314031-9476ee3b-9c37-49f5-b2ee-00276914903f.png)

**Comment by huley76** [comment]
which version of the grbl are you using here? tried the identical setting in setup , but the path is not like yours but continuous.

**Comment by svenhb** [comment]
Ok, sorry. At least it is implemented here: https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_Setup_1664a.exe

**Comment by svenhb** [comment]
Any progress?

**Comment by svenhb** [comment]
No feedback, problem seems to be solved...
