### ISSUE TITLE
Question - CNC router

### ISSUE THREAD

**Issue by diasrobson** [svenhb/GRBL-Plotter#286]
Hi there I was wondering has anyone used this amazing pics of software with a cnc router. I currently have a couple of machines that I need to upgrade from Mach3 I was looking at using grbl and came across this.

The reason this caught my attention is that we cut product casings out of aluminium but before we cut it out we laser etch on labels then put the aluminium sheet on the cnc to be cut out, but as you can see this is a pain to get lined up correctly. So I was hopping this worked with Cnc routers so that i could try and laser etch fiducal markers on the aluminium sheet and have this software Aline up the cnc router cuts with the etch and right now we have a lot of alignment problems 

Thank you

**Comment by svenhb** [comment]
Hi, I use it with my simple DIY router.
Here I show an add on for rounding off an edge: https://youtu.be/N1VzqaF1_io

But I think you are more interested in the fiducial correction (https://grbl-plotter.de/index.php?id=fiducial-correction&setlang=en) ?

**Comment by diasrobson** [comment]
> Hi, I use it with my simple DIY router.
> 
> Here I show an add on for rounding off an edge: https://youtu.be/N1VzqaF1_io
> 
> 
> 
> But I think you are more interested in the fiducial correction (https://grbl-plotter.de/index.php?id=fiducial-correction&setlang=en) ?
> 
> 
> 
> Isn't it possible to attach the laser head at the cnc?
> 
> Or cut first to have defined edges and than laser-etch?

Hi there thanks for the quick reply unfortunately the CO2 laser is its own machine so can't use the same mechanics, and yea i am interested in the fiducial alignment.

So the problem with cutting first is that the problem is then moved to the laser where we then have to try and Aline the cut parts with the laser path the laser is very nice but it has a tendency to wonder during the day and it's cutting path moves just enough to make the part unusable plus I want to take out human error side of it too

**Comment by svenhb** [comment]
I see...
Probably the biggest challenge is to "see" the fiducials on the aluminum

**Comment by diasrobson** [comment]
> I see...
> 
> Probably the biggest challenge is to "see" the fiducials on the aluminum

This is what it looks like 

![image](https://user-images.githubusercontent.com/1339009/168800068-c2d601bb-3859-424e-a1d3-b7568832adde.jpeg)

**Comment by svenhb** [comment]
For automatic recongition, an DXF or SVG import is needed, where the fiducial cirles are named as "fiducial" (or stay in a layer with this name).
But you can also teach the positions manually if you load gcode:
![image](https://user-images.githubusercontent.com/19973251/168810033-ad25fcc4-cd19-41f8-9e25-adb871e4b426.png)

**Comment by svenhb** [comment]
Any real life tests up to now?
