### ISSUE TITLE
Problem with tool change on coreXY pen plotter

### ISSUE THREAD

**Issue by anbello** [svenhb/GRBL-Plotter#288]
**Describe the bug**
I have a coreXY pen plotter with grbl-coreXY 0.9i on Arduino nano and it is near all working OK with GRBL-Plotter.
The problem is on multi group plotting and tool change. I have set to change the tool manual (Pause M0) but when a new group begin the pen goes up then appear the dialog box 'Tool change needed' and then immediately pen goes down. This last pen down should not happen and is a problem.

For pen up / down I have a servo controlled by 'M03 S50' for up and 'M03 S0' for down.

**Comment by svenhb** [comment]
Please check this setting:
I assume the PWM will be switched off via M5 with the result, that the pen goes down...
![image](https://user-images.githubusercontent.com/19973251/170286099-9d12f467-5524-4cbf-b7ed-7e259679f20e.png)

**Comment by svenhb** [comment]
Yes, sure it is ok to uncheck. It is for router with spindel, if you need to change the bit.
