### ISSUE TITLE
Problem with feed slow down on large gcode file

### ISSUE THREAD

**Issue by anbello** [svenhb/GRBL-Plotter#289]
**Describe the bug**
The problem is with my coreXY pen plotter with grbl-coreXY 0.9i on Arduino nano.
With a  gcode of near 100000 lines (produced by many tiny circle) when the plotting is near half complete all the gcode lines has been read by the program and the plotter continue to plot (I think using some sort of buffer) but at a very low speed.

**Comment by svenhb** [comment]
Can you show the output of the COM-window?
What do you mean with "...and the plotter continue to plot", did it stop before because of tool-change?

**Comment by anbello** [comment]
It is a single color plot, no tool change. On the left panel I see all the lines has been read but the plot is near the half, it continues to plot but at low speed.
Now I can't post the output, I will do asap.

**Comment by svenhb** [comment]
Perhaps you can post the gcode from the left panel?

**Comment by svenhb** [comment]
With my Arduino nano on the desk, with grbl 1.1 I could also notice the slow down...
After pressing pause, the speed came back...
No idea for the moment...

I would use different import settings:
For circles I would use G2/G3 commands 
and the N-line numbers are not needed....

Uncheck:
![image](https://user-images.githubusercontent.com/19973251/170508461-0dbe912f-30da-42d9-b489-97126f2086b7.png)
![image](https://user-images.githubusercontent.com/19973251/170510634-d0b157a8-233d-45e6-bd12-46bca5467073.png)

**Comment by anbello** [comment]
Thanks, I will try and will let you know.

**Comment by svenhb** [comment]
I don't have your original SVG or DXF to import it with other settings...

**Comment by anbello** [comment]
Sorry, here it is.
[boids2d-red.svg.zip](https://github.com/svenhb/GRBL-Plotter/files/8780721/boids2d-red.svg.zip)

**Comment by svenhb** [comment]
Ok, too bad, the SVG contains paths in circle shapes, but not real circles, no way to reduce code-size here.
But you could avoid tiny moves, which reduces line-count from 95424 to 38408:
![image](https://user-images.githubusercontent.com/19973251/170576856-6f444b1b-ce4a-4201-ba9e-c11a9113ee78.png)
In 2D view it looks now a bit angular, but I'm sure the real output looks still good:
![image](https://user-images.githubusercontent.com/19973251/170576992-9bff093e-e796-407e-8996-ae925f928270.png)

**Comment by anbello** [comment]
Thanks a lot, I didn't yet tried because the pen plotter is not here with me, I will try today and let you know.

**Comment by anbello** [comment]
Sorry, another question:
Is it normal this behavior with long gcode files or is it something that will be addressed in the future?

**Comment by svenhb** [comment]
I'm working on it

**Comment by svenhb** [comment]
Please check new version: https://github.com/svenhb/GRBL-Plotter/releases

**Comment by anbello** [comment]
I have tested new version, with 'Remove very short moves' < 0.1 it has random slow down and return to normal speed during the plotting, with < 0.5 all OK from start to finish and circles don't seems segmented to the eyes.

Thanks

**Comment by svenhb** [comment]
Thanks for the feedback. So the main problem: "after finish sending the code from left panel the plotter slows down" is solved.

>with 'Remove very short moves' < 0.1 it has random slow down and return to normal speed 

Probably too much commands per seconds needed, to keep the grbl-firmware buffer filled...
At feedrate 1000 mm/min ca. 167 command-lines with ca. 15 chars each needs to be send and visulized in GRBL-Plotter.

**Comment by svenhb** [comment]
>Probably too much commands per seconds needed

You could reduce command length by use of less decimals (just 1 instead of 3):
![image](https://user-images.githubusercontent.com/19973251/170876706-69d33bb7-a93e-4f32-9a7c-f6aba3e84902.png)

By use of "compress" and / or "Relative movements":
![image](https://user-images.githubusercontent.com/19973251/170876791-28939d92-6358-4bce-9ce0-8b0a147d3dd6.png)
