### ISSUE TITLE
Automatic scaling doesnt work on big image 

### ISSUE THREAD

**Issue by yagizzha** [svenhb/GRBL-Plotter#290]
![image](https://user-images.githubusercontent.com/88779645/170715954-ab5bcaa5-8218-48c4-967c-020c702dcb94.png)

Circle is detected and there is no "fiducial not detected" error , also tried centering the circle with shape recognition and that went correctly too however second fiducial (the one shown in image) is not getting correctly recognized . First one is working as intended.

**Comment by svenhb** [comment]
You need to adjust the filters for your needs:
1. enable filter result
2. adjust filter until your fiducial is recognized (red or yellow)
3. save new settings
![image](https://user-images.githubusercontent.com/19973251/170728754-15ad798a-4e1e-47d4-91af-5bfebc91101a.png)

**Comment by svenhb** [comment]
Any improovements?

**Comment by yagizzha** [comment]
Couldnt try yet , will let you know as soon as we get a result

**Comment by svenhb** [comment]
Any improvements?

**Comment by svenhb** [comment]
I hope it is fixed
