### ISSUE TITLE
servo motor command

### ISSUE THREAD

**Issue by ali-allafi-1996** [svenhb/GRBL-Plotter#291]
hello, I have some questions for you 
1- how I can adjust the program ( GRBL Plotter) to don't generate the command (M03/M04),
 when it generates the code this command is automatically generated with the g code.
I don't use the servo motor except for the Gripper when the pen change.
please I want to control my g code generated, I want to code without the (M03/M05) command.
2- the homing cycle in this program how I can fix my homing position for x, y, and z coordinate in this program?

**Comment by svenhb** [comment]
You need to adjust your pen-up/-down commands here: If you don't want M03/M04, don't choose Laser or PWM, but Z axis or put-in your own commands (individual). With Z-axis, you may enable "Don't use spindle", to avoid inital M03.
![image](https://user-images.githubusercontent.com/19973251/170824457-e1bbe92c-acd7-431a-8041-ec29461fccfb.png)

Homing cycle and position is inside grbl-firmware, no chance to change.
After homing you get not changeable machine-coordinates - but who cares. You will use work-coordinates (except for tool-changes): https://grbl-plotter.de/index.php?id=auto-pen-change

**Comment by ali-allafi-1996** [comment]
![image](https://user-images.githubusercontent.com/85343795/170825601-533de440-0a27-4fd3-8a6e-291f885e40e7.png)

**Comment by ali-allafi-1996** [comment]
I don't use the servo as z axes but I used it in the tool changer as a gripper.
I don't need this command in my main g code.
how I can avoid it?

**Comment by ali-allafi-1996** [comment]
![image](https://user-images.githubusercontent.com/85343795/170825804-7882efae-895d-46b4-8350-9f38f416f9ae.png)

**Comment by svenhb** [comment]
Are you using latest version? As you can see, no M3/M4 command:
![image](https://user-images.githubusercontent.com/19973251/170827371-0afee5a1-e810-4d50-92c8-5eb46e444da6.png)

**Comment by svenhb** [comment]
Using individual commands:
![image](https://user-images.githubusercontent.com/19973251/170828190-a79725a3-dfd7-493a-aa84-dc2fc7a9ed94.png)

**Comment by ali-allafi-1996** [comment]
could you give me the setting to use it on my own 
![image](https://user-images.githubusercontent.com/85343795/170829309-80825652-834f-43c2-ae6f-4c08706b92e2.png)

**Comment by ali-allafi-1996** [comment]
I have another problem with the tool changer.
![image](https://user-images.githubusercontent.com/85343795/170829719-c547b00d-5df4-4eb2-9f6b-53363861e040.png)
 how I can use it. because I want to add a special code to the black and blue colors.

**Comment by svenhb** [comment]
Just click into the cell and put in your code

**Comment by ali-allafi-1996** [comment]
![image](https://user-images.githubusercontent.com/85343795/170830289-9f10652f-d855-4044-ace7-22c276654762.png)
is it the right way to use it?

**Comment by ali-allafi-1996** [comment]
m03 for the black color 
m05 for the blue color 
that is what I want.

**Comment by svenhb** [comment]
After changing, you need to save and reload tool table example "myTools"
![image](https://user-images.githubusercontent.com/19973251/170830584-23412741-bb7f-4b74-9e93-0bae39935b81.png)

You need to enable grouping by colors and activate tool table:
![image](https://user-images.githubusercontent.com/19973251/170830638-ca9d81dd-cdc3-4e4d-afab-d673cce71a10.png)

Then code will be applied:
![image](https://user-images.githubusercontent.com/19973251/170830692-b1cf11be-45de-445e-819d-6730d108f9a1.png)

**Comment by ali-allafi-1996** [comment]
Okay, 
I think i don't use this command after now
![image](https://user-images.githubusercontent.com/85343795/170830938-ec0ce997-c151-474f-a616-d638a54b9d22.png)
because I use a special command from the table is it right?

**Comment by svenhb** [comment]
If you don't need scripts for tool change (see below), you need not to enable.
![image](https://user-images.githubusercontent.com/19973251/170831378-0724e1a7-733a-458f-a13c-e39f95fa2ac1.png)

**Comment by ali-allafi-1996** [comment]
Okey my friend thanks for giving me all the answers that I want . 
Now I can turn on my CNC plotter as I want it .
