### ISSUE TITLE
Hi how can I put space before Y line (or end of X line)

### ISSUE THREAD

**Issue by corumlee** [svenhb/GRBL-Plotter#294]
If I convert IMG in to gcode and create G-Code.

Then happens like attached pic

After X command line comes direct Y command line

So my mpcnc machine doesn't recognize the command.

Can somebody help this?

![pic](https://user-images.githubusercontent.com/40646059/174057573-26b02119-9b3e-420f-ae89-8e53006dd1ba.png)

**Comment by svenhb** [comment]
You could use the "replace" command from the editor:
Right click:
![image](https://user-images.githubusercontent.com/19973251/174062650-0540f1a2-185f-41cb-bf09-7956e6551dfc.png)

Then replace "Y" by " Y"
![image](https://user-images.githubusercontent.com/19973251/174062590-127cc14b-dd7f-48a7-b057-f8608ead5bc4.png)

**Comment by corumlee** [comment]
Thank you very much 

It is working now
