### ISSUE TITLE
ERROR: Missing X real time status report per 10 seconds. Interval XXX. Correct baud rate? Try Marlin response

### ISSUE THREAD

**Issue by mdsultan11** [svenhb/GRBL-Plotter#295]
Hi Team, its great pleasure to meet you all here and thanks for the awesome GRBL work.

I have built my small desktop CNC and i'm using GRBL plotter here to run my co-ordinates (X-axis, Y-axis and Z-axis). Everything i have tuned up starting from design, assembly and upto make it run with current setting all etc.
Now i have got a problem with plotter that whenever i dump a code into the plotter and try running it and within some seconds it starts showing the error as Missing X real time status report per 10 seconds. Interval XXX. Correct baud rate? Try Marlin response and stops running the machine. I have tried many times with different codes and minor changes in $$ but still i couldn't able to figure out what's the exact issue! Can somebody please help me with this that how to solve this and make it run without any prob!
A quick help will be more appreciable!! Thanks in advance.
![Missing real time issue](https://user-images.githubusercontent.com/50007635/175024490-616b8d72-c11a-4bde-86e6-fb979c7234ca.jpg)
.

**Comment by mdsultan11** [comment]
Hi Svenhb,

Thanks for the kind and fast reply!!
**can you upload the latest logfile inside the logfiles-folder?** =Which log file!!?
**What kind of controller you are using?** = CNC shield with Arduino Uno!
**Which grbl version?** = 1.6.6.6
**Connected via USB or Ethernet?** =Through USB
**With USB most common problem is a bad shielded USB cable...** = Using good 4 core shielded wire with proper soldering etc!

**Comment by svenhb** [comment]
You click on the path below "Data Path" to open the data folder, then open the logfiles folder and look for "logfile.txt"

Also check your grbl-setup - all ok?
![image](https://user-images.githubusercontent.com/19973251/175036517-53912be0-630d-4d60-979c-2bf24233e51b.png)

**Comment by mdsultan11** [comment]
Hi Sevnhb,
![GRBL setup](https://user-images.githubusercontent.com/50007635/175038053-ed79c05d-cd97-4e78-a721-8669cf850f79.PNG)
[logfile.txt](https://github.com/svenhb/GRBL-Plotter/files/8957919/logfile.txt)

I have attached the pic and log file..

In the lof files i have found multiple log files named log_20220600.0 and .1 and .2 and .3 and .4 and .5 etc

**Comment by svenhb** [comment]
Ok, so I found:
grbl ERROR 'error:33' Motion command target is invalid. for
G3X119.531Y-16.023I-5.000J0.000'  lineNr:139

Can you try to send Gcode from an imported SVG or DXF file? So I know the GCode is ok...

**Comment by svenhb** [comment]
You mean GRBL-Plotter was working with your machine and then from one day to the other the problem occurs?

>Either the Missing real time error pops up or suddenly machine stops and Kill alarm pops up within some seconds. 

I think it ia a problem with your electronic, can you try without motor-shield to avoid noise?

**Comment by svenhb** [comment]
I could run your code on an Arduino nano - without connected hardware - without an error. After 5 minutes I stopped.
Also line 139 was processed without error.

**Comment by mdsultan11** [comment]
> I think it ia a problem with your electronic, can you try without motor-shield to avoid noise?

I havn't fixed any Motor yet to my machine as it is running now just with spring-PEN on paper to check the dimensions of the drawn drawings.

**Comment by svenhb** [comment]
What happens, if you just check your code?
![image](https://user-images.githubusercontent.com/19973251/175231893-0b043b40-dc5b-4b4c-bded-d6c7b626e56d.png)

**Comment by mdsultan11** [comment]
![Shifted](https://user-images.githubusercontent.com/50007635/175234066-1d75bba5-f625-4b61-b3d2-9fd0728e6e77.PNG)
Yes, i just the code and it finished successfully, but again i ran the code and i got an error of Missing X real time issue and also i saw that the picture view is shifted inappropriately as shown in the image!

**Comment by svenhb** [comment]
So, just "Check" is ok, but real streaming not - right?
Your coordinates also looking wred, I assume strong communication issues if your stepper motors are in use...
You may check your power-supply - perhaps voltage drop-down at the arduino, when powering the stepper motors?
![image](https://user-images.githubusercontent.com/19973251/175234888-3b5fc049-30fe-49ad-abc5-f7366f6fd63b.png)

**Comment by mdsultan11** [comment]
I will check once that sir and get back to you soon.

**Comment by mdsultan11** [comment]
![kill alarm](https://user-images.githubusercontent.com/50007635/175304491-8ce670ce-55f7-4bcc-8ce8-980fd5b005f1.PNG)

Hi Svenhb, i have checked the voltage drop-down at the arduino side and i dont see any issues there as it is passing 23.8v from the power supply to the shild side, but still getting an error now as shown in image! Missing X real time status!

**Comment by svenhb** [comment]
Do you use the regular grbl version from here?: https://github.com/gnea/grbl
Or a version I deliver with my setup?
The problem is:
GRBL-Plotter sends frequently a '?' (https://github.com/gnea/grbl/wiki/Grbl-v1.1-Commands#ascii-realtime-command-descriptions)
To get the actual tool coordinates (https://github.com/gnea/grbl/wiki/Grbl-v1.1-Interface#real-time-status-reports)

But your system is not responding during gcode streaming...

**Comment by mdsultan11** [comment]
You mean just the config.h file or complete grbl 1.1 folder?

**Comment by svenhb** [comment]
I mean the data you upload to your arduino, some how you can extract the hex-file from the Adruino-IDE.
Did you try to upload an other grbl version (e.g. the original one), perhaps your change in config.h is the reason...

How to ulpoad a hex-file via Xloader: https://grbl-plotter.de/index.php?id=quick-guide

**Comment by mdsultan11** [comment]
Oh oka..Actually i have uploaded the **grbl upload** file from this above zipped file and i have uploaded through using **Arduino IDE.** 

As you mentioned i will try uploading this attached **hex-file in my Arduino Uno using X-loader** and try running my machine.

**Comment by svenhb** [comment]
BTW: you can watch the status reports, when enabling this checkbox. If you start streaming does they stop?
Note: this feature slows down the streaming process...
![image](https://user-images.githubusercontent.com/19973251/175469616-4c10e952-4786-407c-a8f4-21986da0203f.png)

**Comment by mdsultan11** [comment]
Hi Svenhb,

I have uploaded the **hex-file using X-loader** as you mentioned (I couldn't able to do homing because the Z-axis limit switch is not working here now after uploading the hex-file into the UNO and also i couldn't able to edit the code now and its fine).

But now i didnt see the **Missing X real time status report** now but before the code starts running 'm facing the Kill Alarm issue now
![Kill alarm 2](https://user-images.githubusercontent.com/50007635/175482468-0d248acd-2b79-442e-9264-d7ae65e937a9.PNG)
!

**Comment by svenhb** [comment]
Just press "Kill alarm" 
![image](https://user-images.githubusercontent.com/19973251/175483783-aae29589-bd41-433f-ae44-221444cd9224.png)

**Comment by mdsultan11** [comment]
As soon as i press the Kill Alarm, the tool co ordinates will change and move in another direction.

**Comment by svenhb** [comment]
Then do a hard-reset and the coordinates will set to "0"
![image](https://user-images.githubusercontent.com/19973251/175519429-465261c5-b473-40bb-80c0-aa87679ee634.png)

**Comment by mdsultan11** [comment]
Hi Svenhb, as you said i have done hard-reset and luckily it ran for some time like for 9:56mins (1st time it ran too long). Then again it got stopped because of sudden Kill Alarm as shown in pic and also all the co-ordinates became 0.00
![kill alarm 3](https://user-images.githubusercontent.com/50007635/175541185-cc607d67-d6d3-44d1-8e91-465a7266abd2.JPG)
.

**Comment by svenhb** [comment]
I would say the controller will be reseted externally during streaming:
First a message about streaming progress, next received welcome message, which appears after any reset. But Reset was not initiated via GRBL-Plotter...
```
2022-06-24 17:43:28.3788 | Info  | GrblPlotter.MainForm           | ●●● Streaming Progress:  5%  Duration:00:02:25  Line:  114   Status:    ok   WCO.X:0102.475  Y:-0006.710  Z:-0001.000  A:-0001.000  B:-0001.000  C:-0001.000
2022-06-24 17:45:02.3038 | Info  | GrblPlotter.ControlSerialForm  | ProcessGrblWelcomeMessage - SendStreamEvent

```

**Comment by mdsultan11** [comment]
I didn't do any reset or i don't have any idea about reset of controller!!
Please help me to debug this issue...

**Comment by svenhb** [comment]
Perhaps weak power supply or short curcuit when reaching certain position.
Do you have seperat power for the motor-drivers? Try to switch off and start streaming then to see if the problem still appears.
Or try streaming with spindle switched off to avoid any noise (remove tool before and check for save Z position)

**Comment by svenhb** [comment]
Do you have pictures of your controller and machine?

**Comment by mdsultan11** [comment]
![WhatsApp Image 2022-06-30 at 12 33 34 PM](https://user-images.githubusercontent.com/50007635/176614215-848e47ac-b28e-4a81-8a70-0894895bb7bc.jpeg)
![WhatsApp Image 2022-06-30 at 12 33 01 PM](https://user-images.githubusercontent.com/50007635/176614230-c97a7505-75de-4955-9fd6-196031081b0a.jpeg)
![WhatsApp Image 2022-06-30 at 12 34 25 PM](https://user-images.githubusercontent.com/50007635/176614234-c90afa47-06aa-4b76-be04-9233c970162a.jpeg)
![WhatsApp Image 2022-06-30 at 12 34 24 PM](https://user-images.githubusercontent.com/50007635/176614238-a016d851-c8a0-47ed-9ad9-03a18cc36c09.jpeg)
![WhatsApp Image 2022-06-30 at 12 34 22 PM](https://user-images.githubusercontent.com/50007635/176614241-1e08a928-f3e0-491f-a9d3-dbb9811ce265.jpeg)

Please have look into the attached controller pics!!!

**Comment by svenhb** [comment]
Nice casing, did you make it by your self? 
I hate this USB connectors - perhaps loose contact caused by vibration? I would try to fix the connector additionally with tape:
![image](https://user-images.githubusercontent.com/19973251/176616359-938e59a3-003b-4f82-bea2-56bccb51bc11.png)


And please replace your mains-cable!!!
![image](https://user-images.githubusercontent.com/19973251/176616931-f783988a-5466-4913-b4d9-42382cefb9b2.png)

**Comment by mdsultan11** [comment]
Thankyou, yes i have designed and printed the casing for all the Electronics part..

As you suggested i will tape the connector part and replace the cable and try moving my machine and update you accordingly, thankyou :))

**Comment by svenhb** [comment]
Also check for correct connection in this area:
Perhaps connected to wrong pins? There is also reset available...
https://osoyoo.com/2017/04/07/arduino-uno-cnc-shield-v3-0-a4988/
![image](https://user-images.githubusercontent.com/19973251/176653957-11204344-62a6-4881-b302-7bcb7fe19bbd.png)

**Comment by mdsultan11** [comment]
Hi Svenhb, after changing the power cord cable and covering the USB cable with tape and so that it should shake, but still it produces error while running. Either will get Missing X error or kill alarm error.

**Comment by svenhb** [comment]
Did you also check your connections, marked in the picture above? Perhaps you wired an end-switch with the reset pin?
![image](https://user-images.githubusercontent.com/19973251/176830894-584b648b-f15c-429d-864b-fc07ab0a87a6.png)

**Comment by mdsultan11** [comment]
yes i check that, i have connected the limit switches pins to the X+, Y+ and Z+

**Comment by svenhb** [comment]
I would disconnect any cable which is not needed for basic functionality (end switches, Z axis)
- just keep X,Y axis, then test 
- if test is ok add Z axis

**Comment by mdsultan11** [comment]
Hi Svenhb,

Didnt work this above solution as well!!
Again Missing X real time error!!!

**Comment by svenhb** [comment]
You may try another arduino, perhaps your actual one is defect or has cold solder joints.

**Comment by svenhb** [comment]
You may try another arduino, perhaps your actual one is defect or has cold solder joints.

**Comment by mdsultan11** [comment]
oka bro sure.. i will check other arduino board with same CNC shield and revert back to you!

**Comment by svenhb** [comment]
Perhaps you try other arduino **without** CNC shield first. To be sure streaming works from start to end.

**Comment by mdsultan11** [comment]
How can i do that without CNC shield?

**Comment by svenhb** [comment]
Just connect the Arduino via USB and start streaming the code. The Arduino doesn't know if the CNC-shield is connected or not.

**Comment by mdsultan11** [comment]
oka bro sure thanks.. i will one new Arduino Uno today and check once and revert you back.

**Comment by mdsultan11** [comment]
oka bro sure thanks.. i will one new Arduino Uno today and check once and revert you back.

**Comment by mdsultan11** [comment]
![ARDUINO UNO boards](https://user-images.githubusercontent.com/50007635/177520386-4496125a-9686-4a45-8e80-912ca8ffa5b7.JPG)
Hi Svenhb, It worked very good and fine after long iterations and after changing the Arduino UNO. Thanks for suggesting me to change the Arduino board. 

I used the GOOD arduino as shown in the above image and BAD arduino created a lot of problems like Missing X error and Kill Alarm issue.

Thanks for the continuous co-operation and co-ordination throughout the days. Below is the result as per G-code we had.
![WhatsApp Image 2022-07-06 at 2 56 58 PM](https://user-images.githubusercontent.com/50007635/177521710-8d92a3d2-0315-4e7a-8b11-b8aecd208e7e.jpeg)

**Comment by mdsultan11** [comment]
Hi Svenhb, 
One more help required, As i have started using this machine for my PCB drilling, so when i want my DC motor to start and stop whenever i want to change the drill bit. Can you please tell me the circuit required for it and if any code changes need to be done i grbl 1.1.

**Comment by svenhb** [comment]
Hi,
just connect a relais (driven by a transistor) to pin 11: https://github.com/gnea/grbl/wiki/Connecting-Grbl
https://www.youtube.com/watch?v=RGGxlqCHl_c
Example for relais: https://eckstein-shop.de/5V2F220V1ChannelOptocouplersRelayShieldforArduinoOptokopplerRelaisModul?googlede=1&gclid=EAIaIQobChMIxNqsiYj7-AIVKe7mCh2bDA1qEAQYBSABEgLAgPD_BwE

For manual tool change:
![image](https://user-images.githubusercontent.com/19973251/179240089-177a32d2-13ee-40ff-ba8f-647cd7c151d7.png)

This is also usefull:
![image](https://user-images.githubusercontent.com/19973251/179240322-4cddc207-4cba-432f-9e3b-406ebe986732.png)

**Comment by mdsultan11** [comment]
Hi Svenhb,

Thanks for the suggestion, i have enabled it using 2 channel relay board (only this i had in my inventory) and LM2956 buck converter for my 12V fan for the CNC shield.

And also in the grbl code i have uncommented this line USE_SPINDLE_DIR_AS_ENABLE_PIN (connected the relay1 enable pin to Spindir PIN in CNC shield) to get the DC motor off and on through code only while every tool change.



![WhatsApp Image 2022-07-15 at 8 28 58 PM (1)](https://user-images.githubusercontent.com/50007635/179251717-d1cd3235-745d-4045-8ad7-d5d78d94a46c.jpeg)
![WhatsApp Image 2022-07-15 at 8 28 58 PM](https://user-images.githubusercontent.com/50007635/179251737-2d2d2897-72fa-4ad6-a813-43507b7ecddc.jpeg)


One more help required i.e., i want to enable Z-axis limit switch also(i.e., all the 3 limit switches for homing) while 'm using the spindle enable as well. So whats the change in code i need to do to enable that?

**Comment by svenhb** [comment]
As I know the CNC shield uses old pin-out for grbl version 0.9.
You need to switch the pins in config.h to get it right.

Check default  pin-out of grbl 1.1 https://github.com/gnea/grbl/wiki/Connecting-Grbl

CNC-Shield:
![image](https://user-images.githubusercontent.com/19973251/179254316-fa57818b-1593-4aa5-80d1-85518bd96910.png)

In config.h disable this
![image](https://user-images.githubusercontent.com/19973251/179255679-1dfd063b-7d33-48da-92e2-e692e505a168.png)

to activate correct pins in cpu_map.h :
![image](https://user-images.githubusercontent.com/19973251/179255270-3926d5c4-2135-4309-828b-c59dbd0b1c9e.png)

**Comment by mdsultan11** [comment]
if i disable this VARIABLE SPINDLE then i need to comment i.e., disable USE_SPINDLE_DIR_AS_ENABLE_PIN as well and at the same time i cant use spindle motor rotation but Z-limit switch will activate. 
I need both of the Z-limit switch and Spindle motor control in machine!!!

**Comment by svenhb** [comment]
???
You disable VARIABLE_SPINDLE
and USE_SPINDLE_DIR_AS_ENABLE_PIN is already disabled...
Do you need to switch the rotation direction???

>I need both of the Z-limit switch and Spindle motor control in machine!!!

Just disable VARIABLE_SPINDLE and keep the rest as default.

**Comment by svenhb** [comment]
I would keep everything as default:
Just compare the wiring and connect your z switch with CNC-shield-"spin enable" pin 12
Connect your spindle with CNC-shield "Z-endstop" pin 11
Don't care about PWM, just send M3 S1000 for 100% speed and it will work - also with a relais.
![image](https://user-images.githubusercontent.com/19973251/179344165-cff34ded-96dc-4f2d-b915-6d5ee7bcfa8d.png)
![image](https://user-images.githubusercontent.com/19973251/179344182-968bada4-b89d-4424-821b-44ca0530cfcd.png)

**Comment by mdsultan11** [comment]
Thanks a lot Svenhb, for telling in simple words, its working fine now after following up the above suggestion which you have given. Now i can use all the limit switches as well as the default auto spindle control.

**Comment by svenhb** [comment]
👍

**Comment by mdsultan11** [comment]
Hi Svenhb,

Suddenly i'm not getting a 5v supply to ''Z-endstop'' Pin-11. And my motor is not triggering now suddenly due to that.. checked wiring and all other things. Anything 'm missing here?

**Comment by svenhb** [comment]
Do you have spindle commands in your G-Code, like "M3 S1000"?

**Comment by mdsultan11** [comment]
![CNC2](https://user-images.githubusercontent.com/50007635/181347736-59e2a7ee-d5ef-4bf1-bda9-377ed39a569a.jpeg)
![CNC3](https://user-images.githubusercontent.com/50007635/181347748-15f2cc9c-84b9-45d0-94f6-af1747ee9124.jpeg)

**Comment by svenhb** [comment]
Thanks for sharing your pictures, nice build
