### ISSUE TITLE
Error when compiling source code

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#298]
An error is reported when compiling the source code of version 1.6.6.6
![Snipaste_2022-07-09_15-01-44](https://user-images.githubusercontent.com/53146195/178200534-46c0034a-41c5-4d98-b354-5ef508cd0e49.png)

**Comment by svenhb** [comment]
Try this new files. Perhaps I forgot to update...
https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter/MachineControl/GCodeVisuWorker.cs

**Comment by lianzaozi** [comment]
thank you
