### ISSUE TITLE
Ruler numbers display and insert text option single window.

### ISSUE THREAD

**Issue by Makasudali** [svenhb/GRBL-Plotter#301]
Ruler numbers display and insert text option single window. and other controls also add or update from same window

insted of display gCode text. use this area as tool box for controls like text, shape, images, import files so on.

Please see bellow image. For this if any changes required then can you please do it
![NewMark](https://user-images.githubusercontent.com/109652532/179957509-2ad15ed7-a3e2-410b-b19f-544772fb9157.png)
 and update code this is very easy to use.

**Comment by svenhb** [comment]
For such complicated actions, better use a drawing program like Inkscape.
In Inkscape - when text is complete: Use "Object to Path" for the text.
Then you can copy & paste the path to GRBL-Plotter.

**Comment by Makasudali** [comment]
> Inkscape.

I am very Thankful for your comment I am c# developer working individually as user requirement I need to do some changes in this project. Do you know any Inkscape project compatible with GRBL-Plotter and can you please help me to copy object programmatically to GRBL-Plotter.

Thanks once again.

**Comment by svenhb** [comment]
I just know https://inkscape.org/de/

>can you please help me to copy object

In inkscape use ctrl-C  on the marked path, in GRBL-Plotter use ctrl-V
