### ISSUE TITLE
Can use all windows font 

### ISSUE THREAD

**Issue by Makasudali** [svenhb/GRBL-Plotter#304]
Can I use all windows font in .ttf format into this project. If not then can you please tell me any other way to do this. 
I am happy to say thanks in advance how ever gives best option.

**Comment by svenhb** [comment]
Best wa is to use Inkscape: https://inkscape.org/?switchlang=en
When text is ready, you need to select all text and apply "Object to path".
Then you can copy & paste or save & load the path into GRBL-Plotter

**Comment by svenhb** [comment]
Now I can import real text from Inkscape, please try: https://github.com/svenhb/GRBL-Plotter/releases
