### ISSUE TITLE
A question about the magnification function

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#306]
I'm using version 1.6.6.6, and when I zoom in, I notice that the cursor suddenly goes back to the coordinate (0,0) when I zoom in enough.

The DXF file I used in the test and my operation process are in the attachment
[test1.zip](https://github.com/svenhb/GRBL-Plotter/files/9234004/test1.zip)

**Comment by svenhb** [comment]
Please check if problem is solved: https://github.com/svenhb/GRBL-Plotter/releases

**Comment by lianzaozi** [comment]
> Please check if problem is solved: https://github.com/svenhb/GRBL-Plotter/releases

The source code of version 1.6.7.0 will report an error when compiling
![1](https://user-images.githubusercontent.com/53146195/184335374-1b47fc41-7174-47f8-b13a-1c7561c565b2.png)
![2](https://user-images.githubusercontent.com/53146195/184335445-900854e4-9b32-4b56-b4f7-5ab555345913.png)


Version 1.6.7.0 software zoom function problem has been solved, I will do more testing

**Comment by svenhb** [comment]
Sorry, forgot to upload this files, before generating this relase (means, they are missing in the source.zip)
App. config, Settings.cs, Program.cs, GRBL-Plotter.csproj
in https://github.com/svenhb/GRBL-Plotter/tree/master/GRBL-Plotter
