### ISSUE TITLE
Manual Tool Change Workflow

### ISSUE THREAD

**Issue by ScottEgan** [svenhb/GRBL-Plotter#307]
I'm trying to use a manual tool change procedure for a pen plotter but I would like to set some G-Code to run before the tool change pause. An example would be to move the z-axis up so the pen change is easier.
Is there a way to do this?

Currently I am using these settings to enable a manual tool change:
![image](https://user-images.githubusercontent.com/6709827/182227911-d0e1cac4-b6fd-4152-a702-6a6a62aa93a4.png)

Thank you!

**Comment by svenhb** [comment]
It should work if you place your code into a file which you need to specify here:
Leave the other script-paths empty, if not needed
![image](https://user-images.githubusercontent.com/19973251/182231091-47f78dfe-b392-4168-817d-25ef6e863209.png)

**Comment by ScottEgan** [comment]
Thanks for the quick reply! I'll give it a try.

**Comment by svenhb** [comment]
You could also add your commands here:
![image](https://user-images.githubusercontent.com/19973251/182313173-11b51eff-6127-4e4d-97a6-ee0256ed9193.png)

**Comment by ScottEgan** [comment]
I got it to work by unchecking "Add Pause (M0) instead" and adding an M0 command in the "2) SELECT tool" script. Works well that way as I can control where the pause comes in the program flow. 

The only small issue is that the program starts with a tool change but it is not too much work to skip through it.
