### ISSUE TITLE
Italian language

### ISSUE THREAD

**Issue by 78Matteo78** [svenhb/GRBL-Plotter#309]
Hello How can I help you to have the Italian language too? greetings matteo

**Comment by svenhb** [comment]
I like to use https://github.com/HakanL/resxtranslator/ , when adding a new language:
After creating the new *.resx files, they must be added to the visual studio project.

**Comment by 78Matteo78** [comment]
I try, but I think it will be difficult for me

**Comment by svenhb** [comment]
At least to translate and create the file is not difficult, but a lot of work.
Copy the GRBL-Plotter project to a location and open via Recource Translator.
Add a new language
Insert translation of the "NoLanguageValue"
In most cases it is possible to select and copy more than one cell, translate it via google and copy back to new language cells. It doesn't work if there is a line-break within one cell, which will cause a new cell-row on paste.
![image](https://user-images.githubusercontent.com/19973251/191498133-3ea33821-c8c7-4b5f-a4e4-1db1a99027d2.png)

![image](https://user-images.githubusercontent.com/19973251/191498320-395f5109-d7b8-45da-ba22-574d5fcd0012.png)

![image](https://user-images.githubusercontent.com/19973251/191498921-051af491-be3a-471b-bfd3-349f1a0b1b92.png)

**Comment by 78Matteo78** [comment]
does it only work with visual studio? I'll try to download it ...

**Comment by svenhb** [comment]
Just to create the new resx files doesn't need visual studio, just the resx translator.
Send me the new files and I will make a new GRBL-Plotter version.

**Comment by 78Matteo78** [comment]
ok i managed to understand how it works. it will take me some time, once I have created the new files, I will send them to you by mail. Thanks for your help. Greetings Matteo

**Comment by 78Matteo78** [comment]
Hello i translated all resx files except one, main form in GUI because it gives me the following error in the picture
![Uploading IMG_20220925_153227.jpg…]()

**Comment by 78Matteo78** [comment]
The image in to mail

**Comment by 78Matteo78** [comment]
--
Inviato da Libero Mail per Android giovedì, 22 settembre 2022, 06:51AM +02:00 da Sven  ***@***.*** :

**Comment by svenhb** [comment]
Got no mail up to now

**Comment by 78Matteo78** [comment]
I'm sorry I was wrong ... now it should have arrived

**Comment by svenhb** [comment]
Thanks for your work: https://github.com/svenhb/GRBL-Plotter/releases/tag/v.1.6.7.2
