### ISSUE TITLE
"Z-Height engrave must be negative" causing problem when z-axis directed down

### ISSUE THREAD

**Issue by kirevdokimov** [svenhb/GRBL-Plotter#310]
I have a plotter where z-axis directed down, so 
- Pen down is like `Z 25`, 
- Pen up is like `Z -25`, 

but I cannot set the values to the setup because pen down should be negative and pen up should be positive. 

How to handle this situation?

![image](https://user-images.githubusercontent.com/5202070/192126890-4fe52bf5-d13e-4308-b41a-605c75113c74.png)

**Comment by kirevdokimov** [comment]
Oh, I see I can simply use Individual commands to set up what does pen up and pen down means
![image](https://user-images.githubusercontent.com/5202070/192127440-f152309e-0034-4010-8254-be556d994aa2.png)

**Comment by svenhb** [comment]
What's about inverting the motion direction via $3? To have the "normal" CNC behavior?
https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration#---view-grbl-settings

**Comment by kirevdokimov** [comment]
Oh wow, `$3=4 (dir port invert mask:00000100)`   worked for me, thank you @svenhb :)
