### ISSUE TITLE
UI became a little messy on high dpi monitors

### ISSUE THREAD

**Issue by kirevdokimov** [svenhb/GRBL-Plotter#311]
Initially it loads upscaled blurry as an old legacy app. Not sure if you can notice this with a screenshot itself
![image](https://user-images.githubusercontent.com/5202070/192188606-dfc3cbab-4690-4909-a308-2d34d7dd9608.png)

But when I load an svg the window reloads as HDPI, but some font sizes are messed a little
![image](https://user-images.githubusercontent.com/5202070/192188440-00f32e5a-18f4-42c8-8f71-48897c517fc7.png)

Service buttons are below the frame so unaccessable
![image](https://user-images.githubusercontent.com/5202070/192189108-1bcde4bd-58e9-4f4e-8c6f-e5dce35ef1a4.png)

Current monitor resolution is 3840x2160

**Comment by kirevdokimov** [comment]
This scaling problem can be kind of fixed by user by overriding compatibility options, especially setting high DPI scaling behavior to "System". The app will be blurry and looks like a legacy, but at least not messy

![image](https://user-images.githubusercontent.com/5202070/192192336-a115ec3d-df25-4788-8425-ae9c37ddc124.png)

**Comment by svenhb** [comment]
Yes, there is problem with this scaling and I don't know how to fix it, see also here: https://github.com/svenhb/GRBL-Plotter/issues/239

Thanks for the solution.
