### ISSUE TITLE
Hatch-filling objects actually hatches empty objects on svg imports

### ISSUE THREAD

**Issue by Skynerz** [svenhb/GRBL-Plotter#312]
Hello,
I designed several shapes in a .svg file using inkscape (see attached files). 
When I try to import the file by dragging in the window, the generated gcode shows that every area is hatch-filled. 
I tried to change the filling options by filled the "empty" regions with white, and I also tried to change the .svg export option (Inkscape's svg / plain svg) but nothing changed.

![image](https://user-images.githubusercontent.com/60877014/192818434-a19692d9-d0e0-4ff7-98c1-e3291cdd32a0.png)
![image](https://user-images.githubusercontent.com/60877014/192818566-58b23fa3-5d84-430c-8493-2ebb31ccb0c9.png)

Am I doing anything wrong?

**Comment by svenhb** [comment]
Hi, 
"no fill" should work, could you upload the svg here? Perhaps other keyword?
You can disable hatchfill in the import options and need to disable also in path modification:
![image](https://user-images.githubusercontent.com/19973251/192941562-cc4a7897-78bd-4470-80ba-b5c293bb29d8.png)
![image](https://user-images.githubusercontent.com/19973251/192941654-befaa95d-9aae-4adb-97e3-22302d8243cd.png)

**Comment by Skynerz** [comment]
I want the filled objects to be hatched and the empty ones not to.
If I disable this options, the filled objects will no longer be hatched, right?

Here are the files I get by exporting with Inkscape with "Inkscape SVG" and "Plain SVG" export option:

![Ploxy_inkscapesvg](https://user-images.githubusercontent.com/60877014/192980646-c9168a4e-2d5f-4ddf-b907-55ebe02a4e9c.svg)
![Ploxy_plainsvg](https://user-images.githubusercontent.com/60877014/192980785-461899e8-1e40-41ea-af83-82226b55f4a6.svg)

**Comment by svenhb** [comment]
Seems to be bug in the text import. If you convert the text to path before importing to GRBL-Plotter it should work.
But the hatch fill may have problems with non-filled areas within filled areas...
Then you need to enable this, but not the other option:
![image](https://user-images.githubusercontent.com/19973251/193006477-d5f3dfe2-0bd0-4826-adb4-4153ef63bb35.png)

**Comment by Skynerz** [comment]
You're right, converting objects into paths partly solved the problem!
The letters aren't filled anymore, but if I fill any object, every closed area becomes hatched🤔
I feel it's like the option "Fill closed paths" is enabled if an object is partly filled.
I also double checked that the inner regions are actually not considered as filled regions in Inkscape and confirm they definitely are empty.

![image](https://user-images.githubusercontent.com/60877014/193011634-1ba5fa9b-77d7-4a28-9ae5-2be21ad55429.png)
