### ISSUE TITLE
Tangential Knife and pen Cont.

### ISSUE THREAD

**Issue by jbaker1311** [svenhb/GRBL-Plotter#313]
I've done what you've recommended and now the pen and cutter are working
although in pen "mode" it works fine but when cutting both solenoids are activated.

![G54](https://user-images.githubusercontent.com/83122484/194970744-41e53858-265a-42a4-a159-478188536143.png)
![g55](https://user-images.githubusercontent.com/83122484/194970747-83fc5b3e-0fce-4960-bad7-19232b00b014.png)
![Group](https://user-images.githubusercontent.com/83122484/194970748-dd603424-edb3-48d3-ae57-f0656839ef22.png)
![Spinde](https://user-images.githubusercontent.com/83122484/194970753-c200945b-7b74-4aa8-a25e-f3962b5ba763.png)
![Tool table](https://user-images.githubusercontent.com/83122484/194970757-613d924e-d5df-49e1-88e2-0619993e167b.png)
![Use case](https://user-images.githubusercontent.com/83122484/194970758-a040ccbc-bb29-4545-b87f-4f91762f8938.png)

**Comment by svenhb** [comment]
I think you need to switch off both via "M9", before selecting the new seleonid:
try "G54;M9;M7" and "G55;M9;M8" for your commands.

**Comment by jbaker1311** [comment]
I have done this, I think because my pen is pinned to spindle on/off this is why it's still operating while Mist is activated
I've changed to have pen on flood and cutter on Mist. It's till doing the same thing. Will go over our old thread and reply

**Comment by svenhb** [comment]
I assume you use a servo for the pen-up-down and another servo for the cutter-up-down.
Perhaps you need to switch the pwm-signal to one OR the other servo, using a relais (triggered by the mist-signal)?

**Comment by jbaker1311** [comment]
No I'm using compressed air, with solenoids that run off Mist and Flood signals.
Is there a simple way to keep laser on but independently turn Mist and Flood on and off

**Comment by svenhb** [comment]
>Is there a simple way to keep laser on but independently turn Mist and Flood on and off
Is it possible if you try it manually? Is then working?
http://linuxcnc.org/docs/html/gcode/m-code.html#mcode:m7-m8-m9
M9 - mist and flood off 
M9;M7 only mist
M9;M8 only flood
M7;M8 mist and flood

**Comment by jbaker1311** [comment]
I'll be back at the machine tomorrow, so will give that a crack.
Do I put it in the tool table?

**Comment by jbaker1311** [comment]
I have them working separately now, the next problem I'm encountering is they are no longer going up and down.

**Comment by jbaker1311** [comment]
![image](https://user-images.githubusercontent.com/83122484/195716714-f014be14-e5bd-42fa-8484-c6d3c1ef2417.png)
![image](https://user-images.githubusercontent.com/83122484/195716779-c7204085-6402-456f-95f7-634365f00200.png)
![image](https://user-images.githubusercontent.com/83122484/195716816-4ea1741a-3f1e-48e8-985a-0980540e0379.png)

**Comment by jbaker1311** [comment]
So I've figured out that M3 and M5 are for spindle direction etc.
Not relevant in my situation, I can use M9 to deactivate my solenoids and raise pen. But when i have G55 M8; G54 M7 for pen down, it activates both. I think I need a way to have different commands per each tool.
Maybe an addition to software?
![image](https://user-images.githubusercontent.com/83122484/195739530-69f9926c-9cb7-4548-9836-5e6b168084a2.png)
![image](https://user-images.githubusercontent.com/83122484/195739573-796af243-1159-4226-9737-30748dd01cd7.png)

**Comment by svenhb** [comment]
Perhaps you can describe your mechanics again? I don't get it...
You have a pen, needing "selection" and "up/down"
You have a cutter, needing "selection" and "up/down"
And also a laser?

You could use other hardware / grbl-version: https://github.com/fra589/grbl-Mega-5X/wiki
It has additionally:  Digital output control: M62, M63, M64, M65

**Comment by jbaker1311** [comment]
My machine is a 2d Plotter, I've recommissioned an old industrial plotter made in the late 70's
It's basically an Arduino mega with the mega version of grbl
It has 2 tools that move on a gantry, a static pen and a cutting wheel/blade on a 360° z axis
The tools are air assisted for lifting and compression respectively. Before I gave up on the cutting wheel and just used the pen on the spindle enable and hand cut my job. 
I want use the table to full capacity so I'm trying to sort out the cutting side of it.
Now following our thread I've changed them to Mist/Flood
In the individual commands, I'm using M9 to lift the tool (pen up) then g54 M7: G55 M8 (pen down.) 
I'm asking if there is a command for pen down for a specific tool. E.g. pen down at start, draws, M9 command to lift, then moves to next pos, runs pen down which then runs both commands at once (G54 M7: G55 M8) which makes both tools lower

**Comment by svenhb** [comment]
You need a logic connection of the general up/down signal (M3/M5) and the tool selection (M7/M8).
Tool 1 should be activated via the signals SPINDLE AND MIST
Tool 2 should be activated via the signals SPINDLE AND FLOOD

Perhaps it works with simple diodes:
![image](https://user-images.githubusercontent.com/19973251/195832430-b644695a-22b7-4d35-8f7e-09f9de96e765.png)

But a real circuit would be better (74xx08)

**Comment by jbaker1311** [comment]
I'll have a try at the 5x version of grbl and repin with the new digital toggles. At this stage I don't want to add new hardware

**Comment by jbaker1311** [comment]
I've loaded the 5X version, now I'm not too sure what Command i should be sending to activate

**Comment by jbaker1311** [comment]
Good day Sven,
I've made a breakthrough with my commands problem. Is there a specific way to indicate to the software that I only want a specific tool. 

As it is now, I've repinned to flood and coolant with m9 as a pen up command, and m7/M8 pen down. When paired with G55 M8;G54 M7 it will still activate both at the same time. Although when I go through gcode and delete the specific code that's unwanted it performs perfectly. 

My idea is to somehow tell the gcode creator the when G55 is the tool required to only read that specific pen down command rather than both G55 and G54

**Comment by jbaker1311** [comment]
![image](https://user-images.githubusercontent.com/83122484/197441991-0f1d91f6-2983-4627-841b-505a3680fb5a.png)
![image](https://user-images.githubusercontent.com/83122484/197442020-c6b7f800-c11a-44be-ba07-1d763f46d634.png)
![G54](https://user-images.githubusercontent.com/83122484/197442123-04fe3d04-6940-473a-b3c3-dd3f59cfccd5.png)

**Comment by svenhb** [comment]
You need different pen-up/down commands, depending on selected tool.
Most simple: do a logic AND: (spindle and mist signal) and (spindle and not-mist signal) for the individual tool pen_up/down.
Most complicate: I need to implement individual commands, depending on selected tool-nr. Up to 255 tools possible with 2 states each...

**Comment by svenhb** [comment]
I hope you could manage it with the external logic
