### ISSUE TITLE
dxf line conversion

### ISSUE THREAD

**Issue by lfmmd** [svenhb/GRBL-Plotter#314]
I entered a dxf file dxf file, in the dxf file I used a dashed line when converting gcode he converted it to a solid [line]()
![image](https://user-images.githubusercontent.com/22638264/199137651-36b67a8b-96cd-4d09-82a7-05b1fd7868ce.png)
![image](https://user-images.githubusercontent.com/22638264/199137685-ca080d16-8b1b-4ae7-8c86-db3afea3f898.png)

**Comment by svenhb** [comment]
Sorry it only works for straight lines

**Comment by svenhb** [comment]
I will try to fix that, perhaps you can upload your DXF file?

**Comment by lfmmd** [comment]
@svenhb thank you for your support  I uploaded my dxf file and the reason I speculate is: in dxf the dashed line type is a
 Line description, and some display parameters have been added  
[1.zip](https://github.com/svenhb/GRBL-Plotter/files/9926139/1.zip)

**Comment by svenhb** [comment]
The problem is up to now: I apply the dash pattern to one line segment. If the line segment is shorter than dash-pattern, no pattern is visible. Arcs and circles are converted to many short line segements.
My solution I#M working on: continue the dash pattern over many line-segments.

**Comment by svenhb** [comment]
Try latest release: https://github.com/svenhb/GRBL-Plotter/releases
