### ISSUE TITLE
Camera mount on XY or Z platform "Also scale on rotation not working"

### ISSUE THREAD

**Issue by gorgoi** [svenhb/GRBL-Plotter#315]
Hello svenhb, 

First of all, thanks for your work is a greate software with a lot of potential. 
I tried for several weeks to configure a XY camera with **automatic fiducial correction** and **also scale on rotation**.

I have to cut some plastic that doesn't have constant dimensions.

Problem
-------------------------
When I start **Automatic fiducial correction**, after first red circle recognition,  **enable shape recognition** for second one is deactivated, and then correction doesn't work. 
If I **enable shape recognition** manually rapidly before reaching second one, it see circle and fiducial but scaling/corection  also not working. **Video** attached, down the page.

It's only works for fixed mount camera(example file from you), but my plastic sheets are to large like 600mm to be recoined on fixed camera. 

File:
![Fiducial_file](https://user-images.githubusercontent.com/24373830/202393223-bac84995-9f83-4044-bd03-305818a3c3c7.svg)

Video:
https://user-images.githubusercontent.com/24373830/202392908-b71a33c8-1127-4187-9cc6-72bc3a4eb6c9.mp4

Thanks for your support!

**Comment by svenhb** [comment]
I'm a bit out of the topic and need some time to get used to it again

Did you see this "video" how it should work? https://grbl-plotter.de/data/uploads/pic/plotter_fiducials/fiducial_xy_auto.gif

In your video, there is already a fiducial assined, when starting, you may need to clear this list first (right-click in video-picture):
![image](https://user-images.githubusercontent.com/19973251/202405416-49774f7c-4212-4c62-817a-1bfbf4880047.png)

![image](https://user-images.githubusercontent.com/19973251/202405812-8be51d5c-a9ab-4ff8-8b0c-255f60f1e81e.png)

**Comment by gorgoi** [comment]
Yes, is true. In video, I pressed **Start automatic fiducial correction**, at  second point,  for redo the procedure recognition. 

I will try again tonight and try to capture the screen for a clear view. 

Thanks for your fast replay. It is  a grate help.

**Comment by gorgoi** [comment]
Hello again, 

I've checked again last night, and it seems that the SVG file that I have is not working maybe because it has bigger dimension?, i don't know..

Do you have any limit to **automatic fiducial correction**?... maybe this is the reason. 
Attached I  add it my test. 

**Dimensions:**
![Dimmensions](https://user-images.githubusercontent.com/24373830/202647731-2c1d9c4d-80fb-43a2-acb0-4bd8a9ced757.jpg)

**SVG files_used in videos**
[Files.zip](https://github.com/svenhb/GRBL-Plotter/files/10039167/Files.zip)

**Video my file_NOK**

https://user-images.githubusercontent.com/24373830/202649040-a3f7f39b-bc49-4224-a231-55069f9ee182.mp4



**Video your default file OK**

https://user-images.githubusercontent.com/24373830/202648383-c68cd295-03ba-4b54-8ce8-703529bfeaaa.mp4

**Comment by svenhb** [comment]
Thanks for the detailed information. 
I assume the time, reaching the 2nd fiducial, is too long and a timout happens.
Please check the logfile: look in in the  About box (menu-strip "About") for the data-path, open /logfiles/logfile.txt
If timout happened, an error should be logged: "Fiducial detection: 2, Grbl-Idle not reached" - is this correct?

**Comment by svenhb** [comment]
...but the timeout can't be the reason for clearing the checkbox...
I'm still investigating...

**Comment by gorgoi** [comment]
I was looking at the videos to make a difference, I see  coordinates for  **second fiducial**  picture red  **X:320.00, Y:240.00**   , that looks out of range/ limit..., i don't know what it is.., maybe is has something to do with the problem?... 


**File OK**  (the small one your SVG)seems to be in the range:
1.
![image](https://user-images.githubusercontent.com/24373830/202701353-ac85fde8-d5e0-47f5-8935-47f6fb53067d.png)

2.
![image](https://user-images.githubusercontent.com/24373830/202701184-cab2f89b-8f79-4808-bb4d-963d616e686e.png)

-----------------------------------------------

**File NOK**: seems to be out of range **(picture in RED)**
1.
![image](https://user-images.githubusercontent.com/24373830/202699949-a393ca48-fb21-4b0c-81e9-e0316194ddf2.png)

2. 
doesn't go to next step.


------------------------------------------------
PS: I will check tonight "Please check the logfile: look in in the About box (menu-strip "About") for the data-path, open /logfiles/logfile.txt", when I will be at the computer from home. 

Thanks for your support!

**Comment by svenhb** [comment]
This:
![image](https://user-images.githubusercontent.com/19973251/202709808-e725bd91-a07b-4117-ad02-8cd983a7c570.png)
is the last shown message, before the timeout can occur - unfortunatly I forgot to show a message on this place.

I make a new version, correcting this bug, if you could confirm the error in the logfile

**Comment by svenhb** [comment]
Perhaps you can increase moving speed a lot (just for test) to minimize traveling time and avoid timeout...

**Comment by svenhb** [comment]
I mean G0 feedrate, set via $110 / $111

**Comment by svenhb** [comment]
This checkbox is not needed for the automatic fiducial correction, and will be disabled after the automatic correction.
![image](https://user-images.githubusercontent.com/19973251/202760602-17fbd512-451b-445d-8512-4931f648456c.png)

**Comment by gorgoi** [comment]
Hello, 

Sorry, I'm with the speed at the limit, I can not go forward, it is screw driven. 
I found logs that has been  generated when videos were made, to have the same timeline. Please see:

File **NOK**, first video:
[log_20221117.4_my file_NOK.txt](https://github.com/svenhb/GRBL-Plotter/files/10043498/log_20221117.4_my.file_NOK.txt)

File **OK** scound video:
[log_20221117.5_your file_OK.txt](https://github.com/svenhb/GRBL-Plotter/files/10043501/log_20221117.5_your.file_OK.txt)

Thank you for your time!

**Comment by svenhb** [comment]
I uploaded a new version here: https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_Setup_1_6_7_4_test.exe
I hope bug is fixed.

**Comment by gorgoi** [comment]
Thank you **svenhb**!,  I can confirm that is working. Since I used your test software, I had no problem.
