### ISSUE TITLE
Unble to compile solution

### ISSUE THREAD

**Issue by LeeRossCritchlow** [svenhb/GRBL-Plotter#316]
Screen capture of Errors, Warning, Message.
![Capture](https://user-images.githubusercontent.com/15304861/202923590-8502d992-7676-4e93-be74-b93bbaf1ae10.PNG)

**Comment by LeeRossCritchlow** [comment]
I noticed that I still had vMicro installed. I uninstalled the extension, cleaned solution, rebuild solution. One Error & Warning remained.
![Error-Warning](https://user-images.githubusercontent.com/15304861/202924060-4f13f368-bf2e-4b13-9804-fc6d84d8ae63.PNG)

**Comment by LeeRossCritchlow** [comment]
I cleaned and rebuilt the solution twice. Each time the attached screen capture occurred.
![Error6-Warning](https://user-images.githubusercontent.com/15304861/202924404-dcd55a8b-8299-4f51-ac6f-722db786ab6e.PNG)

**Comment by LeeRossCritchlow** [comment]
ReSharper is reporting 35 errors in 5 files.
![ReSharper Erors](https://user-images.githubusercontent.com/15304861/202924834-d58cd388-9387-4513-ab28-b5591bb3a575.PNG)

**Comment by svenhb** [comment]
Where did you download the source?
I don't have a file "Bootstrapper.cs" and my projects name is GRBL-Plotter

**Comment by svenhb** [comment]
Most probably you try to compile this work: https://github.com/IlyaChernov/grbl-Master/tree/master/grbl.Master.UI
I'm sorry I can't help

**Comment by LeeRossCritchlow** [comment]
The attached Source shows the link on the page shown in Source1.
![Source](https://user-images.githubusercontent.com/15304861/203043044-34dc1124-088c-40a7-b3ff-68d4d9b6422f.PNG)
![Source1](https://user-images.githubusercontent.com/15304861/203043753-581d85bd-69db-40e1-bfb0-dd07896f724d.PNG)

**Comment by svenhb** [comment]
Strange, if I click on the link on this page https://github.com/svenhb/GRBL-Plotter , it opens the corresponding releases-page: https://github.com/svenhb/GRBL-Plotter/releases/tag/v1.6.7.3
And the dowloand of GRBL-Plotter-1.6.7.3.zip shows the correct content.

**Comment by svenhb** [comment]
I think issue-removal is not possible - just closure.
