### ISSUE TITLE
Using Gcode transform-radius compensation does not work correctly.

### ISSUE THREAD

**Issue by Atlan4** [svenhb/GRBL-Plotter#317]
I have a dxf file. after opening the GRBL plotter, I need to generate g code so that the dimensions change when using a 2mm milling cutter (or another size)

using Gcode transform-radius compensation does not work correctly.

As possible, achieve that the generated code has the dimensions of the holes reduced by 1 mm. well thank you

![1](https://user-images.githubusercontent.com/62466726/208170670-4b97f8f4-af14-4c45-a345-aaae30b83105.jpg)
![2](https://user-images.githubusercontent.com/62466726/208170684-50b7c59b-7f53-49cb-933b-6f3097f78ba2.jpg)

**Comment by svenhb** [comment]
You may can upload the original DXF?
I assume the "bad" object consists of not connected lines.
You may try to connect the single lines via GRBL-Plotter by increasing this value in setup:
![image](https://user-images.githubusercontent.com/19973251/208237564-977392de-482a-4d86-8d4b-1a3bbbb577d1.png)

**Comment by Atlan4** [comment]
Yes, your solution worked, even though the lines connected in the eagle field probably had different directions. after redrawing, it already displays normally even without changing the settings. (but it's good that it can be adjusted with the settings, I don't want to redraw it every time)

BUT, as you can see in the picture, the creature cuts from the inside and my special shape from the outside. Is there a solution to this? well thank you
![3](https://user-images.githubusercontent.com/62466726/208242288-37568888-6758-4baf-b36e-4a29e1021930.jpg)
[Panel cnc zadny v1.dxf.txt](https://github.com/svenhb/GRBL-Plotter/files/10251709/Panel.cnc.zadny.v1.dxf.txt)

**Comment by svenhb** [comment]
>the creature cuts from the inside and my special shape from the outside

So the path direction of one is clockwise, from the other counter clockwise. 
If you enable the "Pen-up" path view (press space bar) you see the start direction.
When object is selected, you can reverse the direction - before applying the path offset:
![image](https://user-images.githubusercontent.com/19973251/208246179-bb4fa2cc-13e4-4869-a88b-2d80ee3aa07f.png)

**Comment by Atlan4** [comment]
Thank you, it seems that it will work. I will definitely follow the rules when drawing, if I don't want to fix it later. Thank you again
![4](https://user-images.githubusercontent.com/62466726/208246747-7e0a8683-c7a5-4c92-8267-1f91b100926b.jpg)

**Comment by svenhb** [comment]
Good to hear, that it works now.
