### ISSUE TITLE
The 1.6.8.0 version of the software runs incorrectly, and both the source and release versions have the same problem

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#320]
Click on the menu bar "G-Code Creation">"Creat Text" and an error window will pop up

As shown in the picture below
![image](https://user-images.githubusercontent.com/53146195/211440134-5b6cb3b1-8a7a-415f-9f7b-e5fd89863b44.png)
![image](https://user-images.githubusercontent.com/53146195/211440202-af3cee80-b140-4ab5-a4d8-8eb788d6e42e.png)

**Comment by svenhb** [comment]
Could you save your settings (if needed) and then reset all settings?
Hope this works...

![image](https://user-images.githubusercontent.com/19973251/211471872-12861068-88f5-41f8-9f51-4388bbd08758.png)

![image](https://user-images.githubusercontent.com/19973251/211471891-16edc1ec-62a3-43b0-86ad-a2538a8b6709.png)

**Comment by lianzaozi** [comment]
I followed the method you said, but the same error window still appeared

**Comment by svenhb** [comment]
Do you use "original" windows? Or some workarround and other OS?
The problem is: the initial font is set in the properties and properly not known by your OS:
```
    <Setting Name="createTextSystemFont" Type="System.Drawing.Font" Scope="User">
      <Value Profile="(Default)">Microsoft Sans Serif, 12pt</Value>
    </Setting>

```
You could try to close GRBL-Plotter, edit user.config manually (and set a known font)  and start again.
Location is somwhere C:\User\name\AppData\Local\GRBL-Plotter\....\1.6.8.0\user.config

**Comment by svenhb** [comment]
If you compile by your own, try this (not tested) bug-fix: https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter/GCodeCreation/CreateFromForm/GCodeFromText.cs

**Comment by lianzaozi** [comment]
After compiling with the new code you uploaded, error Windows will still pop up during testing

![image](https://user-images.githubusercontent.com/53146195/211499141-6a6519cf-1689-4053-989b-236c5d031932.png)

**Comment by svenhb** [comment]
Thanks for testing. 
Could you check the logfile for an error-entry?

**Comment by svenhb** [comment]
Hm strange. It doesn't show the expected output:
When opening the form, it should log the font.
And because of error-handling, the error should not pop-up, instead also an error-log should appear...
Like:
```
2023-01-10 17:22:31.4701 | Info  | GrblPlotter.GCodeFromText      |  TextForm_Load initFont:'
2023-01-10 17:22:31.4701 | Info  | GrblPlotter.GCodeFromText      |  TextForm_Load textFont:'
2023-01-10 17:23:31.4701 | Error  | GrblPlotter.GCodeFromText      |  ShowTextSize textFont.Name:'
```

**Comment by svenhb** [comment]
Try new release: https://github.com/svenhb/GRBL-Plotter/releases

**Comment by svenhb** [comment]
No feedback, bug is gone?
