### ISSUE TITLE
Scan Y, extrude X feature using workpiece -> surface scan

### ISSUE THREAD

**Issue by SamuelPascal** [svenhb/GRBL-Plotter#324]
**Describe the bug**
While checking "Scan Y, extrude X" program sends only one line to scan, like nothing else should be checked, resulting in 1-dimensional scan

**To Reproduce**
1. Upload orbitrary g-code
2. Click on 'workpiece', then 'Surface scan/ Height map'
3. Set dimensions to scan to be at least 2x2 matrix
4. Check 'Prove one axis, extrude other' flag and then 'Scan Y, extrude X'.
5. See that it scans only left line from bottom to top.

**Expected behavior**
Scan the surface just like using 'Scan x, extrude Y' option (all the points that programm shows on the screen) 

**Screenshots**
1. Scan starts:
![image](https://user-images.githubusercontent.com/109026770/219445508-2f80e0d3-2fd5-4353-8281-b12b6f3b9b3a.png)
2. Scan ends:
![image](https://user-images.githubusercontent.com/109026770/219446070-f63baa2f-7a6d-4fe3-b981-72441d69b0fd.png)

Expected output:
![image](https://user-images.githubusercontent.com/109026770/219446351-ccd4ef80-45c7-4449-997c-e78cd59a6bd4.png)

Version: 1.6.8.4 2023-01-30

**Comment by svenhb** [comment]
For me the result looks correct:
You selected "Probe one axis (Y) and extrude the other (X)", which means, for one Y-coordinate all X-coordinates will get the same Z value...
![image](https://user-images.githubusercontent.com/19973251/219577583-f99215a2-8060-4c5e-92af-2eec02887046.png)

**Comment by SamuelPascal** [comment]
Oh, so that option only means that it scans one line and a resulting map is just "extruded" line?
I thought, there is an option to select which axis to move and probe **first** and which axis to add a step **after 1 line is scanned**. (I remebmered that in older versions second option "Scan Y, extrude X" caused to program crash..)

I really need this, as one of my axes is very poor quality and has a huge backlash.

**Comment by svenhb** [comment]
I added an option to switch scan direction: https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_1_6_8_5_Setup.exe

![image](https://user-images.githubusercontent.com/19973251/220066214-aca70af0-9ab6-425a-a79b-11f42c1f7635.png)

**Comment by svenhb** [comment]
No response, seems to work

**Comment by SamuelPascal** [comment]
Sorry, I haven't received your message in time. Thank you a lot! 
I will test that feature after I'll re-assemble my cnc).
