### ISSUE TITLE
probing tool length

### ISSUE THREAD

**Issue by Atlan4** [svenhb/GRBL-Plotter#326]
Hi. If I choose the option of searching for the center of the hole, Z is not active (grey), that's fine. However, when I changed the x or y coordinates, item Z is active. (not gray) Is it supposed to be like that, or is it a mistake? in 1690
![ok v1](https://user-images.githubusercontent.com/62466726/225336424-5f37304d-8230-4c67-bafc-ef6209ed4d85.png)
![not ok v1](https://user-images.githubusercontent.com/62466726/225336858-cc834b1b-4847-493b-87c8-6734970ff651.png)

**Comment by svenhb** [comment]
>Is it supposed to be like that, or is it a mistake? 

It's a mistake.

**Comment by svenhb** [comment]
Check new release: https://github.com/svenhb/GRBL-Plotter/releases
