### ISSUE TITLE
MainFormThreadexception in version 1.6.9.2

### ISSUE THREAD

**Issue by kjk25** [svenhb/GRBL-Plotter#334]
I load the gcode, let it run.
then get the message, the program must be closed.

![grafik](https://user-images.githubusercontent.com/8419193/230559714-bdd30e5f-a61f-454b-946d-defcf109485a.png)
![grafik](https://user-images.githubusercontent.com/8419193/230560149-b7d34d5c-f6d4-42db-8389-7cbe230552de.png)

[testCAM.zip](https://github.com/svenhb/GRBL-Plotter/files/11176832/testCAM.zip)

**Comment by svenhb** [comment]
Too bad...
The error occurs because of the 2nd line "( CopperCAM - 23/03/2023 / ISO-Mill Output )"

Check new release for bug fix: https://github.com/svenhb/GRBL-Plotter/releases
