### ISSUE TITLE
Toolchange Feature

### ISSUE THREAD

**Issue by kjk25** [svenhb/GRBL-Plotter#335]
moved this request to this new issue, sorry for confusion.

i use Version 1.6.9.3

perhaps you can create a checkmark for use Toolset yes,no in settings, 
if you like to use your tools set with all parameters for the toolchange or display only the comment.

i would like to use your toolset when a Tx Mx is recognized with a dialg to change to Tool Nr..xxx

G21 G40 G54
G80 G90 G94
( Werkzeug Nr. 1 "Universalfraeser 0.2mm" / Durchmesser 0.2 mm )
T1 M06
M03 S32
G00 Z1
G00 X49.936 Y19.329
G01 F180 Z-1.2

![grafik](https://user-images.githubusercontent.com/8419193/230568900-39470a4d-f917-4185-85d3-967a04f7c014.png)

but i can't execute the toolchange script, where i move to toolchange position 
what is on my machine x0,y0,z1
would be cool to have the flexibility to use still scripts

![grafik](https://user-images.githubusercontent.com/8419193/230566699-d9e5a6ff-f3bd-4f02-892c-c64e3b9dee32.png)

all the best
Kai

_Originally posted by @kjk25 in https://github.com/svenhb/GRBL-Plotter/issues/332#issuecomment-1500050182_

**Comment by svenhb** [comment]
If you use the same toolchange position for each tool, this option is for you:
It processes the given  code on pause during streaming...
![image](https://user-images.githubusercontent.com/19973251/230763569-91194f89-1be6-4819-b2d1-8f117134bfe5.png)

**Comment by kjk25** [comment]
yes this works for me, i use "G0 Z10 X0 Y0 M0 M5 M9;" for the Toolchange command

i have one issue, when the the dialog is shown and i press continue streaming the dialog disapear like expacted.
but then i have a second press for resume.
is this wanted?

please a hint how to move to a park position after project wars fonished.

best wishes
Kai

**Comment by svenhb** [comment]
>please a hint how to move to a park position after project wars fonished.

Just place your code here:
![image](https://user-images.githubusercontent.com/19973251/232289786-0768449d-2f30-4e6a-98e5-36e358e52219.png)

**Comment by svenhb** [comment]
>i have one issue, when the the dialog is shown and i press continue streaming...

You should remove the M0 (pause a running program) from your Toolchange command - the system is already in pause mode...

**Comment by kjk25** [comment]
i use now G28.1 and G28 to move to toolchange otherwise 
if i move the project position 0,0 to a different location it moves to that coordinate.
thank you for all your help.
Kai

**Comment by svenhb** [comment]
👍 Good idea, I was wasn't thinking about predefined positions.
https://grbl-plotter.de/index.php?id=form-coordinates
