### ISSUE TITLE
load tools from filesystem

### ISSUE THREAD

**Issue by kjk25** [svenhb/GRBL-Plotter#336]
like to load Toolset from my Filesystem from a Folder where my Machine Settings for the GBRL-Plotter are secure stored.

otherwise i have to copy my toolset to the Tools directory
![grafik](https://user-images.githubusercontent.com/8419193/232280379-e9ba38b8-5dda-4bd6-ae6d-c90e8ce23e86.png)

**Comment by svenhb** [comment]
It's now implemented: https://github.com/svenhb/GRBL-Plotter/releases
