### ISSUE TITLE
When VisualStudio is used to compile the source code version 1.6.9.3, an error occurs

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#337]
The screenshot of the error is as follows
![1](https://user-images.githubusercontent.com/53146195/232363767-8a5b1646-655f-4c3e-9be0-9a0bd940745e.png)

**Comment by svenhb** [comment]
Strange, was not planned to use it. Will try to get rid off it.
Attached the folder I found in my package folder...
[Microsoft.CodeAnalysis.FxCopAnalyzers.2.9.7.zip](https://github.com/svenhb/GRBL-Plotter/files/11246554/Microsoft.CodeAnalysis.FxCopAnalyzers.2.9.7.zip)
