### ISSUE TITLE
Probe one axis issue.

### ISSUE THREAD

**Issue by ScottEgan** [svenhb/GRBL-Plotter#339]
**Describe the bug**
When probing just one axis using the "Probe one axis, extrude other" function, Scanning along the X axis works fine, and the X dimension increments after each probe. Unfortunately scanning along the Y-axis doesn't work and the tool just stays in one position. This can be seen in the output tab gcode as well. Also in English, I think this function should say "Probe one axis, **_exclude_** other" rather than **_extrude_**.

**To Reproduce**
1. Go to Workpiece > Surface Scan / Height Map
2. Click on the "Area to scan" tab
3. Select the "Probe one axis, extrude other" check box
4. Select the "Scan Y, extrude X" radio box
5. Click "Generate Height Map" at bottom of screen
6. Click the "Output" tab and review the gcode

**Expected behavior**
When scanning along X you can see in the gcode that after each probe command Z will move back up and the X position will increment. This does not happen when scanning along the Y axis.

Scan X gcode snip:
```
(Probing Size X:36 Y:26 )ExtrudeY scan X axis, extrude in Y
Code sent
G90F600
G0Z2
G0Y0
G0Z2
G0X0
G38.3Z-5
G0Z2
G0X20
G38.3Z-5
G0Z2
G0X40
G38.3Z-5
G0Z2
G0X60
G38.3Z-5
G0Z2
G0X80
G38.3Z-5
G0Z2
G0X100
```

Scan Y gcode snip:
```
(Probing Size X:36 Y:26 )ExtrudeX scan Y axis, extrude in X
Code sent
G90F600
G0Z2
G0X0
G0Z2
G0X0
G38.3Z-5
G0Z2
G0X0
G38.3Z-5
G0Z2
G0X0
G38.3Z-5
G0Z2
G0X0
G38.3Z-5
G0Z2
G0X0
```

**Screenshots**
Correct behavior on Scan X
![image](https://user-images.githubusercontent.com/6709827/236733581-7a89cb9b-bae3-4851-a18b-36627a66a721.png)

Incorrect behavior on Scan Y
![image](https://user-images.githubusercontent.com/6709827/236733468-17f99b24-be47-4171-97a4-7b31b28c1330.png)
![image](https://user-images.githubusercontent.com/6709827/236733517-64307e6e-71be-4dc7-b80e-0c6f92a52101.png)

**Comment by svenhb** [comment]
Thanks for the feedback. I made a mistake during code-simplification and forgot to seperate the X and Y axis.
About naming this function: I thought about CAD, generating a 3D model from a 2D scetch -> extrude. Here, 2D data is generated from a 1D scan.

**Comment by ScottEgan** [comment]
Thank you for the quick response!

>About naming this function: I thought about CAD, generating a 3D model from a 2D sketch -> extrude. Here, 2D data is generated from a 1D scan.

Ahh ok. I didn't think about it that way but it makes sense now. Thank you for explaining.

**Comment by svenhb** [comment]
You may try this bug fix version: https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_Setup.exe
Closing this issue happend automatically after uploading the setup.exe...

**Comment by ScottEgan** [comment]
Seems to still behave the same.
![image](https://github.com/svenhb/GRBL-Plotter/assets/6709827/3272b321-239c-408a-8213-0adadef8585c)

**Comment by svenhb** [comment]
Ok, thanks for testing. 
I thought I found the mistake as it was so obvious, without testing...

**Comment by ScottEgan** [comment]
No worries, I don't mind running the tests.

**Comment by svenhb** [comment]
Now it is fixed: https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_Setup.exe

**Comment by ScottEgan** [comment]
Sorry for the late reply, I finally got around to testing.
Works as expected now! Thank you!
We can close

![image](https://github.com/svenhb/GRBL-Plotter/assets/6709827/2c887e15-3805-49fe-a0d1-df0ed2187220)
