### ISSUE TITLE
DIYcontrol port, immediate commands are not supported

### ISSUE THREAD

**Issue by deHarro** [svenhb/GRBL-Plotter#34]
To support jogging with dedicated joystick hardware according to "GRBL V1.1 Jogging" via this second DIYcontrol port, the handling of immediate commands has to be supported.

This implies:
- The receiving thread in GRBL-Plotter has to accept single characters over the serial port
- GRBL-Plotter _must not_ wait for CR LF to treat the received character
- Instead, GRBL-Plotter has to accept every single character on this port when it arrives and forward it immediately to GRBL on the CNC port.

Besides that, to prevent accidental forwarding of jog commands, GRBL-Plotter has to block input on the DIYcontrol port as long as a CNC job is running.
I suppose, that is already guaranteed since there is the "virtual joystick" in GRBL-Plotter.

**Comment by svenhb** [comment]
I will implement somthing like this:
receiving char by char, filtering char > 0x7F -> send real time command, or collect further chars until /r/n is reached, then send by regular function.

**Comment by deHarro** [comment]
Might work, lets see how it performs... :-)
Thanks!

**Comment by svenhb** [comment]
Try test version https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_1202_test.zip
were I implemented my suggestion. Could not test real time commands, because no hardware which can send, I hope it works.

**Comment by deHarro** [comment]
Something went wrong :(
You double every Jog command and GRBL doesn't understand that.

![grafik](https://user-images.githubusercontent.com/26298406/45136229-6f4e7b00-b1a3-11e8-8746-0c0733afa14f.png)

![grafik](https://user-images.githubusercontent.com/26298406/45136326-c48a8c80-b1a3-11e8-804c-46eb1510a1dd.png)

Coordinates in GRBL-Plotter dont change.

It's not clear, whether the realtime command is forwarded to GRBL or not.

(You said, you have a spare Arduino. Are you willing to buy a [joystick ](https://www.ebay.de/itm/JoyStick-Breakout-Module-PS2-Joystick-Game-Controller-for-Arduino/201380684238)at ebay?
If so, I happily send you the sources of my joystick controller for testing.
But we can try debugging together, no problem)

**Comment by deHarro** [comment]
This is my test equipment at the development computer:
![2018-09-06_img_4861](https://user-images.githubusercontent.com/26298406/45136778-f69cee00-b1a5-11e8-8635-48d7287950fa.jpg)

![2018-09-06_img_4862](https://user-images.githubusercontent.com/26298406/45136780-fa307500-b1a5-11e8-8fd0-ef16913b8f04.jpg)

The right Arduino has one stepper on the X axis to get the feeling when stepping, since one is fooled by the changing numbers in the different applications I use when developing, sometimes.

The left Arduino runs the joystick firmware, I can control X and Y, Z is fixed centered in software.
If necessary I can attach one button, the thumb joystick features a NO switch by pressing the knob.

**Comment by svenhb** [comment]
But realtime command works?

**Comment by deHarro** [comment]
As I wrote, I cannot verify that.
To proofe the functionality, GRBL-Plotter and GRBL have to execute the jog commands and _then_ the jog-cancel can cut in and stop the motion underway.

As long as the jog commands are not forwarded correctly... no chance to test. Sorry.

**Comment by svenhb** [comment]
Try new version, hope it works as expected: https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_1203_test.zip
Perhaps have a look to issue #27, #29, #30, #31, #33,

**Comment by deHarro** [comment]
Sorry, same effect as before:

![grafik](https://user-images.githubusercontent.com/26298406/45171271-40b3bd00-b202-11e8-8fa5-51bf6aff0704.png)

**Comment by svenhb** [comment]
Aber jetzt: https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_1204_test.zip

**Comment by deHarro** [comment]
Ok, one step beyond :+1: :-)
The jog commands are forwarded perfectly now.

But how sure are you, that 0x85 chars are transmitted asynchronously and bypassing the already sampled strings (or string parts)?

As far as I can judge from my seeings, this part of the job has potential... will say: That doesn't perform well.

I just fed some seconds of very small and slow but following sequently fast movements  into GRBL-Plotter, the stepper motor follows.
Fine so far.  
(Explanation: "very small": X=1 mm, "slow": F=84, "following fast": every 10 ms)

Then I released the joystick, what should issue the jog-abort commmand (0x85). 
But the stepper happily moved on for around half a minute or so, before the somewhat faster movement came to GRBL.
I even changed rotation direction for some time. This reached my motor after around a minute or so.

This leads me to assumption that the abort command is **not** forwarded passing by the already sampled jog commands.

I try to manage to visualize the characters from my joystick to GRBL-Plotter on the fly...

**Comment by deHarro** [comment]
Ok, got a serial port spy up and running...
I send consecutive jog commands and when releasing the knob of the joystick, one or two 0x85 are issued:

![grafik](https://user-images.githubusercontent.com/26298406/45205440-6ed8e180-b282-11e8-9e6e-34c1d0ce5c81.png)

So far I'm confident, that the culprit lies somewhere in GRBL-Plotter.

Perhaps you managed to deal all well on the listening port from the joystick, but forgot to handle the bypassing on the sending port to GRBL?

**Comment by svenhb** [comment]
I need to check this evening...
>But how sure are you, that 0x85 chars are transmitted asynchronously and bypassing the already ampled strings (or string parts)?
At least the 0x85 are shown in the DIY-control window, with explanation text?

**Comment by deHarro** [comment]
Hi Sven,
is "At least the 0x85 are shown in the DIY-control window, with explanation text?" in the comment above a question from you to me?

If so, no, I do not see any "0x85 with explanation" in the DIY window.

Here is what I get:

![grafik](https://user-images.githubusercontent.com/26298406/45207531-7ef3bf80-b288-11e8-84e5-c76f91565ad0.png)

This is directly after closing/opening both ports (to clear the windows) and performing a short positive X move with the joystick.

Now again a short move in positive X:

![grafik](https://user-images.githubusercontent.com/26298406/45207608-b1052180-b288-11e8-9604-db90088dc421.png)

You see, there is a "?" in front of the first jog command of this second move.
And you see, this "?" is echoed to GRBL _in front of the next jog command_ to GRBL, too! (You can count the jog commands in both pictures to verify this)

**Comment by svenhb** [comment]
I mean your post 2hours ago: "I send consecutive jog commands and when releasing the knob of the joystick, one or two 0x85 are issued"
When you send 0x85 do see it in the DIY-control window?

**Comment by deHarro** [comment]
No, I see only my jog commands and those "?" characters.

**Comment by svenhb** [comment]
The '?' characters matches with your Jog-Stop command?

**Comment by deHarro** [comment]
I would say yes.

**Comment by svenhb** [comment]
New try: https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_1205_test.zip

**Comment by deHarro** [comment]
Hi Sven,
no "?" any more in the in-/output, you now issue a "0x3F Status Report Query" in both log windows.

Hopefully this leads us to a solution, but just now the jog commands are still not cancelled.

0x3F is not what I send, I send 0x85 (actually I use "Serial.write(133);" in my code).

So, where does this 0x3F Status Report Query come from?

**Comment by svenhb** [comment]
Try to send another realtime command below 0x85, like '!' or '~'. What happens then? Perhaps you need to enable your 7th bit to send? (I know doesn't match with 0x85 <-> 0x3F)

**Comment by svenhb** [comment]
Possible real time comands I forward as real time command, (in addition to >0x7F)  are 0x18, '?', '~', '!'

**Comment by deHarro** [comment]
Ok, I will try first with "!"

**Comment by svenhb** [comment]
ok, now I convert unicode to byte - hope is now reading correct values: https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_1206_test.zip

**Comment by deHarro** [comment]
I'm sorry, still 0x3F

![grafik](https://user-images.githubusercontent.com/26298406/45230868-92c01580-b2ca-11e8-9128-3f2e1580e24a.png)

**Comment by deHarro** [comment]
Hi Sven,
did you encounter the following source:
[SerialPort Encoding](https://blogs.msdn.microsoft.com/bclteam/2006/05/26/serialport-encoding-ryan-byington/)

In short: "You have two options; one would be to use the **API’s that deal with byte[] and bypass the Encoding**, or to use the correct Encoding. However finding the correct encoding is a bit tricky..."

**Comment by svenhb** [comment]
No, i didn't know, I will check.
I started with the function "serialPort.ReadTo("\r\n");" which is used in the other serial-windows. But with this I can't filter the real time command. Then I switched to "serialPort.ReadExisting()" (returning a string) but, as we figured out, chars above 0x7F are a problem. 
Next try is "SerialPort.Read" which fills a byte-array. I hope this solves the problem (tomorrow).

**Comment by svenhb** [comment]
Tried "SerialPort.Read": https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_1207_test.zip
Hope is fixed now...

**Comment by deHarro** [comment]
Hi Sven,
I think, we are nearly through :-) 

![grafik](https://user-images.githubusercontent.com/26298406/45254197-96a87200-b374-11e8-86f4-727621daae81.png)

Your port now recognizes characters greater than 0x7F and forwards them to GRBL (as far as I interprete the output of both listboxes).

Only GRBL doesn't stop immediately but continues to move til the end of the issued jog commands.

So I think, now you have to look at the sending side aimed at GRBL.
Perhaps you have to flush (or delete) the output queue instantly after fordwarding the 0x85 to GRBL?

**Comment by svenhb** [comment]
Too bad... I found also another problem: jogging during pause of a stream doesn't work anymore...
You could follow this, to avoid sending too much jog-commands: https://github.com/gnea/grbl/wiki/Grbl-v1.1-Jogging#how-to-compute-incremental-distances

**Comment by svenhb** [comment]
Problem solved, 0x85 will also clear my internal buffer
https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_1208_test.zip

**Comment by deHarro** [comment]
Hi Sven,
seems to work flawlessly, very fine!

I'm on implementing the math for step size, speed and proper command frequency according the joystick throw. Hope the AtMega is fast enough...

**Comment by papillion47** [comment]
Ben acemi bir CNC ve GRBL kullanıcısıyım. İlk başta bana önerilen linkten GRBL yi yükledim. Ve wiki sayfalarından öğrenerek tüm ayarları doğru şekilde yaptım. Vectric Aspire de hazırladığım tap uzantılı işlerimi gayet sağlıklı olarak birkaç yıldır yapmaktaydım. Geçenlerde ne olduysa visualizer ve heightmap çalışmamaya, ekranda hiçbir şey göstermemeye başladı. GRBL yi defalarca silip yeniden yüklemek fayda etmedi. İnternetten bularak GRBL benzeri olan Candle programı yükledim. o zaman da visualizer çalıştı fakat bu defa manuel kumanda ettiren jog komutları aktif olmadı. O komutları kullanmadan gereken spindle yeri ayarları yapılamıyor. Bu konuda bir yardımı olacak çıkarsa çok mutlu olacağım. Aşağıda son ayarlanan durum ekranımı veriyorum. Teşekkürlerimle..
![candle ekranı](https://github.com/user-attachments/assets/5001c1d3-616b-4b80-a6e5-338bae4451f1)

**Comment by svenhb** [comment]
What do you get if you enable "Show real time status report", before connecting the controller?
Should look like this:
![image](https://github.com/user-attachments/assets/c2bf4725-3a9e-4700-9b68-79d3d20c0ad8)

**Comment by papillion47** [comment]
Benim grbl de böyle bir seçenek yok.

**Comment by svenhb** [comment]
You should use latest release of GRBL-Plotter: https://github.com/svenhb/GRBL-Plotter/releases
