### ISSUE TITLE
Source code issues with version 1.6.9.4

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#341]
Click G-Code Creation=>Create Text. The following error message is displayed:"Object reference not set to an instance of an object"

![image](https://github.com/svenhb/GRBL-Plotter/assets/53146195/c47322fd-b42f-4b7d-b758-221950de5375)

![1](https://github.com/svenhb/GRBL-Plotter/assets/53146195/5966d655-1d6a-443d-ac91-3eca971ec40e)

**Comment by svenhb** [comment]
Did you install a new font, without closing and opening GRBL-Plotter?

**Comment by svenhb** [comment]
No idea. Just run the program without debugger....

**Comment by lianzaozi** [comment]
> 不知道。只需在没有调试器的情况下运行程序....

Run file path "bin\Debug\GRBL-Plotter.exe" separately; Nothing unusual appears.

I can't figure out why this problem happened

**Comment by svenhb** [comment]
I think it the usual behavior with debugger:
Inside the "try"-branch the error occurs, the debugger tells you this. After "Continue" the program continue in the "catch"-branch.
