### ISSUE TITLE
Error reading.plt file

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#343]
Error reading.plt file

The left is read by plotter software, and the right is read by other software

![1](https://github.com/svenhb/GRBL-Plotter/assets/53146195/97506243-2b94-419e-9e0f-cf9d3ed4adcd)

![2](https://github.com/svenhb/GRBL-Plotter/assets/53146195/28373e51-1914-4c37-87f1-523e14594a04)

Second other software read
![10](https://github.com/svenhb/GRBL-Plotter/assets/53146195/f96f16c2-fbfa-49d6-b68f-d7448b2ed2df)

![11](https://github.com/svenhb/GRBL-Plotter/assets/53146195/fc1b1d16-65a6-4153-939c-448b25006609)

Test software and test files

[test software and test file.zip](https://github.com/svenhb/GRBL-Plotter/files/11944063/test.software.and.test.file.zip)

**Comment by svenhb** [comment]
I fixed it and also added arc and text import, so your example 'HPGL Example.PLT' also looks almost correct.
Just replace this file:
https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter/GCodeCreation/ImportFromFile/GCodeFromHpgl.cs

**Comment by lianzaozi** [comment]
> I fixed it and also added arc and text import, so your example 'HPGL Example.PLT' also looks almost correct. Just replace this file: https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter/GCodeCreation/ImportFromFile/GCodeFromHpgl.cs

Thank you very much for your work. I have tested it and there are still some small problems
[test file and test screenshot.zip](https://github.com/svenhb/GRBL-Plotter/files/11973494/test.file.and.test.screenshot.zip)

**Comment by svenhb** [comment]
Most of your new files are not matching HPGL standards  E.g. 

- line-terminator  ";" is missing, 
- number-seperator is "." not " " or ","
- unkown commands (like VS, WU, PW), which are not listed here: https://www.isoplotec.co.jp/HPGL/eHPGL.htm

I will try to import them anyway...

**Comment by lianzaozi** [comment]
First of all, thanks for your reply. These.PLT files are automatically generated using software and may not fully conform to the standard plt format. Can you make an option to let the user decide whether to read non-standard.PLT files?

**Comment by lianzaozi** [comment]
I have found a standard explanation book about.PLT format. I have this material, but it is not in English. I can upload it if you need. At the same time I also found this book English link https://dl.acm.org/doi/book/10.5555/523000
![image](https://github.com/svenhb/GRBL-Plotter/assets/53146195/a00b5273-9c1f-4a3b-9869-b90cd176db34)

https://www.amazon.com/exec/obidos/ASIN/0201310147/acmorg-20

**Comment by lianzaozi** [comment]
![image](https://github.com/svenhb/GRBL-Plotter/assets/53146195/c6286413-3ebe-4411-8f4d-ddf3b9913c5c)

The hp website recommends developing based on this book
https://support.hp.com/ca-en/document/c01121263

**Comment by lianzaozi** [comment]
> First of all, thanks for your reply. These.PLT files are automatically generated using software and may not fully conform to the standard plt format. Can you make an option to let the user decide whether to read non-standard.PLT files?

Book <The HP-GL/2 and HP RTL Reference Guide: A Handbook for Program Developers> An explanation of what you said about unknown commands
VS, speed selection
PW, brush width
WU, brush width unit selection

**Comment by svenhb** [comment]
Thanks to point me to this manual: https://people.wou.edu/~soukupm/HPGL2-RTL_ReferenceGuide.pdf

>Can you make an option to let the user decide whether to read non-standard.PLT files?

I will try automatic recognition

**Comment by svenhb** [comment]
It works with your sample-files: https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter/GCodeCreation/ImportFromFile/GCodeFromHpgl.cs

**Comment by lianzaozi** [comment]
Thank you very much for your work.
At present, it seems that the software works very well after the change, and I will conduct more tests.

**Comment by lianzaozi** [comment]
What do these two buttons do?

![111](https://github.com/svenhb/GRBL-Plotter/assets/53146195/5a47b74b-1d58-472e-b968-b6729128d350)
![222](https://github.com/svenhb/GRBL-Plotter/assets/53146195/550d9806-9fae-4f33-8767-236236dd51e3)

**Comment by svenhb** [comment]
During "Import vector graphic", the graphic file will be read and imported, then the importet path will be processed according selected options. Some options like "sort by distance and merge paths", hatch fill, grouping, tiling, take a lot of time.

"Process graphic objects" appears when reading and displaying the G-Code. Collecting the grouped data (XML tags), Creating the graphics-paths to display,...

**Comment by lianzaozi** [comment]
I think this issue should have been fixed, and no problems were found through my other tests.
