### ISSUE TITLE
Could you add a conveyor specification on x axis ? 

### ISSUE THREAD

**Issue by raercan** [svenhb/GRBL-Plotter#346]
Hello . 
I want to feed that plotter with paper rolls . if is it possible please add that option . may be you need a encoder for spliting each paging . or page feeding .  thank you .

**Comment by svenhb** [comment]
This should already work.
How does your conveyor look like?
I would use a 4th axis to pull the paper from the roll. As "GCode Footer" you may add e.g. "A100" to pull 100 mm from the roll.
Also you could use tiling - just on one axis, which also allows you to add code after each tile: https://grbl-plotter.de/index.php?id=form-setup-1#clipping

**Comment by svenhb** [comment]
Any success?
