### ISSUE TITLE
Xloader doesn't open

### ISSUE THREAD

**Issue by gibrie** [svenhb/GRBL-Plotter#350]
Downloaded GRBL-Plotter from github and unzipped. Downloaded XLoader  und unzipped. If I want to open XLoader.exe as described in GRBL-Plotter.de to select the desired .hex file XLoader doesn't open. Any suggestions?

**Comment by svenhb** [comment]
Do you have all Xloader-files in one folder and started the .exe?
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/d702794d-7188-48b2-8397-db44f1d85227)

Which windows version do you use?

**Comment by gibrie** [comment]
I work with Windows 11, all XLoader files are present in one folder (src) but what I see is that XLoader doend’t show the .exe extension.

My download unzippen shows: 
- GRBL-Plotter-1.7.0.2 containing 4 file directories and 11 various sub files
- xLoader-master-> xloader-master-> files ‘images’ +’src’ + ‘license’ + readme.md’; ‘src’ is as in your overview without the .exe-extension at the ‘XLoader’.

I will start the download over to see if the extendsion appears. Can you exactly mention the right site for the XLoader download?

**Comment by svenhb** [comment]
After installation with the regular setup (https://github.com/svenhb/GRBL-Plotter/releases), you should get this folders:
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/108a1031-8f4b-49c7-af85-a75e5b3943ae)
I didn't upload the Xload.exe to my github, I just added to the setup.exe

**Comment by gibrie** [comment]
This is the site I downloaded from and got GRBL-Plotter-1.7.0.2; xLoader has been downloade separately. GRBL-Plotter shows this: 
![Schermafbeelding 2023-08-22 133837](https://github.com/svenhb/GRBL-Plotter/assets/61624015/c05c9144-bb1f-4f4c-9b57-a311ac38c938)
Firmware and GRBL-Plotter are separated, Firmware only containes the .hex-files.

**Comment by svenhb** [comment]
Here is also a source: https://github.com/binaryupdates/xLoader
You need to have all files in one folder

**Comment by svenhb** [comment]
And I mentioned this setup-file: https://github.com/svenhb/GRBL-Plotter/releases/download/v1.7.0.2/GRBL-Plotter_Setup.exe

**Comment by gibrie** [comment]
The pop up screen of the xLoader works for now. Do you want me to enter the file in the firmware aside the hex files or do I leave them apart?
The set-up file of the GRBL plotter succeeded as well and got the short cut on my screen. So far so good!

**Comment by svenhb** [comment]
You need to click on the "..." button and select the desired firmware file:
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/fb2cf506-6819-48b3-9f3e-33ee42b8f5e2)
like
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/0ef6d1b4-29ba-4c58-bf19-3c3509088b22)

**Comment by gibrie** [comment]
I got started with the right sites for the downloads I needed. I am on the right track and going to connect my plotter to do a try-out. Thanks a lot for your support! Excellent job!

**Comment by svenhb** [comment]
Thanks for your question, so I updated my website a little bit. Hopefully the description is a little bit more clear now.
