### ISSUE TITLE
The plotter software version V1.7.0.2 has a bug when reading dxf files

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#353]
Version V1.7.0.2 of the plotter software encountered a bug when reading dxf files, which is not present in version 1.6.6.6 of the grbl plotter

![image](https://github.com/svenhb/GRBL-Plotter/assets/53146195/3ae9fb4f-134b-49e9-88bc-cded8bdddab5)

![image](https://github.com/svenhb/GRBL-Plotter/assets/53146195/3d13b51b-c184-49be-9be3-c30e3c7d3fc5)

The dxf file I used for testing
The dxf file used for testing can be read by the plotter software version 1.6.6.6
[Drawing1.zip](https://github.com/svenhb/GRBL-Plotter/files/12472375/Drawing1.zip)

**Comment by svenhb** [comment]
I don't get the error, what are your settings here:
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/c3a78f84-12ba-4714-92b4-fd71f6846fe1)

**Comment by lianzaozi** [comment]
![image](https://github.com/svenhb/GRBL-Plotter/assets/53146195/74c32181-1702-4b6c-afb6-d2a34e1f3e93)

**Comment by svenhb** [comment]
Can you try with 1.00? As smaller this value as more code lines will be generated. How much RAM does your computer have?

**Comment by svenhb** [comment]
I don't know which other options you did enable:
With the settings above a Gcode Arc move should be generated for the circles 
(e.g. `G02 X347.773 Y510.817 I-158.000 J0.000  F800`   ).
But I assume instead the circles will be drawn by line segments. For example your "Drawing1.dxf":

1. With Arc move - ca. 100 lines
2. With "Avoid G2/3" and 1.00 "Step width" and "Remove very short moves <" 0.1 - ca. 2000 lines
3. With "Avoid G2/3" and 1.00 "Step width" and "Remove very short moves <" disabled - ca. 3300 lines
4. With "Avoid G2/3" and 0.01 "Step width" and "Remove very short moves <" disabled - ca. 327000 lines

Note: version 4 with "Remove very short moves <" 0.1 also generates 327000 objects inernally...

**Comment by lianzaozi** [comment]
Setting this parameter to 1 will not result in a read failure. My computer's memory is 16GB

**Comment by svenhb** [comment]
To avoid generating unnecessary data, I will limit the minimum "Step with" (internally) to the value given by "Remove very short moves" (if enabled).

**Comment by svenhb** [comment]
Try this: https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_Setup_1_7_0_2_b.exe

**Comment by lianzaozi** [comment]
Version V1.7.0.2 of the software can only convert circles to straight lines, not G2 and G3. Whether I check "Avoid G2/3 (Arc Move) commands, draw arcs/circles with line segments" or not, the result is the same

**Comment by svenhb** [comment]
On my computer it works with 1.7.0.2: "Avoid G2/3 (Arc Move)" deselect, I get G2/G3 commands, selected I get line segments.
I assume you enabled a not listed "hidden" option, which enables "Avoid G2/3 (Arc Move)" internally  (like for hatch fill).
You can try to reset all setting here:
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/87245ebb-7e06-4a35-b1f8-00555da01086)

**Comment by svenhb** [comment]
With this options enabled, line segments will be created:
                ```
ConvertArcToLine = Properties.Settings.Default.importGCNoArcs || OptionClipCode || OptionDragTool || OptionHatchFill;
                ConvertArcToLine = ConvertArcToLine || OptionSpecialWireBend || OptionSpecialDevelop || OptionRampOnPenDown || OptionDashPattern;

```

**Comment by lianzaozi** [comment]
Did I reset the settings according to your method or will only generate G01? Here are the settings for my computer

![image](https://github.com/svenhb/GRBL-Plotter/assets/53146195/80b77863-a943-4afc-b209-8303e001d53f)

**Comment by svenhb** [comment]
Can you do a screenshot of the status line, right after import?
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/5d2916fd-cd7d-46fe-a481-070f2d1bfe8f)

**Comment by lianzaozi** [comment]
I have found the issue that circles will not generate G2 and G3 because the plotter software needs to click on the "Reload all settings" button after switching the language from English to Chinese Similarly, to switch from Chinese to English, you need to click on the "Reload all settings" button; This way, the circle can generate code for G2 and G3

**Comment by lianzaozi** [comment]
When using the clipping function, an unnecessary line was added

![image](https://github.com/svenhb/GRBL-Plotter/assets/53146195/9cadf5f2-e3b2-4db8-853e-242c103e8ba6)

![image](https://github.com/svenhb/GRBL-Plotter/assets/53146195/fe7c2c3a-6926-485f-bdf6-32e06dfa925d)



How to display the serial number of each area when using the clipping function, as shown below
![image](https://github.com/svenhb/GRBL-Plotter/assets/53146195/0e8080a6-1fb3-41f7-a481-4aeab3efa970)

**Comment by svenhb** [comment]
👍👍👍 very good you found the reson. 
After switching the language, you are asked to restart the software, this should apply all settings.

>When using the clipping function, an unnecessary line was added

You showd the simulation path, which is a bit inaccurate, better try a real plot.

>How to display the serial number 

Enable the background view:
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/9ecad8ff-632c-4dca-8802-462a0f2393b1)

**Comment by lianzaozi** [comment]
Checking 'background' does not display a serial number

![image](https://github.com/svenhb/GRBL-Plotter/assets/53146195/18fd31b2-8350-42c3-8df2-1a6bb931feaa)

**Comment by svenhb** [comment]
Deüending on options it should work:
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/309e89c6-4834-47b4-9d96-30dd4e99e8f6)
