### ISSUE TITLE
Info Box Is Not Removed When Disabled

### ISSUE THREAD

**Issue by bryandam** [svenhb/GRBL-Plotter#355]
**Describe the bug**
The Info Box is sometimes poorly placed in the top right of the work area. Maybe there's a way to relocate it but I couldn't find how to do so.
![image](https://github.com/svenhb/GRBL-Plotter/assets/5198361/209a7072-b997-4b80-8e01-c9873245eb6b)

If you disable this in the View options it just becomes plain white box. As does the work position box by the cursor:
![image](https://github.com/svenhb/GRBL-Plotter/assets/5198361/cfba04a4-ccde-46ae-aec8-cbe3db0691e9)

This is particularly problematic because, as described in #354, the view gets reset every time an object is transformed putting the info box on top of the work area.
**To Reproduce**
Using 1.7.0.2
Disable View > Info Box

**Expected behavior**
Info Box is entirely removed from the work area UI when that option is disabled.

**Comment by svenhb** [comment]
I never checked this combination (Show machine limits, hide info). 
Will fix this.

**Comment by svenhb** [comment]
Is fixed here; https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_Setup_1_7_0_2_b.exe

**Comment by bryandam** [comment]
Awesome, can confirm this is fixed. 
Thanks Sven!
