### ISSUE TITLE
Reading ellipses stored in blocks can result in incorrect results

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#359]
The software version 1.7.0.2 reads elliptical arcs stored in blocks, which may result in incorrect orientation of the read graphics. This error should exist in all versions

test file
[test.zip](https://github.com/svenhb/GRBL-Plotter/files/12564347/test.zip)

test image 
On the left is the result read by version 1.7.0.2 software, and on the right is the result read by CAD software
![4](https://github.com/svenhb/GRBL-Plotter/assets/53146195/cda3446d-cfae-4334-a611-58abff43ec05)

**Comment by svenhb** [comment]
If I draw such ellipse in LibreCAD, the import in GRBL-Plotter is correct.

**Comment by lianzaozi** [comment]
I used autocad 2019 to draw this figure, and the elliptic arc is in a block. If the elliptic arc is not in the block, it is also correct for plotter to read the elliptic arc that is not in the block

**Comment by svenhb** [comment]
Found the problem: I applied group-angle also to start/end angle of ellipse.
Try https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_Setup_1_7_0_2_f.exe

**Comment by lianzaozi** [comment]
There is also an error reading arcs stored in the block

Plotter software and AutoCAD software read the arcs stored in the block, and the coordinates of the starting point of the arcs displayed by the two software are different

![111](https://github.com/svenhb/GRBL-Plotter/assets/53146195/4e61ffcb-74b4-4668-8154-453cc5bd86d9)

test file

[dxf.zip](https://github.com/svenhb/GRBL-Plotter/files/12575145/dxf.zip)

**Comment by svenhb** [comment]
Should be fixed now: https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_Setup_1_7_0_2_h.exe

**Comment by lianzaozi** [comment]
After testing, version 1.7.0.2-g of the software temporarily found no issues when reading elliptical arcs and arcs stored in blocks

**Comment by svenhb** [comment]
👍 I hope you mean 1.7.0.2-h

**Comment by lianzaozi** [comment]
Sorry, there was an error in the input of the previous reply version



Yes, the version I tested is 1.7.0.2-h, and no issues have been found so far
