### ISSUE TITLE
The plotter software did not consider the scaling of the entities in the block when parsing dxf

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#365]
I inserted a block containing arcs in dxf and set the values of the X and Y scaling factors to 10 during insertion. However, when using the plotter software to read this dxf, it still displayed the arcs before scaling

Please use CAD software to open this dxf file. In the open interface, the upper and lower arcs are the same block. When inserting the upper arc, the scaling factors of X and Y are set to 10. In CAD software, the size of the upper arc is 10 times that of the lower arc, but the two arcs are the same size when opened using Plotter software

Test dxf file
[Drawing1-1.zip](https://github.com/svenhb/GRBL-Plotter/files/13632009/Drawing1-1.zip)

[ScreenShot.zip](https://github.com/svenhb/GRBL-Plotter/files/13635077/ScreenShot.zip)

When parsing blocks, the values of group codes 41 and 42 in DXFinsert.cs should be considered
[Group code values that should be considered.zip](https://github.com/svenhb/GRBL-Plotter/files/13635442/Group.code.values.that.should.be.considered.zip)

**Comment by svenhb** [comment]
Bug fix in in progress...

**Comment by svenhb** [comment]
Check new relase: https://github.com/svenhb/GRBL-Plotter/releases
Should be solved now
