### ISSUE TITLE
Upload of  v1.1_GRBL_coreXY_servo___.ino.with_bootloader.standard.hex fails

### ISSUE THREAD

**Issue by SteveJgithub** [svenhb/GRBL-Plotter#372]
**Describe the bug**
An upload of v1.1_GRBL_coreXY_servo___.ino.with_bootloader.standard.hex to Arduino Uno using Xloader fails.

**To Reproduce**
Launch Xloader specifying the file name above
Wait for Xloader to run to completion
View error message

**Expected behavior**
Expecting a successful upload with a message giving the number of bytes loaded as per usual

**Screenshots**
N/A

Thanks

**Comment by svenhb** [comment]
I will remove both files from the setup.
What setup do you need? CoreXY - with or without servo?

**Comment by svenhb** [comment]
Check new hex files: https://github.com/svenhb/GRBL-Plotter/tree/master/Firmware/hex_files
Also part of new setup: https://github.com/svenhb/GRBL-Plotter/releases
