### ISSUE TITLE
The new version of the software (V1.7.1.1) does not display points in the dxf file

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#373]
Thank you very much for updating the software and adding new features

The software version v1.7.1.1 can correctly parse points in dxf files but will not display points

Plotter software display
![Snipaste_2024-01-25_16-27-17](https://github.com/svenhb/GRBL-Plotter/assets/53146195/6f7a5694-907b-419f-936a-74b0eb5c1727)

CAD software display
![123](https://github.com/svenhb/GRBL-Plotter/assets/53146195/43ecd343-d042-4c80-bfa6-3c7cdbcd0404)

Test dxf
[1.zip](https://github.com/svenhb/GRBL-Plotter/files/14049053/1.zip)

**Comment by svenhb** [comment]
Yes, the problem is again your scaling: this drawing has an width of 479842 mm, the point marker has a size of 4 mm.
If you zoom in you find the point markers.
Any idea how to fix it? Set point marker-size to x% of complete graphics-width?

**Comment by lianzaozi** [comment]
> 是的，问题又出在你的缩放上：该图的宽度为 479842 毫米，点标记的尺寸为 4 毫米。 如果放大，您会发现点标记。 知道如何修复它吗？将点标记大小设置为完整图形宽度的 x%？

I found that in CAD software, when zooming in and out on point entities, the size of the displayed points in CAD does not change with scaling and is a fixed value.Zooming in and out only changes the distance displayed between points (the display size of points does not change with the scaling ratio, and this feature only applies to point entities)


Screenshot of reduced point display
![123](https://github.com/svenhb/GRBL-Plotter/assets/53146195/28c59061-26f2-4a41-be07-e164008aff17)

Screenshot of enlarged point display
![6](https://github.com/svenhb/GRBL-Plotter/assets/53146195/a63af3d0-7fda-4956-b006-d3100999915d)

**Comment by lianzaozi** [comment]
Yes, as you described, I enlarged the graphics to a large size and indeed saw the plotter software displaying the points

**Comment by lianzaozi** [comment]
Thank you for your hard work

**Comment by lianzaozi** [comment]
The software version of the plotter used for testing is V1.7.1.1

I have a question that I don't understand. I would like to ask you a question. My understanding is that whether arcs and circles generate G01 or G02/G03 is determined by the checkbox "Average G2/3 (Arc Move) commands, draw arcs/circles with line segments". After testing, checking and unchecking "Average G2/3 (Arc Move) commands, draw arcs/circles with line segments", the G code for generating arcs and circles is the same



But after verification, I found that after checking "Process Dashed Line Pattern", arcs and circles will generate G01, while unchecking "Process Dashed Line Pattern" will generate G02/G03



After selecting "Process Dashed Line Pattern", the arc and circle will generate screenshots of G01
![1](https://github.com/svenhb/GRBL-Plotter/assets/53146195/11fd01c9-40f6-44a0-bba3-64cae87823bd)



Uncheck the "Process Dashed Line Pattern" to generate screenshots of G02/G03 for arcs and circles
![2](https://github.com/svenhb/GRBL-Plotter/assets/53146195/ffddbf12-62db-4d8a-944c-366ed6c4854b)



Checking and unchecking "Average G2/3 (Arc Move) commands, draw arcs/circles with line segments" The G code generated by arcs and circles is the same
![3](https://github.com/svenhb/GRBL-Plotter/assets/53146195/d9f4d4cc-2eed-488d-b465-679e92fb619a)


Dxf file for testing

[1.zip](https://github.com/svenhb/GRBL-Plotter/files/14052996/1.zip)

**Comment by svenhb** [comment]
>After selecting "Process Dashed Line Pattern",
There is no other way to draw a circle with dashed line pattern then using G01 commands.
G02/G03 will draw an arc or  circle with no interruption.

**Comment by lianzaozi** [comment]
The circles used for testing are drawn using solid lines instead of dashed lines
![image](https://github.com/svenhb/GRBL-Plotter/assets/53146195/0a18a9ea-4573-4154-ac21-5671e3ab6c7e)

**Comment by svenhb** [comment]
If this option is enabled, all possible G02/G03 code will be converted to G01:
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/5cb7721f-6c9a-47e4-8835-507318f38e8a)

**Comment by lianzaozi** [comment]
> "Average G2/3 (Arc Move) commands, draw arcs/circles with line segments"

What does the "Average G2/3 (Arc Move) commands, draw arcs/circles with line segments" check box do?

**Comment by svenhb** [comment]
If you have no other options enabled:
You may want G02/G03 code for short program (scaling aspect ratio must be 1:1) or
you may want G01 for circles to be able to scale the graphics independed from fixed aspect ratio 1:1

**Comment by svenhb** [comment]
Try update: https://github.com/svenhb/GRBL-Plotter/releases/download/v1.7.1.1/GRBL-Plotter_Setup_1711a.exe

**Comment by lianzaozi** [comment]
> Try update: https://github.com/svenhb/GRBL-Plotter/releases/download/v1.7.1.1/GRBL-Plotter_Setup_1711a.exe

https://github.com/svenhb/GRBL-Plotter/issues/373#issuecomment-1910728367
