### ISSUE TITLE
Version V1.7.1.1.a: The plotter software encountered an error while reading entities stored in blocks with inconsistent scaling ratios in the X and Y directions

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#375]
Version V1.7.1.1.a: The plotter software encountered an error while reading entities stored in blocks with inconsistent scaling ratios in the X and Y directions.

The different scaling ratios in the X and Y directions of the entities in the block in the dfx file can cause errors in the plotter software's reading.

The software version of the plotter used for testing is v1.7.1.1.a, and I guess this issue should exist in all versions.

![1](https://github.com/svenhb/GRBL-Plotter/assets/53146195/59888df8-005f-42f4-8c7f-02e8285fd1d0)
Screenshot of CAD software

![2](https://github.com/svenhb/GRBL-Plotter/assets/53146195/ae703942-2cb1-427d-81a7-2edd74d8fd88)
Screenshot of the plotter software

The dxf file used for testing
[1 - (2).zip](https://github.com/svenhb/GRBL-Plotter/files/14122236/1.-.2.zip)

The color display of graphics in the drawing software when reading dxf is different from what is displayed in the CAD software
The display colors of the elements indicated by 1, 2, and 3 in the screenshot are different
![3](https://github.com/svenhb/GRBL-Plotter/assets/53146195/d42800a1-cbbe-4b6e-9297-cbd64563d726)

**Comment by svenhb** [comment]
Thanks again for finding a bug 😉
I found the problem, will release a new version soon.

**Comment by svenhb** [comment]
Check latest release: https://github.com/svenhb/GRBL-Plotter/releases

**Comment by lianzaozi** [comment]
Thank you very much for your hard work. There are still some issues with version v1.7.1.2, and the areas indicated by A, B, and C circled in the screenshot still have issues.

![00](https://github.com/svenhb/GRBL-Plotter/assets/53146195/5101f4ba-469d-4cf9-84d8-29a0eecfe8cd)


The polyline and point at point A are saved in the same block. I guess the problem at point A is related to rotation

The arc and line at point B are saved in the same block.

The circle and line at point C are saved in the same block.

There is still an issue with parsing circles, arcs, and polylines in the block.


There is still a problem with the resolution of graphic colors. The colors displayed on the plotter are different from those in CAD.

![22](https://github.com/svenhb/GRBL-Plotter/assets/53146195/5b21dc9f-6162-40a8-b100-ae0b6a1179c2)

**Comment by svenhb** [comment]
My reference is LibreCAD, there your drawing looks like this, which is close to the GRBL-Plotter output:
Perhaps there are incompatibility problems with AutoCAD versions? LibreCAD can save up to "DXF 2007".
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/5f45b3fa-7e7c-4c6e-99f1-a77e5ea893c9)

**Comment by lianzaozi** [comment]
I am using AutoCAD, and the version saved in DXF is 2018

**Comment by svenhb** [comment]
Can you save with an older DXF version?
I can't support the latest AutoCAD feature because there's no information to be found on the internet - I just found DXF 2012.
To be fair, you should use freeware tools to test GRBL-Plotter.
BTW. also Inkscape can't read your DXF file....

**Comment by lianzaozi** [comment]
Latest dxf format reference document

https://help.autodesk.com/view/OARX/2024/ENU/?guid=GUID-A85E8E67-27CD-4C59-BE61-4DC9FADBE74A

**Comment by svenhb** [comment]
Try new release: https://github.com/svenhb/GRBL-Plotter/releases

**Comment by lianzaozi** [comment]
> Try new release: https://github.com/svenhb/GRBL-Plotter/releases

Thank you for updating the new version. When testing version 1.7.3.0 of the plotter software, I found some issues. In the dxf file, point 1 in the following image coincides with the endpoint 3 of the elliptical arc, while points 2 and 4 coincide; However, when using version 1.7.3.0 plotter to read dxf, point 1 does not coincide with endpoint 3 of the elliptical arc, and points 2 and 4 do not coincide
![image](https://github.com/svenhb/GRBL-Plotter/assets/53146195/4bda4c6b-057f-4487-915e-cf5c602a2bcd)

**Comment by lianzaozi** [comment]
Version 1.7.3.0 of the plotter software can only generate G01 when reading circles stored in blocks. After unchecking "Process drawn line pattern", arcs and circles will not generate G02 and G03.

Should the user be allowed to choose whether to generate G01 or G02/G03 for arcs when the scaling ratios in the x and Y directions of the circles and arcs stored in the block are the same; When the scaling ratios of circles and arcs stored in the block are different in the x and Y directions, arcs can only generate G01.
![image](https://github.com/svenhb/GRBL-Plotter/assets/53146195/cd380095-a5e9-4176-bf50-782529204c0c)

**Comment by svenhb** [comment]
Will change the code: 
If dashpattern is enabled, but pattern is empty, then use G02/G03, otherwise G01 to be able to apply the pattern.

**Comment by svenhb** [comment]
Check latest release: https://github.com/svenhb/GRBL-Plotter/releases

**Comment by lianzaozi** [comment]
感谢你发布新版本,我将进行一些测试
Thank you for releasing the new version. I will conduct some testing

**Comment by lianzaozi** [comment]
Version V1.7.3.1 still does not solve the problem of parsing the coordinate points stored in the block after the elliptical arc is rotated and scaled in the X and Y directions. I drew two points at the starting and ending points of the elliptical arc. If I observe that the starting and ending points of the elliptical arc do not coincide with the point in the plotter, it indicates that the coordinate values of the starting and ending points of the elliptical arc are parsed incorrectly. I did this to facilitate the observation of whether the calculated coordinate values are incorrect in the plotter after parsing.

At the same time, I will take screenshots of the coordinate values displayed in CAD and plotter for comparison of this dxf file

![1](https://github.com/svenhb/GRBL-Plotter/assets/53146195/511ae092-e50c-42ff-ad71-b952a18c5540)
![2](https://github.com/svenhb/GRBL-Plotter/assets/53146195/dbebfd31-76c6-4086-92ae-af370adf09d9)
![3](https://github.com/svenhb/GRBL-Plotter/assets/53146195/1ae39b08-f1c3-4663-978c-589e228f6c9e)
![4](https://github.com/svenhb/GRBL-Plotter/assets/53146195/c460d248-cda2-4416-b2e4-4ec1a4f0ce13)
![5](https://github.com/svenhb/GRBL-Plotter/assets/53146195/28e06b05-af65-4d07-930a-ef3e54e0334b)

test dxf file
[1 - (2).zip](https://github.com/svenhb/GRBL-Plotter/files/14625483/1.-.2.zip)

**Comment by lianzaozi** [comment]
Version 1.7.3.1 of the software does not have settings that allow users to decide whether circles and arcs should generate g02/g03 or g01. Currently, this version can only generate g02/g03 for circles.

**Comment by svenhb** [comment]
>Version 1.7.3.1 of the software does not have settings that allow users to decide whether circles and arcs should generate g02/g03

No need for an extra setting: if (scaling.X == scaling.Y) G02/G03 will be used (if enabled).

**Comment by lianzaozi** [comment]
Where is (if enabled) enabled?

**Comment by svenhb** [comment]
>Where is (if enabled) enabled? 
If scaling X=scaling Y, what should I do to make the circle generate G02?

This checkbox must not be checked:
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/94b29d3e-b4e3-4402-bfb6-66f456ac1e2a)

>If scaling X=scaling Y, what should I do to make the circle generate G01?

Then check "Avoid G2/3"

**Comment by lianzaozi** [comment]
Thank you

**Comment by lianzaozi** [comment]
What is the difference between checking and not checking "Process Dashed Line Pattern"? Will this checkbox affect circle generation G01/G02/G03?

![image](https://github.com/svenhb/GRBL-Plotter/assets/53146195/f60cf1ea-7cc3-4a21-8176-eceb71943ffe)

**Comment by svenhb** [comment]
If you have a dashed line and want to plot it you need to check this option, then, G02/G03 can't be used, because of the interruptions in the drawing path. Otherwise a normal line will be drawn, even if the property is "dashed".
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/0775b30d-16ae-4960-903f-92563b022a26)

**Comment by svenhb** [comment]
Yes

**Comment by lianzaozi** [comment]
Thank you for your reply. After conducting some tests, the following are the test results, and one of them is incorrect

![image](https://github.com/svenhb/GRBL-Plotter/assets/53146195/2673d17f-336c-438f-afdb-ac42c68d3b71)

**Comment by svenhb** [comment]
Then perhaps an other option was also enabled?
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/db526685-cef2-4530-a101-6dde47f0b24c)

**Comment by lianzaozi** [comment]
I haven't changed any other options. I'll upload the file I used for testing and give it a try
[test.zip](https://github.com/svenhb/GRBL-Plotter/files/14652688/test.zip)
![image](https://github.com/svenhb/GRBL-Plotter/assets/53146195/9d210e99-a39f-4fae-8ab7-756349d3eb06)

**Comment by svenhb** [comment]
Ok, there's a bug with DXF import: once the line pattern was set, it couldn't be reset.

**Comment by svenhb** [comment]
About dash pattern: Try test version https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_Setup_1731a.exe

The other problem (start / end pos of ellipse) I can't fix for now. Must be a rounding error, when converting angles back an forth.

**Comment by lianzaozi** [comment]
> About dash pattern: Try test version https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_Setup_1731a.exe
> 
> The other problem (start / end pos of ellipse) I can't fix for now. Must be a rounding error, when converting angles back an forth.

Thank you for your hard work. I will conduct some tests.


After my testing, if the elliptical arc does not exist in the block, the starting and ending coordinates parsed by the plotter software are correct. However, if the elliptical arc exists in the block, and the block is rotated and scaled, the plotter software will read the starting and ending coordinates parsed by the block again, which will be incorrect.

**Comment by lianzaozi** [comment]
![image](https://github.com/svenhb/GRBL-Plotter/assets/53146195/28a39567-ef8e-4188-bf01-95f7852e6a8b)


Elliptical arcs stored in blocks, incorrect resolution of starting and ending coordinates
![1](https://github.com/svenhb/GRBL-Plotter/assets/53146195/375bc80b-413b-4234-a52d-1a22bfaff825)


It is not an elliptical arc stored in a block, and the coordinates of the starting and ending points are parsed incorrectly
![2](https://github.com/svenhb/GRBL-Plotter/assets/53146195/5b23d723-6bcb-4539-841a-7064b8b6cb9e)

test file
[1 - (2) -.zip](https://github.com/svenhb/GRBL-Plotter/files/14695161/1.-.2.-.zip)

**Comment by lianzaozi** [comment]
![image](https://github.com/svenhb/GRBL-Plotter/assets/53146195/a6bcde33-43c3-4289-96f2-8d691679642f)
![image](https://github.com/svenhb/GRBL-Plotter/assets/53146195/3a7508cc-f2ca-40d9-b070-399714363ebb)


The starting angle of an elliptical arc
(45/180)*3.1415926=0.785398163≠ 0.79741212786 (a2)

Termination angle of elliptical arc
(342.097334/180)*3.1415926=5.97072484≠ 5.0571035 (a1)

Perhaps the insufficient accuracy of the numerical values read in dxflib resulted in inaccurate angle values for the starting and ending points of the elliptical arc

test dxf
[1 - (4).zip](https://github.com/svenhb/GRBL-Plotter/files/14818698/1.-.4.zip)

**Comment by lianzaozi** [comment]
![image](https://github.com/svenhb/GRBL-Plotter/assets/53146195/7c0f2249-7ce7-4d31-9f53-2f960d552739)
I tried to draw more points on the elliptical arc and found that the coordinate values resolved by the entire elliptical arc are not accurate. In dxf, these points are completely on the elliptical arc. I will spend some time trying to solve this problem

**Comment by svenhb** [comment]
Yes, as soon as there are different scalings for X and Y inside the block, the angles a1, a2 are no longer correct. 
If acalings are the same, then there is no problem.
Could not figure out why, up to now.

**Comment by lianzaozi** [comment]
How to output these logs

![image](https://github.com/svenhb/GRBL-Plotter/assets/53146195/c9385210-11ff-45ee-b866-096f3b80ea17)

My settings are as follows, but during debugging, there was no output of print logs
![image](https://github.com/svenhb/GRBL-Plotter/assets/53146195/8d2a88ac-7710-48e3-a522-5fd8bfa85333)

**Comment by svenhb** [comment]
You may enable extend logging, by clicking into the marked area
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/cbc14a1d-882d-4c32-9a0a-cbedb880a6d4)

**Comment by lianzaozi** [comment]
I clicked on the part you selected in the red box, do I need to set any other options?

**Comment by lianzaozi** [comment]
Hello, excuse me, I need your help
What does the variable diff represent below?
What does the condition for determining if here mean?
![image](https://github.com/svenhb/GRBL-Plotter/assets/53146195/c4ecaff6-dadd-42f0-9979-cb3966bc6db5)

What does the variable a represent below???
![image](https://github.com/svenhb/GRBL-Plotter/assets/53146195/be28620d-a8b7-4ba7-95ad-0a8ce3346ee7)

**Comment by svenhb** [comment]
the "large" variable is needed to determine the arc behavior: 
a is the axis-rotation 
https://www.w3.org/TR/SVG2/paths.html#PathDataEllipticalArcCommands

**Comment by lianzaozi** [comment]
It seems that solving ellipses in the plotter code is not using elliptic parameter equations


I usually use the following equation to calculate elliptical trajectories
![image](https://github.com/svenhb/GRBL-Plotter/assets/53146195/dd466f1f-5721-4ab8-81e6-76f743bfb0ff)
![image](https://github.com/svenhb/GRBL-Plotter/assets/53146195/2bb6ff77-86d8-4eb8-ab6b-aaf2ca2e299d)

**Comment by lianzaozi** [comment]
From what I understand the variable a in the program should compute t1;
But the actual variable a in plotter is equal to t2

I don't really understand why I'm calculating Angle t2, right? Can you help me explain?

![image](https://github.com/svenhb/GRBL-Plotter/assets/53146195/f33744eb-e6fb-4e06-b209-8bbd81263658)


![image](https://github.com/svenhb/GRBL-Plotter/assets/53146195/562a9ef0-9ba8-4db5-ba68-bcdd82742435)

**Comment by lianzaozi** [comment]
I finally found the reason, not because the scaling ratio of x direction and Y direction was inconsistent, but because the elliptic arc was stored in the block with an Angle, which was 13.178191. The elliptic arc in plotter's parsing block did not take into account that the elliptic arc in the block also had an Angle. Now I have adjusted the Angle to 0, and plotter will The parsing is normal. So we should take this into account when analyzing the elliptic arc in the block

The elliptic arc in the block has no Angle screenshot
[The elliptic arc in the block has no Angle.zip](https://github.com/svenhb/GRBL-Plotter/files/14849607/The.elliptic.arc.in.the.block.has.no.Angle.zip)

![image](https://github.com/svenhb/GRBL-Plotter/assets/53146195/5260053d-8d4d-4686-b246-2b6add44ddbb)


Angular screenshot of the elliptic arc in the block
[The elliptic arc in the block has an Angle.zip](https://github.com/svenhb/GRBL-Plotter/files/14849611/The.elliptic.arc.in.the.block.has.an.Angle.zip)

![image](https://github.com/svenhb/GRBL-Plotter/assets/53146195/1fd0ad65-5b7a-4c32-999c-cb8ba8a076d0)

Open the Elliptic Arc Block editor to measure the Angle of the screenshot
![image](https://github.com/svenhb/GRBL-Plotter/assets/53146195/14d70bfa-50f0-4706-8498-09439166398c)

**Comment by lianzaozi** [comment]
The x and y scales of the above two screenshot blocks are both 2:1

**Comment by svenhb** [comment]
>but because the elliptic arc was stored in the block with an Angle, which was 13.178191

This angle is given by ellipse.MainAxis coordinates. (Endpoint of major axis, relative to the center)

**Comment by lianzaozi** [comment]
YES,Does the current code include 13.178191 when calculating coordinates?

**Comment by svenhb** [comment]
>Does the current code include 13.178191 when calculating coordinates?

Yes: Coordinates are Ellipse center: 407.181; 143.770  Mainaxis  -386.528; 90.504
-386.528; 90.504 results to an angle of -13.17
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/8ca0f1e2-1e91-4329-b0c0-027b5e024655)

**Comment by lianzaozi** [comment]
Hello, where are these logs stored?

![image](https://github.com/svenhb/GRBL-Plotter/assets/53146195/eaaa9bdf-7432-49b3-85c7-073f15237782)

**Comment by svenhb** [comment]
Go to the Data Path/logfiles:
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/26d9d1ed-279e-419a-9578-e826787cf39d)

**Comment by lianzaozi** [comment]
I know why the problem happened,(double w = ellipse.AxisRatio * (double)scaling.Y/(double)scaling.X;) By default, the major axis of the ellipse is parallel to the X-axis of the coordinate system, and the minor axis of the ellipse is parallel to the Y-axis of the coordinate system, but if the ellipse in the block has an Angle, the value of the variable w is not correct, and I think it should be calculated by affine transformation company.

![image](https://github.com/svenhb/GRBL-Plotter/assets/53146195/be2ba925-ac82-4c30-85cf-491e464729d8)

**Comment by lianzaozi** [comment]
.NET open source library for matrix operations, which I thought I might use when parsing ellipses

https://github.com/MKL-NET/MKL.NET

**Comment by lianzaozi** [comment]
I have pinpointed the direction of the problem, or did I encounter a problem while parsing the scaling of the elliptical block? Period
If I set the scaling in the x and y directions separately, there will be problems.
The problem caused by scaling in the x direction is greater

![sx=0 16](https://github.com/svenhb/GRBL-Plotter/assets/53146195/c0d8ea6e-92df-48a1-9d16-4cf60d8ffd49)
test dxf(sx=0.16 sy=1 theta=0)
[sx=0.16.zip](https://github.com/svenhb/GRBL-Plotter/files/14962934/sx.0.16.zip)



![sy=0 08](https://github.com/svenhb/GRBL-Plotter/assets/53146195/73f72b6e-0134-42af-a6df-f3949f8dea93)
test dxf(sx=1 sy=0.08 theta=0)
[sy=0.08.zip](https://github.com/svenhb/GRBL-Plotter/files/14962940/sy.0.08.zip)

**Comment by lianzaozi** [comment]
I have identified the real reason for the incorrect parsing of ellipses and arcs within a block. The different scaling ratios in the X and Y directions are not the cause of this problem. The real reason is that if there are angles between the elliptical arcs and arcs within the block (the major axis of the ellipse is not parallel to the X direction of the coordinate system), this problem will occur


The difference between Ellipse 1 and Ellipse 2 in the ArSeg diagram is that Ellipse 1 has an angle within the block, while Ellipse 2 has no angle within the block; When inserting ellipses 1 and 2, the scaling ratios in the X and Y directions are different, but ellipses 1 are parsed correctly and ellipses 2 are parsed incorrectly
![123](https://github.com/svenhb/GRBL-Plotter/assets/53146195/9b5cb445-773b-4ea7-8a8d-d50b5fe6a0bd)


test dxf file
[123.zip](https://github.com/svenhb/GRBL-Plotter/files/15124561/123.zip)

**Comment by svenhb** [comment]
I assume the current order is wrong: now 1st I apply xy scaling to the ellipse-properties, then I calculate the ellipse points. 
I will try to calculate ellipse points 1st, then apply xy scaling - but it is a huge work.

**Comment by lianzaozi** [comment]
Firstly, obtain the coordinates before scaling, then use matrix operations to calculate the scaled coordinates, and then use the calculated coordinates to form a transformed ellipse. As I am not very familiar with programming, I can only provide you with the conclusion I have drawn after verification in CAD to provide you with an idea

**Comment by svenhb** [comment]
I hope now it is correct, check https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_Setup_1731g.exe

**Comment by svenhb** [comment]
There is still a bug for circle with blockScaling.X != blockScaling.Y. But the fundamental problem has been found...

**Comment by lianzaozi** [comment]
Thank you for updating the software. I will conduct some necessary tests.

**Comment by svenhb** [comment]
Should be fixed now: https://github.com/svenhb/GRBL-Plotter/releases
