### ISSUE TITLE
Dragknife / generated shapes

### ISSUE THREAD

**Issue by rapzak** [svenhb/GRBL-Plotter#377]
Hi,

If i make a squarre in the tool to generate gcode, it seems the dragknife compensation is not added?

Is this normal or do i need to run some in between or is it a small "bug"

Thank you for your great work

**Comment by svenhb** [comment]
Yes, if you use "Simple shapes" to create a rectangle, drag tool compensation is not supported. But tangential axis.
You may create a rectangle in Inkscape and copy/paste it to GRBL-Plotter, this should work.
