### ISSUE TITLE
Cannot connect via hc-05 bluetooth module

### ISSUE THREAD

**Issue by Srallie** [svenhb/GRBL-Plotter#378]
hello,

i have the mega x5 grbl firmware and connect them to a hc-05 bluetooth module. By other programs like laser grbl/ lightburn i will connect directly,but grbl plotter says:

* COM5 not available

*

how to solve?

**Comment by svenhb** [comment]
Perhaps the bluetooth port has an other number?
Did you try to "Scan Ports" and find the correct port?
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/6eebf48c-196d-4836-aed5-169b19a6fa56)
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/6a317987-2041-4668-a66f-5e177e0d554e)

**Comment by Srallie** [comment]
Hello,

Thanks for fast response. When i plug it in with cable, com 3 works perfect. When i turn on Bluetooth on com 5, then it didnt work.

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by svenhb** [comment]
I tried with my bare Mega 2560 (x5 grbl firmware) and it works...
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/86e2111d-4d40-4577-97e6-01efe978df44)

**Comment by Srallie** [comment]
Ok,strange..I will try again this week.👍

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by svenhb** [comment]
Perhaps thats the problem?
NOTE: powering the grbl-controller via PC-USB will cause problems, because RXD/TXD of PC-USB are connected to RXD/TXD of HC-05 module = short circuit of the data lines!
