### ISSUE TITLE
Add Linux Installation Guide to the Wiki and the Website

### ISSUE THREAD

**Issue by metzger100** [svenhb/GRBL-Plotter#379]
Hey Sven,

I've opened a new issue for this, as I believe the README.md isn't the appropriate place for such a complex topic. It seems more fitting to include it in the wiki.

I've drafted a guide specifically for Linux. Unfortunately, I wasn't able to get it to run with Wine, but it did work with Proton (Experimental). I sincerely hope this guide proves useful for users of other distros as well, as I've only tested it on a fresh Arch installation to ensure functionality. I've aimed to make the guide as generic as possible.

You can find the document titled attached in the second comment. Additionally, I've included an image demonstrating how it should appear if successful in the section "Setup USB Port to connect to the CNC" at point 5.

![2024-02-28-12-43-04-image](https://github.com/svenhb/GRBL-Plotter/assets/62517154/4eda4615-d78e-45e7-aed3-1e78ea124c16)

**Comment by metzger100** [comment]
That Issue is related to #374

**Comment by metzger100** [comment]
I refined the guide. There were some language errors and some incomplete informations in it. They are now fixed.
[GRBL-Plotter-Linux.md](https://github.com/svenhb/GRBL-Plotter/files/14439811/GRBL-Plotter-Linux.md)

**Comment by svenhb** [comment]
Thanks alot, will do it at the weekend.

**Comment by metzger100** [comment]
Thanks for commiting. Could you remove line 209? There is a wrong path in it.

**Comment by svenhb** [comment]
ok, done.

**Comment by metzger100** [comment]
I justed faced a crash using Proton Experimental which I could not reproduce on other Linux PCs. Switching to Proton GE fixed it somehow. You can easyly install it with ProtonUP-Qt or manually with the guide at: https://github.com/GloriousEggroll/proton-ge-custom
