### ISSUE TITLE
Can I move genrated paths with different color together

### ISSUE THREAD

**Issue by lyg09270** [svenhb/GRBL-Plotter#380]
**Describe the solution you'd like"
I use a graphic to generate paths with different color.
When I trying move different path in same time.I find that I can only move the path one by one.This caused a litte bit offset in my drawing.Because I can only drag the paths one by one. 
![IMG_20240301_224536.jpg](https://github.com/svenhb/GRBL-Plotter/assets/126072033/27386fcd-5741-4760-8184-aeba94c0c69c)

Maybe I can select them together?I tried Ctrl-A and hold Ctrl to select more path.It dosen't work.

**Comment by svenhb** [comment]
You could put the different paths into a same layer (e.g. in Inkscape) and then group by layer in GRBL-Plotter.
But anyway it would be nice to select different paths by shift-click as in other application. I will check if could implement this.

**Comment by lyg09270** [comment]
I find that I can also move different path at once by this![IMG_20240302_224946.jpg](https://github.com/svenhb/GRBL-Plotter/assets/126072033/5919b6cd-5942-48f0-b3a9-1ee524f941f6)
But i think shift-click is better.For instance,If I have two character in generated path.And I wanna move them closer."Apply offset" couldn't do that.since it move all path together.

**Comment by svenhb** [comment]
Unfortunatly it is not possible to select different objects with the current software design. But I save now the last transform which can be applied to the next selected object: https://github.com/svenhb/GRBL-Plotter/releases

Do a transform on a selected form. select the next form, right click and select "Apply last transform"
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/833696dc-94d5-4fd3-834c-23dc61787dfc)
