### ISSUE TITLE
Tangential knife - reverse selected path bug

### ISSUE THREAD

**Issue by Kikenzi** [svenhb/GRBL-Plotter#384]
Hi there, 

if i want to try reverse selected path, so tool go originally from up to down and I want to reverse it - start down and go up:
![IMG_9411](https://github.com/svenhb/GRBL-Plotter/assets/53473252/97f46487-b06a-4bc9-bf89-0823558f3b4a)

All A axis positions go to 0.00 :
![IMG_9413](https://github.com/svenhb/GRBL-Plotter/assets/53473252/83c8584a-8342-473e-a86f-6cea1333873a)

Is it a bug or I have missed some setting? 
Thank you for your help :)

**Comment by svenhb** [comment]
Check latest release: https://github.com/svenhb/GRBL-Plotter/releases

**Comment by Kikenzi** [comment]
Thank you :)

**Comment by svenhb** [comment]
Now included in new release: https://github.com/svenhb/GRBL-Plotter/releases
