### ISSUE TITLE
Out of memory error with the drag knife path modification enabled?

### ISSUE THREAD

**Issue by vinevinz** [svenhb/GRBL-Plotter#385]
It always says the system is out of memory whenever I load new SVG with the drag knife compensation on in the setup. Whether it is drag knife or tangential knife produce same error. The file it self open and work just fine if path modification is off. ( I tried the file using pencil and it is working great)

Can you help point out what is wrong with the settings?

![Screenshot 2024-03-18 171606](https://github.com/svenhb/GRBL-Plotter/assets/29923628/d0f2ed5f-74e5-4201-8825-b1f10b3c2286)

**Comment by svenhb** [comment]
What kind of PC are you using? Operating system? RAM?
Can you upload the orginal SVG file?

**Comment by vinevinz** [comment]
Step width circumfence settings totally fixed my issues! Thank you for the help. I am really new to this cnc things.

My PC is R5 3500, 16gb Ram, 3060. That is why I do not think spec is the issue.

**Comment by vinevinz** [comment]
Sorry for late reply,

My step width value was on default, I think it was 0.001 or 0.01.

Maybe showing warning about this when enabling Path Compensation would save beginner like me from this error.
