### ISSUE TITLE
Tangential knife A-Axis turn command not getting included in applying height map

### ISSUE THREAD

**Issue by vinevinz** [svenhb/GRBL-Plotter#388]
**Describe the bug**

Before I describe the bug, I know standard GRBL cannot control 4 axis simultaneously. My board is MKS Tiny Bee with FluidNC (apparently works great with this software). The CNC plotter has XYYZA motor all Nema17.

So, I upgraded the machine to tangential knife instead of drag. I'm using rotary cutter directly attached to A axis motor (works like charm).

Problem is, cutting mat is not that flat, probing height map results got me ~0.6mm difference from one edge to the other. As I'm applying the height map to G-Code, the A axis command actually getting removed.

Is this a bug or just the feature not implemented? Or maybe I am doing it wrong, bcs honestly I'm using 3d printer bed leveling logic here (it looks very similar anyway with klipper leveling).

I'm trying to cut circle (has not been successful yet due to uneven flatness issue)

G-Code screenshot attached

**To Reproduce**
1. Load circle SVG, tangential knife enable on A-Axis
2. Probe Z and height map (I am using 2 probe here, first for G38.2, second just limit switch for height map)
3. Height-map = Z-offset -1 (my probing tool offset), max value 0.0
4. Apply map
5. New g-code generated without A axis

**Expected behavior**
G-code includes A-Axis?

**Screenshots**
Original G-Code
![Screenshot 2024-03-23 181038](https://github.com/svenhb/GRBL-Plotter/assets/29923628/bb10fd0e-8a95-485c-b311-c9158b63ad5a)

Applied height map G-Code
![Screenshot 2024-03-23 181112](https://github.com/svenhb/GRBL-Plotter/assets/29923628/1202e419-e41f-49c9-b848-144a925cc1cb)

Other example, A-axis turn command without lifting knife getting omitted when applying height map(this is untested code, please ignore for so much knife lifting)

![Screenshot 2024-03-23 182126](https://github.com/svenhb/GRBL-Plotter/assets/29923628/a74516c5-724b-4683-b4d9-b65342887f97)

Applied G-Code
![Screenshot 2024-03-23 182159](https://github.com/svenhb/GRBL-Plotter/assets/29923628/8adf3bde-922f-4383-b55e-9a02a2018a27)

Thank you!

**Comment by svenhb** [comment]
I need to check

**Comment by svenhb** [comment]
Try test version https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_Setup_1731b.exe

**Comment by vinevinz** [comment]
Sorry for late reply, kinda busy weekend here

It is working but not properly, I will attach the video of without height map and with the height map. Applying height map makes A axis goes kinda crazy on sharp corners and does not work on circles.

This is the normal WITHOUT HEIGHT MAP:


https://github.com/svenhb/GRBL-Plotter/assets/29923628/3d85cf84-4b4d-405c-b8fc-93107e422688



This 2 is with the height map:

https://github.com/svenhb/GRBL-Plotter/assets/29923628/1e6ec445-a9f0-421f-b070-3df4e12d6252

https://github.com/svenhb/GRBL-Plotter/assets/29923628/1664bd9d-5c0e-4128-9919-a5647e897246


Free SVG attached if you wanna try

![tes pola sepatu speed3](https://github.com/svenhb/GRBL-Plotter/assets/29923628/8dfa875e-67b9-49a3-b967-4644250196d2)
![tesktatak2](https://github.com/svenhb/GRBL-Plotter/assets/29923628/c5af3cff-d48c-402e-9f37-c562f1a0ec87)

**Comment by vinevinz** [comment]
On my further analysis I think I found the problem, when applying height map to the g-code, the program doesn't respect the inserted turn command when re-writing it. It just copy whatever A-Axis command after Z lift pen.

The screenshot of the g-code after applying height map from this version of program 
![new inserted height map ](https://github.com/svenhb/GRBL-Plotter/assets/29923628/f85f8f3d-57a9-4f24-96d8-57714d714a49)


Without height map applied, the program respects the turn command
![Screenshot 2024-03-24 210225](https://github.com/svenhb/GRBL-Plotter/assets/29923628/41cb6a07-fc9f-4864-b9ca-5dadf4ea95eb)

**Comment by svenhb** [comment]
Nice cutter 👍
Please try https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_Setup_1731c.exe
Also arc conversion works now (tested with simple shape)

**Comment by vinevinz** [comment]
Hi Sven, 

Thank you, I am building dual head cutter and pen with servo to lift up the pen.

My initial testing looks promising for this version. However circle only works by disabling G2/3 arc commands, is that okay? I am new to CNC world and I don't know if that will be a problem. Besides circle every other pattern works amazing. I think only moves translated from G2/3 commands is broken.

Enabling G2/3 will make A-axis spin uncontrollably which creates beautiful art on its own. Btw I load circle from SVG not simple shapes.
![unnamed](https://github.com/svenhb/GRBL-Plotter/assets/29923628/a26a945f-18ea-47e2-9fc9-d3678c78f472)

**Comment by svenhb** [comment]
>However circle only works by disabling G2/3 arc commands,

Did you try allready version "c"? For me it works with G2/G3 command - also from SVG.
https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_Setup_1731c.exe

**Comment by vinevinz** [comment]
Hi sven, sorry for late reply it was crazy week here. 

Yes it is working perfectly, I think it was installation problem because I was lazy to do clean install. Thank you very much for your help on this problem.

Btw, I have new problem of start and ending edges not meeting. Can you help suggesting whether this is a software or a hardware problem?

![IMG_7072](https://github.com/svenhb/GRBL-Plotter/assets/29923628/03359295-8a9d-4aad-8105-da796c82d5f7)
![IMG_7071](https://github.com/svenhb/GRBL-Plotter/assets/29923628/14f843c9-8ac9-4261-9d95-5844e0cdd8d3)

**Comment by svenhb** [comment]
I assume hardware problem: If you woud use a "regular knife" - perhaps the knife blade is too weak (too long) and bends sidewards, when cutting the circle - as a result the circle radius becomes bigger.

**Comment by vinevinz** [comment]
Hi Sven sorry for late reply, been doing hard work this last 2 week

I have question regarding how does the software determine starting point?
Bcs I'm using rotary cutter which always overcut, I need to adjust the SVG so it will not overcut. It will be nice and easier to know where is the starting point when adjusting the design.

Example of starting point adjustment so, just make the starting point and end point separated by few millimeters.

![Screenshot 2024-04-17 172746](https://github.com/svenhb/GRBL-Plotter/assets/29923628/b79638cc-40e6-479c-b708-271265f2a018)
![Screenshot 2024-04-17 173509](https://github.com/svenhb/GRBL-Plotter/assets/29923628/e7744d0f-454a-4b6b-841b-b53d9b27f14a)

Update on the machine:
I have redesigned everything for Z gantry and upgraded beefier X axis. You are right it is hardware problem. I'm feeling very silly to make it this strong just to cut 0.8mm synthetic leather, no wonder the leather cutting machine cost at least 10k usd 😅

![unnamed (1)](https://github.com/svenhb/GRBL-Plotter/assets/29923628/90c90708-92cd-409f-9045-6409252d2958)

**Comment by svenhb** [comment]
If no sorting is active, the startpoint from the SVG will be used:
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/06f27212-f559-479b-8f9e-2cee386f8b95)

I have an option for overlap in closed figures (for laser cutting), Do you need to apply the "under cut" to each figure or just to open figures?
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/f4e2c435-fc01-440c-816e-2e642566057f)

**Comment by vinevinz** [comment]
Wow that is new info, I just knew SVG got a starting point! Thank you so much!

I think under cut in every figure is nice especially in closed path, I mean everytime the knife needs to lift up and change direction it needs to undercut.

**Comment by svenhb** [comment]
I implemented path shortening, not sure if it meets your needs: https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_Setup_1731e.exe
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/75dccf0c-91cd-4189-b927-93f29c1cf345)

**Comment by vinevinz** [comment]
That one works great! Maybe just maybe if you could, can you add path shortening for the start point too?

Since rotary cutter will overcut the starting point and end point right. I will attached sample svg and picture about what I mean.

![tes pola sepatu speed-starting point](https://github.com/svenhb/GRBL-Plotter/assets/29923628/6194a9bf-7a6f-448e-99a1-417e62968901)

![image_123650291](https://github.com/svenhb/GRBL-Plotter/assets/29923628/6fa3023c-6d2c-4ec4-9fc8-174400177551)

**Comment by svenhb** [comment]
>add path shortening for the start point too

Yes, I can do. What should happen with paths which are shorten then the shortening? Delete at all?

**Comment by svenhb** [comment]
Try this version: https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_Setup_1731f.exe

**Comment by vinevinz** [comment]
Yes it works great now! Thank you so much sven for the hard work, you are writing 2 new features just for me. This is a very amazing feature to have.

> > add path shortening for the start point too
> 
> Yes, I can do. What should happen with paths which are shorten then the shortening? Delete at all?

I think on ideal world it will be nice to give out options to delete at all or ignore path shortening for that  path. But just delete at all will be fine. We can always fix it manually in the svg.

**Comment by svenhb** [comment]
I'm glad to hear it's working. Feel free to give me a star.

**Comment by vinevinz** [comment]
Hi Sven, I have completed my main build and I still have few questions for you, sorry for such an annoying user :(

1. Is there anyway to use tangential axis path modification only on specific tool? For example, I load and SVG that includes path for 2 tools, 1 knife and 1 pen, but I only want the path modification only work on knife. 
2. Is there anyway to move diffrent group path simultaneously? With the same example, I load SVG containing path for 2 tools, 1 pen and 1 knife, they will each create a group based on the layer sorting on the SVG. I can't seem to move it together bcos they need to work together on same object to achieve the desired result. One draw on top, one cut on the same piece, just like your laser and pen example.


Thanks before!

**Comment by svenhb** [comment]
1) I experimented with machine settings given in SVG-Meta Data - perhaps thats a solution: https://grbl-plotter.de/index.php?id=form-setup-1#format-related
Write down whats missing to get it work.
2) Thats not possible yet, will try to implement it, but needs longer time....

**Comment by vinevinz** [comment]
> 1. I experimented with machine settings given in SVG-Meta Data - perhaps thats a solution: https://grbl-plotter.de/index.php?id=form-setup-1#format-related
>    Write down whats missing to get it work.
> 2. Thats not possible yet, will try to implement it, but needs longer time....

1. Got it will try that out and get back to you.
2. That is fine, I was just asking if there's any hidden feature,

By the way, I found another bug!
Applying height map sometimes adding weird move to the A axis, which turns the blade 180 for a brief moment.

Take a look at line 434 and 435, the A axis doing 180 dance
![Screenshot 2024-05-08 114126](https://github.com/svenhb/GRBL-Plotter/assets/29923628/dc4e17d9-b12d-4f8e-95eb-7409f9c4a000)

![Screenshot 2024-05-08 114141](https://github.com/svenhb/GRBL-Plotter/assets/29923628/77fd2389-b10c-4a94-b310-4ea799e05a9c)


Result and image attached

![Screenshot 2024-05-08 172739](https://github.com/svenhb/GRBL-Plotter/assets/29923628/7ef6a726-ba91-4951-a307-26a7142bee4e)

![unnamed (2)](https://github.com/svenhb/GRBL-Plotter/assets/29923628/68d63f2b-e03d-48f6-8a99-5656cab925d3)



Surely this move instantly chip off the tip of the rotary blade ( well im using cheap chinese ones, gotta try with the olfa japan blades later)

**Comment by svenhb** [comment]
From lines 433, 434 -> A0.51 to A-0.54 are just 1° difference, where is the 180° jump!? It is a motion almost only on +X (right) direction.
From the 2D view and your picture the motion must be almost only +Y or -Y (up or down) direction...
Can you upload the original graphic and show your import settings?

**Comment by svenhb** [comment]
And also the height map

**Comment by vinevinz** [comment]
> From lines 433, 434 -> A0.51 to A-0.54 are just 1° difference, where is the 180° jump!? It is a motion almost only on +X (right) direction. From the 2D view and your picture the motion must be almost only +Y or -Y (up or down) direction... Can you upload the original graphic and show your import settings?

Yes it is 1 degree difference but the blade goes from positive to negative value. Isn’t that will rotate the blade 180? I will share the file details later.

**Comment by vinevinz** [comment]
Shared here:

1. SVG File
2. Generated G-Code with Height Map applied
3. Height Map
4. Machine settings

You could try the gcode with path simulation, it shows the blade direction turning 180

https://drive.google.com/drive/folders/1_cNrTTfut05U-jefynt6wD9UhelFIcta?usp=sharing

**Comment by svenhb** [comment]
I could reproduce the problem with your data and fix. Please try: https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_Setup_1731h.exe

**Comment by vinevinz** [comment]
> I could reproduce the problem with your data and fix. Please try: https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_Setup_1731h.exe
> 
> To reduce data, I would use this settings: ![image](https://private-user-images.githubusercontent.com/19973251/329523987-00b99e31-0973-49ae-9a66-44e0f67bd229.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTk5ODAsIm5iZiI6MTcxNTU5OTY4MCwicGF0aCI6Ii8xOTk3MzI1MS8zMjk1MjM5ODctMDBiOTllMzEtMDk3My00OWFlLTlhNjYtNDRlMGY2N2JkMjI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDExMjgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyNzU0YzdmZTUxMGYwOTk0NTI1OTcyZjZkMmRlODUwNzllNTVkNDNjZWM5NTA2Njg2ZTcwNzQ3MmVhZTZjMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NKNX2mYiQ1w2MngRrsHKT-_62dqmQA0kq5V5VS9M4vI)

Hi sven,

this version works like charm fixing that bug. Thank you.

Apparently I can’t use your settings suggestion. Those settings will work fine with pen with bigger tip, but with blades only 0.3mm thick, it will cut jagged edges not smooth curves

**Comment by svenhb** [comment]
Now included in new release: https://github.com/svenhb/GRBL-Plotter/releases
