### ISSUE TITLE
Performance issue with adaptive path

### ISSUE THREAD

**Issue by MarioPerini** [svenhb/GRBL-Plotter#39]
Hallo Sven

Danke für diese Software, echt gut gemacht!

Unfortunately i have a big performance issue with grbl-plotter 1.2.1.0 if i load big nc files.
I started using Fusion360 and got a 2.7MB gcode. The software seems not able to handle this.
the grbl-controller can handle the file so there should nothing be wrong.

My Laptop also should handle it with 32GB RAM, i7-8550U, SSD etc.

So is there a known bug on big files?

Best regards
Mario

**Comment by svenhb** [comment]
Vielen Dank.
Up to know I never tried such big files, perhaps it's possible for you to upload one here, so I could play around with meaningful data?

**Comment by MarioPerini** [comment]
Hi Sven

I send it by mail.

Best regards
Mario

**Comment by svenhb** [comment]
Ok, thanks.
I could load the code without problem on Win7 i5-6500 3,2GHz 8GB Ram.
Zooming is a bit slow. No hardware to check a real run.
What is the actual problem "...seems not able to handle this"?

**Comment by svenhb** [comment]
At home with my old notebook i5 M460 2,53GHz 4GB RAM I can also load the GCode. But I get a message about unknown code "%" in first and last line (option enabled in Setup - Control - Load GCode).
2D View is much slower than with the other PC :-(

**Comment by MarioPerini** [comment]
i have no idea what happens before...  i even did a restart and had the problem again. the plotter hang up und did not respond to clicks. now it works without any issue. I'm really sorry for false reporting.

**Comment by MarioPerini** [comment]
![image](https://user-images.githubusercontent.com/40631006/49834007-a2546c00-fd9b-11e8-8c35-54f1bd7e4af5.png)
