### ISSUE TITLE
Plot information

### ISSUE THREAD

**Issue by Marmadoc** [svenhb/GRBL-Plotter#390]
Hi.
As a plotter I have > 10 000 lines/figures. Software simplified it to 10 000 figures.
My question - can I get total path length?

**Comment by svenhb** [comment]
You may increase this value:
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/67301464-d65e-40ae-8392-89285e6dca81)

**Comment by Marmadoc** [comment]
I know about that. But how to get total length of all paths together? I saw on internet that somebody in description added - total length and total time. I do not know by what software. Maybe it is available in this software as well.

**Comment by svenhb** [comment]
If you activate group, you can get the path length of the group:
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/3b23b329-32c6-4957-8c41-c611e8db437c)

**Comment by svenhb** [comment]
I will check if I can add the total path length into the header section

**Comment by Marmadoc** [comment]
Thank you for your hard work. Sounds fantastic. Maybe not header section but to G-Code dimension Window info.

**Comment by svenhb** [comment]
Check new version: https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_Setup_1731d.exe

![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/a20fbf2a-b52c-44bb-b5d8-a3e89b5d14cb)

**Comment by Marmadoc** [comment]
It is fantastic - thank you very much.
Only one more think - before I created my ini file (case). After new installation my file was deleted. Can you keep setup file during new installation?

**Comment by svenhb** [comment]
Hm, deleting new files should not happen. If the file is from installation, but newer, you will be ask if it can be overwritten. Completly new files (created by you with uniqe name) should not be touched at all...

**Comment by Marmadoc** [comment]
Perhaps i did something wrong. Before I install software in my own location.
Now installation is available only for default location "C".
My ini file is still in previous location, but I'm running out of space on drive C.

One more - maybe you didn't see my post before Graphic Imports -> GCode Generation ->
Lasemode - use S0 instead of M5 to switch off Laser
I think Lasemode is wrong spelling -> Lasermode.

**Comment by svenhb** [comment]
With magnifier, the "r" is there...
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/e750742b-db5f-4e2a-9e32-d9680d51532b)
But I separate the word for better reading:
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/f511996c-77af-462b-9101-6344aa576057)

**Comment by Marmadoc** [comment]
super

**Comment by Marmadoc** [comment]
Thank you

**Comment by Marmadoc** [comment]
Hi Svenhb. I do not know what I did but Path length info disappears from G Code dimension window. Is not in header either.
I did try to download this software from link what you gave me before - but is  not there - Page not Found.
Any idea how to fix it?

**Comment by svenhb** [comment]
I updated the test release: https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_Setup_1731f.exe
Unreleased test version is placed on main page: https://github.com/svenhb/GRBL-Plotter

**Comment by Marmadoc** [comment]
.

**Comment by svenhb** [comment]
Now included in new release: https://github.com/svenhb/GRBL-Plotter/releases
