### ISSUE TITLE
help plotting multi layer svg. manual pen change.

### ISSUE THREAD

**Issue by xn-78j0enb** [svenhb/GRBL-Plotter#391]
I want to plot a multi layer svg. How do I plot one layer at a time then return to 0,0 and pause for manual pen change?

I enabled these settings:
Graphics Import→G-Code Generation→General Options→Add Tool Change command Tx M06 , Add Pause (MO)
Graphics Import→Path Import→Grouping and Tools→Group objects of same property, group by layer.

when I run the simulation it correctly draws the first layer then continues on to the next layer without pausing.

**Comment by svenhb** [comment]
The simulation does not take tool changes into account - sorry. You may check with your plotter and motor-power switched off.
Tool change option should look like this:
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/f8274742-96ee-4296-800b-9ca88f28fea6)

**Comment by Marmadoc** [comment]
It is very important information for me as well.

**Comment by svenhb** [comment]
To move to 0;0 for pen change, you need to set the move command here, like this:
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/1fa1f7f1-b2b2-4723-8aad-1a718dbd11a7)

**Comment by xn-78j0enb** [comment]
This resolved my issue. Thank you.|
Great software. Great support.
