### ISSUE TITLE
servo for pen up and pen down

### ISSUE THREAD

**Issue by Marmadoc** [svenhb/GRBL-Plotter#392]
My plotter with Your software is working.
I have only one problem. Pen down - it is very fast movement, and when hit the surface creates bigger dot.
I saw one your plotter with stepper motor for pen lifter. It works very well, what i Can see, because the movement is much slower.
I was thinking to switch from servo to stepper.
I can add extra arduino board to change servo speed, but
maybe it is possible  to add it to grbl software and add option speed for pen Up and pen Down.
I'm not a programmer but I know how to do this with extra arduino board.

**Comment by svenhb** [comment]
You could try to work with a ramp.
1st find the zero value, where the pen just touches the paper:
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/5f86d04d-2c0b-43ae-9ec3-3901dfaf6ad9)
2nd enable the ramp:
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/3d1c3b6e-8979-49b0-93d2-2617b620a170)

Then a line will be drawn by such code:
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/7773e151-d2ea-4a81-85f6-206b400c9253)

**Comment by Marmadoc** [comment]
I do not have P91 Pen Zero

**Comment by Marmadoc** [comment]
Now I'm stuck. I have Unknown Status - and can't do anything. Laser Grbl and UGS works but not GRBL Plotter.
Reinstall, restart, reload - nothing.
Any Idea what is wrong.

**Comment by svenhb** [comment]
>I do not have P91 Pen Zero

Just press "Advanced settings"

>I have Unknown Status -

Are you sure the serial connection is done? Perhaps wrong port?
You may "Scan Ports" and try an other port?
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/ef0070cb-749a-4583-a65b-462fa41111ac)

Some time a hard reset is needed (my experience with Arduino mega) to be able to connect.

**Comment by Marmadoc** [comment]
Thank You. Regarding servo - I have to try it.
Regarding U known Status - today all is OK. I do not know what was wrong before.
Thank you

**Comment by Marmadoc** [comment]
A like to assign one button to Pen in Zero position.
For Lower Position the line is M3 S#GMIS
For Upper Position the line is M3 S#GMAS
What line to be for zero(middle) position M3 S#G???

**Comment by Marmadoc** [comment]
Perfect. Thank you

**Comment by Marmadoc** [comment]
Thank You
