### ISSUE TITLE
GRBL plotter with laser

### ISSUE THREAD

**Issue by Marmadoc** [svenhb/GRBL-Plotter#393]
I read that GRBLPlotter can be used with laser as well.
I like to try it.
I have LT-80W-AA PRO laser by LaserTree.
I have laser module - 3 wires, and laser module driver adapter P-DA-01 with two wires + Power 12V.
It looks like two wires are Signal and GND.
My question is can I use it with CNC shield V3 - like with servo Z+?
I understand I have to change GRBL setup - but will be OK with GRBLPlotter (instead of servo)?
Thx

**Comment by svenhb** [comment]
Yes you need the "regular" grbl version which creates PWM from 0% to 100% - https://github.com/gnea/grbl
If you use the servo-grbl version your laser will be very week. Servo uses 1ms - 2ms high / 20 ms low, which results to an energy of 5% to 10%.

**Comment by svenhb** [comment]
Here I combined plotter and laser: https://youtu.be/Ebe2kFlE058?si=TBMYBpiT18W6Bk85
But pen is controlled by Z axis, not servo.

**Comment by Marmadoc** [comment]
Thank you. I will try it and let you know.

**Comment by Marmadoc** [comment]
Thx

**Comment by Marmadoc** [comment]
.
