### ISSUE TITLE
SVG import help

### ISSUE THREAD

**Issue by JoeBeef** [svenhb/GRBL-Plotter#394]
Hi,

Is there a way to specify if I want an inside or outside cut when importing an SVG file ?

Regards,

Jean

**Comment by svenhb** [comment]
Not during import, but you could try radius compensation with positive or negative value:
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/85c618b5-c8f4-406b-bd70-0fef266d21f3)

**Comment by JoeBeef** [comment]
Hi,
Thanks , radius compensation seems to do the job.
I will give it a try.

Regards,
Jean
