### ISSUE TITLE
4 axis tangential knife

### ISSUE THREAD

**Issue by abd97khateeb** [svenhb/GRBL-Plotter#397]
Hi, When i start the 4D A tangential machine,  A axis rotates correctly in linear shapes, but in curved shapes it rotates differently than the simulation. What is the reason for this?
 video:
https://drive.google.com/file/d/1kFYyj0nKejBGwWmeREaVROWiceNVjwZd/view?usp=drive_link
Kopy video:
https://drive.google.com/file/d/1kFYyj0nKejBGwWmeREaVROWiceNVjwZd/view?usp=drivesdk

**Comment by svenhb** [comment]
I asked for access to see the video...

**Comment by abd97khateeb** [comment]
İ accept

**Comment by svenhb** [comment]
Ok, my first thoughts:
- there is no feedrate given in the gcode - that is propbably the problem for the simulator.
Will try to fix that.
- you didn't define a pen up/down-translation (no code before "(PD)"): https://grbl-plotter.de/index.php?id=form-setup-3#pen-up-down
- it is just a simulation, better check on real system
- Why the marked tabs are highlighted?
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/eee2a37c-fc5c-4084-89a5-91e2642ba76c)

**Comment by svenhb** [comment]
>you didn't define a pen up/down-translation (no code before "(PD)"

perhaps it is a bug, did you enable "Process meta data for SVG graphic?
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/3091bb6a-da7c-4eba-a4cc-50261cb098d4)

**Comment by abd97khateeb** [comment]
No

**Comment by abd97khateeb** [comment]
عندما يكون الكود بهذا الشكل G02 x10 y10 I0 J10 A90 فانه ينفذ اولا قسم xy ثم A. اعتقد ان المشكلة في انشاء الكود لأنه اعطا نفس المشكلة في برنامج محاكاة آخر.

**Comment by abd97khateeb** [comment]
When the code is like this: G02 x10 y10 I0 J10 A90, it executes the xy section first, then A. I think the problem is in the code generation because it gave the same problem in another simulation program.

**Comment by abd97khateeb** [comment]
Is there another way to write code that contains a circular shape?

**Comment by svenhb** [comment]
If I use your settings, my code looks like this - with Z axis:
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/9f6c9b12-4b40-49b2-ac71-4b08909569ca)



When you experimenting with settings, you should disable "code add on" - the "old" code stays on top....
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/e015a44d-6946-4dd1-b6a5-1e38bb949c74)

**Comment by abd97khateeb** [comment]
Ok thanks i well try.

**Comment by abd97khateeb** [comment]
can I convert Z axis to A axis when creating the code because i used Z axis for tangential knife ?

**Comment by svenhb** [comment]
If you use Z axis for tangential, you may use a servo (controlled via PWM) to lift the knife. Then you need to select this options:
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/2eb59bc0-4300-4b75-8e6d-f000e0892060)
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/fda73dc8-b999-4d7b-b3c8-453250c8a870)

Also note: https://grbl-plotter.de/index.php?id=tangential-knife-1
Units per turn: if using 'Z' as tangential axis, the feedrates will slow down the rotation speed. Using just e.g. 36 units per turn may increase the performance.

**Comment by abd97khateeb** [comment]
ok i will try this options, thanks.

**Comment by abd97khateeb** [comment]
How can I modify the drawing to combine with the black drawing?
![image](https://github.com/svenhb/GRBL-Plotter/assets/169066818/29e1aff5-add8-4cdd-ba4d-7ef3c672cdeb

**Comment by svenhb** [comment]
What do you mean with "combine"? For SVG graphic changes I would use Inkscape...

**Comment by abd97khateeb** [comment]
My gcode is difrent than svg shape.
![IMG_20240512_211359](https://github.com/svenhb/GRBL-Plotter/assets/169066818/b1347301-1f72-4b65-8e58-18c9c29cb342)

**Comment by svenhb** [comment]
I assume you enabled some additional options, please check code and GUI:
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/6a2cfbc4-dd83-444b-a515-dd2bba72211e)

**Comment by abd97khateeb** [comment]
thanke you for helping
