### ISSUE TITLE
How can i set tool offset?

### ISSUE THREAD

**Issue by MayHanGroup** [svenhb/GRBL-Plotter#402]
Hi,  when i import a svg file with a rect size100mm*100mm,     the gcode example :
G01 X100.000 Y0.000
G01 X100.000 Y100.000
G01 X0.000 Y100.000
G01 X0.000 Y0.000

But when i use a tool diameter 10mm ,  i will get the path  should be like X5.0 ~ X95.0  actually,    i want to find any setting,but not found.    can you help me?

**Comment by svenhb** [comment]
For such a simple form, you could use "Gcode from shape" using inside or outside shape option:
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/ec345cfa-dcf2-4a41-8294-b4579dc3cd3a)

You can also try "Radius compensation" with positive or negative value for the radius of the tool:
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/b1e6d0e8-ba46-43b8-bea8-d4179d4231fd)

**Comment by MayHanGroup** [comment]
oh,it's great!  and also,  is the polygon can use pocket function?   i find the option in "Create Simple shapes" , but  in the form "Create Jog path" i can't find any options,  is jog path not support pocket?    
such like this path
![QQ图片20240522214624](https://github.com/svenhb/GRBL-Plotter/assets/8087464/a26f2a9a-74f8-4eb6-876f-9d164d0af84a)

**Comment by svenhb** [comment]
You could try hatch fill for this purpose:
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/769c412b-f2a0-46bb-873b-bc42436ef4d7)

**Comment by svenhb** [comment]
So you would like to have a mix of "Create Jog path" and "Create simple shapes"?
A "Jog path" including pen up/down function to create shapes like in the link you provided.... Have to think about.
Did you try to use Inkscape and copy&paste the shapes?

**Comment by MayHanGroup** [comment]
No,  i don't know how to use Inkscape .     when i try to use the "Hatch fill" setting and the "Radius compensation" both , the result looks not as expected .   i there any way to using tool diameter auto when the gcode generate?   i means like the settings in the form "Create Simple shapes" .   
![3](https://github.com/svenhb/GRBL-Plotter/assets/8087464/75a8c711-13c6-464b-8485-13e197ea8abe)
![1](https://github.com/svenhb/GRBL-Plotter/assets/8087464/4f5d950d-b973-4a64-9dfd-b1c7f41f1c1a)
![2](https://github.com/svenhb/GRBL-Plotter/assets/8087464/e5e409e3-d378-4f75-9535-aa1105b41311)

**Comment by svenhb** [comment]
>i there any way to using tool diameter auto when the gcode generate? 

Not yet. The problem would be, how to determine if the offset should be inside or out side the shape. You must follow a "design rule" when making your drawing (CW and CWW path). What tool do you use (if not inkscape or LibreCAD - both I like to use).
E.g. a picture frame: for the outside contour, the offset must be outside, for the inside contour inside. If the tool-offset is to the left, the outer contour must be CW and the inner CCW.
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/9334375d-350c-4fd9-af44-9d10f106d4f4)

**Comment by MayHanGroup** [comment]
ok i know.  thank you for your help.  @svenhb
