### ISSUE TITLE
Circles not round after Plotting

### ISSUE THREAD

**Issue by GenerativeOlli** [svenhb/GRBL-Plotter#405]

**Comment by GenerativeOlli** [comment]
Note: The txt file contains a gcode I generated later the same way. I dismissed the original when I closed the window.

**Comment by GenerativeOlli** [comment]
please ignore. I found the problem being the way my design script calculated stuff.

**Comment by svenhb** [comment]
Ok, so GRBL-Plotter works as expected?

**Comment by GenerativeOlli** [comment]
Yes it does! Thank you for the great work!

Sven ***@***.***> schrieb am So., 2. Juni 2024, 11:41:
