### ISSUE TITLE
The current shortest path sorting algorithm is not optimal

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#406]
The current shortest path sorting algorithm is not optimal

Plotter software sorting results
![2](https://github.com/svenhb/GRBL-Plotter/assets/53146195/0fe20d9b-9f74-4216-a480-a89716b09148)

Sorting results from other software
![1](https://github.com/svenhb/GRBL-Plotter/assets/53146195/f3ea7268-02b1-41d5-b715-b6924cf8953d)

Test files

[666.zip](https://github.com/user-attachments/files/15527373/666.zip)

**Comment by svenhb** [comment]
It depends on the start-point. In the current version sorting starts with most upper-left object (always).
In the next version you can decide where to start:
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/23367c93-9d7c-440b-8426-a290a9509c39)

**Comment by svenhb** [comment]
Result with new option - start at lower-left edge:
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/01382d27-b68b-42c3-a8ac-fde70a27d0b1)
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/e0888199-1412-48ee-8e59-9963da2d22d4)

**Comment by lianzaozi** [comment]
Thank you for your reply. I appreciate your hard work and look forward to the sorting effect in the next version.
Can you add a line of information below to list the total length of the empty movement path and the total length of the machining path.
![image](https://github.com/svenhb/GRBL-Plotter/assets/53146195/a0033867-843c-42fb-8deb-d8e367598f96)
