### ISSUE TITLE
UI layout malformed

### ISSUE THREAD

**Issue by zengfanfan** [svenhb/GRBL-Plotter#409]
**Describe the bug**
many detail of UI is not hidden when overflow box borders, see:

**To Reproduce**
Not sure if it relates to windows 10 (22H2) layout scalling:
<img src="https://github.com/svenhb/GRBL-Plotter/assets/8079595/91e507fb-ba55-4a1f-a793-290b32b90a6e" width="600">

**Expected behavior**
all UI shows good, and can be interactive with.

**Screenshots**

> many dialog/tabs has this problem, i just show some of them:

![image](https://github.com/svenhb/GRBL-Plotter/assets/8079595/6806ee9a-9482-432c-b9b9-c3d3ed0eef1e)
![image](https://github.com/svenhb/GRBL-Plotter/assets/8079595/f88dcfad-ddb7-4c4b-b79f-9cd05cef44b8)
![image](https://github.com/svenhb/GRBL-Plotter/assets/8079595/14e7987c-6a9c-4160-b7c6-584566e87046)

**Comment by svenhb** [comment]
I know, but don't know how to fix.
But you can widen the window:
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/6a86e685-21bb-45dd-b4a7-15fcf9bfb38d)

Also this infomration may help: https://grbl-plotter.de/index.php?id=quick-guide&setlang=en#highdpi

**Comment by zengfanfan** [comment]
Yes. This alleviated the problem.
