### ISSUE TITLE
Design Update

### ISSUE THREAD

**Issue by RasyidUFA** [svenhb/GRBL-Plotter#41]
Currently, I am working on Design update for GRBL Plotter, can you describe what to-do and not to-do for this kind of issues?

Are you accepting design overhaul? 😆 

because some people have strict rule for their OSS

**Comment by svenhb** [comment]
You mean other arrangement of controls? 
What do you mean "what to-do or not to-do" any example?
What kind of rules for OSS (you mean OS?)?

**Comment by RasyidUFA** [comment]
> You mean other arrangement of controls?

Yup, some arrangement will be nice, UI Change (Icons, Graphics), and Language, *vielleich?

> What do you mean "what to-do or not to-do" any example?

Some people strict others touch some area of their program, like Architecture, UI, etc.

> What kind of rules for OSS (you mean OS?)?

Open Source Software,  this is a great program and it will be awesome if it's provided with contributing guidelines.

Like this 
[Good Contrib Guidelines](https://gist.github.com/PurpleBooth/b24679402957c63ec426)

**Comment by RasyidUFA** [comment]
This is some issue with DPI Scaling. and some fix I've made

![scroll](https://user-images.githubusercontent.com/7088039/50309328-03352000-04d1-11e9-9a65-1ece442c347d.JPG)

Providing small detail in UI can be a meaningful Improvement

**Comment by svenhb** [comment]
Did you change the size of this window? 
On my Pc this window opens like this:
![image](https://user-images.githubusercontent.com/19973251/50365629-cd964280-0575-11e9-809c-54c5f8befa32.png)

What did you change in windows?

**Comment by RasyidUFA** [comment]
Achso, the window is DPI-unaware. 

then it will not render properly on big screen.

**Comment by svenhb** [comment]
No idea what to change
