### ISSUE TITLE
Creating code using G91 instead of G90 with GRBL-plotter

### ISSUE THREAD

**Issue by adiqadu** [svenhb/GRBL-Plotter#410]
I'm fairly new to GRBL plotter. I'm trying to find this function: to create Gcode using G91 instead of G90.
Not able to find this option.
Any help with this?

**Comment by svenhb** [comment]
This is the option you are looking for: but be carefull it is may not implemented (or useful) for all possible options (e.g. 'command extension').
![image](https://github.com/svenhb/GRBL-Plotter/assets/19973251/852b685a-fdb6-4a4d-a788-3414bbe46d75)
