### ISSUE TITLE
GRBL HAL using Teensy 4.1

### ISSUE THREAD

**Issue by mdsultan11** [svenhb/GRBL-Plotter#412]
Hi svenhb,

Hope you are doing well.
I have come back to you with another new request. I have purchased Teensy 4.1 controller board for my new CNC machine. i need you help to setup the controller board, drivers and software for grblHAL.
Please reply once you are available.
Thanks in advance.

**Comment by svenhb** [comment]
I don't have experience with grblHAL, better ask here: https://github.com/grblHAL
