### ISSUE TITLE
Manually set Tool Coordinates

### ISSUE THREAD

**Issue by stujoult** [svenhb/GRBL-Plotter#413]
**Describe the solution you'd like**
Form to manually set current Tool Coordinates

**Describe alternatives you've considered**
Something like UGS
![38573008-1225c24e-3cf5-11e8-85ae-89694e1feea1](https://github.com/user-attachments/assets/4854e391-c352-40e9-955b-2af11dc468b1)

**Comment by svenhb** [comment]
Good idea, need to think about where and how to implement...
- click on digital read out, to show edit box like in your example? Perhaps not intuitive
- right click on joystick control to open extra form with controls?
- or dropdown box below joystick to show controls?
![image](https://github.com/user-attachments/assets/b3a71f50-52cc-49f2-9dd5-17a541c4d862)
![image](https://github.com/user-attachments/assets/b9fc4840-82b3-4f9d-b794-483459f990a8)

**Comment by stujoult** [comment]
Something like this maybe?
![set tool](https://github.com/user-attachments/assets/ee6615a5-e77d-41ac-ad18-4e6f9b9de3a5)

**Comment by svenhb** [comment]
I put it into the control/ jogging area.
Need some tests for other new features, before uploading.
![image](https://github.com/user-attachments/assets/467949fb-5a7e-49e8-a108-85bd706b5847)
![image](https://github.com/user-attachments/assets/5c93f5a9-1f8c-4440-8f34-256122acbef3)

**Comment by stujoult** [comment]
I think it might confuses people. Instead of jogging to specific location like what user would expect, it only moves tool pointer.
Also that STOP Jogging is a good feature. My monkey fingers keep misclicking 5 instead of 1.

**Comment by svenhb** [comment]
>I think it might confuses people. Instead of jogging to specific location like what user would expect, it only moves tool pointer.

I don't get it. In my eyes: Tool-pointer = tool position = work coordinates of the machine...
Move to zero ![image](https://github.com/user-attachments/assets/5afce1a6-b596-4d13-8a2a-bcbe3e142418) is the same as this button ![image](https://github.com/user-attachments/assets/70df0c34-a22b-4569-b5e7-14c983a481ee)
To move to X 100 you put 100 here and press "Move to".
![image](https://github.com/user-attachments/assets/c33554d7-d578-490f-9409-46732239a4c0)
 

 

>My monkey fingers keep misclicking 5 instead of 1.

You talk about the joystick control? Did you know you can resize it`?
![image](https://github.com/user-attachments/assets/07d7041c-d5f3-4abb-9cf7-1c8dc8c2fef6)

**Comment by stujoult** [comment]
> I don't get it. In my eyes: Tool-pointer = tool position = work coordinates of the machine...

I was talking about feature to set virtual tool coordinate without moving the actual tool coordinate. Like when my spindle currently at X10Y75, [Zero XY] only set tool pointer to X0Y0 and spindle position remains unchanged.


> You talk about the joystick control?

Yes. But it is modern laptop touchpad problem. Instead of just click, it will slightly moves cursor and click. My brain is already hardwired to good old touchpad design.
![z3299857764655-c5af566dd2f2791677afe75a1d389072](https://github.com/user-attachments/assets/be08d9ef-6b8a-4255-821e-b6d40da787ea)
The good old design
![touchpad_(3)](https://github.com/user-attachments/assets/75f9789a-40ee-432a-8f3c-7a6c68556f9a)

**Comment by svenhb** [comment]
Got it :-)
Regarding the touchpad: I can't work with it and that's why I always have a mouse connected...

**Comment by stujoult** [comment]
No [Set new origin] for rotary axis?
And missing [STOP Jogging] button.
Thanks in advance.
![grblplotter](https://github.com/user-attachments/assets/bdc4e269-11cf-4653-add6-8912364e6e5f)

**Comment by svenhb** [comment]
Did you connect a controller? 
"Stop Jogging" only appears if connected and grbl version >= 1.1
Set new origin A axis appears if connected  and axis available

**Comment by stujoult** [comment]
Well I only tested it on 0.9. Will test it on Mega later.
