### ISSUE TITLE
Wrong Dimension when open this file

### ISSUE THREAD

**Issue by zengfanfan** [svenhb/GRBL-Plotter#414]
**Describe the bug**
When open a g-code file, the minimal Z value is not right. ( should be 0, but we got 10)

**Screenshots**
![image](https://github.com/user-attachments/assets/3c954e40-4c2c-4aa7-b262-19269193fb8c)

**the g-code file**
[bug.gcode.txt](https://github.com/user-attachments/files/16805785/bug.gcode.txt)

**Comment by svenhb** [comment]
Ok will check.
You can also upload files, instead of copying the content....

**Comment by stujoult** [comment]
Reproduced in older version.
It treats `z0` as non number.
![grblplotter](https://github.com/user-attachments/assets/1b580641-2f06-40c8-a938-1edd02a83dd8)

**Comment by svenhb** [comment]
I don't remember why I did it this way: dimension was only updated for Z, when z-position is not actual grbl z-position:
`if (posWasSet && (newLine.actualPos.Z != Grbl.posWork.Z)) { xyzSize.SetDimensionZ(newLine.actualPos.Z); } `
Is fixed now, I make a new release after finishing other changes...

**Comment by zengfanfan** [comment]
ok. looking forawd to it.

**Comment by svenhb** [comment]
Check new release: https://github.com/svenhb/GRBL-Plotter/releases
