### ISSUE TITLE
Replace G2/3 by lines function

### ISSUE THREAD

**Issue by yang-shaoxiong** [svenhb/GRBL-Plotter#415]
The Replace G2/3 by lines in the G-Code Transform in 1.7.3.1 will report an out of memory error when used, but the actual computer still has a lot of memory. What is the reason for this?

**Comment by svenhb** [comment]
What are your settings here? 
To reduce data amount:
- Try to decrease "Number of line segments in curves"
- Try to increase "Step width on circumference of arcs"
![image](https://github.com/user-attachments/assets/8a247e44-125c-4c72-9683-24e636ed7299)

**Comment by yang-shaoxiong** [comment]
Isn't this a file import? I'm
![Uploading Replace.png…]()
 talking about the Replace G2/3 by lines function in the G-Code Transform menu

**Comment by svenhb** [comment]
I checked the code, it will use this parameter - also for [Menu - G-Code Transform - Replace G2/3]: 
![image](https://github.com/user-attachments/assets/f6d51508-a843-4cb3-beaf-26c5e088975f)

**Comment by yang-shaoxiong** [comment]
Ok, thanks for your reply

**Comment by svenhb** [comment]
You may experiment with a simple G-Code and check the amount of lines after replacing G2/3 with different step-widths...
With step width 0.01 more than 6000 code lines, 
with step width 0.5 less than 150 code lines and it is acurate enough.
```
(<Figure Id="1" Geometry="Shape" >)
G00 X-10.000 Y0.000  
G01 Z-1.000 F400 
G02 X-10.000 Y0.000 I10.000 J0.000  F500 
G00 Z2.000 
(</Figure>)
```

**Comment by yang-shaoxiong** [comment]
That's all. Thank you for your explanation.

**Comment by yang-shaoxiong** [comment]
Hello, can we pay you to customize some features for us? It can be modified on the basis of the original.

**Comment by svenhb** [comment]
No paid orders. List the features, let's see what I can implement and donate ;-)

**Comment by yang-shaoxiong** [comment]
I want to customize the path and the cutting point, and use PLT to represent, not G-Code.

**Comment by svenhb** [comment]
Then it is probably easier to use Inkscape https://www.inkscape.org/ (very good for path editing) and export there to *.plt

**Comment by yang-shaoxiong** [comment]
Good. Thanking

**Comment by yang-shaoxiong** [comment]
Hello author, I try to use Win32_ API for USB communication in GRBL project, but can not get USB device, can get it in other projects. Is this what permissions are set for the project?

**Comment by svenhb** [comment]
No idea what the problem could be. Longer time ago I run GRBL-Plotter on Win-XP but PC was too weak...
Did you install the correct USB driver for your hardware? (e.g. CH 340 -> https://www.google.de/search?q=arduino+ch340)
