### ISSUE TITLE
G2/G3 don't recognize P(full circle) parameter

### ISSUE THREAD

**Issue by zengfanfan** [svenhb/GRBL-Plotter#416]
#### How ?
open the attached file, which includes a 540°(1.5 circle) arc.

#### Bugs
1: the preview image only shows 0.5 circle;
2: it runs 0.5 circle in simulation, but 1.5 circle in real machine.

**preview:**
![image](https://github.com/user-attachments/assets/51fbb26c-4d8a-458c-834e-adde34cd3f0c)

**test file:**
[bug.gcode.txt](https://github.com/user-attachments/files/16988009/bug.gcode.txt)

**Comment by svenhb** [comment]
Too bad, the P-value in `G2 X165.0 Y132.0 I44 J22 P2` is not supported by original grbl (https://github.com/gnea/grbl) and also not supported by GRBL-Plotter.
Original grbl gives this error: 
```
< error:36 	Unused value words found in block.
! Last processed 'G2X165.0Y132.0I44J22P2'  line-Nr:24

```
Can't you use a pre-processor to avoid the P-word?

**Comment by zengfanfan** [comment]
ok.

**Comment by svenhb** [comment]
Perhaps I could fix it for the 2D-View: https://github.com/svenhb/GRBL-Plotter/releases
