### ISSUE TITLE
Simulation not wait on command G4

### ISSUE THREAD

**Issue by zengfanfan** [svenhb/GRBL-Plotter#417]
**Describe the bug**
Simulation ignore command: `G4 P10`

**Expected behavior**
wait 10 seconds on `G4 P10`

**version**
1.7.3.2

**Comment by svenhb** [comment]
It is simulation: no time to wait for G4 😉

**Comment by zengfanfan** [comment]
> It is simulation: no time to wait for G4 😉 How to adapt G4 delay for different simulation speeds? Same factor?

yes. It make sense to apply speed on G4 .

**Comment by svenhb** [comment]
I think I implemented the  consideration of G4 command: https://github.com/svenhb/GRBL-Plotter/releases
