### ISSUE TITLE
Version 1.7.4.0 of the plotter software source code will report errors when compiled

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#419]
Version 1.7.4.0 of the plotter software source code reported an error interface when compiling
![image](https://github.com/user-attachments/assets/35a79b38-117b-4c3d-a1d0-f77cb0f04eb8)

**Comment by svenhb** [comment]
I uploaded the missing files to https://github.com/svenhb/GRBL-Plotter/tree/master/GRBL-Plotter/data/buttons
