### ISSUE TITLE
Suggestion : COM CNC Window should allow Hide

### ISSUE THREAD

**Issue by RasyidUFA** [svenhb/GRBL-Plotter#42]
The COM CNC Window are unable to close, but as tool window, it should be able to hide it when not needed.

Add Button to show detailed Serial information, and change the COM CNC window close behaviour to make it hidden.

It will give users options..

**Comment by RasyidUFA** [comment]
Aha so it's already provided.

**Comment by svenhb** [comment]
Already implemented
