### ISSUE TITLE
The calculation of the total length of the processing trajectory in the plotter software version v1.7.4.0 is correct, but the calculation of the total length of the empty trajectory is incorrect

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#421]
![111111111](https://github.com/user-attachments/assets/d38bea91-22f4-43dd-a7e5-1abfcdb47306)
![22222](https://github.com/user-attachments/assets/5c8ffec7-db44-4ee3-9f8e-12ecdf3c10e0)

The calculation of the total length of the processing trajectory is correct, but the calculation of the total length of the empty trajectory is incorrect. The correct total length of the empty trajectory is 60mm

test file

[111.zip](https://github.com/user-attachments/files/17575147/111.zip)

**Comment by svenhb** [comment]
The first pen-up path will not be taken into account, because the actual tool position can be anywhere.
