### ISSUE TITLE
Version 1.7.4.0 of the plotter software reported an error in the source code when using text to generate the GCode function

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#422]
![1](https://github.com/user-attachments/assets/68cfd85a-7260-4230-bfea-2f518059d745)
![2](https://github.com/user-attachments/assets/a01664cb-fbdf-478c-9547-e009993c944c)
![123](https://github.com/user-attachments/assets/1c01f863-0a2c-4f48-9e6b-08a6773a48d0)

**Comment by svenhb** [comment]
Can you change the marked line
![image](https://github.com/user-attachments/assets/75ee2699-4dfc-42a5-97fb-25f3a0875abb)
 to
`                if ((textFont != null) && (textFont.Size != null) && (textFont.FontFamily != null))`
and check if exception disappears?

**Comment by lianzaozi** [comment]
There are other errors
![11111111](https://github.com/user-attachments/assets/88d96d58-1542-4dce-8200-cf1ab16e08f0)
![222](https://github.com/user-attachments/assets/4ddb6800-157e-45b1-a9d4-00c439e6b2be)

**Comment by svenhb** [comment]
The other error appeared after doing the change?
              `  if ((textFont != null) && (textFont.Size != null) && (textFont.FontFamily != null))`

**Comment by lianzaozi** [comment]
YES

**Comment by lianzaozi** [comment]
Hello, how do I open the second window connected to the com port, which is the window shown in the picture
![123](https://github.com/user-attachments/assets/002d589a-afd9-4d3b-89f1-cb733c3988b2)

**Comment by svenhb** [comment]
![image](https://github.com/user-attachments/assets/e235c497-2347-487d-877c-d2b74f7c8d2c)

If you want the window on program start:
![image](https://github.com/user-attachments/assets/270a1144-139d-494c-a406-7de86af623f5)

**Comment by lianzaozi** [comment]
Thank you very much. Following your instructions, I have already opened this window

**Comment by lianzaozi** [comment]
When using Gcode created from text, the source code will run incorrectly, but running the GRBL-Plotter.exe file under the debug folder will work fine, I was surprised.

![123](https://github.com/user-attachments/assets/d3c33170-25fd-4fa5-a40d-0a5a7bd00b87)

**Comment by svenhb** [comment]
It works because of the "try" / "catch" block, which then handles the error you got.

**Comment by lianzaozi** [comment]
Is there any good way to solve the problem of source code debugging errors? I tried but couldn't find a good solution

**Comment by svenhb** [comment]
I don't know, I don' t get this error... Perhaps you need enable the other checkbox or disable the first....
![image](https://github.com/user-attachments/assets/6a2984ba-2872-499d-8aeb-33bceacf5c45)

**Comment by lianzaozi** [comment]
Thank you, I have one more question
Where can I set the distance and speed of movement after clicking the JOG button each time?
Every time I click the jog button, the motor moves 10mm in a fixed position
![123](https://github.com/user-attachments/assets/202bcad9-3952-404a-8d28-7e01bd9d5e5c)

**Comment by svenhb** [comment]
If a controller is connected and the buttons are enabled - just right click to get a selection list:
![image](https://github.com/user-attachments/assets/776c0ddb-6693-42bc-8cf7-1ac88dc7d805)

The choices you can define here:
![image](https://github.com/user-attachments/assets/256374f3-b46c-42e4-a87f-54603f3cc44b)

**Comment by lianzaozi** [comment]
![1234](https://github.com/user-attachments/assets/28edb2ce-dd23-4fc0-8a59-7517a4dba39d)


After unchecking "Optimize code", using the function of generating Gcode from text will result in an error If checked, there will be no errors

**Comment by svenhb** [comment]
The main thing is that the error does not occur if the program is started regularly and not via VisualStudio
