### ISSUE TITLE
Software Chinese Translation Optimization

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#424]
I have re audited and optimized the Chinese version of the software V1.7.4.0. I have put the file in a compressed file. Please update it to the software. I exported the translated language file using the software "ResxTranslatior-v2.12"

[GRBL-Plotter-master_V.1.7.4.0_Chinese translation.zip](https://github.com/user-attachments/files/17731499/GRBL-Plotter-master_V.1.7.4.0_Chinese.translation.zip)

**Comment by svenhb** [comment]
Thanks, will add it in the next release

**Comment by svenhb** [comment]
Thanks, it is implemented now: https://github.com/svenhb/GRBL-Plotter/releases
