### ISSUE TITLE
Interface text goes small when import SVG o DXF

### ISSUE THREAD

**Issue by Toaro** [svenhb/GRBL-Plotter#426]
When I open the software all appear to be OK, with readable fonts in normal size, if I load a JPG file for conversion still all is normal, but if open a SVG or DXF file, all the interface text becomes very small

**To Reproduce**
1. Open GRBL Plotter soft
2. Drag and drop SVG file, just when you drop, the text interface change

**Expected behavior**
The text interface must to stay in the same size

**Screenshots**
Here some screenshots. I include some desktop icons and text for comparison purposes. I don't move the program window when i load the SVG file, but the window also change the position, as you can see with the desktop icons reference

That is open without touch anything.
<img width="584" alt="normal" src="https://github.com/user-attachments/assets/ae4e7cdb-ea02-4e15-b362-c5888a6c64ec">
That is when I drop any SVG to the window.
<img width="482" alt="import svg" src="https://github.com/user-attachments/assets/2411d6ee-04d2-4e01-a2b4-a3d4c009105c">
As you can see the gcode window text becomes very "unconfortable" to read because lost all the space between the letters and lines. I solve the lines space changing in the configuration menu the line distance, but that becomes in a very large distance when the interface is ok.
<img width="283" alt="espaciado entre lineas" src="https://github.com/user-attachments/assets/53fbd9e1-3a02-432b-97af-355a7176fe24">

Thanks for your work.

**Comment by svenhb** [comment]
I can't fix this HDPI problem, but this may help: https://grbl-plotter.de/index.php?id=quick-guide#highdpi

**Comment by Toaro** [comment]
Thanks!!!. That fix the problem.

Thanks again for the software, your work, and your time. Great

**Comment by svenhb** [comment]
Thanks :-)
