### ISSUE TITLE
The shortest path sorting of text trajectory is not optimal

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#428]
Sorting of plotters
![456](https://github.com/user-attachments/assets/4c016fec-efeb-49a2-8225-1aa9a371876f)

Sorting of other software
![123](https://github.com/user-attachments/assets/2317a50e-ba3e-44e5-ab51-18769cefa942)

**Comment by svenhb** [comment]
Perhaps you used wrong sorting option?
I would use this settings:
![image](https://github.com/user-attachments/assets/bf0b1a88-ed67-4606-a78f-24260f2d52d0)

**Comment by lianzaozi** [comment]
Thank you very much. According to your instructions, the text sorting problem has been solved now. Can you explain the differences between these options for sorting?
![111](https://github.com/user-attachments/assets/82c90f94-7c7e-444d-a02a-8bb9aaccca26)

**Comment by svenhb** [comment]
This is just the starting point for sorting, relativ to the G-Code or actual tool position ("actual pos").

I think in your example you checked "Sort the objects by size, largest comes last"

**Comment by lianzaozi** [comment]
Due to my mistake, I used the default sorting rule and indeed selected 'Sort the objects by size, large returns last'
Thank you very much for your guidance

**Comment by lianzaozi** [comment]
The plotter software does not display the trajectory after reading the image and generating GCode

![456](https://github.com/user-attachments/assets/50dc4901-75ae-4795-a74c-1d1eb250e6a5)
[test file.zip](https://github.com/user-attachments/files/17943127/test.file.zip)

**Comment by svenhb** [comment]
I thing you useed strange option for "pen up/down" translation:
Your Z never go to minus
![image](https://github.com/user-attachments/assets/fe7fbb20-f2d3-48c2-b255-e11af4c599fa)

Also you hide "above 0" paths:
![image](https://github.com/user-attachments/assets/52d2ebb1-88c3-43c6-87af-a5348377b047)
