### ISSUE TITLE
Big Repo size, consider to remove binaries.

### ISSUE THREAD

**Issue by RasyidUFA** [svenhb/GRBL-Plotter#43]
The Repository size is too big, and there's too many generated code inside the program.

Consider removing those files, and make it smaller. so it can be easily fetched.

**Comment by svenhb** [comment]
I don't see the problem, can you explain more detailed?

**Comment by svenhb** [comment]
And how to get the needed Dlls if not delivered in github (e.g. Aforge, sharpDX etc.)? I don't get it.

**Comment by rasyidf** [comment]
we can use Nuget.

**Comment by svenhb** [comment]
No idea what to change.
This project is just a hobby, no time to learn Nuget or what ever - sorry
