### ISSUE TITLE
Issue solved

### ISSUE THREAD

**Issue by kenansatir** [svenhb/GRBL-Plotter#46]
Issue solved

**Comment by kenansatir** [comment]
G54 (Setup - GCode-Header)
M3 S20000 (Start)
G00 X-10.000 Y-10.000  (No problem)
G01 X-10.000 Y10.000 F10 (No problem)
G01 X10.000 Y10.000  (Moves faster than F10)
G01 X10.000 Y-10.000  (No problem)
G01 X-10.000 Y-10.000 (Moves faster than F10)  
M30 (Setup - GCode-Footer)
M30 (Program end)

**Comment by kenansatir** [comment]
I have tested your software with versions 1.2.1 and 1.2.2 .... same result

**Comment by svenhb** [comment]
How did you solve this issue? Perhaps too low feedrate for grbl?

**Comment by kenansatir** [comment]
Too low steps/mm value for the stepper clock... its nonsense but nothing to do...

**Comment by svenhb** [comment]
What was the problem?
