### ISSUE TITLE
"Create simple shapes" command does not work when " depth (Z) = 0 "

### ISSUE THREAD

**Issue by kenansatir** [svenhb/GRBL-Plotter#47]
as in the issue title, "G Code creation" / "Create simple shapes" menu command does not work when " depth (Z) value is zero...

**Comment by svenhb** [comment]
Will change control property to avoid values for Z-depth of >=0.

**Comment by svenhb** [comment]
Should be fixed in Version 1.2.3.x - just don't allow value >=0
