### ISSUE TITLE
0.1 Precision edit boxes...

### ISSUE THREAD

**Issue by kenansatir** [svenhb/GRBL-Plotter#50]
![image](https://user-images.githubusercontent.com/32985245/50613312-396d9900-0eee-11e9-8543-ed58a2b5e2e0.png)

0.1 precision edit boxes can accept 0.01 precision value... can not display it... But it works as entered...

For example i can enter 0.12 to "Z-Height save" value, it accept my enter, does not diplay it but it works as 0.12...

**Comment by svenhb** [comment]
Should be fixed in Version 1.2.3.x - extended displayed precision to 0.01
