### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Gabse** [svenhb/GRBL-Plotter#54]
Hi, I tried to run the new version from Release folder and get the following issue on run:
![unbenannt](https://user-images.githubusercontent.com/8307733/50724980-cc791f80-10f6-11e9-8f48-838396b9cd92.JPG)

After hitting OK the following window appears:
![unbenannt2](https://user-images.githubusercontent.com/8307733/50724987-f4688300-10f6-11e9-8878-ee5adc2a5207.JPG)

It can be cleared by hitting ok again and the software seems to work.
When I try to navigate to settings and GamePad I get another error:
![unbenannt3](https://user-images.githubusercontent.com/8307733/50725005-34c80100-10f7-11e9-99cb-3e738bf3e55d.JPG)

It won’t disappear by clicking OK, and I have to kill the software via Task manager.

Something else: does limiting the working area work at your setup?
In my case it works on X and Y-axis, but on Z it will exceed de work area.

**Comment by svenhb** [comment]
During normal setup, the hotkeys.xml would be copied to the correct location.
Now you have to copy it manually from here: https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter/hotkeys.xml

**Comment by svenhb** [comment]
I copied the missing file to the given location.
