### ISSUE TITLE
Feature request: Third column with custom buttons

### ISSUE THREAD

**Issue by Comet12** [svenhb/GRBL-Plotter#57]
Hi Sven,

it would be very useful to have 4 macro buttons more, especially
for probing with different tools with different diameters.

So long
Thomas

**Comment by svenhb** [comment]
Have a look to the new version 1.2.3.9: https://github.com/svenhb/GRBL-Plotter/releases/latest

**Comment by Comet12** [comment]
Incredible! Thank you!

**Comment by svenhb** [comment]
Thanks for the feedback
