### ISSUE TITLE
Feature request: Display feedrate and spindle speed in main window

### ISSUE THREAD

**Issue by Comet12** [svenhb/GRBL-Plotter#58]
Hi Sven,
it would be very useful to see the actual spindle speed and feedrate in the main window.
To display them should be easy, the needed information is also displayed in the serial window.

So long
Thomas

**Comment by svenhb** [comment]
Have a look to the new version 1.2.3.9: https://github.com/svenhb/GRBL-Plotter/releases/latest

Override of spindle speed doesn't work with grbl_v1.1f.20170801.hex? Can you confirm?

**Comment by Comet12** [comment]
Thank you for your work, I can see now both value!

In the meantime I switch to grbl v1.1g on my uno and mega and spindle speed override
works fine with both. 
BTW: I don't use the pre-compiled hex-file, I compile with Atmel Studio on my own.

**Comment by svenhb** [comment]
Thanks for the feedback
