### ISSUE TITLE
Closing connection via Close Button should save last position

### ISSUE THREAD

**Issue by Comet12** [svenhb/GRBL-Plotter#60]
Hi Sven,
closing the connection via Close Button in COM window should save the current position
in the same way as closing the application. 

Regards
Thomas

**Comment by svenhb** [comment]
I added this feature to the new test version 1.2.3.10 
https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_12310_publish.zip

**Comment by Comet12** [comment]
Saving via Close button doesn't work (old behaviour). Are all relevant files enclosed?

**Comment by svenhb** [comment]
I just uploaded the compiled version in a zip file, no single files.

**Comment by Comet12** [comment]
OK, but the feature doesn't work.

**Comment by svenhb** [comment]
I checked the code right now: I made a mistake with the code change...
I will fix it this evening

**Comment by svenhb** [comment]
Please check again https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_12311_publish.zip

**Comment by svenhb** [comment]
No bugs reported, seems to work as expected
