### ISSUE TITLE
Index was outside the bounds

### ISSUE THREAD

**Issue by raminrajabi** [svenhb/GRBL-Plotter#67]
![500](https://user-images.githubusercontent.com/15262281/62850173-56c1db80-bcf7-11e9-95aa-3ceea117cf7e.png)

when I want to connect to my Arduino port and after some command comminution I got this error message in log text box: out of bounds

in line 817:
 grbl.getPosition(dataField[4] + "," + dataField[5] + "," + dataField[6]+" ", ref posWork);

my dataFiled only has 4 items but in the line above it's want to read the item 5 and 6;

the command is : Idle,WPos:0.000,0.000,0.000

**Comment by svenhb** [comment]
I will check. Perhaps you can upgrade to grbl version 1.1?
https://github.com/gnea/grbl/releases/tag/v1.1f.20170801

**Comment by raminrajabi** [comment]
I downloaded the latest version of grbl and compiled it and I've got this message but when I downloaded the precompiled hex file and using it the problem is gone.
now it's working perfectly
thanks.

**Comment by svenhb** [comment]
>I downloaded the latest version of grbl and compiled it 
Can you give me the link to the source you used?

**Comment by raminrajabi** [comment]
[grbl.zip](https://github.com/svenhb/GRBL-Plotter/files/3496286/grbl.zip)

a used source with compiling of Arduino UNO

**Comment by svenhb** [comment]
Found weak code, add a check if index is within bounds
