### ISSUE TITLE
Teach lower position crash

### ISSUE THREAD

**Issue by ivahru** [svenhb/GRBL-Plotter#71]
After wrong coordinates click during tryout of teach lower position the display ends without picture . Next message asks for program quit. There shall be some step back possible and values treated the way it warns the user that something goes wrong.

![GRBL_Plotter_CameraErr](https://user-images.githubusercontent.com/49569572/65541684-18caf080-df0e-11e9-9b23-8af429f3b496.jpg)

**Comment by svenhb** [comment]
Found weak code, check for division by zero now. Should be fixed in Update 1.3.0.0
