### ISSUE TITLE
Vinyl Plotter With the Z axis is an electromagnet?

### ISSUE THREAD

**Issue by GioLangLe** [svenhb/GRBL-Plotter#75]
Thanks for your great project. I want the Z axis to work with an electromagnet. What do I have to fix? Or must the Z axis be a Servo motor?

**Comment by svenhb** [comment]
Just connect your magnet as a spindle. In Setup - Graphics Import - G-Code generation select Spindle on/off - perhaps you need to set Spindle speed to a higher value - if PWM is enabled in your controller. The Spindle (your magnet) will be switched on on 'Pen down' and switched off on 'Pen up'. Note also the 'Delay after spindle on' to give the magnet time to reach and position.
![image](https://user-images.githubusercontent.com/19973251/67616040-32dd4480-f7d4-11e9-9991-9b430a945d68.png)

**Comment by svenhb** [comment]
Question is answered, I think.
