### ISSUE TITLE
In settings menu, there is no option to exit without saving

### ISSUE THREAD

**Issue by FelisucoVFR** [svenhb/GRBL-Plotter#77]
I have realized if I close the settings window with the "X", it saves the changes anyway same like "Apply changes".

"X" button should ask if save or not.

**Comment by svenhb** [comment]
It's not possible to change, because almost each Setup-Control is connected with a Properties.Settings variable. Any change in the control will be saved imediatly.
The "Apply changes" button forces the main GUI to read back the Properties.Settings and update it's controls.
