### ISSUE TITLE
Spanish language corrections

### ISSUE THREAD

**Issue by FelisucoVFR** [svenhb/GRBL-Plotter#78]
Hi,

I have a few suggestion to correct the Spanish tags.

![GBL Plotter_SP_01](https://user-images.githubusercontent.com/20519852/67755250-1ccfbe00-fa38-11e9-9798-cb875538fdb0.JPG)

![GBL Plotter_SP_02](https://user-images.githubusercontent.com/20519852/67755278-2b1dda00-fa38-11e9-9368-78c3a1795d9a.JPG)

![GBL Plotter_SP_03](https://user-images.githubusercontent.com/20519852/67755298-340eab80-fa38-11e9-9397-952426317116.JPG)

![GBL Plotter_SP_04](https://user-images.githubusercontent.com/20519852/67755309-383ac900-fa38-11e9-908e-5b629edd456b.JPG)

![GBL Plotter_SP_05](https://user-images.githubusercontent.com/20519852/67755316-3bce5000-fa38-11e9-93ef-1ff5336a5b4e.JPG)

![GBL Plotter_SP_06](https://user-images.githubusercontent.com/20519852/67755325-3f61d700-fa38-11e9-964e-5d6a2670778a.JPG)

1 - "Conectar" (Open) or "Desconectar" (Close)
2 - "Archivo"
3 - "Modificación G-Code"
4 - "Control / Mover"
5 - "Parar al soltar el ratón"
6 - "Transmisión de G-Code"
7 - "Coordenadas (Trabajo/Máquina)"
8 - "Dimensiones G-Code"
9 - "Herramienta en husillo" (Option: "Herr. en husillo" or "Herr. en Spindle")
10 - "Vel." or "Velocidad" or just "Speed" as it is, everybody understand this.
11 - "Refrigerante"
12 - "Pausa"
13 - "Continuar"
14 - "Mostrar informe de estado"

15 - "Abrir archivo"
16 - "Abrir archivo reciente"
29 - "Ajustes"

17 - "Girar -90º (en sentido horario)"
18 - "Rotar ...º"
19 - "Diámetro eje rotativo"

20 - "Sistema de coordenadas"
21 - "Control DIY" (Not sure how to translate this nor what this do...)
22 - "Control 2º GRBL"

23 - "Área de la máquina"
24 - "Tabla de herramientas"

25 - "Acerca de"
26 - "Versión"
27 - "Ruta del programa"
28 - "Comprobar actualización" or "Actualizar"

Just as a start point. I need more free time to enter into the menus, specially the Settings one.

Thanks

**Comment by FelisucoVFR** [comment]
Sorry about the "bug" label. No idea how to change it to "enhancement"

**Comment by svenhb** [comment]
I made the changes...
https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_1311_es_publish.zip

**Comment by FelisucoVFR** [comment]
@svenhb Great, I will try to continue with the rest soon.
Thanks

**Comment by svenhb** [comment]
No more feedback about translation...
