### ISSUE TITLE
Open dxf file error

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#79]
Excuse me, this is how it happened. I opened the dxf file and selected the configuration file in the red box.
Is there any documentation for this software?
![image](https://user-images.githubusercontent.com/53146195/69129239-f528be80-0ae8-11ea-8d1a-1c4c806dc013.png)
![image](https://user-images.githubusercontent.com/53146195/69129299-0b367f00-0ae9-11ea-819a-7c754c37719b.png)

**Comment by svenhb** [comment]
It seems there is no LineType given in your DXF - I need to check this in my code.
I will fix it in the next days.

**Comment by lianzaozi** [comment]
The same dxf file, open with versions prior to 1.2.5.0 is fine, but opening with versions 1.3.2.0, 1.3.2.0, 1.3.0.0, 1.3.1.0 will be problematic. Is it better to parse dxf files with netdxf.dll? Netdxf.dll supports many metafiles

**Comment by svenhb** [comment]
Yes, in 1.3.0.0 I added "process dashed lines from DXF or SVG".
I need to fix my code, if no LineType is given in your DXF

**Comment by svenhb** [comment]
Can you upload your example - so I can test my changings

**Comment by lianzaozi** [comment]
[arc.zip](https://github.com/svenhb/GRBL-Plotter/files/3863142/arc.zip)

OK

**Comment by svenhb** [comment]
fixed it
