### ISSUE TITLE
Display area zoom problem

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#81]
![image](https://user-images.githubusercontent.com/53146195/69201366-05887a00-0b79-11ea-9c23-e18510c72a12.png)
This is what it looks like when you open the file.
![image](https://user-images.githubusercontent.com/53146195/69201426-35378200-0b79-11ea-8977-7d58bdcd60c2.png)
After scrolling the mouse wheel to zoom in, the display area is in the upper left corner, resulting in no visible at all, and there is no way to move the display area.

**Comment by lianzaozi** [comment]
At present, the parsing of the spline is also problematic, and the appearance is different from the actual one.

![image](https://user-images.githubusercontent.com/53146195/69201939-fc001180-0b7a-11ea-9179-e4b251c9226f.png)
![image](https://user-images.githubusercontent.com/53146195/69202493-d116bd00-0b7c-11ea-83a2-d0effe88b4f1.png)

Note that this is not the same as the above picture.
In addition ,the accuracy of parsing the spline curve
is not high enough.
You are parsing the spline curve into small line segments.

The accuracy is not high enough.

**Comment by lianzaozi** [comment]
This is the dxf file for the test spline
[Spline1.zip](https://github.com/svenhb/GRBL-Plotter/files/3866955/Spline1.zip)

**Comment by svenhb** [comment]
Zooming: mouse position is center of zooming - sometimes strange - I can't fix.
Spline: In know there is a weak point I will fix soon.

**Comment by lianzaozi** [comment]
OK。
You can refer to the algorithm or idea of dxf2gcode software.(https://sourceforge.net/projects/dxf2gcode/)

**Comment by svenhb** [comment]
Thanks

**Comment by svenhb** [comment]
Spline Import should be fixed in Version 1.3.2.3
