### ISSUE TITLE
How to use the seccond GRBL ?

### ISSUE THREAD

**Issue by LeoVerheyden** [svenhb/GRBL-Plotter#82]
Is there a Tuto available ?  How to take control off the 2 GRBL tool change ?
I tried with TwM06 but I still sty in the first.

**Comment by svenhb** [comment]
Commands for 2nd GRBL will be introduced via special formatted remarks in GCode e.g.: (^2 G90 X2) to move 2nd GRBL to position X2.

Video: https://youtu.be/fvYWyE2GBsg

And check the scripts in data/scripts   script_pen_select, ..._remove, ..._pickup.

Hope that helps...

**Comment by LeoVerheyden** [comment]
Thanks it works well. How do I put on zero  G54 in seconds arduino ( com tool changer) ?

**Comment by svenhb** [comment]
Should work in the same way: "(^2 G54)" or manually via COM-window of 2nd grbl.
To set set G54 to zero you may use "(^2 G10 L2 P0 X0 Y0)" P0 = active coordinate system, or use P1 to set G54 explicite..
Better read this: http://linuxcnc.org/docs/html/gcode/g-code.html#gcode:g10-l2

**Comment by LeoVerheyden** [comment]
Thank you

Leo Verheyden
________________________________
De : Sven <notifications@github.com>
Envoyé : samedi 30 novembre 2019 10:08
À : svenhb/GRBL-Plotter <GRBL-Plotter@noreply.github.com>
Cc : Leo Verheyden <leo.verheyden@berlo.be>; Author <author@noreply.github.com>
Objet : Re: [svenhb/GRBL-Plotter] How to use the seccond GRBL ? (#82)


Should work in the same way: "(^2 G54)" or manually via COM-window of 2nd grbl.
To set set G54 to zero you may use "(^2 G10 L2 P0 X0 Y0)" P0 = active coordinate system, or use P1 to set G54 explicite..
Better read this: http://linuxcnc.org/docs/html/gcode/g-code.html#gcode:g10-l2

**Comment by svenhb** [comment]
Question was answered - hopefully with success ;-)
