### ISSUE TITLE
Reading file problem

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#85]
When a dxf file is opened by the CAD software, use GRBL-Plotter software to open the dxf file again. GRBL-Plotter software will get stuck, so I recommend GRBL-Plotter to have a prompt message when opening any file that is being used .

![image](https://user-images.githubusercontent.com/53146195/69640483-63e1bb00-1099-11ea-9b15-07614f7d4433.png)
Click the OK button in the figure above, the software is stuck. Opening the task manager to view the process of the plotter software also shows no response. This state persists, only the software is forcibly closed.
![image](https://user-images.githubusercontent.com/53146195/69640609-97bce080-1099-11ea-8784-11986550c2d1.png)

**Comment by svenhb** [comment]
I will implement a check

**Comment by svenhb** [comment]
Check is implemented, but could not be tested.
