### ISSUE TITLE
Press the middle mouse button to move the mouse to move the track display interface

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#86]
I want to be able to move the interface showing the trajectory by moving the mouse by pressing the mouse wheel

![image](https://user-images.githubusercontent.com/53146195/69641120-93dd8e00-109a-11ea-9bc9-b510b4ec22d7.png)

This feature is very important, I hope you add

**Comment by svenhb** [comment]
The will take some more time to implement - I will try during x-mass hollidays

**Comment by lianzaozi** [comment]
Thank you

**Comment by svenhb** [comment]
Function is implemented:
1. select figure - then marked yellow
2. use middle mouse button to move figure
3. press right mouse button, select "Move selected path" to apply offset
