### ISSUE TITLE
Can you share your modified dxflib.dll source code for download?

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#87]
Hello
Can you share your modified dxflib.dll source code for download?

I suggest sharing the source code of the third-party libraries used by the software, so that it is convenient for everyone to study, modify bugs, and add features together.

**Comment by svenhb** [comment]
It' just one line I added... Where should I store the edited file? It' not really part of GRBL-Plotter?
Perhaps follow the original issue: https://github.com/mkernel/DXFLib/issues/4

**Comment by lianzaozi** [comment]
Thank you

**Comment by svenhb** [comment]
Just follow the original issue: mkernel/DXFLib#4
