### ISSUE TITLE
Chinese garbled

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#90]
Hello, here shows that Chinese characters will be garbled
![image](https://user-images.githubusercontent.com/53146195/69791550-b0dfa180-11ff-11ea-8c57-b57c102704de.png)

**Comment by svenhb** [comment]
What do you expect to see?

**Comment by lianzaozi** [comment]
Chinese fonts can be displayed normally

**Comment by svenhb** [comment]
Anyway I can't fix it because it's a library I use: https://github.com/PavelTorgashov/FastColoredTextBox
