### ISSUE TITLE
Arc is resolved

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#91]
Hello, I found that the arc is parsed into G01, why is this? Wouldn't it be better to parse the arc into G02 and G03?

**Comment by svenhb** [comment]
Yes, because I just could find an algorithm for lines. For me it's good enough.
I had a look to dxf2gcode but it's too complicated for me....

**Comment by lianzaozi** [comment]
I have also recently researched the source code of dxf2gcode, which is difficult to understand.

**Comment by svenhb** [comment]
Up to now it's not planned to change the algorithm.
