### ISSUE TITLE
Without the buttons in your screenshot

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#92]
![image](https://user-images.githubusercontent.com/53146195/70383287-3accfe80-19a6-11ea-855c-41661a5c8895.png)
Thank you very much for your reply
Without the buttons in your screenshot, the software version is V1.3.2.5。

When opening the dxf file through CAD software, please use GRBL-Plotter software to open the dxf file again. GRBL-Plotter software will be stuck, now after my test version V11.3.2.5 software will not get stuck when opening dxf occupied by other software, thank you

**Comment by svenhb** [comment]
Strange... did you compile by yourself, or do you use the ready exe?

**Comment by lianzaozi** [comment]
> 奇怪...是您自己编译的，还是使用现成的exe？

I unzip the file GRBL-Plotter_1324_publish.zip directly, and then run the GRBL-Plotter.exe program inside

**Comment by lianzaozi** [comment]
I downloaded https://github.com/svenhb/GRBL-Plotter/releases on this link

**Comment by svenhb** [comment]
Hopefully now it works:
https://github.com/svenhb/GRBL-Plotter/blob/master/GRBL-Plotter_1325_publish.zip

**Comment by lianzaozi** [comment]
The problem is still the same, no button is displayed. 
Test environment: windows10 x64 home version version 1903

**Comment by lianzaozi** [comment]
The problem has been solved, and the button is displayed after recompiling

**Comment by svenhb** [comment]
Problem fixed
