### ISSUE TITLE
How to move the dxf trajectory display

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#93]
In addition to zooming, how to move the display of dxf track? Pressing the mouse wheel like AutoCAD software can move the drawing area. Similar functions

**Comment by svenhb** [comment]
If you press middle mouse button on selected (yellow) path, you can move it...
After move in 2D-View, apply transformation via right-click menu

**Comment by lianzaozi** [comment]
![image](https://user-images.githubusercontent.com/53146195/70425327-fd529900-1aab-11ea-9135-06315ff9a3aa.png)
No "Apply Conversion" option via right-click menu

**Comment by lianzaozi** [comment]
The function of pressing the middle mouse button to move the mouse to control the track display area can be compared with libreCAD software. After you draw a lot of graphics in the drawing area in the libreCAD software, and then press the middle mouse button to move the mouse, you will find that the entire drawing in the drawing area moves with your mouse. What I want to express is that. If my expression is not very clear, you can draw a dozen straight lines in the libreCAD software, and then move the mouse while holding down the middle mouse button, and you will observe the scenario I described, which is what I want The meaning expressed. At present, the plotter software is zooming in on the track display area, and there is no way to move this area while keeping the zoomed state unchanged.

**Comment by svenhb** [comment]
"Move selected path" will apply the offset to the GCode...
Perhaps better naming needed?

**Comment by lianzaozi** [comment]
I hope I have accurately expressed my thoughts

**Comment by svenhb** [comment]
Now I got it.

**Comment by svenhb** [comment]
With latest release 1.3.3.0
Middle mouse button will move complete view or selected form
