### ISSUE TITLE
Idioma

### ISSUE THREAD

**Issue by Wdespontin** [svenhb/GRBL-Plotter#94]
Good afternoon, congratulations on always improving this software.
A version of GRBL Ploter 1325 that was recently released with Portuguese translation.
Some words are going beyond the windows where you can enter numbers by following red underlined photos of what happens.
English - Brazil is a bit confusing in some words.
It's like translating Portuguese into English and vice versa, there are some wrong interpretations of the words.
But there must be an error in the translator, also on the first graphic screen marked with blue ray, where the white zoom screen appears, which allows much to follow or follow the trace of the drawing that could be left in another fixed location, thanks

**Comment by svenhb** [comment]
Yes I know .... I used google translator and was hoping for correction by users - like you.
Give me some help to shorten words / find abbreviations.

**Comment by Wdespontin** [comment]
Good morning, I can change or delete this text here and send it to you,
edit it, this is an open program, how do I have any editable file that I
can fix and send you, thanks

*Att; *
*Valter*


Em qui., 12 de dez. de 2019 às 15:45, Sven <notifications@github.com>
escreveu:

**Comment by svenhb** [comment]
How to edit language files:
a) Easy method for me: you download all files and use a tool like "ResxTranslator" (https://github.com/HakanL/resxtranslator).
b) Easy method for you: I setup a excel or CSV file you could edit with any program.

Finally send me the files. Tell me your choice, for a) I need to update files on github first...

**Comment by Wdespontin** [comment]
Good morning, I already downloaded the resx translator, you can send me the
CSV file or I can find it in the GRBL Ploter folder, thanks

*Att; *
*Valter*


Em sex., 13 de dez. de 2019 às 04:01, Sven <notifications@github.com>
escreveu:

**Comment by svenhb** [comment]
Hi, a third option is:
making screenshot, and mark the changings as done here: #78 

[setup.zip](https://github.com/svenhb/GRBL-Plotter/files/3960789/setup.zip)
[mainForm.zip](https://github.com/svenhb/GRBL-Plotter/files/3960790/mainForm.zip)

**Comment by svenhb** [comment]
If you download setup or mainForm file, please check for actual version 1.3.2.5a

**Comment by svenhb** [comment]
Up to now no updates for language corrections...
