### ISSUE TITLE
FastColoredTextBox display Chinese garbled solution

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#95]
FastColoredTextBox displays Chinese garbled characters, the problem of overlap has been resolved, please use the following library https://github.com/ks3dev/FastColoredTextBox
At the same time, when storing the Gcode code, you can choose UTF-16 BE or UTF-16 LE as the text format. If you use UTF-8 and ANSI storage, the Chinese comments in the G code will not display properly after opening.

**Comment by svenhb** [comment]
Thank you, I will try soon

**Comment by svenhb** [comment]
Check new release

**Comment by lianzaozi** [comment]
Thank you very much, the problem has been solved, and I wish you a Merry Christmas in advance.

**Comment by lianzaozi** [comment]
Thank you very much, the problem has been solved.

**Comment by svenhb** [comment]
Problem solved with suggested change
