### ISSUE TITLE
Simulation

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#96]
Hi merry christmas I would like to ask if I will consider adding the function of simulation processing so that the processing process can be directly observed even if the software is not connected to the hardware, which is convenient to use. At present, the corresponding trajectory can be observed by selecting Gcode. However, this method is convenient for local viewing, but it is a lot of work for global viewing through this method. Simulation processing is, if you do a simulation processing Button, click this button and the path display area will display the movement track of GCode from the first line to the last line. This function is available on many cam software.

**Comment by svenhb** [comment]
In new version 1.3.3.0 
* Path simulation   
  - automatically go through G-Code lines and show position in 2D view

Could be improved in the future by intermediate steps for long straight lines (G0, G1)
