### ISSUE TITLE
where is set new option "Don't change pen width on zooming"？

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#97]
This software is already great, but I can't find "Don't change pen width on zooming"

**Comment by lianzaozi** [comment]
Hi, svenhb, thank you for providing such a good platform for lovers to communicate. Where can I buy a hardware control board for use with GRBL-Plotter? If you have a purchase link, please send it to me. I mainly use it for laser engraving. It is best to have a control board with PWM or analog to control the laser energy. I am currently in China. Thank you.

**Comment by svenhb** [comment]
Hi, for "Don't change pen width on zooming" I added a checkbox in [Setup - Joystick/Colors].
I bought all my boards on ebay, just search for "Arduino CNC". For 10€ you sometimes get the Arduino, the CNC-Shield and motor drivers...

**Comment by lianzaozi** [comment]
Thank you for your reply.

**Comment by svenhb** [comment]
Probably found
