### ISSUE TITLE
The mouse clicks on the primitives in the three blue boxes. The software selects the elliptical arcs in the black boxes.

### ISSUE THREAD

**Issue by lianzaozi** [svenhb/GRBL-Plotter#98]
The mouse clicks on the primitives in the three blue boxes. The software selects the elliptical arcs in the black boxes.

test.zip file is the dxf file for my test

![无标题](https://user-images.githubusercontent.com/53146195/71964477-98b86480-3238-11ea-92ac-a8fd4887aa64.png)

[test.zip](https://github.com/svenhb/GRBL-Plotter/files/4034382/test.zip)

**Comment by lianzaozi** [comment]
![无标题](https://user-images.githubusercontent.com/53146195/71964731-2c8a3080-3239-11ea-996c-6714169abffd.png)

**Comment by lianzaozi** [comment]
[Software error screenshot.zip](https://github.com/svenhb/GRBL-Plotter/files/4034391/Software.error.screenshot.zip)

**Comment by svenhb** [comment]
The Problem seems to be the import of DXF 'Point' geometry - without points it works...
I will fix it.

**Comment by lianzaozi** [comment]
Thank you for your reply.

It is best to add a mouse to select geometric primitives. All the selected primitives are selected, and then these selected primitives can be moved as a whole. Box selection is the same as LibreCAD software. Then right-click and add an item in the pop-up menu to set the distance of the x direction and the y direction of the movement. Set the distance. The selected geometrical elements just moved to the new position with the set value

**Comment by lianzaozi** [comment]
Or it also supports ctrl + mouse click multiple selection
